-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_npc_death", fun = this.nepis_umer })
  sm:subscribe({ signal = "on_spawn",     fun = this.nepis_free })
end


---------------------------------------------------------------------
-- Привет от Сяка 
---------------------------------------------------------------------

local math_random = math.random
local math_atan2 = math.atan2
local math_sin = math.sin
local math_cos = math.cos
local string_find = string.find
local string_format = string.format
local string_gsub = string.gsub

function add_new_escape_100()
add_new_lc(9100,4426,"На Кордон","info_way100a",3)
end
function add_new_agroprom_101()
add_new_lc(9101,2826,"На Агропром","info_way101a",4)
end
function add_new_yantar_102()
add_new_lc(9102,4427,"На Янтарь","info_way102a",1)
end
function add_new_agroprom_103()
add_new_lc(9103,8355,"На Агропром","info_way103a",3)
end
function add_new_mil_104()
add_new_lc(9104,6941,"На Армейские Склады","info_way104a",4)
end


function add_new_rostok_105()
  local sobj = add_new_lc(
    story_ids.exit_to_rostok_105, 7482, "На Дикую Территорию", "info_way105a",
    4
  )
end


function add_new_radar_106()
  local sobj = alife():story_object( story_ids.exit_to_radar_106 )
  if not sobj then
    sobj = add_new_lc(
      story_ids.exit_to_radar_106, 8356, "На Радар", "info_way106a", 1
    )
    local sobj2 = amk_anoms.spawn_anomaly(
      "zone_teleport",
      sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
      { shtype = 0, radius = 1, center = { 0, 0, 0 } }
    )
    alife():assign_story_id( sobj2.id, story_ids.exit_to_radar_106_zone )
  end
  local tname = "sak.remove_new_radar_106"
  if ogse_st_mgr.timer_exists( tname ) then
    ogse_st_mgr.get_timer( tname ):stop()
  end
  ogse_st_mgr.start_gtimer(
    tname, math.random( 12, 20 ) * 3600,
    "sak.remove_new_radar_106"
  )
end

function remove_new_radar_106()
  for _, sid in ipairs({ "exit_to_radar_106", "exit_to_radar_106_zone" }) do
    local sobj = alife():story_object( story_ids[ sid ] )
    if sobj then
      dsh_alife.release( sobj )
    end
  end
end


function add_new_darkvalley_107()
  add_new_lc( 9107, 9109, "В Тёмную Долину", nil, 2 )
end


function add_new_yantar_108()
add_new_lc(9108,9108,"На Янтарь","info_way108a",3)
end


function add_new_radar_109()
  add_new_lc(
    story_ids.exit_to_radar_109, 5157, "На Радар", "info_way109a", 2
  )
  local tname = "sak.remove_new_radar_109"
  if ogse_st_mgr.timer_exists( tname ) then
    ogse_st_mgr.get_timer( tname ):stop()
  end
  ogse_st_mgr.start_gtimer(
    tname, math.random( 20, 28 ) * 3600,
    "sak.remove_new_radar_109"
  )
end

function remove_new_radar_109()
  local sobj = alife():story_object( story_ids.exit_to_radar_109 )
  if sobj then
    dsh_alife.release( sobj )
  end
end

function dont_has_new_radar_109()
  local sobj = alife():story_object( story_ids.exit_to_radar_109 )
  if sobj then return false end
  return true
end


function add_new_mil_110()
  local sobj = add_new_lc(
    story_ids.exit_to_mil_110, 5158, "На Армейские Склады", "info_way110a", 1
  )
  if sobj then
    alife():teleport_object(
      sobj.id, vector():set( -66.320304870605, 1.0114997625351, 80.36954498291 ),
      96736, 899
    )
  end
end


function add_new_darkvalley_111()
  local sobj = add_new_lc(
    story_ids.exit_to_darkvalley_111, 7483, "В Тёмную Долину", "info_way111a",
    3
  )
  if sobj then
    local lc = sobj:get_level_changer()
    ASSERT(
      lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
    )
    lc.dest_game_vertex_id  = 899
    lc.dest_level_vertex_id = 97547
    lc.dest_position        = vector():set( -65.978820800781, 0.65926766395569, 76.747947692871 )
  end
end


function add_new_military_01()
  add_new_lc( 1008, 9390, "На Армейские Склады", nil, 3 )
end


function add_new_military()
add_new_lc(592,6851,"На Армейские Склады","info_way113a",1)
end
--' болото-старая деревня
function add_new_rostok()
add_new_lc(97101,13109,"В Старую Деревню","info_way114a",1)
end


function add_new_to_garbage()
  add_new_lc(
    story_ids.peshera_to_svalka, 13822, "На Свалку",
    "info_way_arhara_peshera_cvalka", 2
  )
end


function add_new_to_agro()
  local sobj = add_new_lc(
    story_ids.peshera_to_agroprom, 13823, "На Агропром",
    "info_way_arhara_peshera_agro", 4
  )
  alife():teleport_object(
    sobj.id, vector():set( -0.06, -1.92, -12.81 ), 32280, 2880
  )
end


-- открывается сразу 2 перехода
function add_new_to_peshera1()
  -- add_new_lc(
  --   story_ids.exit_to_peshera_from_garbage, 3793, "В Пещеру",
  --   "info_way_arhara_cvalka_peshera", 4
  -- )
  local sobj = add_new_lc(
    story_ids.exit_to_peshera_from_agroprom, 4395, "В Пещеру",
    "info_way_arhara_agro_peshera", 2
  )
  local lc = sobj:get_level_changer()
  ASSERT(
    lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
  )
  lc.dest_game_vertex_id  = 2880
  lc.dest_level_vertex_id = 32284
  lc.dest_position        = vector():set( -0.06, -2.48, -10.11 )
  add_new_to_agro()
end


-- кордон-болота
function add_new_to_peshera2()
  local sobj = add_new_lc(
    14002, 2823, "На Болота", "info_way_arhara_kordon_boloto", 4
  )
  if sobj then
    alife():teleport_object(
      sobj.id, vector():set( -254.01,-16.35,-205.71 ), 8329, 41
    )
  end
end


function add_new_to_les()
  local sobj = add_new_lc(
    story_ids.darkvalley_les, 5150, "В Забытый Лес", "info_way_arhara_td_les", 4
  )
  amk_anoms.spawn_anomaly(
    "zone_teleport",
    sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
    { shtype = 0, radius = 1, center = { 0, 0, 0 } }
  )
  sobj = alife():story_object( story_ids.to_td_level_changer_from_puzir )
  if not sobj then
    sobj = add_new_lc(
      story_ids.to_td_level_changer_from_puzir, nil, "В Тёмную Долину",
      "info_way_arhara_td_les", 2
    )
    amk_anoms.spawn_anomaly(
      "zone_teleport",
      sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
      { shtype = 0, radius = 1, center = { 0, 0, 0 } }
    )
  end
end


function add_new_to_peshera3()
add_new_lc(97081,522,"В Пещеру","info_way_arhara_labirint_peshera",4)
end
function add_new_to_labirint()
add_new_lc(97021,13686,"В Лабиринт","info_way_arhara_peshera_labirint",2)
end
function add_new_labirint_to_yantar()
add_new_lc(11512,335,"На Янтарь","info_way_arhara_labirint_yantar",1)
end
function add_new_labirint_to_earth()
add_new_lc(11511,314,"На Неразведанную Землю","info_way_arhara_labirint_earth",1)
end
function add_new_yantar_to_labirint()
add_new_lc(11515,8352,"В Лабиринт","info_way_arhara_yantar_labirint",3)
end


function add_new_atp_to_pripyat()
  local sobj = add_new_lc(
    story_ids.level_changer_na_pripyat, 94, "В Центральную Припять",
    "info_way_arhara_atp_pripyat", 1
  )
  amk_anoms.spawn_anomaly(
    "zone_teleport",
    sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
    { shtype = 0, radius = 1, center = { 0, 0, 0 } }
  )
end


function add_new_atp_to_military()
add_new_lc(97091,132,"На Армейские Склады","info_way_arhara_atp_military",2)
end


-- на самом деле в Бар
function add_new_atp_to_kordon()
  local sobj = add_new_lc(
    story_ids.level_changer_na_kordon, 133, "В Бар",
    "info_way_arhara_atp_kordon", 3
  )
  amk_anoms.spawn_anomaly(
    "zone_teleport",
    sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
    { shtype = 0, radius = 1, center = { 0, 0, 0 } }
  )
  local lc = sobj:get_level_changer()
  ASSERT(
    lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
  )
  lc.dest_game_vertex_id  = 1173
  lc.dest_level_vertex_id = 46026
  lc.dest_position        = vector():set( 139.62, 8.06, -121.74 )
  lc.dest_direction       = vector():set( 0, -1, 0 )
end


function add_new_atp_to_svalka()
add_new_lc(97093,183,"На Свалку","info_way_arhara_atp_svalka",2)
end
--' Припять-Старая Деревня
function add_new_military_to_earth()
add_new_lc(97100,10243,"В Старую Деревню","info_way_arhara_pripyt_village",4)
end


-- открывается сразу 2 перехода
function add_new_td_to_earth()
  add_new_lc(
    11513, 5151, "На Неразведанную Землю", "info_way_arhara_td_earth", 4
  )
  add_new_td_to_earth2()
end

function add_new_td_to_earth2()
  local sobj = add_new_lc(
    story_ids.exit_to_darkvalley_111,
    7478, "На Неразведанную Землю", "info_way_arhara_military_earth", 3
  )
  local lc = sobj:get_level_changer()
  ASSERT(
    lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
  )
  lc.dest_game_vertex_id  = 2904
  lc.dest_level_vertex_id = 1419650
  lc.dest_position        = vector():set(
    307.12255859375,-33.947151184082,418.322296142578
  )
  lc.dest_direction       = vector():set( 0, 3, 0 )
  return sobj
end


function add_new_svalka_to_earth()
  add_new_lc(
    story_ids.svalka_to_aver_level_changer, 3792, "На Неразведанную Землю",
    "info_way_arhara_svalka_earth", 2
  )
end


function add_new_earth_to_labirint()
add_new_lc(11510,774,"В Лабиринт","info_way_arhara_earth_labirint",4)
end


-- открывается сразу 2 перехода
function add_new_radar_to_warlab()
  dsh_hand_teleporter.create_level_changer(
    story_ids.radar_level_changer_to_warlab,
    { 307.16, -39.39, -25.97 }, 69058, 1930, "level_changer4", "В Варлаб",
    { 4.75, 9.26, 22.81 }, 5317, 3210, { 0, 3, 0 }, 0, 0.01
  )
  dsh_hand_teleporter.create_level_changer(
    story_ids.exit_warlab_to_l10_radar,
    { 7.24, 9.53, 21.07 }, 5593, 3210, "level_changer1", "На Радар",
    { 305.39, -39.39, -25.98 }, 68330, 1930, { 0, 1.5, 0 }, 0, 0.01
  )
  db.actor:give_info_portion( "info_way_arhara_radar_warlab" )
  sak.info_received()
  -- add_new_lc(
  --   story_ids.warlab_level_changer_to_brainlab, 14961, "В Лабораторию Х-16",
  --   "info_way_arhara_warlab_brainlab", 4
  -- )
end


--' х18-Варлаб
function add_new_warlab_to_brainlab()
add_new_lc(97098,5867,"В Варлаб","info_way_arhara_x18_warlab",1)
end


function add_new_warlab_to_skladu()
  add_new_lc(
    story_ids.warlab_skladu_level_changer, 14827, "На Армейские Склады",
    "info_way_arhara_warlab_skladu", 1
  )
end


-- переход АТП - Красный лес
function add_new_radar_na_red_forest()
  local sobj = level_new.create_level_changer(
    story_ids.atp_to_red_forest,
    vector():set( -188.30001831055, -1.2002944946289, 339.5 ),
    104511, 2799, 57550, 3278,
    vector():set( -12.0748300552368, 0.833330512046814, -429.453979492188 ),
    vector():set( 0.138911306858063, 0, 0.990304827690125 ),
    "red_forest", 0
  )
  level.map_add_object_spot_ser(
    sobj.id, "level_changer4", "В Красный лес"
  )
  local sobj2 = amk_anoms.spawn_anomaly(
    "zone_teleport",
    sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
    { shtype = 0, radius = 1, center = { 0, 0, 0 } }
  )
  alife():assign_story_id( sobj2.id, story_ids.atp_to_red_forest_zone )
end

--[=[
function add_new_radar_na_red_forest()
  add_new_lc(
    story_ids.radar_to_red_forest, 9080, "В Красный лес",
    "info_way_arhara_radar_forest", 4
  )
end
--]=]


function add_new_chaes2_to_atp()
add_new_lc(97099,11300,"На АТП","info_way_arhara_chaes2_atp",2)
end
function add_new_village_to_limansk()
add_new_lc(11529,12993,"В Лиманск","info_way_arhara_village_limansk",4)
end
function add_new_village_to_hospital()
add_new_lc(11531,12994,"В Госпиталь","info_way_arhara_village_hospital",1)
end
function add_new_chaes_to_generator()
add_new_lc(97103,10857,"На Генераторы","info_way_arhara_chaes_generator",3)
end
function add_new_hospital_to_agroprom()
add_new_lc(97104,2219,"На Агропром","info_way_arhara_hospital_agroprom",3)
end


function add_new_agroprom_to_marsh1()
  if alife():story_object( story_ids.agroprom_marsh1 ) then return end
  local sobj = add_new_lc(
    story_ids.agroprom_marsh1, 4344, "На Болота",
    "info_way_arhara_agroprom_marsh1", 3
  )
  arhara_dialog.agro_boloto_imitator()
end


function add_new_bar_to_atp()
  local sobj = add_new_lc(
    story_ids.bar_atp_level_changer, 6453, "На АТП", "info_way_arhara_bar_atp",
    4
  )
  amk_anoms.spawn_anomaly(
    "zone_teleport",
    sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
    { shtype = 0, radius = 1, center = { 0, 0, 0 } }
  )
  local lc = sobj:get_level_changer()
  ASSERT(
    lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
  )
  lc.dest_game_vertex_id  = 2807
  lc.dest_level_vertex_id = 254907
  lc.dest_position        = vector():set( -84.73,-2.50,-345.16 )
  lc.dest_direction       = vector():set( 0, 0, 0 )
end


function add_new_gener_to_pripyat()
  local sobj = add_new_lc(
    story_ids.gener_pripyat_level_changer, 1830, "В Центральную Припять",
    "info_way_arhara_gener_pripyat", 3
  )
  local lc = sobj:get_level_changer()
  lc.dest_game_vertex_id  = 2151
  lc.dest_level_vertex_id = 8430
  lc.dest_position        = vector():set( -115.12, -0.57, 240.81 )
end


function add_new_chaes2_to_chaes()
  if not alife():story_object( story_ids.chaes2_chaes_level_changer ) then
    local sobj = add_new_lc(
      story_ids.chaes2_chaes_level_changer, 11299, "На ЧАЭС-1",
      "info_way_arhara_chaes2_chaes", 3
    )
    local lc = sobj:get_level_changer()
    lc.dest_game_vertex_id  = 2371
    lc.dest_level_vertex_id = 10374
    lc.dest_position        = vector():set( -43.05, -0.10, -72.22 )
  end
  if not alife():story_object( story_ids.chaes_chaes2_level_changer ) then
    dsh_hand_teleporter.create_level_changer(
      story_ids.chaes_chaes2_level_changer,
      { -43.03, -0.10, -69.23 }, 10378, 2371, "level_changer1", "На ЧАЭС-2",
      { -41.17, -0.03, 59.09 }, 10104, 2517, { 0, 0, 0 }, 0, 1.0
    )
  end
end


function add_new_gener_to_hospital()
add_new_lc(11521,1558,"В Госпиталь","info_way_arhara_gener_hospital",1)
end
function add_new_warlab_to_generators()
add_new_lc(97096,14782,"На Генераторы","info_way_arhara_warlab_generators",1)
end


function add_new_limansk_to_generators()
  add_new_lc(
    story_ids.limansk_to_generators, 12451, "На Генераторы",
    "info_way_arhara_limansk_generators", 2
  )
end


function add_new_forest_to_warlab()
add_new_lc(97108,14320,"В Варлаб","info_way_arhara_forest_warlab",1)
end

-- переходы МГ
function add_new_dcity()
  local sobj = add_new_lc(
    story_ids.lima_to_dead_city, 12395, "В Мёртвый Город",
    "info_way_arhara_lima_dcity", 2
  )
  local lc = sobj:get_level_changer()
  ASSERT(
    lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
  )
  lc.dest_game_vertex_id  = 3593
  lc.dest_level_vertex_id = 100962
  lc.dest_position        = vector():set( -239.38876342773, -2.0321259498596, 300.58901977539 )
  lc.dest_direction       = vector():set( 0, -2.5, 0 )
  alife():teleport_object(
    sobj.id, vector():set( -52.046, -10.754, -184.263 ), 45067, 3016
  )
  sobj = add_new_lc(
    story_ids.dcity_to_limansk, 1287, "В Лиманск",
    "info_way_arhara_dcity_limansk", 1
  )
  lc = sobj:get_level_changer()
  ASSERT(
    lc, "[%s]: level_changer not found for %s", script_name(), sobj:name()
  )
  lc.dest_game_vertex_id  = 2991
  lc.dest_level_vertex_id = 2669
  lc.dest_position        = vector():set( -52.171314239502, -10.753299713135, -180.0738067627 )
  -- add_new_lc( 97110, 1288, "На АТП", "info_way_arhara_dead_city_atp", 2 )
  -- add_new_lc( 97111, 1289, "На Дикую Территорию", "info_way_arhara_dcity_rostok", 3 )
  -- add_new_lc( 97112, 302, "В Мёртвый Город", "info_way_arhara_atp_dead_city", 4 )
end


function add_new_dcity_to_zaton()
  add_new_lc(
    story_ids.dcity_to_zaton, 1446, "На Затон", "info_way_arhara_dcity_zaton",
    2
  )
end


-- Убрана привязка к номеру секции - переделано на spawn_story_id. 
-- levchn больше не нужен. 
-- При добавлении сюда новых переходов прописывать им в алспавне
-- spawn_story_id, равный story_id.
function add_new_lc( levch, levchn, levchm, info, dir )
  local objt = alife():story_object( levch )
  if not objt then
    -- alife():create( levchn )
    alife():create( alife():spawn_id( levch ) )
  end
  local obj = alife():story_object( levch )
  if obj then
    level.map_add_object_spot_ser(
      obj.id, "level_changer" .. tostring( dir ), levchm
    )
    if info and db.actor:dont_has_info( info ) then
      db.actor:give_info_portion( info )
      info_received()
    end
  end
  return obj
end


function add_new_military_false()
local obj = alife():story_object(5212)
level.map_add_object_spot_ser(obj.id, "level_changer1","На ЧАЭС")
  db.actor:give_info_portion("info_way_false")
  info_received()
end
function out_new_lc(levch,info)
  if not db.actor:has_info(info) then
    local objt = alife():story_object(levch)
    if objt then
      alife():release(objt)
    end
  end
end
function add_new_item_in(item,sidlh)
local nps = sidlh.id
amk.spawn_item_in_inv(item,nps) 
end
local krysyk_treasure
function add_new_lcitem()
amk.spawn_item("sak_document",vector():set(350,-51.74,-24.45),2031,93051) -- документ под трупом ученого в рж лесу
amk.spawn_item("rad_document6",vector():set(621.95,-42.64,187.38),1910,224619) -- дело в кунге у монолитовцув
amk.spawn_item("amk_zapiska",vector():set(-132.93,11.04,-203.2),629,105467) --записка на третьем этаже Агропрома
amk.spawn_item("sak_document2",vector():set(-80,-1.30,153),163,187916) -- документ  под жд насыпью Кордона
amk.spawn_item("garbage_pda",vector():set(-226,-7.37,-132.36),252,208345) -- ПДА в лагере бандитов на свалке
amk.spawn_item("rad_document6",vector():set(-28.4,-0.26,-173.55),676,211656) -- дело в вагончике Агропрома
amk.spawn_item("rad_pda",vector():set(530.7,-49.41,-241.61),2061,180657) -- ПДА в вагончике на Радаре
amk.spawn_item("rad_document6",vector():set(-139.6,-25.03,-355.6),19,116593) -- дело на кордоне
amk.spawn_item("sak_book4",vector():set(-3.77,-4.25,191.19),2195,97948) --книга доктора
--amk.spawn_item("m_inventory_seif",vector():set(306.47,-39.39,-26.22),1930,69058)
	for a=1000,20000,1 do
		local obj=alife():object(a)
		if obj and ((string_find(obj:name(),"af_") and not string_find(obj:name(),"esc_af_")  and not string_find(obj:name(),"pri_af_" ) and not string_find(obj:name(),"af_dumm")) or string_find(obj:name(),"esc_wpn")) then
			alife():release(obj,true)
		end
	end
end
function add_ak47()
amk.spawn_item("wpn_ak47",vector():set(108.5,7.74,-9.07),987,304788)
end
function add_doktor_book()
amk.spawn_item("sak_book4",vector():set(-3.49,-4.26,191.34),2195,96166)
end
function add_notebook()
amk.spawn_item("notebook",vector():set(23.87,-5.65,-18.38),1140,6287) 
end


-- Akill begin Изменены к-ты спавна дипломата + монстры
function add_diplomat()
  alife():create(
    "taynik_diplomat",
    vector():set( -100.60708618164, 22.614040374756, -24.21527671814 ),
    505, 1529
  )
  akill.x16_mutant_spawn()
end
-- Akill end


function add_computer()
amk.spawn_item("computer",vector():set(-114.96,-2.23,8.18),2248,8511) 
end
function add_new_103item()
amk.spawn_item("quest_case_06",vector():set(-196.5,2.48,92.88),678,40284) --кейс в кунге дезертира
end
function add_sak_plan()
amk.spawn_item("sak_plan",vector():set(-213.13,2.96,92.58),535,22245) -- мешок плана в кунге дезертира 
end
function add_krot_pda()
amk.spawn_item("agroprom_pda",vector():set(254.866424,-0.201872,79.064804),498,428654) --ПДА в ЖД тоннеле Агропрома
end
function add_und_pda()
amk.spawn_item("und_pda",vector():set(-45.12,-4.01,-30.08),718,4466) --ПДА в подземелье Агропрома
end
function add_seif()
amk.spawn_item("inventory_sakbox_03",vector():set(15.52,-12.43,8.59),1156,5132) --Сейф в подземелье X-18
end
function give_seif(obj)
amk.remove_item_from_inventory_by_name(obj,db.actor)
amk.spawn_item("m_inventory_seif",vector():set(34.37,-3.37,-37.29),1997,21736)  --передача сейфа
end


-- Akill begin Изменены к-ты спавна декодера + монстры
function add_decoder()
  -- декодер в  X-16 возле главного пульта
  alife():create(
    "taynik_decoder1",
    vector():set( -60.656967163086, 19.434055328369, -16.232734680176 ),
    1661, 1530
  )
  akill.x16_mutant_spawn()
end
-- Akill end


function add_gauss() -- Гаусс-пистолет  в ТД
  local sobj = alife():object( "val_rob_leader" )
  if sobj then
    alife():create(
      "wpn_gungauss",
      sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id, sobj.id
    )
  else
    local sobj = alife():create(
      "wpn_gungauss", vector():set( -126.11, 0.91, -533.55 ), 31356, 836
    )
    dsh.clear_useful_for_ai( sobj )
  end
end


--function add_medusa_green()
--amk.spawn_item("af_medusa_green",vector():set(260.59,-9.82,-135),404,373051) --Изумрудная медуза на свалке
--end
function add_medusa_green()
local obj = alife():create("af_medusa_green",vector():set(5.3799324035645,-0.00055783987045288,222.37449645996),192846,2883)
end
function add_pellicle_red()
amk.spawn_item("af_dummy_pellicle_red",vector():set(-239.99,4.85,99.93),1362,13956) --Изумрудная медуза на Ростке
end
--function add_vyvert_green()
--amk.spawn_item("af_vyvert_green",vector():set(115.13,4.83,-409.26),942,311330) --Изумрудный выверт в ТД
--end


function add_blood_green()
  amk.spawn_item("af_blood_green",vector():set(55.34,1.27,40.89),1511,68094) --Изумрудная кровь на Янтаре
  battle.create_enemies(
    {
      { "yan_zombied_respawn_1",vector():set(75.406539916992,0.34422329068184,23.229085922241),79415,1512 },
      { "yan_zombied_respawn_2",vector():set(41.926971435547,0.037857890129089,20.751808166504),60400,1445 },
      { "tushkano_normal",vector():set(106.78483581543,-8.8652667999268,-212.50025939941),96215,1472 },
      { "tushkano_normal",vector():set(106.78483581543,-8.8652667999268,-212.50025939941),96215,1472 },
      { "tushkano_normal",vector():set(106.78483581543,-8.8652667999268,-212.50025939941),96215,1472 },
      { "tushkano_normal",vector():set(106.78483581543,-8.8652667999268,-212.50025939941),96215,1472 },
      { "tushkano_normal",vector():set(106.78483581543,-8.8652667999268,-212.50025939941),96215,1472 },
      { "burer_normal",vector():set(58.236850738525,-0.84842598438263,-20.68497467041),69709,1508 },
      { "burer_normal",vector():set(56.451206207275,0.046565324068069,-60.764457702637),68827,1516 },
      { "burer_normal",vector():set(27.053871154785,0.084938794374466,-9.735237121582),52620,1507 },
      { "burer_normal",vector():set(90.896003723145,0.028825730085373,12.075715065002),87194,1513 },
      { "burer_normal",vector():set(15.076522827148,0.030788093805313,19.65348815918),46805,1445 },
    }
  )
end


function add_battery_red()
amk.spawn_item("af_dummy_battery_red",vector():set(668.9,-45.79,-39.93),1896,227187) --Рубиновая батарейка на Радаре 
end


function add_two_corpses()
  local sobj = amk.spawn_item( "yan_ecolog_respawn_2",vector():set(187.84,5.18,-360.68),938,386349 )
  local pk   = get_netpk( sobj )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  local data = pk:get()
  data.health     = 0
  data.upd.health = 0
  pk:set( data )
  alife():assign_story_id( sobj.id, 48800 )
  alife():create( "scaintist_docs",sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id, sobj.id )
  sobj = amk.spawn_item( "yan_ecolog_respawn_2",vector():set(187.66,5.03,-375.97),938,386327 )
  pk   = get_netpk( sobj )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  data.health     = 0
  data.upd.health = 0
  pk:set( data )
  alife():assign_story_id( sobj.id, 48801 )
  amk.spawn_item( "inventory_sakbox_05",vector():set(176.83,8.37,-375.96),938,377568 )
  battle.create_enemies(
    {
      { "borov_11_chimera_normal", vector():set( 176.83, 8.37, -375.96 ), 377568, 938 },
      { "borov_11_chimera_normal", vector():set( 176.83, 8.37, -375.96 ), 377568, 938 },
    }
  )
end


function add_scaintist_body()
  local sobj = amk.spawn_item( "yan_ecolog_respawn_2",vector():set(-46.53,-2.2,-98.36),2258,53082 )
  local pk   = get_netpk( sobj )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  local data = pk:get()
  data.health     = 0
  data.upd.health = 0
  pk:set( data )
  alife():assign_story_id( sobj.id, 48802 )
  alife():create( "scaintist_pda",sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id, sobj.id )
end


function add_agroprom_box()
	for a=1000,10000,1 do
	local obj=alife():object(a)
		if (obj and obj.name and obj:name() == "agr_quest_case_02") then
		alife():release(obj, true)
		--dbglog("keis: "..a) ~5665
		end
	end	
	--amk.spawn_item("quest_case_02",vector():set(18.76,-2.23,-219.12),436,259029)
	dialogs.relocate_item_section(db.actor, "quest_case_02", "in")
end


-- Akill begin
function add_kontainer()
  alife():create("inventory_sakbox_05",vector():set(467.15960693359,-48.180206298828,-294.86013793945),155265,2063)
  battle.create_enemies(
    {
      { "chimera_normal",vector():set(486.33248901367,-48.54475402832,-236.83911132813),160400,2058 },
      { "zombie_normal",vector():set(544.77508544922,-50.461318969727,-251.75929260254),187962,2114 },
      { "zombie_normal",vector():set(545.21411132813,-57.409252166748,-226.63201904297),188356,1873 },
      { "zombie_normal",vector():set(568.07763671875,-60.318313598633,-221.79908752441),199631,1873 },
      { "chimera_normal",vector():set(514.51159667969,-50.558048248291,-283.08618164063),172856,2060 },
      { "chimera_normal",vector():set(478.98034667969,-54.138397216797,-254.24066162109),157244,2111 },
      { "controller_senator",vector():set(543.19293212891,-53.148582458496,-239.98249816895),187241,2114 },
    }
  )
end


function agroprom_wpm()
local obj = alife():story_object(9115)
alife():create("wpn_vintorez_m1",obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id, obj.id)
	alife():create("zasada_tonnel_agro_2",vector():set(-120.86868286133,14.998485565186,-192.318359375),118958,642)
	alife():create("agro_elite_rpg",vector():set(-170.82591247559,5.3163747787476,-182.25466918945),66088,667)
	alife():create("zasada_tonnel_agro_1",vector():set(-121.89569091797,4.9972257614136,-198.87106323242),118189,617)
	alife():create("soldier_mines_regular",vector():set(-196.39508056641,7.3849902153015,-223.58135986328),39867,555)
	alife():create("soldier_mines_veteran",vector():set(-175.36352539063,7.3837895393372,-154.81077575684),61033,560)
	alife():create("soldier_mines_regular",vector():set(-106.75975036621,7.3841366767883,-136.29498291016),132868,696)
	alife():create("soldier_mines_veteran",vector():set(-108.10691833496,7.3828616142273,-207.12539672852),132051,552)
end
function add_books()
amk.spawn_item("sak_book1",vector():set(28.11,-12.07,38.93),1161,6530) 
amk.spawn_item("sak_book2",vector():set(-120.27,21.56,-32.65),1529,165) 
amk.spawn_item("sak_book3",vector():set(0.77,-19.45,24.89),2768,6203) 
end
function add_new_111item()
	alife():create("soldier_mines_veteran",vector():set(69.474830627441,0.55580735206604,25.300632476807),305190,671)
	alife():create("soldier_mines_regular",vector():set(63.35139465332,-0.20042996108532,-0.63388842344284),299977,462)
	alife():create("soldier_mines_veteran",vector():set(9.7593650817871,0.97461330890656,37.45044708252),250081,490)
	local obj = alife():create("dynamite",vector():set(54.160469055176,0.78570091724396,23.48705291748),292636,461)
	level.map_add_object_spot_ser(obj.id, "crlc_big", "Возможное местоположение динамита")
end
function dynamite_metka_delete()
  for a, obj in alife():objects() do
    if string.find(obj:name(),"dynamite") then
      level.map_remove_object_spot(obj.id,"crlc_big")
      break
    end
  end
end


function add_new_109item()
  alife():create(
    "quest_case_05",
    vector():set( 124.79997253418, 2.2573802471161, -263.01544189453 ),
    321655, 955
  )
  akill.kontrik_zasada_soldier()
  akill.kontrik_zasada_zombied()
end


-- Akill end
function info_received()
  amk.send_tip("","Новый путь!",0,10,"gen_info")
end
--function add_resiver()
--amk.spawn_item("sak_resiver",vector():set(-185.57,-3.58,94.89),338,39411) 
--end


function add_drug()
  amk.spawn_item(
    "dogfrend", vector():set( -6.71, 0.41, 247.19 ), 258, 170000
  )
end


function del_drug()
  for id, sobj in alife():objects() do
    if sobj:section_name() == "dogfrend" then
      alife():release( sobj )
      break
    end
  end
end


--function add_strelok_pda()
--amk.spawn_item("strelok_pda",vector():set(42.95,61.56,-26.25),2417,6406) 
--end
function info_strelok_pda()
  amk.send_tip("","Сталкер! Остановись!",0,10,"gen_info")
end
function info_artmod()
  amk.send_tip("","Новый артмод!",0,10,"gen_info")
end
function info_doktor()
  amk.send_tip("","Болотный доктор жив!",0,10,"gen_info")
end
function info_teleport()
  amk.send_tip("","Телепорт готов.",0,10,"gen_info")
end

local items_count=0
local itemin=nil

function have_item_namber(itm,need_namber)
	return amk_utils.inventory_search(itm, need_namber)
end


function create_items( npc, section, number )
  local created_items = {}
  for i = 1, number do
    local sobj = alife():create(
      section, 
      npc:position(),
      npc:level_vertex_id(), npc:game_vertex_id(),
      npc:id()
    )
    table.insert( created_items, sobj )
  end
  return created_items
end


-- Спавн в инвентарь гг с выдачей сообщения.
function create_items_actor( itm_section, number )
  local items = this.create_items( db.actor, itm_section, number )
  news_manager.relocate_item( db.actor, "in", itm_section, number )
  return items
end


-- функция удаления всех itm_section из инвентаря ГГ. Полезна, когда
-- количество неизвестно
function out_item_all( itm_section )
  amk_utils.out_items({ itm_section })
end


function out_item_namber( itm_section, need_number )
  amk_utils.out_items_number({
    [ itm_section ] = need_number
  })
end


function relocate_item_namber( stalker, itm_section, need_number )
  amk_utils.out_items_number({
    [ itm_section ] = need_number
  })
end


function make_kill_task_failed(actor,npc,p1,p2) 
  local nid=npc:id()
  if nid==db.actor:id() then
    nid=actor:id()
  end
  local targets=task_manager.amk_kill_targets()
  for n,v in pairs(targets) do
    if v.id==nid then
      task_manager.make_task_failed(v.task_id)
    end
  end  
end


function check_used_item( obj )
  local info
  if level.name() == "l03_agroprom" and obj:section() == "amk_zapiska" then
    add_new_escape_100()
    amk.drop_item( db.actor, obj )
    amk.remove_item( obj )
  elseif level.name() == "l10_radar" and obj:section() == "rad_document6" then
    db.actor:give_info_portion( "info_way107a" )
    amk.drop_item( db.actor, obj )
    amk.remove_item( obj )
  elseif level.name() == "l03_agroprom" and obj:section() == "rad_document6" then
    info = "info_artmod_rusty_thorn_buzz"
    amk.drop_item( db.actor, obj )
    amk.remove_item( obj )
    info_artmod()
  elseif level.name() == "l01_escape" and obj:section() == "rad_document6" then
    info = "info_artmod_rusty_kristall_mincer"
    amk.drop_item( db.actor, obj )
    amk.remove_item( obj )
    info_artmod()
  elseif level.name() == "l10_radar" and obj:section() == "sak_document" then
    db.actor:give_info_portion( "info_way106a" )
    info_received()
    amk.drop_item( db.actor, obj )
    amk.remove_item( obj )
  elseif
    level.name() ~= "l03_agroprom" and db.actor:has_info( "ratcatcher_order_done" )
  then
    info = "ratcatcher_out"
  elseif level.name() ~= "l05_bar" and db.actor:has_info( "info_way_false" ) then
    info = "informer_out"
  elseif
    db.actor:dont_has_info( "info_artmod_electra_flash_zharka" )
    and obj:section() == "sak_document2"
  then
    info = "info_artmod_electra_flash_zharka"
    info_artmod()
  elseif
    db.actor:dont_has_info( "info_artmod_drops_mincer" )
    and obj:section() == "garbage_pda"
  then
    info = "info_artmod_drops_mincer"
    info_artmod()
  elseif
    db.actor:dont_has_info( "info_artmod_ameba_mica_galant" )
    and obj:section() == "rad_pda"
  then
    info = "info_artmod_ameba_mica_galant"
    info_artmod()
  elseif
    db.actor:dont_has_info( "info_artmod_fireball_buzz" )
    and obj:section() == "volkodav_pda"
  then
    info = "info_artmod_fireball_buzz"
    info_artmod()
  elseif
    obj:section() == "outfit_bandit_m1"
    and db.actor:dont_has_info( "esc_shustryi_outfit" )
  then
    info = "esc_shustryi_outfit"
  elseif
    obj:section() == "sak_book4" and db.actor:dont_has_info( "doktor_alife" )
  then
    info = "doktor_alife"
    info_doktor()
  end
  if info and db.actor:dont_has_info( info ) then
    db.actor:give_info_portion( info )
  end
end


-- Akill последние 6 к-т новые
local point_drop={
    {x=-240, y=-7, z=300},
    {x=-250, y=-5, z=294},
	{x=55, y=18, z=157},
    {x=67, y=22, z=154},
	{x=7, y=-1, z=115},
    {x=12, y=1, z=125},
	{x=35, y=60, z=30}, 
	{x=17, y=50, z=35},
	{x=376, y=-1, z=15},
	{x=393, y=2, z=65},
	{x=80, y=8, z=-16},
	{x=88, y=12, z=-24},
	{x=7, y=3, z=11},
	{x=15, y=7, z=19},
	{x=-126, y=19, z=-28},
	{x=-134, y=23, z=-36}
	}

function check_droped_item(obj)
if db.actor==nil then
	return
end
	local actor = db.actor
-- arc_main.lose_item(obj)
local info=nil 
	local v = vector():set( 0, 0, 0 )
	if level.name()=="l07_military" and
		actor:has_info("yan_scientist_teleport_01_start") and
		obj:section()=="sak_resiver_yantar" and
		amk.check_npc_in_box(actor, point_drop[1],point_drop[2])~=false then
			info="yan_scientist_teleport_01_done"
			amk.remove_item(obj)
			amk.spawn_item("m_sak_resiver_yantar",v:set(-244.62,-5.98,299.94),1797,89408) 
	elseif level.name()=="l01_escape" and
		actor:has_info("yan_scientist_teleport_02_start") and
		obj:section()=="sak_resiver_yantar" and
		amk.check_npc_in_box(actor, point_drop[3],point_drop[4])~=false then
			info="yan_scientist_teleport_02_done"
			amk.remove_item(obj)
			amk.spawn_item("m_sak_resiver_yantar",v:set(62.99,29.23,154.39),97,359827) 
	elseif level.name()=="l11_pripyat" and
		actor:has_info("yan_scientist_teleport_03_start") and
		obj:section()=="sak_resiver_yantar" and
		amk.check_npc_in_box(actor, point_drop[5],point_drop[6])~=false then
			info="yan_scientist_teleport_03_done"
			amk.remove_item(obj)
			amk.spawn_item("m_sak_resiver_yantar",v:set(9.47,0.32,119.13),2166,113785)
	elseif level.name()=="l12_stancia" and
		actor:has_info("life_heart_sahar_start") and
		obj:section()=="sak_resiver_yantar" and
		amk.check_npc_in_box(actor, point_drop[9],point_drop[10])~=false then
			info="life_heart_sahar_have"
			amk.remove_item(obj)
			amk.spawn_item("m_sak_resiver_yantar",v:set(387.51,0.16,31.10),2384,168953)
-- Akill begin
	elseif level.name()=="l08u_brainlab" and
		db.actor:has_info("ohota_suker_start") and
		obj:section()=="poison_gaz_ballon" and
		amk.check_npc_in_box(actor, point_drop[11],point_drop[12])~=false then
			db.actor:give_info_portion("ohota_suker_have1")
			amk.remove_item(obj)
			alife():create("m_poison_gaz_ballon",v:set(84.25,10.17,-20.63),6077,1544)
	elseif level.name()=="l08u_brainlab" and
		db.actor:has_info("ohota_suker_start") and
		obj:section()=="poison_gaz_ballon" and
		amk.check_npc_in_box(actor, point_drop[13],point_drop[14])~=false then
			db.actor:give_info_portion("ohota_suker_have2")
			amk.remove_item(obj)
			alife():create("m_poison_gaz_ballon",v:set(11.52,5.59,15.10),4459,1537)
	elseif level.name()=="l08u_brainlab" and
		db.actor:has_info("ohota_suker_start") and
		obj:section()=="poison_gaz_ballon" and
		amk.check_npc_in_box(actor, point_drop[15],point_drop[16])~=false then
			db.actor:give_info_portion("ohota_suker_have3")
			amk.remove_item(obj)
			alife():create("m_poison_gaz_ballon",v:set(-130.45,21.56,-32.76),3,1529)
-- Akill end
	elseif level.name()=="l12u_sarcofag" and
		actor:has_info("strelok_pda_done") and
		dsh.is_af_alias_of( obj:section(), "af_gold_fish" ) and
		amk.check_npc_in_box(actor, point_drop[7],point_drop[8])~=false then
			amk_mod.af_flash(obj) get_sarcofag_stancia()
	elseif obj:section()=="af_life_heart" and
		actor:has_info("life_heart_final") then
		deadman_to_life(obj)
	--elseif obj:section()=="pda_art_mod" then pda_art_mod.f_pda_art_mod_use(obj)
	elseif obj:section()=="af_hl" then deadman_to_life(obj)
end 
	  if info==nil or actor:has_info(info) then
    return
  end
	  actor:give_info_portion(info)
end

function agr_ratcatcher__id()
for a=5000,6000,1 do
		local obj=alife():object(a)
		if (obj and obj.name and obj:name() == "agr_ratcatcher") then
		--dbglog("Entered: "..obj:name().." id "..a.." sid "..obj.m_story_id) -- id~5564
		amk.save_variable("agr_ratcatcher_id", a) 
		end
	end
end


-- список неписей, которых можно воскресить живым сердцем.
--
-- story_id   = story_id непися
--
-- _umer = true - у непися есть поршень с приставкой "_umer"
--
-- info  = дополнительные поршни, которые выдаются при смерти
--
-- script = функция, которая воскрешает непися при скриптовом спавне
--
-- при добавлении непися в эту таблицу в info_arhara_way нужно
-- добавить поршень "nu"..story_id, а также в алспауне прописать
-- spawn_story_id, равное story_id
local nepis = {
  -- Кордон
  -- Шустрый
  [     4 ] = {
    _umer = true,
    not_after_info = { "esc_shustryi_medusa_done" },
  },
  -- Лис
  [     5 ] = {
    _umer = true,
    not_after_info = { "esc_fox_medkit_done", "fox_kriss_done" },
  },
  [     6 ] = { _umer = true }, -- Волк
  -- Толик
  [     7 ] = { _umer = true, not_after_info = { "mil_volk_resiver_done" } },
  -- Петруха
  [     9 ] = { _umer = true, not_after_info = { "esc_petruha_toz_done" } },
  [    22 ] = { _umer = true, info = { "esc_fanat_die" } }, -- Фанат
  [    32 ] = { _umer = true }, -- Кузнецов
  -- Проводник
  [    92 ] = { _umer = true, not_after_info = { "esc_find_groza_done" } },
  -- Пантера на Кордоне
  [ 19032 ] = { trup = true, script = "dsh.make_pantera_alive" },
  -- Свалка
  -- Бес
  [   107 ] = {
    _umer = true,
    info  = { "gar_hellcar_death", "sar2_death_14" },
    not_after_info = { "gar_hellcar_outfit_done", "val_pula_ammo_done", },
  },
  [   115 ] = {                 -- Прапор
    _umer = true,
    not_after_info = { "gar_dolg_psevdodog_tail_done", "koloda_prapor", "seriy_helm", "prapor_peremirie" },
  },
  [  9509 ] = { info = { "death_artem" } }, -- Кулинар
  [  9510 ] = { info = { "death_voron" } }, -- Ворон
  -- Серый
  [   100 ] = {
    info = { "garbage_meetstalker_die", "sar2_death_10" },
    not_after_info = { "val_pula_ammo_done" },
  },
  -- Юрик
  [   104 ] = {
    _umer = true,
    info = { "gar_dm_novice_dead" },
    not_after_info = {
      "gar_dram_novice_mp5_m1_done",
      "gar_dram_novice_burer_hand_done",
    },
  },
  -- Агропром
  -- Крот
  [   302 ] = {
    _umer  = true,
    info   = { "agr_krot_dead", "sar2_death_19" },
    not_after_info = { "agr_krot_PDA_done" },
    script = "dsh.make_agr_krot_alive",
  },
  [   370 ] = { _umer = true, info = { "sar2_death_11"} }, -- Дезертир
  [  9506 ] = {},                                          -- Шерстюк
  -- Забытый Лес
  -- Химик труп
  [ 30118 ] = { trup = true, script = "buusty_dialog.himik_resurrect" },
  -- Химик живой
  [ 30124 ] = { script = " buusty_dialog.himik_resurrect" },
  -- Темная Долина
  [   400 ] = {                 -- Макс Любер
    _umer = true,
    not_after_info = { "doctor_drug_done" },
  },
  [   406 ] = {                 -- Пуля
    _umer = true,
    not_after_info = { "val_escort_scene_end", "val_escort_PDA_done" },
  },
  -- Мессер
  [   422 ] = {
    info = { "val_sos_dead", "val_sos_got_medkit" },
    not_after_info = { "val_sos_give_info" },
  },
  [   425 ] = { info = { "val_borov_dead" } },          -- Боров
  [  9507 ] = {},                                       -- Жила
  -- Бар
  -- Иванцов
  [   505 ] = {
    _umer = true,
    info = { "sar2_death_41" },
  },
  [   506 ] = { _umer = true, info = { "sar2_death_42" } }, -- Петренко
  -- Воронин
  [   507 ] = { _umer = true, info = { "sar2_death_43", "bar_voronin_dead" } },
  [   516 ] = { _umer = true }, -- Пличко
  [ 19805 ] = {},               -- Гарик
  [   515 ] = {},               -- Осведомитель
  [   504 ] = {},               -- Охотник
  [   510 ] = {              -- Бром (которому ружье принести нужно)
    not_after_info = { "info_amk_recipt_grandmother_glassbeards" },
    script_free = "dsh.free_bar_drunk_dolg",
  },
  [   607 ] = {},              -- Лысый
  -- [   519 ] = { _umer = true }, -- Барин
  -- [   571 ] = {},               -- Арни
  [  9619 ] = {},               -- Фримен
  [   518 ] = {},               -- Киценко (командир южного блокпоста)
  [  9613 ] = {},               -- Захар
  -- Дикая Территория
  -- Круглов на ДТ
  [   503 ] = { info = { "bar_heli_scene_professor_die", "sar2_death_13" } },
  -- Янтарь
  [   900 ] = { info = { "yan_scientist_die" } }, -- Круглов на Янтаре
  [ 19028 ] = { info = { "chernomor_umer"} }, -- Черномор вылеченный
  -- Армейские Склады
  [   702 ] = { _umer = true }, -- Макс
  [   707 ] = { _umer = true }, -- Лукаш
  [   728 ] = { _umer = true }, -- Повар
  [   734 ] = { _umer = true }, -- Скряга
  [ 777888 ] = {},            -- Шуруп
  -- Альфа 2012 (охранник на входе на базу Свободы)
  [ 19810 ] = {
    not_after_info = { "raritet_ykut" },
    keep = true,
  },
  -- Кэп (командир Барьера)
  [   724 ] = {
    not_after_info = { "mil_fblockpost_quest_reward" },
  },
  -- [   725 ] = { trup = true }, -- Угрюмый из Деревни Кровососов
  -- ЧАЭС2
  -- Брат Тени Монолита
  [  9969 ] = {_umer  = true, script = "kostya_dialog.tm_brother_2chaes_spawn" },
  -- Болота
  [ 19811 ] = {                 -- Дьяк
    info = { "dyak_dead" },
    not_after_info = {
      "dyak_help_done",
      "koloda_dyak",
      "ohota_biblik_done",
    },
  },
  [ 14003 ] = { info = { "kalmyak_dead" } }, -- Калмык
  -- ВП
  -- Акилл
  [ 21005 ] = { info = { "akill_npc_dead" }, script = "akill.akill_npc_spawn" },
  -- Варлаб
  [ 19809 ] = {},             -- Сольвадор
  -- НЗ
  [  9973 ] = {},              -- Старик
  [  9974 ] = {},              -- Отшельник
  -- Генераторы
  [ 19806 ] = { _umer = true }, -- Земляк
  [ 19807 ] = {},               -- Андерсен

  -- Раненный Денис из КЛ
  [ story_ids.forest_wound ] = {
    not_after_info = { "denis_wound_next" },
  },

  -- Колмогор
  [ story_ids.kolmogor ] = {
    not_after_info  = { "derevny_zashita_done" },
    -- удаляем после ухода из Старой Деревни
    release_on_kick = true,
  },
}

function deadman_to_life( art )
  for sid, v in pairs( nepis ) do
    local obj = alife():story_object( sid )
    if
      obj and ( not obj:alive() )
      and obj.level_name == level.name()
      and obj.position:distance_to( db.actor:position() ) < 2
    then
      -- снимаем нужные поршни
      if not v.trup then
        db.actor:disable_info_portion( "nu" .. tostring( sid ) )
      end
      if v._umer then
        db.actor:disable_info_portion( obj:name() .. "_umer" )
      end
      if v.info then
        for b = 1, table.getn( v.info ) do
          db.actor:disable_info_portion( v.info[ b ] )
        end
      end
      --  воскрешаем
      level.start_stop_menu( level.main_input_receiver(), true )
      amk_mod.af_flash( art )
      local npc_name = archievements.get_npc_name( obj )
      alife():release( obj )
      local sobj
      if v.script then
        local f, msg = loadstring( "return " .. v.script .. "(...)" )
        ASSERT( f, msg )
        sobj = f()
      else
        sobj = alife():create( alife():spawn_id( sid ) )
      end
      if sobj then
        sobj = alife():object( sobj.id )
      else
        sobj = alife():story_object( sid )
      end
      if sobj.need_brain_update then
        smart_terrain.smart_brain_update( sobj )
        sobj.need_brain_update = false
      end
      amk.send_tip(
        "%c[255,0,255,0]Обнаружен новый сталкер: " .. npc_name
          .. ". Добавлен в базу данных сети.%c[default]",
        "ЛОКАЛЬНАЯ СЕТЬ", 0, 15, "questman_death"
      )
      return
    end
  end
end


function has_all_info( t )
  for _, info in ipairs( t ) do
    if not db.actor:has_info( info ) then return false end
  end
  return true
end


function nepis_umer( npc )
  local sid = npc:story_id()
  if not sid then return end
  local data = nepis[ sid ]
  if data then
    local process = true
    if data.not_after_info and has_all_info( data.not_after_info ) then
      process = false
    end
    if process then
      local obj  = alife():object( npc:id() )
      ASSERT( obj, "alife():object() not found for %s", npc:name() )
      local name = obj:name()
      local nu   = "nu" .. tostring( sid )
      if data._umer then
        db.actor:give_info_portion( name .. "_umer" )
      end
      if ( not data.trup ) and ( not has_alife_info( nu ) ) then
        db.actor:give_info_portion( nu )
        archievements.send_umer_info( obj )
      end
    end
  end
  if
    has_alife_info( "mil_Svoboda_trader_plan_faze" )
    and has_alife_info( "agr_ratcatcher_umer" )
  then
    db.actor:give_info_portion( "mil_Svoboda_trader_plan_2faze" )
    add_sak_plan()
  elseif
    (
      has_alife_info( "esc_vagon_wounded_umer" )
      and has_alife_info( "esc_stalker_fanat_umer" )
      or  has_alife_info( "esc_wolf_umer" )
    )
    and not has_alife_info( "mil_volk_resiver_fail" )
  then
    db.actor:give_info_portion( "mil_volk_resiver_fail" )
  elseif
    (
      has_alife_info( "bar_dolg_ivancov_umer" )
      or has_alife_info( "mil_freedom_member0021_umer" )
    )
    and not has_alife_info( "bar_ivancov_rg6_fail" )
  then
    db.actor:give_info_portion( "bar_ivancov_rg6_fail" )
  end
end


function nepis_free()
  for sid, v in pairs( nepis ) do
    local need_kick, sobj = false
    if v.not_after_info and not v.keep then
      sobj      = alife():story_object( sid )
      need_kick = sobj and sobj.level_name ~= level.name()
        and has_all_info( v.not_after_info )
    end
    if need_kick then
      if v.release_on_kick then
        log2(
          "[%s]: release %s (%s)", script_name(), sobj:name(), sobj.level_name
        )
        dsh.release_mob( sobj )
      elseif v.script_free then
        local f, msg = loadstring( "return " .. v.script_free .. "(...)" )
        ASSERT( f, msg )
        f( sobj )
      else
        make_nepis_free( sobj )
      end
    end
  end
end


function make_nepis_free( sobj )
  log2(
    "[%s]: make %s (%s) free", script_name(), sobj:name(), sobj.level_name
  )
  local pk = get_netpk( sobj, 1 )
  ASSERT( pk and pk:isOk(), "can't read netpacket of %s", sobj:name() )
  local data = pk:get()
  data.base_out_restrictors = ""
  data.custom_data:setTable( {} )
  data.story_id = -1
  pk:set( data )
  smart_terrain.unregister_npc( sobj )
  dsh.clear_smart_terrain_conditions( sobj )
end




function about_life_heart_done()
  if
    (
      has_alife_info( "about_life_heart_sahar" )
      and has_alife_info( "about_life_heart_sidor" )
      and has_alife_info( "about_life_heart_barman" )
    )
    and not has_alife_info( "about_life_heart_done" )
  then
    db.actor:give_info_portion( "about_life_heart_done" )
  end
end


-- проверка для уборщика по списку воскрешаемых ЖС
function can_be_resurrected( obj )
  local data = nepis[ obj.m_story_id ]
  if data then
    if data.not_after_info then
      return not has_all_info( data.not_after_info )
    end
    return true
  end
  return false
end


-- проверка что все квестовики живы
function all_questmen_alive()
  for a = 1, table.getn( nepis ) do
    local obj = alife():story_object( nepis[ a ].story_id )
    if obj and not obj:alive() then return false end
  end
  return true
end


function af_zone_off(af)
 local anom=amk_anoms.get_nearest_anomaly(db.actor)
 local sid=alife():object(anom)
  level.add_pp_effector("teleport.ppe", 1524, false)
  amk.remove_item(af)
  alife():release(sid,true)
end
function inv_item_cond(item,val)
local obj=db.actor:object(item)
	if obj~=nil then
	  obj:set_condition(val)
	end
end


local teleport_points = {
  points_kordon = {
    { position={x=-244.69,y=-14.27,z=-16.33},gv=67,lv=12579 },
    { position={x=107.54,y=-7.14,z=1.09},gv=119,lv=408816   },
    { position={x=71.48,y=1.92,z=158.79},gv=96,lv=362726    },
    { position={x=33.69,y=5.02,z=407.89},gv=246,lv=565356   },
    { position={x=220.57,y=7.62,z=100.55},gv=152,lv=511605  },
  },
  points_yantar = {
    { position={x=165.06,y=-8.19,z=-103.95},gv=1442,lv=131181 },
    { position={x=92.58,y=0.02,z=-39.23},gv=1515,lv=87813     },
    { position={x=34.48,y=0.04,z=18.19},gv=1445,lv=56341      },
    { position={x=24.61,y=0.02,z=-62.60},gv=1505,lv=51069     },
    { position={x=-60.17,y=-10.21,z=-202.66},gv=1447,lv=17529 },
  },
  points_pripat = {
    { position={x=49.78,y=-3.6,z=120.99},gv=2166,lv=161768   },
    { position={x=191.20,y=-2.0,z=219.52},gv=2219,lv=260280  },
    { position={x=164.51,y=-3.89,z=80.83},gv=2145,lv=250751  },
    { position={x=-97.65,y=-2.4,z=71.81},gv=2140,lv=18233    },
    { position={x=116.64,y=-0.61,z=216.98},gv=2163,lv=226288 },
  },
  points_military = {
    { position={x=81.65,y=-12.57,z=60.67},gv=1558,lv=379105   },
    { position={x=-35.96,y=-21.29,z=375.80},gv=1821,lv=272475 },
    { position={x=-264.86,y=-22.6,z=275.85},gv=1797,lv=72698  },
    { position={x=-340.59,y=-13.62,z=388.84},gv=1847,lv=12469 },
  },
  points_stancia = {
    { position={x=374.82,y=0,z=33.345},gv=2384,lv=161393 },
  },
  out_points_kordon_sak = {
    { position={x=-210,y=-20.53,z=-145.78},gv=61,lv=43273 },
  },
  out_points_kordon = {
    { position={x=301.11,y=13.31,z=276.43},gv=246,lv=565356 },
  },
  out_points_yantar = {
    { position={x=-60.78,y=-13.02,z=-253.92},gv=1454,lv=17204 },
  },
  out_points_pripat = {
    { position={x=52.17,y=-3.5,z=120.94},gv=2166,lv=164012 },
  },
  out_points_military = {
    { position={x=-94.71,y=-20.55,z=229.54},gv=1734,lv=220072 },
  },
  out_points_sarcofag = {
    { position={x=23.58,y=56,z=25.68},gv=2417,lv=5160 },
  },
}

function get_kordon_military() get_teleport("kordon","military",1,9121) end
function get_kordon_yantar() get_teleport("kordon","yantar",1,9121) end
function get_kordon_pripyat() get_teleport("kordon","pripat",1,9121) end
function get_pripyat_military() get_teleport("pripat","military",1,9122) end
function get_pripyat_yantar() get_teleport("pripat","yantar",1,9122) end
function get_pripyat_kordon() get_teleport("pripat","kordon",1,9122) end
function get_military_kordon() get_teleport("military","kordon",1,9123) end
function get_military_pripyat() get_teleport("military","pripat",1,9123) end
function get_military_yantar() get_teleport("military","yantar",1,9123) end
function get_yantar_military() get_teleport("yantar","military",1,9124) end
function get_yantar_kordon() get_teleport("yantar","kordon",1,9124) end
function get_yantar_pripyat() get_teleport("yantar","pripat",1,9124) end
function get_kordon_militaryr() get_teleport("kordon","military",0,9121) end
function get_kordon_yantarr() get_teleport("kordon","yantar",0,9121) end
function get_kordon_pripyatr() get_teleport("kordon","pripat",0,9121) end
function get_pripyat_militaryr() get_teleport("pripat","military",0,9122) end
function get_pripyat_yantarr() get_teleport("pripat","yantar",0,9122) end
function get_pripyat_kordonr() get_teleport("pripat","kordon",0,9122) end
function get_military_kordonr() get_teleport("military","kordon",0,9123) end
function get_military_pripyatr() get_teleport("military","pripat",0,9123) end
function get_military_yantarr() get_teleport("military","yantar",0,9123) end
function get_yantar_militaryr() get_teleport("yantar","military",0,9124) end
function get_yantar_kordonr() get_teleport("yantar","kordon",0,9124) end
function get_yantar_pripyatr() get_teleport("yantar","pripat",0,9124) end
function get_sarcofag_stancia() get_teleport("sarcofag","stancia",1,9125) end

function get_teleport( pos_out, pos_in, made, sidlc )
  local a = teleport_points[ "out_points_" .. pos_out ][ 1 ]
  local b = teleport_points[ "points_" .. pos_in  ]
  if made == 0 then
    b = b[ math_random( table.getn( b ) ) ]
  elseif made == 1 then
    b = b[ 1 ]
  end
  for _, sid in ipairs({ story_ids.level_changer, story_ids.level_changer_zone }) do
    local sobj = alife():story_object( sid )
    if sobj then
      alife():release( sobj )
    end
  end
  dsh_hand_teleporter.create_level_changer(
    story_ids.level_changer,
    vector():set( a.position.x, a.position.y, a.position.z ), a.lv, a.gv,
    nil, nil,
    vector():set( b.position.x, b.position.y, b.position.z ), b.lv, b.gv,
    vector():set( 0, 0, 0 ), 1, 5
  )
  local sobj = amk_anoms.spawn_anomaly(
    "zone_teleport",
    vector():set( a.position.x, a.position.y, a.position.z ), a.lv, a.gv,
    { shtype = 0, radius = 1, center = { 0, 0, 0 } }
  )
  alife():assign_story_id( sobj.id, story_ids.level_changer_zone )
end


-- часы---------------ON------------------------
function show_time( redraw )
  local hud = get_hud()
  local cs  = hud:GetCustomStatic( "hud_show_time" )
  if redraw == true and cs then
    hud:RemoveCustomStatic( "hud_show_time" )
    cs = nil
  end
  if not bind_stalker.scopeUsed then
    if not cs then
      hud:AddCustomStatic( "hud_show_time", true )
      cs = hud:GetCustomStatic( "hud_show_time" )
    end
    local time_h = level.get_time_hours()
    local time_m = level.get_time_minutes()
    local msg = "" .. ( time_h >= 10 and "" or "0" ) .. "%d:"
      .. ( time_m >= 10 and "" or "0" ) .. "%d\\n"
    cs:wnd():SetText( string.format( msg, time_h, time_m ) )
  else
    if cs then
      hud:RemoveCustomStatic( "hud_show_time" )
    end
  end
end
-- часы----------------OFF---------------------------

function switch_timer_stancia()
	for a=2000,2100,1 do
		local obj=alife():object(a)
		if (obj and obj.name and obj:name() == "aes_space_restrictor_timer") then
		local pk   = get_netpk( obj, 1 )
		ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", obj:name() )
		local data = pk:get()
		--dbglog("Entered: "..obj:name().." id-"..a.." sid-"..obj.m_story_id) --id~2031
		data.custom_data:setString( "[logic]\ncfg = scripts\\aes\\aes_space_timer.ltx" )
		pk:set( data )
		end
	end
end
function switch_mil_matugalnik()
	for a=10500,11500,1 do
		local obj=alife():object(a)
		if (obj and obj.name and obj:name() == "mil_physic_destroyable_object_0046") then
		local pk   = get_netpk( obj, 1 )
		ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", obj:name() )
		local data = pk:get()
		--dbglog("Entered: "..params.custom)
		--dbglog("Entered: "..obj:name().." id-"..a.." sid-"..obj.m_story_id) --id~11017
		data.custom_data:setString( "[logic]\ncfg = scripts\\mil\\matugalnik.ltx" )
		--dbglog("Entered: "..params.custom)
		pk:set( data )
		end
	end
end
function add_3repair_item_outfit()
	sak.create_items_actor("repair_item_outfit",3)
end
function add_3repair_item_weapon()
	sak.create_items_actor("repair_item_weapon",3)
end
function add_repair_item_outfit()
	sak.create_items_actor("repair_item_outfit",1)
end
function add_repair_item_weapon()
	sak.create_items_actor("repair_item_weapon",1)
end
function add_10repair_item_outfit()
	sak.create_items_actor("repair_item_outfit",10)
end
function add_10repair_item_weapon()
	sak.create_items_actor("repair_item_weapon",10)
end
function add_medkit(first_speaker, second_speaker)
     dialogs.relocate_item_section(second_speaker, "medkit", "in")
     dialogs.relocate_item_section(second_speaker, "snotvornoe_tele", "in")
end 
function set_community(actor, npc)
	db.actor:set_character_community("stranger", 0, 0)
end
function drink_vodka()
	db.actor:eat(db.actor:object("vodka"))
end
function take_trasure(npc, npc1)
	treasure_manager.get_treasure_manager():dialog(npc)
end


function have_trasure( first_speaker, second_speaker )
  local tname = "sak.have_trasure_delayed"
  if ogse_st_mgr.timer_exists( tname ) then
    db.actor:give_info_portion( "havent_sak_treasure" )
  else
    local tres = 80
    local ran  = dsh.get_next_random( "sak.have_trasure.rnd", 100 )
    if ran > tres and dsh_ogse_relations.has_enough_reputation( true ) then
      db.actor:give_info_portion( "have_sak_treasure"   )
    else
      db.actor:give_info_portion( "havent_sak_treasure" )
    end
    dsh.start_gtimerDHMS(
      tname,
      0, math.random( 3, 20 ), 0, 0,
      "sak.have_trasure_delayed"
    )
  end
end
function have_trasure_delayed() end


function zombie_checkup()
  if not db.actor then return end
  archievements.acv_count_event( "acv_fzom", 100, "Друг зомби" )
  local rnd = dsh.get_next_random( "sak.zombie_checkup" )
  if rnd < 0.7 then return end
  local af_serpantin = inventory.on_belt_obj( "af_serpantin" )
  if af_serpantin then
    for _, af in ipairs( af_serpantin ) do
      local af_cond = af:condition()
      if af_cond > 0 then
        if af_cond > 0.01 then
          dsh.set_condition( af, af_cond - 0.01 )
        else
          dsh_art_degrad.degrade_artefact( af )
        end
        return
      end
    end
  end
  local h = hit()
  h:bone( "bip01_spine" )   -- чтобv учитvвалась броня
  h.draftsman = db.actor
  h.direction = vector():set( 0, 0, 0 )
  h.type      = hit.telepatic
  h.power     = 0.3 + math.random() / 2
  h.impulse   = 1.0
  db.actor:hit( h )
  h.type      = hit.strike
  db.actor:hit( h )
  h.type      = hit.radiation
  db.actor:hit( h )
  level.add_pp_effector( "alcohol.ppe", 100, false )
  local sounds = {
    [[characters_voice\human_01\stalker\fight\hit\hit_1]],
    [[characters_voice\human_01\stalker\fight\hit\hit_2]],
    [[characters_voice\human_01\stalker\fight\hit\hit_3]],
    [[characters_voice\human_01\stalker\fight\hit\hit_6]],
    [[characters_voice\human_01\stalker\fight\hit\hit_7]],
    [[characters_voice\human_01\stalker\fight\hit\hit_8]],
  }
  local snd_obj = xr_sound.get_safe_sound_object(
    sounds[ math.random( table.getn( sounds ) ) ]
  )
  snd_obj:play_no_feedback( db.actor, sound_object.s2d, 0, vector():set( 0, 0, 0 ), 1.0 )
end


function add_spot_of_docent( a )
  local old_spot = amk.load_variable( "spot_of_nps", 0 )
  if old_spot ~= 0 then
    local obj_old = alife():story_object( old_spot )
    if obj_old then
      amk.remove_spot_from_map( obj_old.id, "blue_location" )
    end
  end
  local obj = alife():story_object( a )
  if obj and IsStalker( obj ) then
    amk.add_spot_on_map( obj.id, "blue_location", obj:name() .. "_sak" )
    amk.save_variable( "spot_of_nps", a )
  end
end


function add_tail()
  db.actor:set_character_community( "actor", 0, 0 )
  -- if level.name() == "l04_darkvalley" then	
  --   local obj = alife():story_object( 425 )
  --   if obj and IAmAStalker[ obj:clsid() ] and obj:alive() then
  --     if db.actor:has_info( "val_bandit_talk" ) then
  --       db.actor:set_character_community( "stranger", 0, 0 )
  --     end
  --   else
  --     db.actor:set_character_community( "actor", 0, 0 )
  --   end
  -- else
  --   db.actor:set_character_community( "actor", 0, 0 )
  -- end

  if
    ( level.name() == "l05_bar" or level.name() == "zaton" )
    and not has_alife_info( "bar_random" )
    and not has_alife_info( "bar_smile"  )
    and not has_alife_info( "bar_rock"   )
    and not has_alife_info( "bar_rockn"  )
    and not has_alife_info( "bar_modern" )
    and not has_alife_info( "bar_retro"  )
  then
    db.actor:give_info_portion( "bar_random" )
  end
  if level.name() == "l01_escape" then
    db.actor:give_info_portion( "sidor_music" )
  end
end


function off_testobj()
  -- переделано на поршни - при выбросе снимаем все поршни, при спавне артов на
  -- локе выдаем
  local ini = game_ini()
  for _, lname in ipairs( get_section_keys( "level_maps_single", ini ) ) do
    db.actor:disable_info_portion( "testsak_" .. lname )
  end
  if ini:section_exist( "level_maps_single_ext" ) then
    for _, lname in ipairs(
      get_section_keys( "level_maps_single_ext", ini )
    ) do
      db.actor:disable_info_portion( "testsak_" .. lname )
    end
  end
end


function add_borov_treasure()
	treasure_manager.get_treasure_manager():give_treasure("mil_borov_secret")
end
function add_krysyk_treasure()
	treasure_manager.get_treasure_manager():give_treasure("agr_krysyk_secret")
end
function add_krysyk_pda()
	treasure_manager.get_treasure_manager():give_treasure("val_krysyk_secret")
end


-- Продолжение Крысюк - Жила:
function krysyk_enemy( npc, actor )
  if db.actor and db.actor:id() == npc:id() then
    actor, npc = npc, actor
  end
  npc:set_character_community( "bandit", 0, 0 )
  npc:set_relation( game_object.enemy, db.actor )
  db.actor:give_info_portion( "bandit_krisyk_finish" )
  dsh.timeout(
    250,
    function()
      db.actor:give_info_portion( "bandit_krisyk_enemy"  )
    end
  )
end


function krysyk_umer()
	if has_alife_info("bandit_krisyk_finish") then 
		db.actor:give_info_portion("bandit_krisyk_finish2")
	else
		db.actor:give_info_portion("bandit_krisyk_umer2")
	end
end
--
function dbglog(fmt,...)
  local msg = string_format(fmt, ...)
  local msg_no_ws = string_gsub(msg, "%s", "___")
  get_console():execute("dbg:" .. msg_no_ws)
end
-----------------------------------------------------------------------------------------------------------
