-- -*- mode: lua; coding: windows-1251-dos -*-

local colors = {
  { -- health
    { 255, 255,   0,   0 },
    { 229, 255,  51,  51 },
    { 204, 255, 102,  51 },
    { 178, 255, 204,  51 },
    { 153, 255, 255,  51 },
    { 127, 204, 255,  51 },
    { 102, 102, 255,  51 },
    {  76,  51, 255, 102 },
    {  51,  51, 255, 204 },
    {  25,  51, 204, 204 },
  },
  { -- power
    { 240, 250, 250, 250 },
    { 240, 180, 180, 180 },
    { 190, 153, 153, 153 },
    { 178, 153, 153, 153 },
    { 153, 153, 153, 153 },
    { 127, 153, 153, 153 },
    { 102, 153, 153, 153 },
    {  76, 153, 153, 153 },
    {  51, 153, 153, 153 },
    {  25, 153, 153, 153 },
  },
  { -- wound
    { 255, 255,   0,   0 },
    { 248, 255,   0,  20 },
    { 235, 255,  20,  20 },
    { 229, 255,  40,  40 },
    { 204, 255,  60,  60 },
    { 178, 255,  80,  80 },
    { 153, 255, 100, 100 },
    { 127, 255, 120, 120 },
    { 102, 255, 140, 140 },
    {  51, 255, 153, 153 },
  },
  { -- satiety
    { 255, 255,   0,   0 },
    { 229, 255,  51,  51 },
    { 204, 255, 102,  51 },
    { 178, 255, 204,  51 },
    { 153, 255, 255,  51 },
    { 127, 204, 255,  51 },
    { 102, 102, 255,  51 },
    {  76,  51, 255, 102 },
    {  51,  51, 255, 204 },
    {  25,  51, 204, 204 },
  },
  { -- psy_health
    { 255,   0,   0, 255 },
    { 248,   0,  25, 255 },
    { 235,   0,  51, 255 },
    { 229,   0,  77, 255 },
    { 204,   0, 102, 255 },
    { 178,   0, 127, 255 },
    { 153,   0, 153, 255 },
    { 127,   0, 178, 255 },
    { 102,   0, 204, 255 },
    {  51,   0, 255, 255 },
  },
  { -- radiation
    { 255, 255,   0,   0 },
    { 248, 255, 255,  20 },
    { 235, 255, 255,  40 },
    { 229, 255, 255,  55 },
    { 204, 255, 255,  70 },
    { 178, 255, 255,  85 },
    { 153, 255, 255, 100 },
    { 127, 255, 255, 115 },
    { 102, 255, 255, 140 },
    {  51, 255, 255, 155 },
  },
}

local icons = {
  [ "health"     ] = 1,
  [ "power"      ] = 2,
  [ "wound"      ] = 3,
  [ "satiety"    ] = 4,
  [ "psy_health" ] = 5,
  [ "radiation"  ] = 6,
}

-- частота обновления иконок
local refresh_freq = 500


function attach( sm )
  sm:subscribe({ signal = "on_actor_update", fun = this.on_update })
end


function on_update()
  ogse_signals.get_mgr():reschedule( refresh_freq )
  update_icons()
end


local flashing = {}

function hide_icon( n )
  setup_game_icon( n, 0, 0, 0 )
  if flashing[ n ] then
    flashing[ n ]:stop()
    flashing[ n ] = nil
  end
end


function set_icon_color( n, value )
  if value < 0 then value = 0 end
  local idx   = math.floor( value * 10 ) + 1
  local color = colors[ n ][ idx ]
  setup_game_icon( n, GetARGB( unpack( color ) ), 0, 0 )
  if idx == 1 then
    if not flashing[ n ] then
      local flash = true
      flashing[ n ] = dsh.rt_exec_periodic(
        refresh_freq,
        function()
          if flash then
            setup_game_icon( n, GetARGB( unpack( color ) ), 0, 0 )
            flash = false
          else
            setup_game_icon(
              n, GetARGB( 51, color[ 2 ], color[ 3 ], color[ 4 ] ), 0, 0
            )
            flash = true
          end
        end
      )
      flashing[ n ]:set_script_name( "dsh_hud_icons.set_icon_color" )
    end
  else
    if flashing[ n ] then
      flashing[ n ]:stop()
      flashing[ n ] = nil
    end
  end
end


local light_hunger_limit = get_float( "actor_condition", "satiety_light_limit" )

function update_icons()
  if db.actor.health < 0.92 then
    set_icon_color( icons.health, db.actor.health / 0.92 )
  else
    hide_icon( icons.health )
  end

  if db.actor.psy_health < 0.95 then
    set_icon_color( icons.psy_health, db.actor.psy_health / 0.95 )
  else
    hide_icon( icons.psy_health )
  end

  if db.actor.satiety < light_hunger_limit then
    set_icon_color( icons.satiety, db.actor.satiety / light_hunger_limit )
  else
    hide_icon( icons.satiety )
  end

  if db.actor.power < 0.8 then
    set_icon_color( icons.power, db.actor.power / 0.8 )
  else
    hide_icon( icons.power )
  end

  if db.actor:get_bleeding() > 0.05 then
    set_icon_color( icons.wound, 1 - ( db.actor:get_bleeding() / 5 ) )
  else
    hide_icon( icons.wound )
  end

  local rad = db.actor.radiation
  if rad > 0.02 and inventory.can_detect_actor_radiation() then
    set_icon_color( icons.radiation, 1 - rad )
  else
    hide_icon( icons.radiation )
  end
end
