-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_item_to_slot", fun = this.check_armor })
end


function check_armor( wpn )
  if get_bool( wpn:section(), "dsh.requires_exo", false ) then
    local outfit = db.actor:get_current_outfit()
    if not ( outfit and string.find( outfit:section(), "exo" ) ) then
      db.actor:mark_item_dropped( wpn )
      news_manager.send_tip(
        db.actor, game.translate_string( "wpn-m_134-no_exo_message" ),
        nil, "nano", 5000
      )
    end
  end
end
