-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_mm_return_game", fun = this.on_mm_return_game })
  sm:subscribe({ signal = "on_spawn",          fun = this.on_spawn          })
end


function on_spawn()
  if isIndoor( level.name() ) then
    cmd( "r2_sun_lumscale_amb 0.1" )
  end
end


function on_mm_return_game()
  on_spawn()
end
