-- -*- mode: lua; coding: windows-1251-dos -*-

-- Callback на смерть монстров
function monster_death( victim, who )
  if string.find( victim:name(), "marsh_controller" ) then
    db.actor:give_info_portion( "marsh_controller_dead" )
  elseif string.find( victim:name(), "rad_red_burer1" ) then
    db.actor:give_info_portion( "rad_red_burer1_dead" )
  elseif string.find( victim:name(), "rad_red_krovosos1" ) then
    db.actor:give_info_portion( "rad_red_krovosos1_dead" )
  elseif string.find( victim:name(), "mil_red_burer1" ) then
    db.actor:give_info_portion( "mil_red_burer1_dead" )
  elseif string.find( victim:name(), "mil_red_krovosos1" ) then
    db.actor:give_info_portion( "mil_red_krovosos1_dead" )
  elseif string.find( victim:name(), "agr_red_burer1" ) then
    db.actor:give_info_portion( "agr_red_burer1_dead" )
  elseif string.find( victim:name(), "agr_red_krovosos1" ) then
    db.actor:give_info_portion( "agr_red_krovosos1_dead" )
  elseif string.find( victim:name(), "val_red_burer1" ) then
    db.actor:give_info_portion( "val_red_burer1_dead" )
  elseif string.find( victim:name(), "val_red_krovosos1" ) then
    db.actor:give_info_portion( "val_red_krovosos1_dead" )
  end
end


-- Callback на смерть непися
function npc_death( victim, who )
  kostya_dialog.stealth_fail_task( victim, who )
end


-- Callback на взятие предмета в инвентарь гг
function actor_item_take( obj )
  inventory_update( obj, 1 )
end


-- Callback на потерю предмета из инвенаря гг
function actor_item_drop( obj )
  inventory_update( obj, -1 )
end


--Кеш текущего состояния инвентаря ГГ (только предметы проверяемые
--функцией inventory_search, их обычно немного)
local InventoryState = {}

-- Проверка на количество предметов в инвентаре гг
function inventory_search( iItemSection, iNeededCount )
  -- Взятие из кеша текущего состояния инвентаря:
  return (
    InventoryState[ iItemSection ]
      and InventoryState[ iItemSection ].cnt >= iNeededCount
  )
end


-- Обработчик появления или исчезновения предмета в инвентаре (нужно
-- обновить кеш):
function inventory_update( iObject, iCountDelta )
  if not iObject then return end
  local vItemSection = iObject:section()
  if not InventoryState[ vItemSection ] then
    InventoryState[ vItemSection ] = {
      [ "cnt" ] = 0,
      [ "obj" ] = {},
    }
  end
  -- Взятие из кеша текущего состояния инвентаря:
  local vCount = InventoryState[ vItemSection ].cnt
  -- Обновление текущего состояния инвентаря в кеше:
  vCount = vCount + iCountDelta
  ASSERT(
    vCount >= 0,
    "negative vCount (%s) for %s, iCountDelta = %s",
    vCount, iObject:name(), iCountDelta
  )
  InventoryState[ vItemSection ].cnt = vCount
  if iCountDelta > 0 then
    InventoryState[ vItemSection ].obj[ iObject:id() ] = iObject
  else
    InventoryState[ vItemSection ].obj[ iObject:id() ] = nil
  end
end


function inventory_iterate_section( sect, f )
  if InventoryState[ sect ] then
    for id, obj in pairs( InventoryState[ sect ].obj ) do
      f( obj )
    end
  end
end
