-- -*- mode: lua; coding: windows-1251-dos -*-
excluded_npcs = {
  ["Sak"]=true,
  ["aes2_Monolit_specnaz"]=true,
  ["aes_Soldier_military"]=true,
  ["agr_factory_defence_stalker3"]=true,
  ["agr_factory_defence_stalker5_0000"]=true,
  ["agr_krot"]=true,
  ["agr_nebo_chromov"]=true,
  ["agr_nii_commander"]=true,
  ["agr_ratcatcher"]=true,
  ["agr_sniper1"]=true,
  ["agr_soldier_commander1"]=true,
  ["agr_soldier_commander2"]=true,
  ["agro_adrenalin"]=true,
  ["agro_chsovoy_trezv"]=true,
  ["agro_mobil_torgash"]=true,
  ["agro_piyn_soldier1"]=true,
  ["agro_piyn_soldier2"]=true,
  ["amk_artem_kulinar"]=true,
  ["amk_artem_kulinar"]=true,
  ["amk_vitek_voron"]=true,
  ["andersen"]=true,
  ["arhara_ecolog_guard1"]=true,
  ["arhara_zaton"]=true,
  ["atp_brigada1"]=true,
  ["atp_brigada4"]=true,
  ["atp_kalinin"]=true,
  ["atp_mobil_torgovetz"]=true,
  ["aver_filin"]=true,
  ["aver_hunter_respawn_1"]=true,
  ["aver_hunter_stalk_1"]=true,
  ["aver_hunter_stalk_2"]=true,
  ["aver_hunter_stalk_3"]=true,
  ["aver_hunter_stalk_4"]=true,
  ["aver_hunter_stalk_5"]=true,
  ["aver_odnonogiy"]=true,
  ["aver_pantera_new"]=true,
  ["aver_zlobnuy"]=true,
  ["aver_zvezdochet2"]=true,
  ["bar_arena_man"]=true,
  ["bar_bar_drunk_dolg"]=true,
  ["bar_bar_guard"]=true,
  ["bar_bar_hunter"]=true,
  ["bar_bar_lisiy"]=true,
  ["bar_bar_osvedomitel"]=true,
  ["bar_barman"]=true,
  ["bar_docent"]=true,
  ["bar_dolg_guard_commander"]=true,
  ["bar_dolg_ivancov"]=true,
  ["bar_dolg_leader"]=true,
  ["bar_dolg_petrenko"]=true,
  ["bar_dolg_regular_5"]=true,
  ["bar_ecolog_guard_default2"]=true,
  ["bar_ecolog_professor"]=true,
  ["bar_freedom_attacker_commander"]=true,
  ["bar_ohotnik_respawn_1"]=true,
  ["bar_stalker_0001"]=true,
  ["bar_svoboda_attack_commander"]=true,
  ["bar_zastava_guard_3"]=true,
  ["bkot"]=true,
  ["black_doctor"]=true,
  ["black_generators_stalk1"]=true,
  ["black_generators_stalk2"]=true,
  ["black_generators_stalk6"]=true,
  ["black_generators_stalk9"]=true,
  ["bodi_pantera1"]=true,
  ["bodi_pantera2"]=true,
  ["body1_pantera_new"]=true,
  ["body2_pantera_new"]=true,
  ["boloto_provodnik"]=true,
  ["bunker_kluk"]=true,
  ["chaes1_prizrak"]=true,
  ["city_starshoy"]=true,
  ["city_tema_likvidator"]=true,
  ["clear_scy_leader"]=true,
  ["dark_sold_atak1"]=true,
  ["dark_sold_atak2"]=true,
  ["dcity2_dok2_bolot2_vid"]=true,
  ["dcity_dok_bolot"]=true,
  ["dcity_dok_nevidim"]=true,
  ["dcity_kontrol_stalk"]=true,
  ["dcity_last_rasstrel1"]=true,
  ["dcity_last_rasstrel2"]=true,
  ["dcity_last_vhod_1"]=true,
  ["dcity_last_vhod_2"]=true,
  ["dcity_last_vhod_3"]=true,
  ["dcity_last_vhod_4"]=true,
  ["dcity_obmorok_stalk"]=true,
  ["dcity_oxran_1"]=true,
  ["dcity_parfumer"]=true,
  ["dead_city_molniy"]=true,
  ["dead_city_zlobnuy"]=true,
  ["devchonka"]=true,
  ["doktor"]=true,
  ["doktor1"]=true,
  ["dolgovazyi"]=true,
  ["dyak"]=true,
  ["esc_akim"]=true,
  ["esc_blokpost_commander"]=true,
  ["esc_bridge_soldier5"]=true,
  ["esc_father_pant"]=true,
  ["esc_fox"]=true,
  ["esc_hunter_zaschita_1"]=true,
  ["esc_hunter_zaschita_2"]=true,
  ["esc_hunter_zaschita_3"]=true,
  ["esc_kostya"]=true,
  ["esc_novice_attacker1"]=true,
  ["esc_provodnik"]=true,
  ["esc_shustryi"]=true,
  ["esc_soldier_regular_default2"]=true,
  ["esc_soldier_specnaz_default2"]=true,
  ["esc_stalker_fanat"]=true,
  ["esc_tutorial_wounded"]=true,
  ["esc_vagon_wounded"]=true,
  ["esc_wolf"]=true,
  ["esc_zvezdochet"]=true,
  ["escape_trader"]=true,
  ["final_akim"]=true,
  ["final_ara"]=true,
  ["final_arhara"]=true,
  ["final_barman"]=true,
  ["final_borov"]=true,
  ["final_chimaera"]=true,
  ["final_dan"]=true,
  ["final_dok_arh"]=true,
  ["final_holod"]=true,
  ["final_klenov"]=true,
  ["final_kluk"]=true,
  ["final_kolmogor"]=true,
  ["final_krot"]=true,
  ["final_lukash"]=true,
  ["final_muxa"]=true,
  ["final_otshelnik"]=true,
  ["final_petrenko"]=true,
  ["final_piligrim"]=true,
  ["final_prizrak"]=true,
  ["final_saharov"]=true,
  ["final_shade_mono"]=true,
  ["final_shaxter"]=true,
  ["final_voronin"]=true,
  ["forest_lesnik"]=true,
  ["forest_ohotnik1"]=true,
  ["forest_ohotnik2"]=true,
  ["forest_ohotnik3"]=true,
  ["forest_ohotnik4"]=true,
  ["forest_ohotnik5"]=true,
  ["frits"]=true,
  ["gar_dm_novice"]=true,
  ["gar_dolg_blokpost_commander"]=true,
  ["gar_hellcar"]=true,
  ["gar_seryi"]=true,
  ["gar_sniper1"]=true,
  ["gar_sniper7"]=true,
  ["gen_andersen1"]=true,
  ["gen_pantera_life"]=true,
  ["gen_prizrak_izomorf"]=true,
  ["gen_sapsan1"]=true,
  ["gen_solvador1"]=true,
  ["gener_bl_doktor1"]=true,
  ["gener_desant_black1"]=true,
  ["gener_desant_black2"]=true,
  ["gener_desant_black3"]=true,
  ["gener_desant_black_komandir"]=true,
  ["gener_dok_stalk1"]=true,
  ["gener_dok_stalk2"]=true,
  ["gener_dok_stalk3"]=true,
  ["gener_frits2"]=true,
  ["generators_black_dok"]=true,
  ["generators_prizrak"]=true,
  ["generators_udav"]=true,
  ["hos_father_new"]=true,
  ["hos_new_panterka"]=true,
  ["hos_no_gulag_vhod_black1"]=true,
  ["hosp_father"]=true,
  ["hosp_real_bl_dok"]=true,
  ["hospital_bl_dok"]=true,
  ["hospital_pantera_girl"]=true,
  ["kalmyak"]=true,
  ["kapitan_agro"]=true,
  ["kluk_bar"]=true,
  ["kluk_chaes2"]=true,
  ["kluk_sklad"]=true,
  ["kolmogor"]=true,
  ["kordon_bandit_podmoga4"]=true,
  ["kot"]=true,
  ["kot_hos"]=true,
  ["kuzhetsov"]=true,
  ["labirint_monolit_shahter"]=true,
  ["labirint_shade_monolit"]=true,
  ["land_arhara_zvezdochet"]=true,
  ["land_arhara_zvezdochet"]=true,
  ["land_lazaret_stalker1"]=true,
  ["land_lazaret_stalker2"]=true,
  ["land_lazaret_stalker3"]=true,
  ["land_lazaret_starik"]=true,
  ["land_medik"]=true,
  ["last_dokplen_nachalnik"]=true,
  ["marsh_barman"]=true,
  ["marsh_dan"]=true,
  ["marsh_hunters_respawn_1"]=true,
  ["marsh_ohotnik1"]=true,
  ["marsh_ohotnik2"]=true,
  ["marsh_ohotnik3"]=true,
  ["marsh_ohotnik4"]=true,
  ["marsh_ohotnik5"]=true,
  ["marsh_remont"]=true,
  ["marsh_udav"]=true,
  ["mil_Dolg_specnaz_cherep"]=true,
  ["mil_Killer_informator"]=true,
  ["mil_Svoboda_cook"]=true,
  ["mil_Svoboda_engineer"]=true,
  ["mil_Svoboda_leader"]=true,
  ["mil_Svoboda_master_Max"]=true,
  ["mil_Svoboda_master_Ugrumiy"]=true,
  ["mil_Svoboda_stukach"]=true,
  ["mil_Svoboda_trader"]=true,
  ["mil_freedom_member0012"]=true,
  ["mil_freedom_member0021"]=true,
  ["mil_freedom_stalker0004"]=true,
  ["mil_gavr_bodyguard2"]=true,
  ["mil_sniper1"]=true,
  ["mil_stalker_respawn_315439"]=true,
  ["mil_stalker_respawn_320572"]=true,
  ["mil_stalker_respawn_33750"]=true,
  ["mil_trader_gavr"]=true,
  ["military_vitamin"]=true,
  ["molniy"]=true,
  ["muha_soldat_ranen"]=true,
  ["new_kluk_nz"]=true,
  ["new_prizrak"]=true,
  ["odnonogiy_stalk"]=true,
  ["otshelnik"]=true,
  ["pantera"]=true,
  ["pantera_new"]=true,
  ["parfumer_dcity_shtab"]=true,
  ["peshera_plennyi"]=true,
  ["peshera_shaxter"]=true,
  ["peshera_stahanov"]=true,
  ["peshera_xabaruch"]=true,
  ["piligrim"]=true,
  ["piligrim_1"]=true,
  ["piligrim_2"]=true,
  ["piligrim_bar"]=true,
  ["piligrim_sklad"]=true,
  ["piyan_kapitan"]=true,
  ["prip_dok_arh"]=true,
  ["prip_radist2_ozhil"]=true,
  ["puzir_crest"]=true,
  ["puzir_sniper3"]=true,
  ["rad_monolit_bunker_default2"]=true,
  ["rad_monolit_bunker_default6"]=true,
  ["rad_monolit_specnaz_default1"]=true,
  ["rad_soldier_specnaz_default2"]=true,
  ["radar_vitamin"]=true,
  ["radist_after"]=true,
  ["rostok_stalker"]=true,
  ["sadik1_mono_valker4"]=true,
  ["sadik_mono_valker2"]=true,
  ["sadik_mono_valker3"]=true,
  ["sak_military_stalker"]=true,
  ["sar_monolith_exo_default4"]=true,
  ["sar_monolith_specnaz_default1"]=true,
  ["sar_monolith_specnaz_default4"]=true,
  ["sim_stalker_master_chuchelo"]=true,
  ["sim_stalker_master_diador"]=true,
  ["sim_stalker_master_master"]=true,
  ["solvador"]=true,
  ["soprov_muha_soldat"]=true,
  ["stalk_kluk"]=true,
  ["stalk_radist"]=true,
  ["stalk_semetskiy"]=true,
  ["stalker_green_bar1"]=true,
  ["stalker_green_bar2"]=true,
  ["stalker_green_bar3"]=true,
  ["stalker_green_zahar"]=true,
  ["stalker_rost_sysh"]=true,
  ["tehnik_golograma"]=true,
  ["val_bandit_krisyk"]=true,
  ["val_bandit_trader"]=true,
  ["val_dolg_prisoner"]=true,
  ["val_escort_captive"]=true,
  ["val_escort_halfdead"]=true,
  ["val_escort_nap1"]=true,
  ["val_lager_bandits_borov"]=true,
  ["val_sos_wounded"]=true,
  ["village_pantera"]=true,
  ["village_piligrim"]=true,
  ["warlab_andersen2"]=true,
  ["warlab_boss"]=true,
  ["warlab_golograma"]=true,
  ["warlab_solvador2"]=true,
  ["warlab_stalker_oso"]=true,
  ["warlab_vitamin"]=true,
  ["yakut_agro"]=true,
  ["yakut_agro2"]=true,
  ["yan_ecolog_help"]=true,
  ["yantar_baty"]=true,
  ["yantar_chernomor"]=true,
  ["yantar_ecolog_general"]=true,
  ["zemlyk"]=true,
  ["zvezd_after_warl"]=true,

  -- snp
  ["anna_jupiter"] = true,
  ["anna_zaton"] = true,
  ["anna_zaton2"] = true,
  ["ariadna_bar"] = true,
  ["ariadna_zaton"] = true,
  ["bibliofrend_talk_black_zaton"] = true,
  ["bibliofrend_talk_zaton"] = true,
  ["boroda_jupiter"] = true,
  ["boroda_zaton"] = true,
  ["brodaga_mg"] = true,
  ["brodaga_zaton"] = true,
  ["bubulyka_zaton"] = true,
  ["elsa_yantar"] = true,
  ["fenrir_2chaes"] = true,
  ["fenrir_jupiter"] = true,
  ["fenrir_zaton"] = true,
  ["gena_oso"] = true,
  ["kotobegemot_bar"] = true,
  ["kotobegemot_zaton"] = true,
  ["lobsang_zaton"] = true,
  ["ludmila_zaton"] = true,
  ["maria_kordon"] = true,
  ["ozersky"] = true,
  ["parad_tm"] = true,
  ["proper70_jupiter"] = true,
  ["proper70_limansk"] = true,
  ["proper70_zaton"] = true,
  ["resident_evil_jupiter"] = true,
  ["resident_evil_zaton"] = true,
  ["snegir2_2chaes"] = true,
  ["snegir3_2chaes"] = true,
  ["snegir_2chaes"] = true,
  ["snegir_kordon"] = true,
  ["tm_brother_2chaes"] = true,
  ["tm_brother_labirint"] = true,
  ["tm_jupiter1"] = true,
  ["vesker_zaton"] = true,
  ["volazar"] = true,
  ["volazar_new"] = true,
  ["wolffrend_talk_zaton"] = true,
  ["wolffrend_talk_zaton2"] = true,

  -- но-2
  ["akill_npc"]=true,
  ["alexandrych_marsh"]=true,
  ["buusty_team_1"]=true,
  ["buusty_zaton"]=true,
  ["chudak_npc"]=true,
  ["dasha_npc"]=true,
  ["elbrus_volna"]=true,
  ["esc_buusty"]=true,
  ["esc_kuzmat"]=true,
  ["esc_pantera_zadan_soldier"]=true,
  ["fenix_volna"]=true,
  ["gluhar_volna"]=true,
  ["gonta_volna"]=true,
  ["grif_volna"]=true,
  ["gromoboi_volna"]=true,
  ["kogot_volna"]=true,
  ["kuzmat_zaton"]=true,
  ["locman_volna"]=true,
  ["masha_npc"]=true,
  ["medved_volna"]=true,
  ["mercaushiy_zaton"]=true,
  ["nazar_npc"]=true,
  ["nazar_volna"]=true,
  ["noi_npc"]=true,
  ["pes_volna"]=true,
  ["slavka_volna"]=true,
  ["zat_doc"]=true,
  ["zat_romale"]=true,
  ["zaton_dasha"]=true,
  ["zaton_masha"]=true,
}

armor_levels = {
  green_stalker_suit = 0,
  novice_suit = 0,
  bandit_suit = 0,
  bandit_black_suit = 2,
  bandit_brown_suit = 2,
  stalker_killer_suit = 2,
  monolit_suit = 3,
  specnaz_suit = 2,
  specnaz_soldier_suit = 2,
  stalker_suit = 2,
  stalker_guard_suit = 2,
  stalker_suit_m1g = 2,
  stalker_suit_m2g = 2,
  stalker_suit_v1 = 2,
  stalker_suit_v1g = 2,
  stalker_suit_v2 = 2,
  stalker_suit_v2g = 2,
  stalker_suit_v3 = 2,
  stalker_suit_v3g = 2,
  exoskelet = 4,
  exoskelet_mo_skunk = 4,
  exoskelet_sv_skunk = 4,
  exoskelet_ki_skunk = 4,
  exoskelet_ne_skunk = 4,
  exoskelet_do_skunk = 4,
  bandit_exoskelet = 4,
  svoboda_light_suit = 1,
  svoboda_heavy_suit = 2,
  dolg_suit = 2,
  stalker_scient_suit = 3,
  stalker_dolg_nauchniy_suit = 3,
  stalker_free_nauchniy_suit = 3,
  stalker_kill_nauchniy_suit = 3,
  stalker_mono_nauchniy_suit = 3,
  monolit_suit_black = 3,
  ecolog_suit = 3,
  scientist_suit = 3,
  stalker_military_suit = 3,
--      soldier_suit = 1,
  nebo_light_suit = 1,
  nebo_heavy_suit = 2,
  nebo_nauchniy_suit = 3,
  exoskelet_nebo = 4,
  stalker_comander_suit = 3
}

suits_to_visuals = {
  stalker = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    bandit_suit = {
      [[bandit\stalker_bandit_3]],
      [[bandit\stalker_bandit_5]],
      [[bandit\stalker_bandit_8]],
    },
    bandit_brown_suit = {
      [[bandit\stalker_bandit_veteran]],
    },
    bandit_black_suit = {
      [[bandit\stalker_bandit_master]],
    },
    stalker_killer_suit = {
      [[killer\stalker_ki_mask]],
      [[killer\stalker_ki_antigas]],
    },
    monolit_suit = {
      [[monolit\stalker_mo_mask]],
      [[monolit\stalker_mo_hood_9]],
      [[monolit\stalker_mo_head1]],
    },
    specnaz_suit = {
      [[soldier\soldier_antigas]],
      [[soldier\soldier_spetsnaz]],
    },
    specnaz_soldier_suit = {
      [[soldier\soldier_mask]],
    },
    stalker_suit = {
      [[neytral\stalker_neytral_hood_8]],
      [[neytral\stalker_neytral_balon_8]],
    },
    stalker_guard_suit = {
      [[neytral\stalker_bar_security]],
    },
    stalker_suit_m1g = {
      [[neytral\stalker_neytral_hood_9]],
    },
    stalker_suit_m2g = {
      [[neytral\stalker_neytral_hood_92]],
    },
    stalker_suit_v1g = {
      [[neytral\stalker_2_gas]],
    },
    stalker_suit_v2g = {
      [[neytral\stalker_3_gas]],
    },
    stalker_suit_v3g = {
      [[neytral\stalker_4_gas]],
    },
    stalker_suit_v1 = {
      [[neytral\stalker_2_mask]],
      [[neytral\stalker_2_ochki]],
    },
    stalker_suit_v2 = {
      [[neytral\stalker_3_mask]],
    },
    stalker_suit_v3 = {
      [[neytral\stalker_4_ochki]],
    },
    exoskelet = {
      [[neytral\stalker_neytral_exoskeleton]],
    },
    exoskelet_mo_skunk = {
      [[monolit\stalker_mo_exo]],
    },
    exoskelet_sv_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[killer\stalker_ki_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[neytral\stalker_ne_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    bandit_exoskelet = {
      [[bandit\stalker_bandit_exoskeleton]],
    },
    svoboda_light_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    svoboda_heavy_suit = {
      [[svoboda\stalker_sv_hood_9]],
      [[svoboda\stalker_sv_hood_91]],
    },
    dolg_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_scient_suit = {
      [[neytral\stalker_neytral_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  nebo = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    bandit_suit = {
      [[bandit\stalker_bandit_3]],
      [[bandit\stalker_bandit_5]],
      [[bandit\stalker_bandit_8]],
    },
    bandit_brown_suit = {
      [[bandit\stalker_bandit_veteran]],
    },
    bandit_black_suit = {
      [[bandit\stalker_bandit_master]],
    },
    stalker_killer_suit = {
      [[killer\stalker_ki_mask]],
      [[killer\stalker_ki_antigas]],
    },
    monolit_suit = {
      [[monolit\stalker_mo_mask]],
      [[monolit\stalker_mo_hood_9]],
      [[monolit\stalker_mo_head1]],
    },
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    specnaz_suit = {
      [[soldier\soldier_antigas]],
      [[soldier\soldier_spetsnaz]],
    },
    specnaz_soldier_suit = {
      [[soldier\soldier_mask]],
    },
    stalker_suit = {
      [[neytral\stalker_neytral_hood_8]],
      [[neytral\stalker_neytral_balon_8]],
    },
    stalker_guard_suit = {
      [[neytral\stalker_bar_security]],
    },
    stalker_suit_m1g = {
      [[neytral\stalker_neytral_hood_9]],
    },
    stalker_suit_m2g = {
      [[neytral\stalker_neytral_hood_92]],
    },
    stalker_suit_v1g = {
      [[neytral\stalker_2_gas]],
    },
    stalker_suit_v2g = {
      [[neytral\stalker_3_gas]],
    },
    stalker_suit_v3g = {
      [[neytral\stalker_4_gas]],
    },
    stalker_suit_v1 = {
      [[neytral\stalker_2_mask]],
      [[neytral\stalker_2_ochki]],
    },
    stalker_suit_v2 = {
      [[neytral\stalker_3_mask]],
    },
    stalker_suit_v3 = {
      [[neytral\stalker_4_ochki]],
    },
    exoskelet = {
      [[neytral\stalker_neytral_exoskeleton]],
    },
    exoskelet_mo_skunk = {
      [[monolit\stalker_mo_exo]],
    },
    exoskelet_sv_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[killer\stalker_ki_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[neytral\stalker_ne_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    bandit_exoskelet = {
      [[bandit\stalker_bandit_exoskeleton]],
    },
    svoboda_light_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    svoboda_heavy_suit = {
      [[svoboda\stalker_sv_hood_9]],
      [[svoboda\stalker_sv_hood_91]],
    },
    dolg_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_scient_suit = {
      [[neytral\stalker_neytral_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
    stalker_nano_suit = {
      [[nano\stalker_nano]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  monolith = {
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    exoskelet_mo_skunk = {
      [[monolit\stalker_mo_exo]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
  },
  killer = {
    stalker_killer_suit = {
      [[killer\stalker_ki_antigas]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    exoskelet_ki_skunk = {
      [[killer\stalker_ki_exoskeleton]],
    },
  },
  ecolog = {
    stalker_scient_suit = {
      [[neytral\stalker_neytral_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
  },
  sniper = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    bandit_suit = {
      [[bandit\stalker_bandit_3]],
      [[bandit\stalker_bandit_5]],
      [[bandit\stalker_bandit_8]],
    },
    bandit_brown_suit = {
      [[bandit\stalker_bandit_veteran]],
    },
    bandit_black_suit = {
      [[bandit\stalker_bandit_master]],
    },
    stalker_killer_suit = {
      [[killer\stalker_ki_mask]],
      [[killer\stalker_ki_antigas]],
    },
    monolit_suit = {
      [[monolit\stalker_mo_mask]],
      [[monolit\stalker_mo_hood_9]],
      [[monolit\stalker_mo_head1]],
    },
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    specnaz_suit = {
      [[soldier\soldier_antigas]],
      [[soldier\soldier_spetsnaz]],
    },
    specnaz_soldier_suit = {
      [[soldier\soldier_mask]],
    },
    stalker_suit = {
      [[neytral\stalker_neytral_hood_8]],
      [[neytral\stalker_neytral_balon_8]]
    },
    stalker_guard_suit = {
      [[neytral\stalker_bar_security]],
    },
    stalker_suit_m1g = {
      [[neytral\stalker_neytral_hood_9]],
    },
    stalker_suit_m2g = {
      [[neytral\stalker_neytral_hood_92]],
    },
    stalker_suit_v1g = {
      [[neytral\stalker_2_gas]],
    },
    stalker_suit_v2g = {
      [[neytral\stalker_3_gas]],
    },
    stalker_suit_v3g = {
      [[neytral\stalker_4_gas]],
    },
    stalker_suit_v1 = {
      [[neytral\stalker_2_mask]],
      [[neytral\stalker_2_ochki]],
    },
    stalker_suit_v2 = {
      [[neytral\stalker_3_mask]],
    },
    stalker_suit_v3 = {
      [[neytral\stalker_4_ochki]],
    },
    exoskelet = {
      [[neytral\stalker_neytral_exoskeleton]],
    },
    exoskelet_mo_skunk = {
      [[monolit\stalker_mo_exo]],
    },
    exoskelet_sv_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[killer\stalker_ki_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[neytral\stalker_ne_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    bandit_exoskelet = {
      [[bandit\stalker_bandit_exoskeleton]],
    },
    svoboda_light_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    svoboda_heavy_suit = {
      [[svoboda\stalker_sv_hood_9]],
      [[svoboda\stalker_sv_hood_91]],
    },
    dolg_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_scient_suit = {
      [[neytral\stalker_neytral_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  green = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    bandit_suit = {
      [[bandit\stalker_bandit_3]],
      [[bandit\stalker_bandit_5]],
      [[bandit\stalker_bandit_8]],
    },
    bandit_brown_suit = {
      [[bandit\stalker_bandit_veteran]],
    },
    bandit_black_suit = {
      [[bandit\stalker_bandit_master]],
    },
    stalker_killer_suit = {
      [[killer\stalker_ki_mask]],
      [[killer\stalker_ki_antigas]],
    },
    monolit_suit = {
      [[monolit\stalker_mo_mask]],
      [[monolit\stalker_mo_hood_9]],
      [[monolit\stalker_mo_head1]],
    },
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    specnaz_suit = {
      [[soldier\soldier_antigas]],
      [[soldier\soldier_spetsnaz]],
    },
    specnaz_soldier_suit = {
      [[soldier\soldier_mask]],
    },
    stalker_suit = {
      [[neytral\stalker_neytral_hood_8]],
      [[neytral\stalker_neytral_balon_8]],
    },
    stalker_guard_suit = {
      [[neytral\stalker_bar_security]],
    },
    stalker_suit_m1g = {
      [[neytral\stalker_neytral_hood_9]],
    },
    stalker_suit_m2g = {
      [[neytral\stalker_neytral_hood_92]],
    },
    stalker_suit_v1g = {
      [[neytral\stalker_2_gas]],
    },
    stalker_suit_v2g = {
      [[neytral\stalker_3_gas]],
    },
    stalker_suit_v3g = {
      [[neytral\stalker_4_gas]],
    },
    stalker_suit_v1 = {
      [[neytral\stalker_2_mask]],
      [[neytral\stalker_2_ochki]],
    },
    stalker_suit_v2 = {
      [[neytral\stalker_3_mask]],
    },
    stalker_suit_v3 = {
      [[neytral\stalker_4_ochki]],
    },
    exoskelet = {
      [[neytral\stalker_neytral_exoskeleton]],
    },
    exoskelet_mo_skunk = {
      [[monolit\stalker_mo_exo]],
    },
    exoskelet_sv_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[killer\stalker_ki_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[neytral\stalker_ne_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    bandit_exoskelet = {
      [[bandit\stalker_bandit_exoskeleton]],
    },
    svoboda_light_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    svoboda_heavy_suit = {
      [[svoboda\stalker_sv_hood_9]],
      [[svoboda\stalker_sv_hood_91]],
    },
    dolg_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_scient_suit = {
      [[neytral\stalker_neytral_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  dolg = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    stalker_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_m1g = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_m2g = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_v1g = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_v2g = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_v3g = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_v1 = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_v2 = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_suit_v3 = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_guard_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    exoskelet_mo_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    exoskelet_sv_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    bandit_exoskelet = {
      [[dolg\stalker_do_exoskeleton]],
    },
    dolg_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_scient_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  freedom = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    stalker_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_m1g = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_m2g = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_v1g = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_v2g = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_v3g = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_v1 = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_v2 = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_suit_v3 = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    stalker_guard_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    exoskelet_mo_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_sv_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    bandit_exoskelet = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    svoboda_light_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    svoboda_heavy_suit = {
      [[svoboda\stalker_sv_hood_9]],
      [[svoboda\stalker_sv_hood_91]],
    },
    stalker_scient_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  bandit = {
    green_stalker_suit = {
      [[novice\green_stalker_1]],
      [[novice\green_stalker_10]],
      [[novice\green_stalker_antigas]],
    },
    novice_suit = {
      [[novice\green_stalker_2]],
      [[novice\green_stalker_3]],
      [[novice\green_stalker_4]],
    },
    bandit_suit = {
      [[bandit\stalker_bandit_3]],
      [[bandit\stalker_bandit_5]],
      [[bandit\stalker_bandit_8]],
    },
    bandit_brown_suit = {
      [[bandit\stalker_bandit_veteran]],
    },
    bandit_black_suit = {
      [[bandit\stalker_bandit_master]],
    },
    stalker_killer_suit = {
      [[killer\stalker_ki_mask]],
      [[killer\stalker_ki_antigas]],
    },
    monolit_suit = {
      [[monolit\stalker_mo_mask]],
      [[monolit\stalker_mo_hood_9]],
      [[monolit\stalker_mo_head1]],
    },
    monolit_suit_black = {
      [[monolit\stalker_mo_elite]],
    },
    specnaz_suit = {
      [[soldier\soldier_antigas]],
      [[soldier\soldier_spetsnaz]],
    },
    specnaz_soldier_suit = {
      [[soldier\soldier_mask]],
    },
    stalker_suit = {
      [[neytral\stalker_neytral_hood_8]],
      [[neytral\stalker_neytral_balon_8]],
    },
    stalker_guard_suit = {
      [[neytral\stalker_bar_security]],
    },
    stalker_suit_m1g = {
      [[neytral\stalker_neytral_hood_9]],
    },
    stalker_suit_m2g = {
      [[neytral\stalker_neytral_hood_92]],
    },
    stalker_suit_v1g = {
      [[neytral\stalker_2_gas]],
    },
    stalker_suit_v2g = {
      [[neytral\stalker_3_gas]],
    },
    stalker_suit_v3g = {
      [[neytral\stalker_4_gas]],
    },
    stalker_suit_v1 = {
      [[neytral\stalker_2_mask]],
      [[neytral\stalker_2_ochki]],
    },
    stalker_suit_v2 = {
      [[neytral\stalker_3_mask]],
    },
    stalker_suit_v3 = {
      [[neytral\stalker_4_ochki]],
    },
    exoskelet = {
      [[neytral\stalker_neytral_exoskeleton]],
    },
    exoskelet_mo_skunk = {
      [[monolit\stalker_mo_exo]],
    },
    exoskelet_sv_skunk = {
      [[svoboda\stalker_sv_exoskeleton]],
    },
    exoskelet_ki_skunk = {
      [[killer\stalker_ki_exoskeleton]],
    },
    exoskelet_ne_skunk = {
      [[neytral\stalker_ne_exoskeleton]],
    },
    exoskelet_do_skunk = {
      [[dolg\stalker_do_exoskeleton]],
    },
    bandit_exoskelet = {
      [[bandit\stalker_bandit_exoskeleton]],
    },
    svoboda_light_suit = {
      [[svoboda\stalker_sv_rukzak_1_1]],
      [[svoboda\stalker_sv_rukzak_3_1]],
    },
    svoboda_heavy_suit = {
      [[svoboda\stalker_sv_hood_9]],
      [[svoboda\stalker_sv_hood_91]],
    },
    dolg_suit = {
      [[dolg\stalker_do_antigas]],
      [[dolg\stalker_do_balon_8]],
      [[dolg\stalker_do_mask]],
    },
    stalker_scient_suit = {
      [[neytral\stalker_neytral_nauchniy]],
    },
    stalker_dolg_nauchniy_suit = {
      [[dolg\stalker_do_nauchniy]],
    },
    stalker_free_nauchniy_suit = {
      [[svoboda\stalker_sv_nauchniy]],
    },
    stalker_kill_nauchniy_suit = {
      [[killer\stalker_ki_nauchniy]],
    },
    stalker_mono_nauchniy_suit = {
      [[monolit\stalker_mo_nauchniy]],
    },
    ecolog_suit = {
      [[ecolog\stalker_ecolog]],
    },
    nebo_light_suit = {
      [[nebo\stalker_nebo_rukzak]],
    },
    nebo_heavy_suit = {
      [[nebo\stalker_nebo_balon_1]],
    },
    nebo_nauchniy_suit = {
      [[nebo\stalker_nebo_nauchniy]],
    },
    exoskelet_nebo = {
      [[nebo\stalker_nebo_exoskeleton]],
    },
    scientist_suit = {
      [[ecolog\stalker_ecolog_military]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
  military = {
    specnaz_suit = {
      [[soldier\soldier_antigas]],
      [[soldier\soldier_spetsnaz]],
    },
    specnaz_soldier_suit = {
      [[soldier\soldier_mask]],
    },
    stalker_military_suit = {
      [[militari\stalker_militari_antigas_1]],
      [[militari\stalker_militari_1]],
    },
    stalker_comander_suit = {
      [[militari\stalker_militari_antigas_2]],
      [[militari\stalker_militari_2]],
    },
  },
}

vis_to_sect = {
  -- bandit
  [ "stalker_bandit_4"       ] = "bandit_outfit_red",
  [ "stalker_bandit_2"       ] = "bandit_outfit_red",
  [ "stalker_bandit_5"       ] = "bandit_outfit_blue",
  [ "stalker_bandit_9"       ] = "bandit_outfit_blue",
  [ "stalker_bandit_1"       ] = "bandit_outfit_red1",
  [ "stalker_bandit_drunk"   ] = "outfit_bandit_m1",
  [ "stalker_bandit_8"       ] = "bandit_gaz_outfit_m1",
  [ "stalker_bandit_veteran" ] = "bandit_veteran_outfit",
  [ "stalker_bandit_borov"   ] = "bandit_master_outfit",
  [ "stalker_bandit_master"  ] = "bandit_master_outfit",
  [ "stalker_bandit_exoskeleton" ] = "exo_bandit_outfit",

  -- dolg
  [ "stalker_do_antigas"     ] = "dolg_gaz_outfit_m1",
  [ "stalker_do_komandir"    ] = "outfit_dolg_m1",
  [ "stalker_do_nauchniy"    ] = "dolg_scientific_outfit",
  [ "stalker_do_exoskeleton" ] = "dolg_black_exoskeleton",

  -- nebo
  [ "stalker_nebo_balon_1"   ] = "nebo_heavy_outfit",
  [ "stalker_nebo_rukzak"    ] = "nebo_light_outfit",
  [ "stalker_nebo_nauchniy"  ] = "nebo_scientific_outfit",
  [ "stalker_nebo_exoskeleton" ] = "nebo_exo_outfit",

  -- ecolog, nauchniy, protect
  [ "stalker_ecolog"         ] = "ecolog_outfit",
  [ "nauchniy_1"             ] = "ecolog_outfit",
  [ "protect_suit2"          ] = "ecolog_outfit",
  [ "stalker_ecolog_military" ] = "protection_outfit",
  [ "stalker_chemical"       ] = "protection_outfit",
  [ "nauchniy_0"             ] = "protection_outfit",
  [ "protect_suit1"          ] = "protection_outfit",

  -- izgoy
  [ "izgoy"                  ] = "bandit_veteran_outfit",

  -- killer
  [ "stalker_ki_head_1"      ] = "outfit_killer_m1",
  [ "stalker_ki_antigas"     ] = "killer_gaz_outfit_m1",
  [ "stalker_ki_nauchniy"    ] = "merc_scientific_outfit",
  [ "stalker_ki_exoskeleton" ] = "killer_blue_exoskeleton",

  -- militari
  [ "stalker_militari_1"     ] = "military_outfit",
  [ "stalker_militari_antigas_1" ] = "military_outfit",
  [ "stalker_military"       ] = "military_outfit",
  [ "stalker_military_green" ] = "military_outfit",
  [ "stalker_militari_2"     ] = "militaryspec_outfit",
  [ "stalker_militari_antigas_2" ] = "militaryspec_outfit",
  [ "stalker_commander"      ] = "militaryspec_outfit",
  [ "stalker_military_black" ] = "militaryspec_outfit",

  -- monolit
  [ "stalker_monolit"        ] = "monolit_outfit",
  [ "stalker_mo_hood_9"      ] = "monolit_gaz_outfit_m1",
  [ "stalker_mo_nauchniy"    ] = "monolit_scientific_outfit",
  [ "stalker_mo_exo"         ] = "monolit_exoskeleton",
  [ "stalker_mo_elite"       ] = "monolit_black_outfit",

  -- neytral              
  [ "stalker_hood"           ] = "stalker_outfit",
  [ "stalker_bar_security"   ] = "stalker_guard_outfit",
  [ "stalker_neytral_hood_92" ] = "neytral_gaz_outfit_m1",
  [ "stalker_neytral_hood_9" ] = "neytral_gaz_outfit_m2",
  [ "stalker_2_gas"          ] = "neytral_gaz_outfit_v1",
  [ "stalker_3_gas"          ] = "neytral_gaz_outfit_v2",
  [ "stalker_4_gas"          ] = "neytral_gaz_outfit_v3",
  [ "stalker_2_mask"         ] = "stalker_outfit_v1",
  [ "lisiy"                  ] = "stalker_outfit_v1",
  [ "stalker_2_mask"         ] = "stalker_outfit_v1",
  [ "stalker_2_ochki"        ] = "stalker_outfit_v1",
  [ "stalker_2_rozh1"        ] = "stalker_outfit_v1",
  [ "stalker_2_usi"          ] = "stalker_outfit_v1",
  [ "stalker_3_mask"         ] = "stalker_outfit_v2",
  [ "hellcar"                ] = "stalker_outfit_v2",
  [ "stalker_3_mask"         ] = "stalker_outfit_v2",
  [ "stalker_3_rozh2"        ] = "stalker_outfit_v2",
  [ "stalker_3_usi"          ] = "stalker_outfit_v2",
  [ "stalker_4_rozh3"        ] = "stalker_outfit_v3",
  [ "serega"                 ] = "stalker_outfit_v3",
  [ "stalker_4_ochki"        ] = "stalker_outfit_v3",
  [ "stalker_prizrak"        ] = "outfit_stalker_m1",
  [ "stalker_neytral_nauchniy" ] = "scientific_outfit",
  [ "stalker_scien"          ] = "scientific_outfit",
  [ "stalker_neytral_exoskeleton" ] = "exo_outfit",
  [ "stalker_exoskeleton"    ] = "exo_outfit",

  -- novice
  [ "green_stalker_1"        ] = "neytral_novice_outfit_m1",
  [ "green_stalker_2"        ] = "novice_outfit",
  [ "stalker_novice"         ] = "outfit_novice_m1",
  [ "green_stalker_3"        ] = "novice_outfit_rain_1",
  [ "green_stalker_4"        ] = "neytral_novice_outfit_cam",
  [ "green_stalker_5"        ] = "novice_outfit_new_2",
  [ "green_stalker_6"        ] = "novice_outfit_rain_2",
  [ "green_stalker_7"        ] = "neytral_novice_outfit_cam_2",
  [ "green_stalker_8"        ] = "neytral_novice_outfit_cam_3",
  [ "green_stalker_9"        ] = "novice_outfit_new_1",
  [ "green_stalker_10"       ] = "neytral_novice_outfit_cam_1",
  [ "green_stalker_11"       ] = "neytral_novice_outfit_new",
  [ "green_stalker_antigas"  ] = "neytral_novice_gaz_outfit_m1",

  -- soldier
  [ "soldier_mask"           ] = "outfit_soldier_m1",
  [ "soldier_obichniy"       ] = "outfit_soldier_m1",
  [ "stalker_soldier"        ] = "outfit_soldier_m1",
  [ "soldier_spetsnaz"       ] = "specops_outfit",
  [ "stalker_specops"        ] = "specops_outfit",
  [ "soldier_antigas"        ] = "outfit_specnaz_m1",

  -- stalker_zombi
  [ "stalker_zombie1"        ] = "bandit_outfit",
  [ "stalker_zombie2"        ] = "dolg_outfit",
  [ "zombie_fresh_1"         ] = "dolg_outfit",
  [ "stalker_zombie3"        ] = "stalker_outfit",
  [ "stalker_zombie6"        ] = "stalker_outfit",
  [ "zombie_fresh_2"         ] = "stalker_outfit",
  [ "stalker_zombie4"        ] = "killer_outfit",
  [ "stalker_zombie5"        ] = "stalker_guard_outfit",
  [ "stalker_zombie7"        ] = "novice_outfit",
  [ "stalker_zombie8"        ] = "neytral_novice_outfit_m1",
  [ "stalker_zombie_specnaz" ] = "specops_outfit",
  [ "zombie_fresh_0"         ] = "svoboda_heavy_outfit",
  [ "zombie_exoskeleton"     ] = "broken_exoskeleton",

  -- svoboda
  [ "stalker_sv_rukzak_1_1"  ] = "svoboda_light_outfit",
  [ "stalker_sv_rukzak_3"    ] = "svoboda_light_outfit",
  [ "stalker_svoboda_light"  ] = "svoboda_light_outfit",
  [ "stalker_sv_rukzak_1"    ] = "svoboda_heavy_outfit",
  [ "stalker_sv_rukzak_2"    ] = "svoboda_heavy_outfit",
  [ "stalker_sv_rukzak_3_1"  ] = "svoboda_heavy_outfit",
  [ "stalker_sv_cook"        ] = "svoboda_heavy_outfit",
  [ "stalker_sv_max"         ] = "svoboda_heavy_outfit",
  [ "stalker_svoboda_heavy"  ] = "svoboda_heavy_outfit",
  [ "stalker_sv_hood_91"     ] = "svoboda_gaz_outfit_m1",
  [ "stalker_sv_hood_9"      ] = "svoboda_heavy_gaz_outfit_m1",
  [ "stalker_sv_nauchniy"    ] = "freedom_scientific_outfit",
  [ "stalker_sv_exoskeleton" ] = "svoboda_exoskeleton",
  [ "stalker_sv_leader"      ] = "outfit_svoboda_m1",
}

vis_find_to_sect = {
  { "stalker_bandit",         "bandit_outfit"        },
  { "stalker_do",             "dolg_outfit"          },
  { "stalker_ki",             "killer_outfit"        },
  { "stalker_mo",             "monolit_outfit"       },
  { "stalker_neytral",        "stalker_outfit"       },
  { "stalker_neytral_rukzak", "outfit_stalker_m2"    },
  { "soldier_bandana",        "outfit_soldier_m1"    },
  { "soldier_beret",          "outfit_soldier_m1"    },
  { "stalker_sv_balon_1",     "svoboda_heavy_outfit" },
}
