-- -*- mode: lua; coding: windows-1251-dos -*-

-- таблица настроек битв
battles = {
          -- Берём Хостел-телепорт
          [ 30 ] = {
            {
              any_level = true,
              create    = "create_enemies_like_teleport",
              dist      = 60,
              timeout   = 60,
              enemy     = {     -- 9
                [ "burer_normal"  ] = 2,
                [ "zombie_normal" ] = 7,
              },
            },
            {
              any_level = true,
              create    = "create_enemies_like_teleport",
              dist      = 60,
              timeout   = 180,
              enemy     = {     -- 16
                [ "zombie_normal"   ] = 9,
                [ "chimera_normal"  ] = 2,
                [ "burer_normal"    ] = 4,
                [ "fracture_normal" ] = 1,
              },
            },
            {
              any_level = true,
              create    = "create_enemies_like_teleport",
              dist      = 60,
              timeout   = 180,
              enemy     = {     -- 17
                [ "bloodsucker_normal" ] =  1,
                [ "burer_normal"       ] =  4,
                [ "fracture_normal"    ] =  1,
                [ "zombie_normal"      ] = 11,
              },
            },
            {
              any_level = true,
              create    = "create_enemies_like_teleport",
              dist      = 60,
              timeout   = 180,
              enemy     = {     -- 17
                [ "bloodsucker_normal" ] =  1,
                [ "burer_normal"       ] =  4,
                [ "fracture_normal"    ] =  1,
                [ "zombie_normal"      ] = 11,
              },
            },
            {
              any_level = true,
              func      = "akill.pda_zagadka_hostel_teleport()",
            },
          },


          -- Тайна Соснодуба
                [31] = {
                        [1]     = {
                                timeout = 40
                        },
                        [2]     = {
                                dist = 60,
                                timeout = 150,
                                enemy = {
                                        ["boar_strong"] = 4,
                                        ["boar_kachok"] = 6,
                                        ["kikimora"] = 3,
                                        ["molerat"] = 3,
                                        ["spider"] = 5,
                                        ["tushkano_normal"] = 4,
                                        ["tushkano_strong"] = 4,
                                        ["nosales"] = 4,
                                        ["flesh_weak"] = 1,
                                        ["flesh_normal"] = 1,
                                        ["flesh_swamp"] = 2,
                                        ["flesh_strong"] = 1
                                }
                        },
                        [3]     = {
                                dist = 90,
                                timeout = 150,
                                enemy = {
                                        ["dog_habaruch"] = 4,
                                        ["dog_sil_hill"] = 3,
                                        ["dog_skeleton"] = 5,
                                        ["dog_green"] = 6,
                                        ["dog_strong"] = 2,
                                        ["dog_zombie"] = 3,
                                        ["pseudodog_big"] = 3,
                                        ["volkodav"] = 2,
                                        ["pseudodog_strong"] = 2
                                }
                        },
                        [4]     = {
                                dist = 90,
                                timeout = 150,
                                enemy = {
                                        ["cat_strong"] = 2,
                                        ["cat_normal"] = 2,
                                        ["cat_weak"] = 1,
                                        ["psy_dog"] = 1,
                                        ["snork_stronger"] = 1,
                                        ["snork_nosach"] = 2,
                                        ["vypolzen"] = 4,
                                        ["vypolzen_red"] = 3,
                                        ["fracture_master"] = 2,
                                        ["fracture_karlik"] = 2,
                                        ["poltergeist_build"] = 2,
                                        ["karlito"] = 2,
                                        ["pseudodog_big"] = 1,
                                        ["pseudodog_strong"] = 3
                                }
                        },
                        [5]     = {
                                dist = 90,
                                enemy = {
                                        ["gigant_big_strong"] = 2,
                                        ["gigant_strong"] = 3,
                                        ["gigant_red_strong"] = 1,
                                        ["gigant_jumper_normal"] = 2,
                                        ["m_poltergeist_dd"] = 2,
                                        ["electro_polter"] = 2,
                                        ["polter_xray"] = 2,
                                        ["m_controller_act"] = 1,
                                        ["controller_flame"] = 1,
                                        ["gigant_virus_strong"] = 1
                                }
                        }
                },
-- Доводы Ноя
                [32] = {
                        [1]     = {
                                timeout = 30
                        },
                        [2]     = {
                                dist = 70,
                                timeout = 90,
                                enemy = {
                                        ["boar_strong"] = 2,
                                        ["boar_kachok"] = 2,
                                        ["spider"] = 6,
                                        ["kikimora"] = 2,
                                        ["molerat"] = 3,
                                        ["tushkano_normal"] = 4,
                                        ["tushkano_strong"] = 4,
                                        ["nosales"] = 4,
                                        ["zanoza"] = 1,
                                        ["flesh_weak"] = 2,
                                        ["flesh_normal"] = 2,
                                        ["flesh_swamp"] = 2,
                                        ["flesh_strong"] = 2
                                }
                        },
                        [3]     = {
                                dist = 70,
                                timeout = 90,
                                enemy = {
                                        ["dog_habaruch"] = 3,
                                        ["dog_sil_hill"] = 3,
                                        ["dog_skeleton"] = 4,
                                        ["dog_green"] = 3,
                                        ["dog_strong"] = 3,
                                        ["dog_zombie"] = 3,
                                        ["volkodav"] = 2,
                                        ["pseudodog_big"] = 2,
                                        ["pseudodog_strong"] = 3
                                }
                        },
                        [4]     = {
                                dist = 70,
                                timeout = 90,
                                enemy = {
                                        ["cat_strong"] = 2,
                                        ["cat_normal"] = 2,
                                        ["cat_weak"] = 2,
                                        ["psy_dog"] = 1,
                                        ["snork_jumper"] = 2,
                                        ["snork_nosach"] = 2,
                                        ["vypolzen_red"] = 2,
                                        ["vypolzen"] = 2,
                                        ["fracture_master"] = 2,
                                        ["fracture_karlik"] = 2,
                                        ["volkodav"] = 1,
                                        ["pseudodog_big"] = 1,
                                        ["pseudodog_strong"] = 2
                                }
                        },
                        [5]     = {
                                dist = 70,
                                timeout = 80,
                                enemy = {
                                        ["bloodsucker_effector"] = 1,
                                        ["oboroten"] = 2,
                                        ["gigant_jumper_normal"] = 2,
                                        ["gigant_big_strong"] = 2
                                }
                        },
                        [6]     = {
                                dist = 70,
                                timeout = 80,
                                enemy = {
                                        ["deathclaw_normal"] = 1,
                                        ["deathclaw_strong"] = 1,
                                        ["new_hell"] = 1,
                                        ["bear"] = 1,
                                        ["chimera_normal"] = 3
                                }
                        },
                        [7]     = {
                                dist = 70,
                                timeout = 90,
                                enemy = {
                                        ["electro_chimera"] = 1,
                                        ["chimera_x_ray"] = 1,
                                        ["chimera_wolf"] = 1,
                                        ["new_electro_chimera"] = 1,
                                        ["fire_chimera"] = 1,
                                        ["chimera_black"] = 1,
                                        ["chimera_strong"] = 1
                                }
                        },
                        [8]     = {
                                dist = 70,
                                timeout = 90,
                                enemy = {
                                        ["fracture_normal"] = 3,
                                        ["karlito"] = 2,
                                        ["bibliotekar"] = 2,
                                        ["bibliotekar_black"] = 2,
                                        ["snork_stronger"] = 2
                                }
                        },
                        [9]     = {
                                dist = 70,
                                enemy = {
                                        ["kontrik_yantar1"] = 1,
                                        ["kontrik_yantar2"] = 1,
                                        ["poltergeist_build"] = 2,
                                        ["m_poltergeist_dd"] = 2,
                                        ["electro_polter"] = 2,
                                        ["polter_xray"] = 2,
                                        ["m_controller_act"] = 1,
                                        ["controller_flame"] = 1,
                                        ["kontrik_labx16"] = 1
                                }
                        }
                },
-- Подготовка к волне
                [33] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 17,
                                tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Сталкеры, это Ной. Я нашёл человека, способного повести нас за собой. Ему, как и мне, предначертано спасти всех нас от волны мутантов. Запомните это имя - Меченый.".."".."\n"
                        },
                        [3]     = {
                                timeout = 12,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Арни, разыщи Коршуна. Передай ему, что у него есть уникальная возможность открыть свой зоопарк из редких мутантов, но придётся изрядно пострелять. Спроси его, что он хочет за свою помощь.".."".."\n"
                        },
                        [4]     = {
                                timeout = 17,
                                tip = "%c[255,160,160,160]".."АРНИ:".."\\n".."%c[255,255,128,128]Понял, сейчас же отправлю ему сообщение. За ответом приходи ко мне, потолкуем.".."".."\n"
                        },
                        [5]     = {
                                timeout = 12,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Адреналин, ты можешь связаться с Седым, торговцем на вертушке? Нужен его транспорт для перевозки боеприпасов на Затон и вывоза сталкеров оттуда. Узнай, сколько он хочет за свои услуги.".."".."\n"
                        },
                        [6]     = {
                                timeout = 12,
                                tip = "%c[255,160,160,160]".."АДРЕНАЛИН:".."\\n".."%c[255,255,128,128]Хорошо. Что ты задумал? В войнушку поиграть решил?".."".."\n"
                        },
                        [7]     = {
                                timeout = 30,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Узнаешь при встрече. Я к тебе ещё загляну.".."".."\n"
                        },
                        -- [8]     = {
                        --         tip = "%c[255,160,160,160]".."БАСТИ:".."\\n".."%c[255,255,128,128]Эй, Меченый, подойди-ка. А то промчался как метеор, ни тебе здрасьте, ни до свиданья!".."".."\n"
                        -- },
                },
-- Секунды до смерти
                [34] = {
                        [1]     = {
                                timeout = 400
                        },
                        [2]     = {
                                func = "akill.saper_code_fail()"
                        }
                },
-- Встреча с Blackwater
                [35] = {
                        [1]     = {
                                timeout = 50
                        },
                        [2]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Акилл, угадай, кого я сегодня встретил. Наших старых друзей из Блэквотер. Эти черти никак не угомонятся.".."".."\n"
                        },
                        [3]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."АКИЛЛ:".."\\n".."%c[255,255,128,128]У тебя талант находить неприятности. Тебе никто об этом не говорил? Что им нужно?".."".."\n"
                        },
                        [4]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Как всегда, прототипы ЭМ-оружия. На ближайшее время отмени прогулки по Затону.".."".."\n"
                        },
                        [5]     = {
                                tip = "%c[255,160,160,160]".."АКИЛЛ:".."\\n".."%c[255,255,128,128]Учту это. До встречи!".."".."\n"
                        }
                },
-- Волна: день нулевой
                [36] = {
                        [1]     = {
                                timeout = 6
                        },
                        [2]     = {
                                timeout = 45,
                                func = "akill.volna_day0_spawn()",
                                tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Меченый, на юго-западе, в 70 метрах от Шевченко обнаружена стая химер. Быстро приближаются.".."".."\n"
                        },
                },
-- Волна: день первый
                [37] = {
                        [1]     = {
                                info = "volna_goodwill",
                                timeout = 9
                        },
                        [2]     = {
                                timeout = 17,
                                func = "akill.volna_day1_sound()",
                                tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Меченый, с юга движется большое число мутантов. Впервые регистрирую такое количество! На мониторе одно сплошное пятно из меток. Будут у вас через восемь минут. Что бы там не происходило, желаю вам выбраться оттуда живым!".."".."\n"
                        },
                        [3]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Сталкеры, братья, я не обладаю талантом произносить ободряющие речи, но хочу сказать вот что.".."".."\n"
                        },
                        [4]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Мне неизвестно, как закончится сегодняшний день, и увидим ли мы закат солнца... Нас не так уж много, а наши шансы выжить ещё меньше.".."".."\n"
                        },
                        [5]     = {
                                timeout = 450,
                                tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Но я знаю одно! То, что вы находитесь сейчас здесь, рядом со мной, говорит о том, что люди не утратили веры в будущее, веры в друг друга, веры в самих себя! Это даёт нам преимущество над любым врагом! Запомните это!".."".."\n"
                        },
                        [6]     = {
                                timeout = 15,
                                func = "akill.volna_day1_dogs()"
                        },
                        [7]     = {
                                timeout = 80,
                                info = "noi_defenders_otboi",
                                func = "akill.volna_day1_boars()"
                        },
                        [8]    = {
                                dist = 95,
                                timeout = 140,
                                enemy = { -- 26
                                        [ "boar_normal"     ] = 2,
                                        [ "boar_strong"     ] = 4,
                                        [ "flesh_normal"    ] = 5,
                                        [ "flesh_strong"    ] = 2,
                                        [ "flesh_weak"      ] = 2,
                                        [ "tushkano_normal" ] = 9,
                                        [ "tushkano_strong" ] = 2,
                                }
                        },
                        [9]    = {
                                dist = 95,
                                timeout = 140,
                                enemy = { -- 26
                                        [ "boar_normal"     ] =  2,
                                        [ "boar_strong"     ] =  3,
                                        [ "flesh_normal"    ] =  5,
                                        [ "flesh_strong"    ] =  2,
                                        [ "flesh_weak"      ] =  2,
                                        [ "tushkano_normal" ] = 10,
                                        [ "tushkano_strong" ] =  2,
                                }
                        },
                        [10]    = {
                                dist = 95,
                                timeout = 90,
                                enemy = { -- 25
                                        [ "dog_normal"       ] = 15,
                                        [ "dog_strong"       ] =  4,
                                        [ "pseudodog_normal" ] =  4,
                                        [ "pseudodog_strong" ] =  2,
                                }
                        },
                        [11]    = {
                                dist = 95,
                                timeout = 100,
                                enemy = { -- 25
                                        [ "dog_normal"       ] = 15,
                                        [ "dog_strong"       ] = 4,
                                        [ "pseudodog_normal" ] = 4,
                                        [ "pseudodog_strong" ] = 2,
                                }
                        },
                        [12]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Скинул рюкзак с припасами, рядом с тобой.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 50,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 15, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  3, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  3, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  2, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                  [ "medkit_army"       ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                }
                        },
                        [13]    = {
                                dist = 90,
                                timeout = 30,
                                enemy = { -- 24
                                        [ "burer_normal"    ] = 4,
                                        [ "cat_normal"      ] = 1,
                                        [ "cat_strong"      ] = 1,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 2,
                                        [ "snork_normal"    ] = 6,
                                        [ "snork_strong"    ] = 2,
                                }
                        },
                        [14]    = {
                                create = "create_enemies_like_alife",
                                tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Это Свобода. Почему без нас начали?".."".."\n",
                                dist = 60,
                                timeout = 10,
                                enemy = {
                                        ["freedom_volna"] = 3
                                }
                        },
                        [15]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 50,
                                enemy = {
                                        ["freedom_volna"] = 3
                                }
                        },
                        [16]    = {
                                dist = 100,
                                timeout = 160,
                                enemy = { -- 22
                                        [ "burer_normal"    ] = 4,
                                        [ "cat_normal"      ] = 2,
                                        [ "cat_strong"      ] = 1,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 2,
                                        [ "gigant_strong"   ] = 1,
                                        [ "snork_normal"    ] = 5,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [17]    = {
                                dist = 100,
                                timeout = 120,
                                enemy = { -- 26
                                        [ "burer_normal"    ] = 4,
                                        [ "cat_normal"      ] = 2,
                                        [ "cat_strong"      ] = 2,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 2,
                                        [ "snork_normal"    ] = 7,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [18]    = {
                                dist = 95,
                                timeout = 140,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 10,
                                        [ "chimera_strong"     ] =  2,
                                        [ "controller_senator" ] =  1,
                                        [ "gigant_normal"      ] =  1,
                                }
                        },
                        [19]    = {
                                dist = 100,
                                timeout = 160,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "bloodsucker_strong" ] =  1,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] =  1,
                                }
                        },
                        [20]    = {
                                dist = 100,
                                timeout = 230,
                                enemy = { -- 20
                                        [ "chimera_normal"     ] = 16,
                                        [ "burer_normal"       ] = 1,
                                        [ "controller_senator" ] = 1,
                                        [ "chimera_strong"     ] = 2,
                                }
                        },
                        [21]    = {
                                dist = 100,
                                timeout = 250,
                                enemy = { -- 14
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "chimera_normal"     ] = 12,
                                        [ "chimera_strong"     ] =  1,
                                }
                        },
                        [22]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Оглядись, патроны в рюкзаке.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 80,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  3, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 12, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                  [ "medkit_army"       ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                }
                        },
                        [23]    = {
                                dist = 90,
                                timeout = 30,
                                enemy = { -- 7
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 3,
                                        [ "gigant_strong"      ] = 1,
                                }
                        },
                        [24]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 15,
                                enemy = {
                                        ["freedom_volna"] = 3
                                }
                        },
                        [25]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 80,
                                enemy = {
                                        ["freedom_volna"] = 3
                                }
                        },
                        [26]    = {
                                dist = 90,
                                timeout = 150,
                                enemy = { -- 10
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 5,
                                        [ "gigant_strong"      ] = 2,
                                }
                        },
                        [27]    = {
                                dist = 95,
                                timeout = 150,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] =  1,
                                        [ "controller_senator" ] =  1,
                                }
                        },
                        [28]    = {
                                dist = 90,
                                timeout = 180,
                                enemy = { -- 11
                                        [ "bloodsucker_normal" ] = 2,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 5,
                                        [ "gigant_strong"      ] = 2,
                                }
                        },
                        [29]    = {
                                dist = 100,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  4,
                                        [ "fracture_normal"    ] = 10,
                                        [ "fracture_strong"    ] =  2,
                                }
                        },
                        [30]    = {
                                dist = 100,
                                timeout = 200,
                                enemy = { -- 14
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 4,
                                        [ "fracture_normal"    ] = 8,
                                        [ "fracture_strong"    ] = 2,
                                }
                        },
                        [31]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Смотри под ноги, маслята принёс.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 70,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 18, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  6, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_gauss"        ] = {
                                    count =  6, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 12, game_type = "medkit",
                                  },
                                  [ "medkit_scientic"   ] = {
                                    count = 12, game_type = "medkit",
                                  },
                                }
                        },
                        [32]    = {
                                dist = 100,
                                timeout = 30,
                                enemy = { -- 13
                                        [ "bloodsucker_normal" ] = 6,
                                        [ "fracture_normal"    ] = 1,
                                        [ "snork_normal"       ] = 5,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [33]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 200,
                                enemy = {
                                        ["freedom_volna"] = 5
                                }
                        },
                        [34]    = {
                                dist = 100,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] = 5,
                                        [ "fracture_normal"    ] = 2,
                                        [ "snork_normal"       ] = 8,
                                }
                        },
                        [35]    = {
                                dist = 100,
                                timeout = 200,
                                enemy = { -- 11
                                        [ "bloodsucker_normal" ] = 3,
                                        [ "fracture_normal"    ] = 1,
                                        [ "kontrik_yantar1"    ] = 1,
                                        [ "snork_normal"       ] = 5,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [36]    = {
                                dist = 90,
                                timeout = 180,
                                enemy = { -- 19
                                        [ "bloodsucker_normal" ] =  3,
                                        [ "snork_normal"       ] = 14,
                                        [ "snork_strong"       ] =  2,
                                }
                        },
                        [37]    = {
                                dist = 100,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] = 13,
                                        [ "bloodsucker_strong" ] =  2,
                                        [ "burer_normal"       ] =  1,
                                        [ "burer_strong"       ] =  1,
                                }
                        },
                        [38]    = {
                                dist = 90,
                                timeout = 30,
                                enemy = { -- 26
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "boar_normal"        ] = 2,
                                        [ "burer_normal"       ] = 4,
                                        [ "chimera_normal"     ] = 6,
                                        [ "chimera_strong"     ] = 1,
                                        [ "fracture_normal"    ] = 4,
                                        [ "fracture_strong"    ] = 1,
                                        [ "gigant_normal"      ] = 1,
                                        [ "gigant_strong"      ] = 1,
                                        [ "pseudodog_normal"   ] = 1,
                                        [ "snork_normal"       ] = 3,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [39]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 200,
                                enemy = {
                                        ["freedom_volna"] = 5
                                }
                        },
                        [40]    = {
                                dist = 90,
                                timeout = 200,
                                enemy = { -- 26
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "boar_normal"        ] = 2,
                                        [ "burer_normal"       ] = 4,
                                        [ "chimera_normal"     ] = 8,
                                        [ "chimera_strong"     ] = 1,
                                        [ "fracture_normal"    ] = 4,
                                        [ "fracture_strong"    ] = 1,
                                        [ "gigant_normal"      ] = 1,
                                        [ "gigant_strong"      ] = 1,
                                        [ "pseudodog_normal"   ] = 1,
                                        [ "snork_normal"       ] = 2,
                                }
                        },
                        [41]    = {
                                dist = 90,
                                timeout = 220,
                                enemy = { -- 21
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "fracture_normal"    ] = 7,
                                        [ "gigant_normal"      ] = 1,
                                        [ "kontrik_labx16"     ] = 1,
                                        [ "kontrik_yantar2"    ] = 1,
                                        [ "snork_normal"       ] = 8,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [42]    = {
                                dist = 70,
                                enemy = {
                                        ["kontrik_senator"] = 1
                                }
                }
                },
-- Волна: день первый окончен
                [38] = {
                        [1]     = {
                                timeout = 7
                        },
                        [2]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Седой, снова нужна твоя птичка. Сможешь отвезти раненых сталкеров на Неразведанную Землю? Местный доктор присмотрит за ними. Я сообщу ему о твоём прилёте... Спасибо за игрушки!".."".."\n"
                        },
                        [3]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."СЕДОЙ:".."\\n".."%c[255,255,128,128]Сделаем, не волнуйся... Всегда пожалуйста!".."".."\n"
                        },
                        [4]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Шура, в скором времени к вам подлетит вертолёт с ранеными бойцами. Очень прошу, позаботься о них как следует. О медикаментах не беспокойся. Если ещё что-то понадобится, обращайся, всем обеспечу.".."".."\n"
                        },
                        [5]     = {
                                tip = "%c[255,160,160,160]".."ШУРА ГИНЕКОЛОГ:".."\\n".."%c[255,255,128,128]Не вопрос. Нуждающимся в моей помощи я никогда не откажу.".."".."\n"
                        }
                },
-- Волна: день второй начался
                [39] = {
                        [1]     = {
                                timeout = 15
                        },
                        [2]     = {
                                timeout = 20,
                                tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Сталкеры, внимание! С юго-востока в вашем направлении бегут мутанты. Судя по форме меток на экране, они разделены на две большие группы. Первая пройдёт рядом с Лесничеством, другая - по руслу реки. Будут примерно через полчаса.".."".."\n"
                        },
                        [3]     = {
                                tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Меченый, в суматохе я забыл сказать тебе кое-что важное. У нас есть ещё время. Срочно вернись ко мне!".."".."\n"
                        }
                },
-- Волна: день второй
                [40] = {
                        [1]     = {
                                info = "volna_goodwill",
                                timeout = 15
                        },
                        [2]     = {
                                timeout = 430,
                                tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]До подхода мутантов осталось семь минут.".."".."\n"
                        },
                        [3]     = {
                                timeout = 20,
                                func = "akill.volna_day2_dogs()"
                        },
                        [4]     = {
                                timeout = 60,
                                func = "akill.volna_day2_boars()"
                        },
                        [5]    = {
                                dist = 80,
                                info = "kogot_defenders_otboi",
                                timeout = 80,
                                enemy = { -- 22
                                        [ "cat_normal"      ] = 2,
                                        [ "cat_strong"      ] = 2,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 3,
                                        [ "snork_normal"    ] = 6,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [6]    = {
                                dist = 80,
                                timeout = 150,
                                enemy = { -- 18
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 14,
                                        [ "chimera_strong"     ] =  1,
                                        [ "controller_senator" ] =  1,
                                }
                        },
                        [7]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 20
                                        [ "burer_normal"  ] =  1,
                                        [ "burer_strong"  ] =  1,
                                        [ "gigant_normal" ] =  1,
                                        [ "snork_normal"  ] = 13,
                                        [ "snork_strong"  ] =  4,
                                }
                        },
                        [8]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  4,
                                        [ "fracture_normal"    ] = 10,
                                        [ "fracture_strong"    ] =  2,
                                }
                        },
                        [9]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Я здесь. Бросил рюкзак возле тебя.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 60,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 13, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  3, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  2, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                  [ "medkit_army"       ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                }
                        },
                        [10]    = {
                                dist = 80,
                                timeout = 30,
                                enemy = { -- 21
                                        [ "boar_normal"     ] = 7,
                                        [ "boar_strong"     ] = 3,
                                        [ "flesh_normal"    ] = 3,
                                        [ "flesh_strong"    ] = 1,
                                        [ "flesh_weak"      ] = 1,
                                        [ "tushkano_normal" ] = 4,
                                        [ "tushkano_strong" ] = 2,
                                }
                        },
                        [11]    = {
                                create = "create_enemies_like_alife",
                                tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Долг спешит на помощь. Мы подорвали взрывчатку, но мутантов оказалось слишком много. Часть из них рванула в сторону Шевченко.".."".."\n",
                                dist = 60,
                                timeout = 16,
                                enemy = {
                                        ["dolg_volna1"] = 1,
                                        ["dolg_volna2"] = 1,
                                        ["dolg_volna3"] = 1,
                                        ["dolg_volna4"] = 1,
                                        ["ohotnik_volna"] = 1
                                }
                        },
                        [12]    = {
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ничего, мы справимся. Не снижайте темп стрельбы.".."".."\n",
                                timeout = 12
                        },
                        [13]    = {
                                dist = 80,
                                timeout = 110,
                                enemy = { -- 20
                                        [ "boar_normal"     ] = 6,
                                        [ "boar_strong"     ] = 3,
                                        [ "flesh_normal"    ] = 3,
                                        [ "flesh_strong"    ] = 1,
                                        [ "flesh_weak"      ] = 1,
                                        [ "tushkano_normal" ] = 4,
                                        [ "tushkano_strong" ] = 2,
                                }
                        },
                        [14]    = {
                                dist = 80,
                                timeout = 110,
                                enemy = { -- 21
                                        [ "dog_normal"       ] = 13,
                                        [ "dog_strong"       ] =  3,
                                        [ "pseudodog_normal" ] =  3,
                                        [ "pseudodog_strong" ] =  2,
                                }
                        },
                        [15]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 23
                                        [ "burer_normal"    ] = 4,
                                        [ "cat_normal"      ] = 1,
                                        [ "cat_strong"      ] = 1,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 2,
                                        [ "gigant_strong"   ] = 1,
                                        [ "snork_normal"    ] = 5,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [16]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 7
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 3,
                                        [ "gigant_strong"      ] = 1,
                                }
                        },
                        [17]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "bloodsucker_strong" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] = 1,
                                        [ "controller_senator" ] = 1,
                                }
                        },
                        [18]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 4,
                                        [ "fracture_normal"    ] = 8,
                                        [ "fracture_strong"    ] = 2,
                                }
                        },
                        [19]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Ты пустой? Тогда подбери очередной боекомплект.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 100,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 18, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                  [ "medkit_army"       ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                }
                        },
                        [20]    = {
                                dist = 80,
                                timeout = 40,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "bloodsucker_strong" ] =  2,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] =  1,
                                }
                        },
                        [21]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 120,
                                enemy = {
                                        ["dolg_volna1"] = 1,
                                        ["dolg_volna2"] = 1,
                                        ["dolg_volna3"] = 1,
                                        ["dolg_volna4"] = 1,
                                        ["ohotnik_volna"] = 1
                                }
                        },
                        [22]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 7
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 3,
                                        [ "gigant_strong"      ] = 1,
                                }
                        },
                        [23]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        ["chimera_normal"] = 15,
                                        ["chimera_strong"] =  2,
                                }
                        },
                        [24]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 10
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 2,
                                        [ "gigant_strong"      ] = 5,
                                }
                        },
                        [25]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 12,
                                        [ "chimera_strong"     ] =  1,
                                        [ "controller_senator" ] =  1,
                                }
                        },
                        [26]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  4,
                                        [ "fracture_normal"    ] = 10,
                                        [ "fracture_strong"    ] =  2,
                                }
                        },
                        [27]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 14
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "chimera_normal"     ] = 12,
                                        [ "chimera_strong"     ] =  1,
                                }
                        },
                        [28]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 4,
                                        [ "fracture_normal"    ] = 8,
                                        [ "fracture_strong"    ] = 2,
                                }
                        },
                        [29]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Скинул рюкзачок полный всякого добра. Осмотрись внимательно.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 80,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 19, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  6, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_gauss"        ] = {
                                    count =  7, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 11, game_type = "medkit",
                                  },
                                  [ "medkit_scientic"   ] = {
                                    count = 11, game_type = "medkit",
                                  },
                                }
                        },
                        [30]    = {
                                dist = 100,
                                timeout = 40,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 5,
                                        [ "fracture_normal"    ] = 2,
                                        [ "snork_normal"       ] = 7,
                                        [ "snork_strong"       ] = 2,
                                }
                        },
                        [31]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 180,
                                enemy = {
                                        ["dolg_volna1"] = 1,
                                        ["dolg_volna2"] = 1,
                                        ["dolg_volna3"] = 1,
                                        ["dolg_volna4"] = 1,
                                        ["ohotnik_volna"] = 1
                                }
                        },
                        [32]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 14
                                        [ "bloodsucker_normal" ] = 4,
                                        [ "fracture_normal"    ] = 2,
                                        [ "snork_normal"       ] = 7,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [33]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 14
                                        [ "bloodsucker_normal" ] = 3,
                                        [ "fracture_normal"    ] = 2,
                                        [ "kontrik_yantar1"    ] = 1,
                                        [ "snork_normal"       ] = 7,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [34]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] = 13,
                                        [ "bloodsucker_strong" ] =  2,
                                        [ "burer_normal"       ] =  1,
                                        [ "burer_strong"       ] =  1,
                                }
                        },
                        [35]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 27
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "boar_normal"        ] = 2,
                                        [ "burer_normal"       ] = 4,
                                        [ "chimera_normal"     ] = 7,
                                        [ "chimera_strong"     ] = 1,
                                        [ "fracture_normal"    ] = 4,
                                        [ "fracture_strong"    ] = 1,
                                        [ "gigant_normal"      ] = 1,
                                        [ "gigant_strong"      ] = 1,
                                        [ "pseudodog_normal"   ] = 1,
                                        [ "snork_normal"       ] = 3,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [36]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 26
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "boar_normal"        ] = 2,
                                        [ "burer_normal"       ] = 4,
                                        [ "chimera_normal"     ] = 8,
                                        [ "chimera_strong"     ] = 1,
                                        [ "fracture_normal"    ] = 4,
                                        [ "fracture_strong"    ] = 1,
                                        [ "gigant_normal"      ] = 1,
                                        [ "gigant_strong"      ] = 1,
                                        [ "pseudodog_normal"   ] = 1,
                                        [ "snork_normal"       ] = 2,
                                }
                        },
                        [37]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "fracture_normal"    ] = 7,
                                        [ "gigant_normal"      ] = 1,
                                        [ "kontrik_labx16"     ] = 1,
                                        [ "kontrik_yantar2"    ] = 1,
                                        [ "snork_normal"       ] = 9,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [38]    = {
                                dist = 70,
                                enemy = {
                                        ["kontrik_senator"] = 1
                                }
                        }
                },
-- Штурм станции
                [41] = {
                        [1]     = {
                                timeout = 17,
                                tip = "%c[255,160,160,160]".."ФЕНИКС:".."\\n".."%c[255,255,128,128]Меченый, появилась небольшая проблема. Наш отряд рядом со станцией переработки отходов. Бандиты решили устроить там свою базу. Мы готовы штурмовать её в любой момент. Ждём лишь твоего приказа.".."".."\n"
                        },
                        [2]     = {
                                timeout = 17,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]До моего прихода не предпринимайте никаких действий. Я скоро буду.".."".."\n"
                        },
                        [3]     = {
                                tip = "%c[255,160,160,160]".."ФЕНИКС:".."\\n".."%c[255,255,128,128]Так точно. Найдёшь нас к западу от станции.".."".."\n"
                        }
                },
-- Волна: день третий
                [42] = {
                        [1]     = {
                                info = "volna_goodwill",
                                timeout = 25
                        },
                        [2]     = {
                                timeout = 500,
                                tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Мутанты вот-вот нагрянут, у вас в запасе девять минут.".."".."\n"
                        },
                        [3]     = {
                                timeout = 50,
                                func = "akill.volna_day3_boars()"
                        },
                        [4]     = {
                                timeout = 150,
                                func = "akill.volna_day3_chimera()"
                        },
                        [5]     = {
                                dist = 80,
                                timeout = 100,
                                enemy = { -- 22
                                        [ "boar_normal"     ] = 8,
                                        [ "boar_strong"     ] = 3,
                                        [ "flesh_normal"    ] = 3,
                                        [ "flesh_strong"    ] = 1,
                                        [ "flesh_weak"      ] = 1,
                                        [ "tushkano_normal" ] = 4,
                                        [ "tushkano_strong" ] = 2,
                                }
                        },
                        [6]     = {
                                dist = 80,
                                info = "fenix_defenders_otboi",
                                timeout = 100,
                                enemy = { -- 21
                                        [ "dog_normal"       ] = 13,
                                        [ "dog_strong"       ] =  3,
                                        [ "pseudodog_normal" ] =  3,
                                        [ "pseudodog_strong" ] =  2,
                                }
                        },
                        [7]     = {
                                dist = 80,
                                timeout = 90,
                                enemy = { -- 23
                                        [ "cat_normal"      ] = 2,
                                        [ "cat_strong"      ] = 2,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 3,
                                        [ "snork_normal"    ] = 7,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [8]    = {
                                dist = 80,
                                timeout = 150,
                                enemy = { -- 22
                                        [ "burer_normal"  ] = 1,
                                        [ "burer_strong"  ] = 1,
                                        [ "gigant_normal" ] = 1,
                                        [ "snork_normal"  ] = 15,
                                        [ "snork_strong"  ] = 4,
                                }
                        },
                        [9]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 18
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 14,
                                        [ "chimera_strong"     ] =  1,
                                        [ "controller_senator" ] =  1,
                                }
                        },
                        [10]    = {
                                dist = 80,
                                timeout = 100,
                                enemy = { -- 21
                                        [ "dog_normal"       ] = 13,
                                        [ "dog_strong"       ] =  3,
                                        [ "pseudodog_normal" ] =  3,
                                        [ "pseudodog_strong" ] =  2,
                                }
                        },
                        [11]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 4,
                                        [ "fracture_normal"    ] = 8,
                                        [ "fracture_strong"    ] = 2,
                                }
                        },
                        [12]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Поищи рюкзак на земле.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 60,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 13, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  3, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  2, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                  [ "medkit_army"       ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                }
                        },
                        [13]    = {
                                dist = 80,
                                timeout = 30,
                                enemy = { -- 20
                                        [ "boar_normal"     ] = 6,
                                        [ "boar_strong"     ] = 3,
                                        [ "flesh_normal"    ] = 3,
                                        [ "flesh_strong"    ] = 1,
                                        [ "flesh_weak"      ] = 1,
                                        [ "tushkano_normal" ] = 4,
                                        [ "tushkano_strong" ] = 2,
                                }
                        },
                        [14]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 40,
                                enemy = {
                                        ["stalker_volna1"] = 1,
                                        ["stalker_volna2"] = 1,
                                        ["stalker_volna3"] = 1,
                                        ["stalker_volna4"] = 1
                                }
                        },
                        [15]    = {
                                dist = 80,
                                timeout = 100,
                                enemy = { -- 21
                                        [ "dog_normal"       ] = 13,
                                        [ "dog_strong"       ] =  3,
                                        [ "pseudodog_normal" ] =  3,
                                        [ "pseudodog_strong" ] =  2,
                                }
                        },
                        [16]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 23
                                        [ "burer_normal"    ] = 4,
                                        [ "cat_normal"      ] = 2,
                                        [ "cat_strong"      ] = 1,
                                        [ "cat_weak"        ] = 1,
                                        [ "fracture_normal" ] = 6,
                                        [ "fracture_strong" ] = 2,
                                        [ "gigant_strong"   ] = 1,
                                        [ "snork_normal"    ] = 5,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [17]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 10
                                        [ "bloodsucker_normal" ] = 2,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 5,
                                        [ "gigant_strong"      ] = 1,
                                }
                        },
                        [18]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] =  1,
                                        [ "controller_senator" ] =  1,
                                }
                        },
                        [19]    = {
                                dist = 80,
                                timeout = 100,
                                enemy = { -- 21
                                        [ "boar_normal"     ] = 7,
                                        [ "boar_strong"     ] = 3,
                                        [ "flesh_normal"    ] = 3,
                                        [ "flesh_strong"    ] = 1,
                                        [ "flesh_weak"      ] = 1,
                                        [ "tushkano_normal" ] = 4,
                                        [ "tushkano_strong" ] = 2,
                                }
                        },
                        [20]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 4,
                                        [ "fracture_normal"    ] = 8,
                                        [ "fracture_strong"    ] = 2,
                                }
                        },
                        [21]    = {
                                dist = 80,
                                timeout = 100,
                                enemy = { -- 21
                                        [ "dog_normal"       ] = 13,
                                        [ "dog_strong"       ] =  3,
                                        [ "pseudodog_normal" ] =  3,
                                        [ "pseudodog_strong" ] =  2,
                                }
                        },
                        [22]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Около тебя лежит рюкзак. Не пробеги мимо.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 100,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 19, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  4, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                  [ "medkit_army"       ] = {
                                    count = 10, game_type = "medkit",
                                  },
                                }
                        },
                        [23]    = {
                                dist = 80,
                                timeout = 90,
                                enemy = { -- 27
                                        [ "burer_normal"    ] = 4,
                                        [ "cat_normal"      ] = 2,
                                        [ "cat_strong"      ] = 2,
                                        [ "cat_weak"        ] = 2,
                                        [ "fracture_normal" ] = 7,
                                        [ "fracture_strong" ] = 2,
                                        [ "snork_normal"    ] = 7,
                                        [ "snork_strong"    ] = 1,
                                }
                        },
                        [24]    = {
                                create = "create_enemies_like_alife",
                                dist = 60,
                                timeout = 100,
                                enemy = {
                                        ["stalker_volna1"] = 1,
                                        ["stalker_volna2"] = 1,
                                        ["stalker_volna3"] = 1,
                                        ["stalker_volna4"] = 1
                                }
                        },
                        [25]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] = 2,
                                        [ "burer_normal"       ] = 3,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 6,
                                        [ "gigant_strong"      ] = 3,
                                }
                        },
                        [26]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 20
                                        [ "burer_normal"       ] =  1,
                                        [ "chimera_normal"     ] = 16,
                                        [ "chimera_strong"     ] =  2,
                                        [ "controller_senator" ] =  1,
                                }
                        },
                        [27]    = {
                                dist = 80,
                                timeout = 180,
                                enemy = { -- 10
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 1,
                                        [ "burer_strong"       ] = 1,
                                        [ "gigant_normal"      ] = 2,
                                        [ "gigant_strong"      ] = 5,
                                }
                        },
                        [28]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 13
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] =  1,
                                }
                        },
                        [29]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "burer_normal"       ] =  4,
                                        [ "fracture_normal"    ] = 10,
                                        [ "fracture_strong"    ] =  2,
                                }
                        },
                        [30]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 15
                                        [ "bloodsucker_normal" ] =  1,
                                        [ "bloodsucker_strong" ] =  2,
                                        [ "chimera_normal"     ] = 11,
                                        [ "chimera_strong"     ] =  1,
                                }
                        },
                        [31]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "burer_normal"       ] = 4,
                                        [ "fracture_normal"    ] = 9,
                                        [ "fracture_strong"    ] = 2,
                                }
                        },
                        [32]    = {
                                sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Глянь-ка вниз, найдёшь там рюкзачок.".."".."\n",
                                rest = true,
                                rukzak = true,
                                timeout = 80,
                                items = {
                                  [ "ammo_12.7x108r"    ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_12x76_zhekan" ] = {
                                    count = 21, game_type = "ammo",
                                  },
                                  [ "ammo_23x76_shrap"  ] = {
                                    count =  6, game_type = "ammo",
                                  },
                                  [ "ammo_7.62x54r"     ] = {
                                    count =  6, game_type = "ammo",
                                  },
                                  [ "ammo_balon"        ] = {
                                    count =  5, game_type = "ammo",
                                  },
                                  [ "ammo_gauss"        ] = {
                                    count =  7, game_type = "ammo",
                                  },
                                  [ "bandage"           ] = {
                                    count = 11, game_type = "medkit",
                                  },
                                  [ "medkit_scientic"   ] = {
                                    count = 11, game_type = "medkit",
                                  },
                                }
                        },
                        [33]    = {
                                dist = 100,
                                timeout = 40,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 5,
                                        [ "fracture_normal"    ] = 2,
                                        [ "snork_normal"       ] = 7,
                                        [ "snork_strong"       ] = 2,
                                }
                        },
                        [34]    = {
                                create = "create_enemies_like_alife",
                                tip = "%c[255,160,160,160]".."СЛАВКА АНТИЗОМБИ:".."\\n".."%c[255,255,128,128]Меченый, это Славка, племянник Скряги. Спешу к вам на помощь.".."".."\n",
                                dist = 60,
                                timeout = 180,
                                enemy = {
                                        ["slavka_volna"] = 1,
                                        ["stalker_volna1"] = 1,
                                        ["stalker_volna2"] = 1,
                                        ["stalker_volna3"] = 1,
                                        ["stalker_volna4"] = 1
                                }
                        },
                        [35]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] = 5,
                                        [ "fracture_normal"    ] = 3,
                                        [ "snork_normal"       ] = 7,
                                        [ "snork_strong"       ] = 2,
                                }
                        },
                        [36]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 4,
                                        [ "fracture_normal"    ] = 3,
                                        [ "kontrik_yantar1"    ] = 1,
                                        [ "snork_normal"       ] = 7,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [37]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] = 13,
                                        [ "bloodsucker_strong" ] =  2,
                                        [ "burer_normal"       ] =  1,
                                        [ "burer_strong"       ] =  1,
                                }
                        },
                        [38]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 27
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "boar_normal"        ] = 2,
                                        [ "burer_normal"       ] = 4,
                                        [ "chimera_normal"     ] = 7,
                                        [ "chimera_strong"     ] = 1,
                                        [ "fracture_normal"    ] = 4,
                                        [ "fracture_strong"    ] = 1,
                                        [ "gigant_normal"      ] = 1,
                                        [ "gigant_strong"      ] = 1,
                                        [ "pseudodog_normal"   ] = 1,
                                        [ "snork_normal"       ] = 3,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [39]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 25
                                        [ "bloodsucker_normal" ] = 1,
                                        [ "boar_normal"        ] = 2,
                                        [ "burer_normal"       ] = 4,
                                        [ "chimera_normal"     ] = 8,
                                        [ "chimera_strong"     ] = 1,
                                        [ "fracture_normal"    ] = 4,
                                        [ "fracture_strong"    ] = 1,
                                        [ "gigant_normal"      ] = 1,
                                        [ "gigant_strong"      ] = 1,
                                        [ "pseudodog_normal"   ] = 1,
                                        [ "snork_normal"       ] = 2,
                                }
                        },
                        [40]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 23
                                        [ "bloodsucker_normal" ] = 2,
                                        [ "burer_normal"       ] = 1,
                                        [ "fracture_normal"    ] = 7,
                                        [ "gigant_normal"      ] = 1,
                                        [ "kontrik_labx16"     ] = 1,
                                        [ "kontrik_yantar2"    ] = 1,
                                        [ "snork_normal"       ] = 9,
                                        [ "snork_strong"       ] = 1,
                                }
                        },
                        [41]    = {
                                dist = 70,
                                enemy = {
                                        ["kontrik_senator"] = 1
                                }
                }
                },
-- Волна: последняя битва началась
                [43] = {
                        [1]     = {
                                timeout = 7
                        },
                        [2]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Кавалерия прибыла! Бронетехника к вашим услугам. Как вы тут, ещё держитесь?".."".."\n"
                        },
                        [3]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Никогда не думал, что скажу это военному, но как же я рад вам, ребята!".."".."\n"
                        },
                        [4]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Словесности оставим на потом. Я смог связаться с учёными, монстры совсем рядом. Мы привезли с собой ящики с патронами. Где нам их выгрузить и где лучше всего занять позиции? Надо бы создать сплошную линию обороны.".."".."\n"
                        },
                        [5]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Наши лагеря на Шевченко, в Лесничестве и на станции переработки. Между ними большие незащищённые пространства.".."".."\n"
                        },
                        [6]     = {
                                timeout = 18,
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Вас понял. Прикажу своим укрепиться у портовых кранов, у лагеря Изумрудное и возле заправки... Меченый, у тебя будет особое задание. Ты должен отвлекать мутантов на себя, пока мои хлопцы утюжат их изо всех орудий. Иначе никак, нашу броню просто-напросто сметут. Беги, встречай коробочку в первой точке.".."".."\n"
                        },
                        [7]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Значит, я буду в качестве приманки? Спасибо тебе, капитан, удружил!".."".."\n"
                        },
                        [8]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ной, наше положение кардинально изменилось. По моей просьбе прибыла военная делегация на БТРах, вместе с боеприпасами, между прочим. Совсем забыл тебе о ней рассказать.".."".."\n"
                        },
                        [9]     = {
                                timeout = 10,
                                tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Ну ты и сволочь! Из-за тебя я усомнился в самом себе, в намерениях Создателя... Но всё же я рад это услышать. Я передам остальным радостную весть... Желаю нам всем пережить сегодняшний день!".."".."\n"
                        },
                        [10]    = {
                                info = "volna_goodwill",
                                info = "volna_day4_start"
                        }
                },
-- Волна: последняя битва, портовые краны
                [44] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 20,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Мужики, я на месте. Вы только по мне не палите, хорошо? Цельтесь как следует.".."".."\n"
                        },
                        [3]     = {
                                dist = 70,
                                timeout = 200,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [4]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [5]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  7,
                                        [ "chimera_normal"     ] = 10,
                                }
                        },
                        [6]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 20
                                        [ "bloodsucker_normal" ] =  3,
                                        [ "chimera_normal"     ] =  7,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [7]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  7,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [8]     = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 24
                                        [ "bloodsucker_normal" ] =  4,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [9]     = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 6,
                                        [ "chimera_normal"     ] = 5,
                                        [ "fracture_normal"    ] = 5,
                                }
                        },
                        [10]    = {
                                dist = 80,
                                timeout = 150,
                                enemy = { -- 24
                                        [ "bloodsucker_normal" ] =  4,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [11]    = {
                                dist = 80,
                                timeout = 100,
                                enemy = {
                                        ["volna_biblik"] = 1
                                }
                        },
                        [12]    = {
                                timeout = 15,
                                func = "akill.volna_day1_dogs()",
                                tip = "%c[255,160,160,160]".."ЖНЕЦ-21:".."\\n".."%c[255,255,128,128]К нашим позициям приближается волна мутантов.".."".."\n"
                                },
                        [13]    = {
                                func = "spawn_restrictor.volna_btr2_sr1()",
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Меченый, срочно беги к лагерю Изумрудное. Мои ребята тебя прикроют.".."".."\n"
                                }
                },
-- Волна: последняя битва, лагерь Изумрудное
                [45] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."КОРШУН:".."\\n".."%c[255,255,128,128]Меченый, нас тут сильно прижали. Медведь и Пёс тяжело ранены, шестеро долговцев мертвы. Пришли сюда хотя бы один БТР.".."".."\n"
                        },
                        [3]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Капитан, охотников в Лесничестве изрядно потрепали. Прикажи своим бойцам выдвинутся им на помощь.".."".."\n"
                        },
                        [4]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Хорошо... Жнец-11 удерживайте свою позицию, Жнец-12 срочно выдвигайтесь в сторону Лесничества и окажите поддержку сталкерам.".."".."\n"
                        },
                        [5]     = {
                                dist = 70,
                                timeout = 200,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [6]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [7]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  7,
                                        [ "chimera_normal"     ] = 10,
                                }
                        },
                        [8]     = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 20
                                        [ "bloodsucker_normal" ] =  3,
                                        [ "chimera_normal"     ] =  7,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [9]     = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  7,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [10]    = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 24
                                        [ "bloodsucker_normal" ] =  4,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [11]    = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 6,
                                        [ "chimera_normal"     ] = 5,
                                        [ "fracture_normal"    ] = 5,
                                }
                        },
                        [12]    = {
                                dist = 80,
                                timeout = 150,
                                enemy = { -- 24
                                        [ "bloodsucker_normal" ] =  4,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [13]    = {
                                dist = 80,
                                timeout = 100,
                                enemy = {
                                        ["volna_deathclaw"] = 1
                                }
                        },
                        [14]    = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Внимание всем! Треть мутантов отделилась от основной волны и движется по южной части Затона, в обход ваших позиций.".."".."\n"
                },
                        [15]    = {
                                func = "spawn_restrictor.volna_btr3_sr1()",
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Меченый, мы перехватим их возле заправки. Дуй сюда как можно быстрее.".."".."\n"
                }
                },
-- Волна: последняя битва, заправка
                [46] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 16,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Капитан, мы не должны пропустить эту волну. Если не справимся, то все защитники будут окружены.".."".."\n"
                        },
                        [3]     = {
                                timeout = 20,
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Сам знаю. Ты, главное, выведи монстров на открытую местность, а дальше мы сами.".."".."\n"
                        },
                        [4]     = {
                                dist = 70,
                                timeout = 210,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [5]     = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 22
                                        [ "bloodsucker_normal" ] =  2,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [6]     = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  7,
                                        [ "chimera_normal"     ] = 10,
                                }
                        },
                        [7]     = {
                                dist = 80,
                                timeout = 210,
                                enemy = { -- 20
                                        [ "bloodsucker_normal" ] =  3,
                                        [ "chimera_normal"     ] =  7,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [8]     = {
                                dist = 80,
                                timeout = 220,
                                enemy = { -- 17
                                        [ "bloodsucker_normal" ] =  7,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [9]     = {
                                dist = 80,
                                timeout = 220,
                                enemy = { -- 24
                                        [ "bloodsucker_normal" ] =  4,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [10]    = {
                                dist = 80,
                                timeout = 220,
                                enemy = { -- 16
                                        [ "bloodsucker_normal" ] = 6,
                                        [ "chimera_normal"     ] = 5,
                                        [ "fracture_normal"    ] = 5,
                                }
                        },
                        [11]    = {
                                dist = 80,
                                timeout = 200,
                                enemy = { -- 24
                                        [ "bloodsucker_normal" ] =  4,
                                        [ "chimera_normal"     ] = 10,
                                        [ "fracture_normal"    ] = 10,
                                }
                        },
                        [12]    = {
                                dist = 80,
                                timeout = 170,
                                enemy = {
                                        ["volna_new_hell"] = 1
                                }
                        },
                        [13]    = {
                                timeout = 10,
                                tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Вроде бы, всё чисто, никого не упустили... Погоди-ка, сейчас я вылезу из этой жестянки...".."".."\n"
                        },
                        [14]    = {
                                func = "akill.cap_filatov_spawn()"
                        }
                },
-- Подарок Оружейника
                [47] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 8,
                                func = "akill.taynik_podarok_bum()"
                        },
                        [3]     = {
                                func = "akill.taynik_podarok_mutant()"
                        }
                },
-- Паучья сеть
                [48] = {
                        [1]     = {
                                timeout = 30
                        },
                        [2]     = {
                                dist = 45,
                                timeout = 40,
                                enemy = {
                                        ["spider"] = 11
                                }
                        },
                        [3]     = {
                                dist = 45,
                                timeout = 40,
                                enemy = {
                                        ["spider"] = 12
                                }
                        },
                        [4]     = {
                                dist = 42,
                                enemy = {
                                        ["ohota_spider1"] = 1,
                                        ["ohota_spider2"] = 1
                                }
                        }
                },
-- Паучья сеть, взрываем бомбы
                [49] = {
                        [1]     = {
                                timeout = 5,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Назар, взрывчатка заложена, я выбрался из пещер, произвожу детонацию. Взгляни-ка на юг...".."".."\n"
                        },
                        [2]     = {
                                timeout = 6,
                                func = "akill.nazar_spider_timer()"
                        },
                        [3]     = {
                                timeout = 18,
                                func = "akill.nazar_spider_bum()"
                        },
                        [4]     = {
                                tip = "%c[255,160,160,160]".."НАЗАР:".."\\n".."%c[255,255,128,128]Красота! Дело сделано, возвращайся на корабль.".."".."\n",
                                info = "nazar_spider_end"
                        }
                },
-- Немецкий орден, немцы из тп
                [50] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 6,
                                func = "akill.nazar_orden_flash()"
                        },
                        [3]     = {
                                timeout = 15,
                                tip = "%c[255,160,160,160]".."НАЗАР:".."\\n".."%c[255,255,128,128]Видел белую вспышку? Наверняка скоро снова откроются временные порталы. Если нашёл генерала и забрал орден, поспеши на корабль. Фрицы не заставят себя долго ждать.".."".."\n"
                        },
                        [4]     = {
                                timeout = 15,
                                func = "akill.orden_tp1()"
                        },
                        [5]     = {
                                timeout = 30,
                                func = "akill.orden_tp2()"
                        },
                        [6]     = {
                                timeout = 30,
                                func = "akill.orden_tp3()"
                        },
                        [7]     = {
                                func = "akill.orden_tp2()"
                        }
                },
-- Немецкий орден, совр. немцы из тп
                [51] = {
                        [1]     = {
                                timeout = 5
                        },
                        [2]     = {
                                timeout = 6,
                                func = "akill.nazar_orden_flash()"
                        },
                        [3]     = {
                                timeout = 8,
                                tip = "%c[255,160,160,160]".."НАЗАР:".."\\n".."%c[255,255,128,128]Ну вот опять! Всем - будьте начеку! Солдаты могут появиться откуда угодно.".."".."\n"
                        },
                        [4]     = {
                                timeout = 8,
                                tip = "%c[255,160,160,160]".."МЕРЦАЮЩИЙ:".."\\n".."%c[255,255,128,128]Лучше бы к нам из прошлого цистерну с самогоном перекинуло.".."".."\n"
                        },
                        [5]     = {
                                timeout = 30,
                                func = "akill.orden_tp4()"
                        },
                        [6]     = {
                                timeout = 30,
                                func = "akill.orden_tp5()"
                        },
                        [7]     = {
                                timeout = 30,
                                func = "akill.orden_tp6()"
                        },
                        [8]     = {
                                timeout = 30,
                                func = "akill.orden_tp4()"
                        },
                        [9]     = {
                                timeout = 30,
                                func = "akill.orden_tp5()"
                        },
                        [10]    = {
                                func = "akill.orden_tp6()"
                        }
                },
-- Засада немцев у Изумрудного
                [52] = {
                        [1]     = {
                                timeout = 2
                        },
                        [2]     = {
                                timeout = 5,
                                func = "akill.nazar_orden_flash()"
                        },
                        [3]     = {
                                timeout = 3,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Это ещё что такое?".."".."\n"
                        },
                        [4]     = {
                                func = "akill.zasada_vermaht_spawn()"
                        }
                },
-- Защита госпиталя
                [53] = {
                        [1]     = {
                                timeout = 3,
                        },
                        [2]     = {
                                timeout = 90,
                                tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ной, я на вышке. Вижу неколько зомбарей. Думаю, справлюсь в одиночку.".."".."\n",
                                func = "akill.defend_hospital_spawn1()"
                        },
                        [3]     = {
                                timeout = 100,
                                func = "akill.defend_hospital_spawn2()"
                        },
                        [4]     = {
                                timeout = 120,
                                func = "akill.defend_hospital_spawn3()"
                        },
                        [5]     = {
                                timeout = 100,
                                func = "akill.defend_hospital_spawn1()"
                        },
                        [6]     = {
                                timeout = 10,
                                func = "akill.defend_hospital_spawn4()"
                        },
                        [7]     = {
                                func = "akill.volna_day1_dogs()"
                        }
                },
}
