-- -*- mode: lua; coding: windows-1251-dos -*-

-- таблица настроек битв
battles = {
  -- Один в темноте
  [ 30 ] = {
    {
      timeout = 15,
      tip     = "%c[255,160,160,160]МЕЧЕНЫЙ:\\n%c[255,255,128,128]Димак, мой фонарик и ПНВ приказали долго жить, мне нужны новые. У тебя найдутся?\n",
      dist    = 42,
      enemy   = {
        [ "bloodsucker_weak"] = 1,
        [ "fracture_weak"   ] = 1,
      },
    },
    {
      timeout = 15,
      tip     = "%c[255,160,160,160]ДИМАК:\\n%c[255,255,128,128]Есть в наличии и то, и другое.\n",
      dist    = 42,
      enemy   = {
        [ "bloodsucker_strong" ] = 1,
        [ "fracture_normal"    ] = 1,
      },
    },
    {
      timeout = 15,
      dist    = 42,
      enemy   = {
        [ "bloodsucker_normal" ] = 1,
        [ "fracture_normal"    ] = 1,
      },
    },
    {
      timeout = 20,
      dist    = 42,
      enemy   = {
        [ "bloodsucker_normal" ] = 1,
        [ "fracture_normal"    ] = 1,
      },
    },
    {
      timeout = 20,
      dist    = 42,
      enemy   = {
        [ "bloodsucker_strong" ] = 1,
        [ "fracture_normal"    ] = 1,
      },
    },
    {
      timeout = 30,
      dist    = 42,
      enemy   = {
        [ "bloodsucker_strong" ] = 1,
        [ "fracture_normal"    ] = 1,
      },
    },
    {
      dist    = 42,
      enemy   = {
        [ "bloodsucker_normal" ] = 1,
        [ "fracture_normal"    ] = 1,
      },
    },
  },
}
