-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_monster_update", fun = this.on_update })
end


function on_update( obj )
  if obj:alive() then
    -- в ¬олне все эффекты отключаем
    if not has_alife_info( "volna_goodwill" ) then
      if obj:clsid() == clsid.bloodsucker_s then
        bloodsucker_hit( obj )
      elseif obj:clsid() == clsid.dog_s then
        dog_attack( obj )
      end
    end
  end
end


function master_koef()
  return 1 / ( 4 - level.get_game_difficulty() )
end


function bloodsucker_hit( obj )
  if obj.health < 0.52 then return end
  local enemy = obj:get_enemy()
  if not (
    enemy and enemy:id() == db.actor:id() and obj:see( enemy )
  ) then
    return
  end
  local binder = obj:binded_object()
  --/ если у кровососа есть враг/цель и кровосос его видит то ...
  local distance = obj:position():distance_to( enemy:position() )
  local need_phantom = false
  if distance < 2.5 then --/ дистанци€ дл€ анимации 'засоса'
    local timer = time_global()
    if ( binder.timer_anim or 0 ) < timer then
      binder.timer_anim = timer + 2000 --/ таймер анимации ~ 2 сек
      if obj:animation_count() > 0 then
        obj:clear_animations()
      end
      obj:add_animation( "vampire_0", true ) --/ варианты: "vampire_0" | "idle"
      --/ озвучка 'засоса'
      local sound = sound_object( "monsters\\bloodsucker\\vimpire_sucking" )
      sound:play_at_pos( obj, obj:position() )
      --/ хит жертве (прит€гиваем)
      if
        ( binder.timer_hit or 0 ) < timer
        and ( binder.timer_anim and binder.timer_anim + 2000 >= timer )
      then
        binder.timer_hit = timer + 800 --/ таймер хита ~ 0.5 сек
        local h = hit()
        local vDir    = obj:direction() --/ вектор кровососа
        local vDirHit = vector_rotate_y( vDir, 179.0 )
        h:bone( "bip01_spine" ) --/ дл€ учета 'брони'
        h.draftsman = obj
        h.direction = vDirHit --/ направление хита
        h.power     = 0.10
        h.impulse   = 120 / distance --/ чем ближе - тем сильнее 'засос'
        h.type      = hit.wound --hit.strike
        level.add_pp_effector( "fire_hit.ppe", 3000, false )
        -- db.actor:set_actor_position( obj:position() )
        -- db.actor:set_actor_direction( vDirHit:getH() )
        enemy:hit( h ) --/ наносим хит жертве
      end
    end
  else
    if binder.attack_t and binder.attack_t > time_global() then return end
    if obj:section() == "bloodsucker_strong" then
      if not (
        binder.phantom_spawned_id
        and level.object_by_id( binder.phantom_spawned_id )
      ) then
        binder.phantom_spawned_id = nil
        if math.random() < 0.4 then
          need_phantom = true
        end
      end
    end
    binder.attack_t = time_global() + 10000
  end
  if need_phantom then
    local sobj = alife():create(
      "phantom_krovosos_" .. math.random( 2 ),
      obj:position(),
      enemy:level_vertex_id(), enemy:game_vertex_id()
    )
    binder.phantom_spawned_id = sobj.id
  end
end


function dog_attack( obj )
  if obj.health < 0.05 then return end
  local enemy = obj:get_enemy()
  if not (
    enemy and enemy:id() == db.actor:id() and obj:see( enemy )
  ) then
    return
  end
  local binder = obj:binded_object()
  if binder.attack_t and binder.attack_t > time_global() then return end
  local dist = obj:position():distance_to( enemy:position() )
  if dist > 20 then return end
  local need_phantom, need_telepatic_hit = false, false
  if
    obj:section() == "dog_strong" or obj:section() == "dog_habaruch"
  then
    if not (
      binder.phantom_spawned_id
      and level.object_by_id( binder.phantom_spawned_id )
    ) then
      binder.phantom_spawned_id = nil
      local distance = obj:position():distance_to( enemy:position() )
      if distance > 2 and math.random() < 0.4 then
        need_phantom       = true
      else
        need_telepatic_hit = true
      end
    end
  else
    need_telepatic_hit = true
  end
  if need_phantom then
    local sobj = alife():create(
      "phantom_dog_" .. math.random( 2 ),
      obj:position(),
      enemy:level_vertex_id(), enemy:game_vertex_id()
    )
    binder.phantom_spawned_id = sobj.id
  end
  if need_telepatic_hit then
    level.add_pp_effector( "radiation.ppe", 2012, false )
    local h = hit()
    h.type      = hit.telepatic
    h.power     = 0.02 + math.random() * 0.05 * master_koef()
    h.impulse   = 0.0
    h:bone( "bip01_spine" ) -- чтобы учитывалась брон€
    h.draftsman = obj
    h.direction = obj:direction()
    db.actor:hit( h )
    if math.random() < 0.02 and not inventory.on_belt( "af_idol_monolita" ) then
      local active_slot = db.actor:active_slot()
      if active_slot and ( active_slot == 1 or active_slot == 2 ) then
        db.actor:drop_item( db.actor:active_item() )
        archievements.acv_count_event( "acv_drop", 10, "ћаша-растер€ша" )
      end
    end
  end
  binder.attack_t = time_global() + 10000
end
