function attach( sm )
  sm:subscribe({ signal = "on_drop",  fun = this.on_drop  })
  sm:subscribe({ signal = "on_spawn", fun = this.on_spawn })
  sm:subscribe({ signal = "on_take_from_box", fun = this.on_take_from_box })
end

function on_drop( obj, sobj )
  zamok.add( obj )
end

function on_spawn()
  zamok.restore()
end

function on_take_from_box( box, item, sitem )
  zamok.remove( box, item )
end
