function attach( sm )
  sm:subscribe({ signal = "on_take", fun = this.on_take })
  sm:subscribe({ signal = "on_take_from_box", fun = this.on_take_from_box })
  sm:subscribe({ signal = "on_use",  fun = this.on_use })
end

function on_use( obj, sobj )
  if not sobj then return end
  spawn_level_changer.checking_droped_obj( obj )
end

function on_take( obj, sobj )
  if not sobj then return end
  if obj:section() == "separator" then return end
  spawn_level_changer.on_take_teleporter( obj )
end

function on_take_from_box( box, item, sitem )
  if not sitem then return end
  spawn_level_changer.on_take_teleportator( item )
end
