-- -*- mode: lua; coding: windows-1251-dos -*-
local vip_npc = {
  [ "amk_artem_kulinar"    ] = true, -- Артем Кулинар
  [ "amk_vitek_voron"      ] = true, -- Ворон
  [ "bar_dolg_petrenko"    ] = true, -- Петренко
  [ "bar_zastava_guard_3"  ] = true, -- Киценко
  [ "dyak"                 ] = true, -- Дьяк
  [ "esc_bridge_soldier5"  ] = true, -- Кузнецов
  [ "esc_wolf"             ] = true, -- Волк
  [ "kalmyak"              ] = true, -- Калмык
  [ "sak_military_stalker" ] = true, -- Шерстюк
}

function attach( sm )
  sm:subscribe({ signal = "on_npc_before_hit", fun = this.on_npc_before_hit })
end


function on_npc_before_hit( obj, hit_data, p_s_hit, p_ignore_flags )
  if vip_npc[ obj:name() ] then
    write_memory_float( 0, p_s_hit, hit_offset.power )
  end
end
