-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_monster_death",  fun = this.on_death         })
  sm:subscribe({ signal = "on_monster_hit",    fun = this.on_hit           })
  sm:subscribe({ signal = "on_monster_spawn",  fun = this.on_monster_spawn })
  sm:subscribe({ signal = "on_update",         fun = this.on_actor_update  })
end


function on_actor_update()
  ogse_signals.get_mgr():reschedule( 8538 )
  local s_nd = level.get_snd_volume()
  if s_nd < 1 then
    s_nd = s_nd + 0.1
    level.set_snd_volume( s_nd )
  end
end


function may_attack()
  if
    has_alife_info( "volna_goodwill" ) or has_alife_info( "peshera_go" )
  then
    return false
  end
  return true
end


function on_monster_spawn( obj, binder )
  local s_name     = "on_monster_update." .. obj:id()
  local subscribed = {}
  if obj:alive() then
    if obj:clsid() == clsid.bloodsucker_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.set_custom_panic,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.bloodsucker_attack,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

      if
        obj:section() == "bloodsucker_strong"
        or obj:section() == "bloodsucker_effector"
      then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.bloodsucker_attack_phantom,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

      end
    elseif obj:clsid() == clsid.boar_s then

      if
        obj:section() == "boar_weak"
        or obj:section() == "boar_normal"
        or obj:section() == "boar_strong"
        or obj:section() == "boar_kachok"
      then

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.boar_attack,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })
      end

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = boar_body_attack,
        [ "queued" ] = true,
      })

    elseif obj:clsid() == clsid.burer_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.burer_attack,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

    elseif obj:clsid() == clsid.cat_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.set_custom_panic,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.cat_attack,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

    elseif obj:clsid() == clsid.chimera_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.chimera_attack,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

    elseif obj:clsid() == clsid.dog_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.dog_attack,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

      if obj:section() == "dog_strong" or obj:section() == "dog_habaruch" then

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.dog_attack_phantom,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })

      end
    elseif obj:clsid() == clsid.poltergeist_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = this.poltergeist_attack,
        [ "queued" ] = true,
        [ "__unsubscribe_on_death" ] = true,
      })

    elseif obj:clsid() == clsid.pseudodog_s then
      if obj:section() ~= "volkodav" then

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.pseudodog_attack,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })

      end
    elseif obj:clsid() == clsid.tushkano_s then
      if not string.find( obj:section(), "rat_", 1, true ) then

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.tushkano_attack,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })

      end
    elseif obj:clsid() == clsid.zombie_s then
      if obj:section() == "zombie_plague" then

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.zombie_plague_attack,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })

      elseif obj:section() == "zombie_plague_komar" then

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.zombie_plague_komar_attack,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })

      else

        table.insert( subscribed, {
          [ "signal" ] = s_name,
          [ "fun"    ] = this.zombie_attack,
          [ "queued" ] = true,
          [ "__unsubscribe_on_death" ] = true,
        })

      end
    end
  else
    if obj:clsid() == clsid.boar_s then

      table.insert( subscribed, {
        [ "signal" ] = s_name,
        [ "fun"    ] = boar_body_attack,
        [ "queued" ] = true,
      })

    end
  end

  if table.getn( subscribed ) > 0 then
    local sm = ogse_signals.get_mgr()
    for _, s in ipairs( subscribed ) do
      sm:subscribe( s )
    end
    binder[ script_name() .. ".subscribed" ] = subscribed
  end
end


function on_death( obj, who )
  local binder     = obj:binded_object()
  local subscribed = binder[ script_name() .. ".subscribed" ]
  if subscribed then
    local left = {}
    local sm   = ogse_signals.get_mgr()
    for _, s in ipairs( subscribed ) do
      if s[ "__unsubscribe_on_death" ] then
        sm:unsubscribe( s )
      else
        table.insert( left, s )
      end
    end
    if table.getn( left ) > 0 then
      binder[ script_name() .. ".subscribed" ] = left
    else
      binder[ script_name() .. ".subscribed" ] = nil
    end
  end
  if obj:section() == "zombie_plague" then
    level.remove_pp_effector( 1001 )
    insect_particle:stop()
  elseif obj:section() == "zombie_plague_komar" then
    level.remove_pp_effector( 1002 )
    insect_particle:stop()
  end
end


function on_hit( obj, amount, local_direction, who, bone_index )
  if obj:alive() then
    local chk_dist = obj:position():distance_to( who:position() )
    if chk_dist > obj:range() then
      obj:set_range( chk_dist * 1.1 )
    end
    obj:make_object_visible_somewhen( who )
  end
end


function master_koef()
  return 1 / ( 4 - level.get_game_difficulty() )
end


function bloodsucker_attack( obj )
  local distance = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule( distance < obj:range() and 1000 or 5000 )
  if distance > 15     then return end
  if not may_attack()  then return end
  if obj.health < 0.05 then return end
  ogse_signals.get_mgr():reschedule(  500 )
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  ogse_signals.get_mgr():reschedule( 1000 )
  if math.random() < 0.5 then
    local snd_obj = xr_sound.get_safe_sound_object(
      "monsters\\bloodsucker\\bloodsucker_attack"
    )
    snd_obj:play_no_feedback( enemy, sound_object.s2d, 0, vector(), 5.0 )
    local h = hit()
    h.type      = hit.explosion
    h.direction = vector():set( 0, 0, 0 )
    h.power     = 0.05 + 0.02 * level.get_game_difficulty()
    h.impulse   = 0
    h.draftsman = obj
    enemy:hit( h )
    h.type      = hit.wound
    enemy:hit( h )
  end
end


function bloodsucker_attack_phantom( obj )
  local attack_dist = 15
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < obj:range() and dist > attack_dist ) and 1000 or 5000
  )
  if dist < attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.05  then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  ogse_signals.get_mgr():reschedule( 5000 )
  local binder = obj:binded_object()
  if
    binder.phantom_spawned_id
    and level.object_by_id( binder.phantom_spawned_id )
  then
    return
  end
  binder.phantom_spawned_id = nil
  if math.random() < 0.4 then
    local sobj = alife():create(
      "phantom_krovosos_" .. math.random( 2 ),
      obj:position(),
      enemy:level_vertex_id(), enemy:game_vertex_id()
    )
    binder.phantom_spawned_id = sobj.id
  end
end


function boar_attack( obj )
  local attack_dist = 2
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist * 3 and 100 )
    or ( dist < obj:range() and 1000 )
    or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.05  then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  local v1 = obj:direction()
  local v2 = db.actor:direction()
  if ( v1.x * v2.x ) + ( v1.z * v2.z ) < -0.6 then
    local h = hit()
    h.draftsman = obj
    h.type      = hit.wound
    h.direction = vector():set(
      math.random( -10, 10 ) / 10,
      math.random(   0, 30 ) / 10,
      math.random( -10, 10 ) / 10
    )
    h:bone( "bip01_spine" ) --/ для учета 'брони'
    h.power     = 0
    h.impulse   = 1000
    db.actor:hit( h )
    ogse_signals.get_mgr():reschedule( 400 )
  end
end


function boar_body_attack( obj )
  local attack_dist = 3
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist * 2 and 100 )
    or ( dist < attack_dist * 10 and 1000 )
    or 5000
  )
  if not may_attack() then return end
  local binder = obj:binded_object()
  if dist < attack_dist then
    local belt_rs = inventory.on_belt_restore_speed(
      "radiation_restore_speed"
    )
    if belt_rs > 0 then
      belt_rs    = 0
    elseif belt_rs < 0 then
      if binder.attack_pt then
        local previous_check_time = game.CTime()
        previous_check_time:set( unpack( binder.attack_pt ) )
        local current_time        = game.get_game_time()
        local dt = current_time:diffSec( previous_check_time )
        belt_rs  = 0 - belt_rs * dt
      else
        belt_rs  = 0
      end
    end
    db.actor.radiation = 0.0005 + 0.0002 * level.get_game_difficulty()
      + 0.008 * dsh.get_this_level_difficulty() + belt_rs
    binder.attack_pt   = { game.get_game_time():get() }
    if dsh_hud_fx.has_detector() then
      local snd_obj = sound_object(
        "detectors\\geiger_" .. math.random( 4 )
      )
      snd_obj:play_no_feedback(
        db.actor, sound_object.s2d, 0, vector(), 0.5
      )
    end
  elseif binder.attack_pt then
    binder.attack_pt = nil
  end
end


function burer_attack( obj )
  local attack_dist = 25
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist and 100 )
    or ( dist < obj:range() and 1000 )
    or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.05  then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  local v1 = obj:direction()
  local v2 = db.actor:direction()
  if ( v1.x * v2.x ) + ( v1.z * v2.z ) < -0.6 then
    local diff = level.get_game_difficulty()
    if math.random() < diff / 10 then
      db.actor.power = -1.0
    end
    local aitem = db.actor:active_item()
    if
      aitem and math.random() < diff / 20
      and ( db.actor:active_slot() == 1 or db.actor:active_slot() == 2 )
    then
      if
        ( not inventory.on_belt( "af_idol_monolita" ) )
        or math.random() < 0.5
      then
        db.actor:drop_item( aitem )
        archievements.acv_count_event( "acv_drop", 10, "Маша-растеряша" )
      end
    end
    ogse_signals.get_mgr():reschedule( 6000 * ( 1 + math.random( -0.2, 0.2 ) ) )
  end
end


function cat_attack( obj )
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < obj:range() and 250 )
    or ( dist < obj:range() * 2 and 1000 )
    or 5000
  )
  if not may_attack()  then return end
  if obj.health < 0.05 then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  if math.random() < 0.15 + ( 0.05 * level.get_game_difficulty() ) then
    level.add_pp_effector( "black_cats.ppe", 2015, false )
    dsh_sleep.zevota()
    dsh_sleep.test_for_need_sleep( 17 )
  end
  ogse_signals.get_mgr():reschedule( 500 )
end


function chimera_attack( obj )
  local attack_dist = 15
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist and 250 )
    or ( dist < attack_dist * 2 and 1000 )
    or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.5   then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  if math.random() < 0.5 then
    local snd_obj = sound_object( "monsters\\chimera\\attack_2" )
    snd_obj:play_no_feedback( db.actor, sound_object.s2d, 0, vector(), 5.0 )
    db.actor.power = -0.05
  end
  ogse_signals.get_mgr():reschedule( 500 )
end


-- Удар контролёра руками из Зова Припяти (Автор: demover123)
function controller_attack( obj )
  if not may_attack() then return end
  local target = obj:best_enemy()
  if
    target and obj:see( target )
    and target:id() == db.actor:id()
  then
    local binder = obj:binded_object()
    if not binder.attack_get_hit then
      binder.attack_get_hit             = time_global() + 100
      binder.attack_start_anim_hit_cont = true
    elseif binder.attack_get_hit <= time_global() then
      local dist = obj:position():distance_to( target:position() )
      if dist <= 1.7 then
        if binder.attack_start_anim_hit_cont then
          if obj:animation_count() > 0 then
            obj:clear_animations()
          end
          obj:add_animation(
            "stand_walk_fwd_" .. math.random( 0, 1 ), true
          )
          obj:play_cycle( "stand_attack_1", true )
          local song_start = xr_sound.get_safe_sound_object(
            "monsters\\controller\\controller_hit_2"
          )
          song_start:play_at_pos(
            obj, obj:position(), sound_object.s3d
          )
          binder.attack_start_anim_hit_cont = false
        end
        if not binder.attack_hit_to_enemy then
          binder.attack_hit_to_enemy = time_global() + 300
        elseif binder.attack_hit_to_enemy <= time_global() then
          level.add_cam_effector(
            "camera_effects\\hit_back_left.anm", 777, false, ""
          )
          local h = hit()
          h.draftsman = obj
          h.direction = vector():set( 0, 0, 0 )
          h:bone( "bip01_spine" )
          h.power     = 0.4
          h.impulse   = 1
          h.type      = hit.wound
          target:hit( h )
          binder.attack_hit_to_enemy = nil
          binder.attack_get_hit      = nil
        end
      end
    end
  end
  if obj:animation_count() < 1 then
    local i = math.random( 0, 5 )
    obj:add_animation( "stand_walk_fwd_" .. i, true )
  end
end


function dog_attack( obj )
  local attack_dist = 8
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist and 250 )
    or ( dist < attack_dist * 2 and 1000 )
    or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.05  then return end
  local enemy = obj:best_enemy()
  if not (
    enemy and enemy:id() == db.actor:id() and obj:see( enemy )
  ) then
    return
  end
  ogse_signals.get_mgr():reschedule( 1513 )
  if math.random() > dsh.get_this_level_difficulty() then return end
  level.add_pp_effector( "radiation.ppe", 2012, false )
  local h = hit()
  h.type      = hit.telepatic
  h.power     = 0.01 + 0.02 * master_koef() * dsh.get_this_level_difficulty()
  h.impulse   = 0.0
  h:bone( "bip01_spine" ) -- чтобы учитывалась броня
  h.draftsman = obj
  h.direction = obj:direction()
  db.actor:hit( h )
  local dog_shield = inventory.on_belt( "af_idol_monolita" ) and 0 or 1
  local drop       = (
    0.05 + ( 0.03 * level.get_game_difficulty() )
  ) * dog_shield
  if math.random() < drop then
    local active_slot = db.actor:active_slot()
    if active_slot and ( active_slot == 1 or active_slot == 2 ) then
      db.actor:drop_item( db.actor:active_item() )
      archievements.acv_count_event( "acv_drop", 10, "Маша-растеряша" )
    end
  end
end


function dog_attack_phantom( obj )
  local attack_dist = 8
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < obj:range() and dist > attack_dist ) and 1000 or 5000
  )
  if dist < attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.05  then return end
  local enemy = obj:best_enemy()
  if not (
    enemy and enemy:id() == db.actor:id() and obj:see( enemy )
  ) then
    return
  end
  ogse_signals.get_mgr():reschedule( 5000 )
  local binder = obj:binded_object()
  if not (
    binder.phantom_spawned_id
    and level.object_by_id( binder.phantom_spawned_id )
  ) then
    binder.phantom_spawned_id = nil
    if math.random() < 0.3 then
      local sobj = alife():create(
        "phantom_dog_" .. math.random( 2 ),
        obj:position(),
        enemy:level_vertex_id(), enemy:game_vertex_id()
      )
      binder.phantom_spawned_id = sobj.id
    end
  end
end


function poltergeist_attack( obj )
  local attack_dist = 3
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist * 2 and 250 )
    or ( dist < obj:range() and 1000 )
    or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  local enemy = obj:enemy()
  if not (
    enemy and enemy:id() == db.actor:id() and obj:see( enemy )
  ) then
    return
  end
  charge_tushkano( obj, enemy )
  ogse_signals.get_mgr():reschedule( 100 )
end


local pseudodog_cam_t

function pseudodog_attack( obj )
  local attack_dist = 20
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist and 500 )
    or ( dist < obj:range() and 1000 )
    or 5000
  )
  if not may_attack()  then return end
  if obj.health < 0.05 then return end
  local enemy = obj:best_enemy()
  if not (
    enemy and enemy:id() == db.actor:id() and obj:see( enemy )
  ) then
    return
  end
  local time_next_attack = 2500
  local time_cam_effect  = 700
  if enemy:see( obj ) then
    local v1 = obj:direction()
    local v2 = db.actor:direction()
    if
      ( v1.x * v2.x ) + ( v1.z * v2.z ) < -0.6 and dist < attack_dist
    then
      for _, n in ipairs({ 1, 2 }) do
        level.add_cam_effector(
          "build_1935_pseudodog_effect_" .. n .. ".anm", 990 + n, false,
          ""
        )
      end
      level.add_pp_effector ( "psy_antenna.ppe", 395, false )
      local h = hit()
      h.draftsman = obj
      h.type      = hit.telepatic
      h.direction = vector():set( 0, 0, 0 )
      h:bone( "bip01_spine" ) --/ для учета 'брони'
      h.power     = 0.05 + 0.02 * master_koef() * dsh.get_this_level_difficulty()
      h.impulse   = 0.0
      db.actor:hit( h )
      local snd = xr_sound.get_safe_sound_object(
        "monsters\\pseudodog\\psy_affect_0", sound_object.s2d
      )
      snd:play_at_pos( db.actor, db.actor:position() )
      local dog_shield = inventory.on_belt( "af_idol_monolita" ) and 0 or 1
      local drop       = (
        0.05 + ( 0.03 * level.get_game_difficulty() )
      ) * dog_shield
      if math.random() < drop then
        local active_slot = db.actor:active_slot()
        if active_slot and ( active_slot == 1 or active_slot == 2 ) then
          db.actor:drop_item( db.actor:active_item() )
          archievements.acv_count_event( "acv_drop", 10, "Маша-растеряша" )
        end
      end
      ogse_signals.get_mgr():reschedule(
        time_next_attack * ( 1 + math.random( -0.2, 0.2 ) ) + time_cam_effect
      )
      if pseudodog_cam_t then pseudodog_cam_t:stop() end
      pseudodog_cam_t = dsh.timeout( time_cam_effect, function()
        level.remove_pp_effector( 395 )
        for _, n in pairs({ 1, 2 }) do
          level.remove_cam_effector( 990 + n )
        end
        pseudodog_cam_t = nil
      end )
    end
  end
end


function set_custom_panic( obj )
  local panic_dist = 6
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < panic_dist * 3 and 100 )
    or ( dist < obj:range() and 1000 )
    or 5000
  )
  if dist > panic_dist then return end
  if not may_attack()  then return end
  if obj.health < 0.05 then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  if
    enemy:active_slot() == 0
    and enemy:active_item() and dsh.is_knife( enemy:active_item():section() )
    and enemy:see( obj )
  then
    obj:set_custom_panic_threshold( 1 )
  else
    obj:set_custom_panic_threshold( 0 )
  end
end


function tushkano_attack( obj )
  local attack_dist = 2
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist * 2 and 250 )
    or ( dist < obj:range() and 1000 )
    or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  ogse_signals.get_mgr():reschedule( 100 )
  if obj:section() == "electro_tushkano_normal" then
    charge_tushkano( obj, enemy )
  else
    if math.random() > 0.25 then return end
    local h = hit()
    h.type      = hit.chemical_burn
    h.direction = vector():set( 0, 0, 0 )
    h.power     = 0.03 + 0.015 * level.get_game_difficulty()
    h.impulse   = 0
    h.draftsman = enemy
    enemy:hit( h )
  end
end


function zombie_attack( obj )
  local attack_dist = 35
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    dist < attack_dist and 1000 or 5000
  )
  if dist > attack_dist then return end
  if not may_attack()   then return end
  if obj.health < 0.05  then return end
  local enemy = obj:best_enemy()
  if
    not (
      enemy and enemy:id() == db.actor:id() and obj:see( enemy )
    )
  then
    return
  end
  if math.random() < 0.2 + 0.1 * level.get_game_difficulty() then
    if math.random() < 0.4 then
      local snd_obj=xr_sound.get_safe_sound_object(
        "monsters\\zombie\\zombi_attack2"
      )
      snd_obj:play_no_feedback( enemy, sound_object.s2d, 0, vector(), 5.0 )
      level.set_snd_volume( 0.1 )
    end
    if db.actor.satiety >= 0.1 then
      db.actor.satiety = -0.1
    end
  end
end


-- Атака насекомых при приближении к чумному зомби
local insect_particle = particles_object( "ogsm\\ogsm_flies_00" )
local insect_sound    = xr_sound.get_safe_sound_object( [[anomaly\flies]] )

function zombie_plague_attack( obj )
  local attack_dist = 10
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist and 100 )
    or ( dist < attack_dist * 2 and 1000 )
    or 5000
  )
  if not may_attack() then return end
  local binder = obj:binded_object()
  if binder.attack_t and binder.attack_t > time_global() then return end
  binder.attack_t   = time_global() + (
    dist < ( attack_dist * 2 ) and 250 or 1000
  )
  if dist < attack_dist then
    level.add_pp_effector( "dead_zone.ppe", 1001, true )
    level.set_pp_effector_factor( 1001, 0.1 )
    local actor = db.actor:position()
    if not insect_particle:playing() then
      insect_particle:play_at_pos(
        vector():set( actor.x, actor.y + 1.8, actor.z )
      )
    else
      insect_particle:move_to(
        vector():set( actor.x, actor.y + 1.8, actor.z ),
        vector():set( actor.x, actor.y + 1.8, actor.z )
      )
    end
    if not insect_sound:playing() then
      insect_sound:play_at_pos( db.actor, actor )
      local zh = hit()
      zh.draftsman = obj
      zh.type      = hit.chemical_burn
      zh.direction = obj:position():sub( actor )
      zh:bone( "bip01_spine" )
      zh.power     = 5
      zh.impulse   = 1.0
      db.actor:hit( zh )
    else
      insect_sound:set_position( actor )
    end
  else
    level.remove_pp_effector( 1001 )
    insect_particle:stop()
  end
end


-- Атака насекомых при приближении к комариному зомби
local komar_sound = xr_sound.get_safe_sound_object( [[anomaly\komar]] )

function zombie_plague_komar_attack( obj )
  local attack_dist = 12
  local dist = obj:position():distance_to( db.actor:position() )
  ogse_signals.get_mgr():reschedule(
    ( dist < attack_dist and 250 )
    or ( dist < attack_dist * 2 and 1000 )
    or 5000
  )
  if not may_attack() then return end
  if dist < attack_dist then
    level.add_pp_effector( "total_recall.ppe", 1002, true )
    level.set_pp_effector_factor( 1002, 0.1 )
    local actor = db.actor:position()
    if not insect_particle:playing() then
      insect_particle:play_at_pos(
        vector():set( actor.x, actor.y + 1.8, actor.z )
      )
    else
      insect_particle:move_to(
        vector():set( actor.x, actor.y + 1.8, actor.z ),
        vector():set( actor.x, actor.y + 1.8, actor.z )
      )
    end
    if not komar_sound:playing() then
      komar_sound:play_at_pos( db.actor, actor )
      local zh = hit()
      zh.draftsman = obj
      zh.type      = hit.chemical_burn
      zh.direction = obj:position():sub( actor )
      zh:bone( "bip01_spine" )
      zh.power     = 8
      zh.impulse   = 2.0
      db.actor:hit( zh )
    else
      komar_sound:set_position( actor )
    end
  else
    level.remove_pp_effector( 1002 )
    insect_particle:stop()
  end
end


local tushkano_particle = particles_object( "anomaly2\\electra_entrance_big" )
local tushkano_sound    = sound_object( [[monsters\tushkano\tushkano_spark]] )

function charge_tushkano( obj, enemy )
  if not tushkano_particle:playing() then
    tushkano_particle:play_at_pos( obj:position() )
  end
  if not tushkano_sound:playing() then
    tushkano_sound:play_at_pos( obj, obj:position(), 0 )
    local zh = hit()
    zh.draftsman = enemy
    zh.type      = hit.shock
    zh.direction = obj:position():sub( enemy:position() )
    zh:bone( "pelvis" )
    zh.power     = 0.075 + 0.025 * level.get_game_difficulty()
    zh.impulse   = 0.05
    enemy:hit(zh)
  end
end
