-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_after_save",   fun = this.on_after_save   })
  sm:subscribe({ signal = "on_first_update", fun = this.on_first_update })
end


function on_first_update()
  -- local memuse = collectgarbage( "count" ) * 1024
  collectgarbage( "collect" )
end


function on_after_save()
  collectgarbage( "collect" )
end
