-- -*- mode: lua; coding: windows-1251-dos -*-

-- эти объекты будем пересоздавать, т.к. они могут смещаться
local fix_ph_position = {
  [ "jupiter" ] = {
    [ "jup_b205_door_button" ] = 2343, -- кодовый замок на ЗРК "Волхов"
  },
  [ "l01_escape" ] = {
    [ "rebyta_smertniki_koster" ] = 3839, -- кострище Басти и К
  },
  [ "l04_darkvalley" ] = {
    [ "val_door_nedostroyka" ] = 5713, -- дверь в оружейку бандитов
  },
  [ "l07_military" ] = {
    [ "mil_physic_object0034" ] = 7854, -- дверь в оружейку свободы
    [ "mil_zabor_0000"        ] = 7991, -- взрываемый забор
  },
  [ "puzir" ] = {
    [ "puzir_arhara_vagonchik" ] = 14372, -- вагончик в ЗЛ
  },
}


function attach( sm )
  sm:subscribe({ signal = "on_before_first_update", fun = this.on_first_update })
  sm:subscribe({ signal = "on_before_spawn", fun = this.on_spawn })
end


local processed_info = {}
local vname          = "dsh_fixes.version"

function on_first_update()
  local fixes = {
    all_spawn_fix.respawn_allspawn,
    this.kill_journalist_npc,
    this.free_bar_visitors,
    this.free_bar_visitors_fix2,
    this.free_bar_ohotnik,
    this.free_kalmyak_marsh,
    this.free_marsh_exit_nebo,
    this.free_marsh_hunters,
    this.remove_ogse_relation_reverse_table,
    this.fix_zone_ameba,
    this.fix_prizrak_wpn,
    this.fix_val_rob_buying,
    this.fix_val_rob_buying,
    this.start_dsh_walking_job,
    this.fix_prizrak_gauss,
    this.fix_gener_spawn_tvari,
    this.fix_rx_wmgr_boxes,
    this.fix_nevid_monolit,
    this.free_aver_otshelnik,
    this.free_aver_hunter,
    this.fix_red_psy_dog_phantom,
    this.free_green_forest,
    this.free_stalker_forest_bashya,
    this.remove_marsh_ameba1,
    this.fix_crow_respawns,
    this.fix_taynik_alexandrych,
    this.fix_military_fotomuzhik,
    this.free_generators_orly,
    this.fix_af_pero,
    this.respawn_gavr_and_co, -- 29
    this.remove_padar_spawn_zombi_kukla_restrictor,
    this.fix_bandit_goodwill,
    this.fix_aes_battle_sounds,
    this.fix_pri_battle_sounds,
    this.fix_ogse_actor_conditions_mgr_cam_inert,
    this.fix_esc_bridge_pass_fire,
    this.respawn_gavr_and_co_2,
    this.fix_detector_suit,
    this.fix_mil_tush1,
    this.fix_grib_respawn,
    this.fix_horrortime_begin,
    this.fix_af_transform_cnt,
    this.fix_trade_dialog_timers,
    this.fix_trade_dialog_timers2,
    this.fix_stalk_semetskiy,
    this.fix_amk_anoms_generate_art,
    this.fix_trade_dialog_timers3,
    this.fix_kot_hos,
    this.fix_esc_buldozer22,
    this.fix_gg_need_sleep,
    this.fix_val_zapis,
    this.fix_dead_military_esc,
    this.fix_yantar_arhara_mine1,
    this.fix_horrortime_begin2,
    this.fix_foto_monolitovets,
    this.fix_emb,
    this.fix_dead_military_esc2,
    this.fix_war_door_lab,
    this.fix_find_chip,
    this.fix_dragunov_ohota_talk,
    this.fix_marsh_band_spawn,
    this.fix_bar_arena_door_0000,
    this.fix_aem_admin,
    this.fix_news_check,
    this.fix_show_news,
    this.fix_kotobegemot_bar,
    this.fix_drop_boxes,
    this.fix_running_treasure,
    this.fix_jup_gun_3,
    this.fix_letters,
    this.fix_krest_topor,
    this.fix_sleep_bags,
    this.fix_bar_arena_triger,
    this.fix_wpn_toz34_arena,
    this.fix_explosive_barrel,
    this.fix_tamaz_body2,
    this.fix_gar_dm_novice,
    this.fix_rebind_keys,
    this.fix_podval_btr_nevid1,
    this.fix_spawn_bunker_sekret,
    this.fix_bunker_art_v_spiral_restrictor,
    this.fix_btr_nevid_krusha_kultorg,
    this.fix_yakut_agro,
    this.fix_spawn_monstrov,
    this.fix_marsh_m_car,
    this.fix_gar_no_gravity_vorota,
    this.fix_marsh_havan_restr,
    this.fix_explosive_barrel2,
    this.fix_gar_angar,
    this.free_marsh_baza_nebo,
    this.fix_sysh_treasure_box,
    this.fix_zone_ozero,
    this.fix_zat_fireball,
    this.fix_door_hospital_01_l_0003,
    this.fix_mil_physic_object_0001,
    this.fix_dragunov_ohota,
    this.fix_l10u_bunker_codedoor_key_0000,
    this.fix_buusty_kvest_task,
    this.fix_strelok_taynik_pda0,
    this.fix_esc_dinamit_panera,
    this.fix_hamster_kuznec6,
    this.fix_handmade_arts_cnt,
    this.make_free_prizrak,
    this.fix_land_arhara_biliyrd,
    this.fix_se_respawn,
    this.fix_stalker_kisluy,
    this.fix_trade_dialog_maks,
    this.fix_esc_surprise_box_015,
    this.fix_dsh_rukzak_storage,
    this.fix_pseudodog_forest,
    this.fix_l10u_bunker_codedoor_key_0000_2,
    this.fix_dsh_ogse_relations,
    this.fix_dsh_deadmans_table_proxy,
    this.fix_dark_bland,
    this.fix_netpacket_pda,
    this.fix_amk_transmutator,
    this.fix_anim_ph_zone_0004,
    this.fix_sak_flash,
    this.fix_mozg,
    this.fix_wpn_gungauss,
    this.fix_info_restriction,
    this.fix_vasily_chertez_reminder,
    this.fix_prizrak_treasure_box,
    this.fix_dcity_pyatietazhka_yzik1,
    dsh_life_saver.got_life_saver,
    this.fix_explosive_barrel_all,
    this.fix_atp_presled_last,
    this.fix_warlab_sekret_generator5,
    this.fix_yakut_treasure_box,
    this.fix_black_dok_gener_say_done,
    this.fix_dsh_rukzak_access_time,
    this.fix_add_lchanger_location,
    this.fix_foto_ohota_have,
    this.fix_create_sr18,
    this.fix_dcity_stalki_matras_1,
    this.fix_add_new_lima_to_dead_city,
    this.fix_aver_muha_bazar_sms_restrictor,
    this.fix_val_bandit_krisyk,
    this.fix_dsity_rasstrel_end,
    this.fix_dcity_gg_neytral_restrictor,
    this.fix_dokplen_spawn_one_restrictor,
    this.fix_dcity_lastday,
    this.fix_marsh_udav,
    this.fix_val_borov_dead,
    this.fix_av_peshera_mono2_bunker_niz,
    this.fix_av_peshera_zone_emi1,
    this.fix_mar_level_changer_to_escape_1,
    this.fix_yan_st_stalker3_kamp_1,
    this.fix_pri_dimak,
    this.fix_pripyat_campfires,
    this.fix_x18_campfires,
    this.fix_pripyat_campfires2,
    this.fix_lab_pri1,
    this.fix_jupiter_underground,
    this.fix_lab_under,
    this.fix_labx8,
    this.fix_esc2_smart_stalker_exit_kamp_1,
    this.fix_agr2_st_factory_kamp_1,
    this.fix_l03_agroprom_candles,
    this.fix_l03u_agr_underground_candles,
    this.fix_jupiter,
    this.fix_jupiter_campfires,
    this.fix_warlab_fountain_average1_niz,
    this.fix_aver_zone_emi1,
    this.fix_arm_sklady_rg_box_0033,
    this.fix_marsh_campfires,
    this.fix_zaton,
    this.fix_zaton_campfires,
    this.fix_sherstuk_enemy,
    this.fix_zaton_campfires2,
    this.fix_karta_peschera,
    this.fix_pri1_zaton,
    this.fix_zaton_ukamney_lager,
    this.fix_bandit_zaton1,
    this.fix_upiter_gigants,
    this.fix_spawn_babki_dcity_restrictor,
    this.fix_esc_akim_lager,
    this.fix_arny_kogot,
    this.fix_haker_soft,
    this.fix_poisk_partizan_spawn,
    this.fix_val_zone_radioactive_average,
    this.fix_esc_dogs_swarm,
    this.fix_add_new_mil_110,
    this.fix_add_new_darkvalley_111,
    this.fix_radar_campfires,
    this.fix_x10_campfires,
    this.fix_poisk_partizan_spawn_2,
    this.fix_esc_kidalo,
    this.fix_grom_npc,
    this.fix_red_forest_candles,
    this.fix_limansk_campfires,
    this.fix_volazar,
    this.fix_living_dead_code,
    this.fix_fotograf_about,
    this.fix_volna_sak_have,
    this.fix_marsh_campfires2,
  }
  local version = ogse.load_var( vname, 0 )
  if version < table.getn( fixes ) then
    for i = version + 1, table.getn( fixes ) do
      fixes[ i ]( version )
    end
    ogse.save_var( vname, table.getn( fixes ), "u32" )
  end
  local fixes_on_info = {
    [ "vitamin_reyd_zadan_done" ] = {
      this.free_warlab_svobodovzu,
    },
    [ "borman_glushitel_done" ] = {
      this.free_freedom_limansk,
    },
    [ "derevny_zashita_done" ] = {
      this.free_lost_village_bandit,
      this.free_village_gulag_small,
    },
    [ "village_after_razborka" ] = {
      this.free_village_gulag_big,
    },
    [ "vkluchit_generator_done" ] = {
      this.free_generators_svoboda,
    },
    [ "spawn_kamen_udachy" ] = {
      this.free_hospital_black,
    },
  }
  for k, v in pairs( fixes_on_info ) do
    if db.actor:has_info( k ) and not processed_info[ k ] then
      log2( "%s: found fixes for '%s', applying...", script_name(), k )
      for _, f in ipairs( v ) do
        f()
        processed_info[ k ] = true
        local processed = ogse.load_var( "dsh_fixes.processed_info", {} )
        table.insert( processed, k )
        ogse.save_var(
          "dsh_fixes.processed_info", processed, "array_template",
          { "string" }
        )
      end
    end
  end
end


function on_spawn()
  local processed = ogse.load_var_safe( "dsh_fixes.processed_info" )
    or {}
  for _, k in ipairs( processed ) do
    processed_info[ k ] = true
  end
  fix_physic_objects()
  fix_bar_barman()
  fix_bar_angar_zoneguard()
  fix_bar_zastava_guard_3()
  fix_marsh_barman()
  fix_bar_arena_man()
  fix_yantar_ecolog_general()
  fix_dragunof_npc()
  fix_pri_dimak_pos()
  fix_akill_npc()
end


-- Сделать труп журналиста, который случайно заспаунился живым
function kill_journalist_npc()
  local sobj = alife():story_object( story_ids.journalist_npc )
  if sobj then
    local obj = level.object_by_id( sobj.id )
    if obj then
      obj:kill( obj )
    else
      ogse.kill_offline_npc( sobj )
    end
  end
end

function free_smart_terrain( name, skip_npc )
  local skip_npc_keys = {}
  if skip_npc then
    for _, v in ipairs( skip_npc ) do
      skip_npc_keys[ v ] = true
    end
  end
  local strn = smart_terrain.get_smart_terrain_by_name( name )
  for id, v in pairs( strn.npc_info ) do
    local sobj = alife():object( id )
    if not skip_npc_keys[ sobj:name() ] then
      local pk = get_netpk( sobj, 1 )
      if pk:isOk() then
        local data = pk:get()
        local cd   = data.custom_data:getTable()
        cd.smart_terrains = nil
        data.custom_data:set( cd )
        pk:set( data )
      end
      smart_terrain.unregister_npc( sobj )
      sobj.smart_terrain_conditions = nil
      sobj:brain():update()
    end
  end
end


-- Убрать у сталкеров жесткую привязку к смарту, что бы они могли уходить.
function free_bar_visitors()
  free_smart_terrain( "bar_visitors" );
end
function free_bar_visitors_fix2( ver )
  -- выполнять только если уже выполнялся free_bar_visitors()
  if ver == 2 then
    free_smart_terrain( "bar_visitors" );
  end
end

function free_bar_ohotnik()
  free_smart_terrain( "bar_ohotnik", { "stalker_green_zahar" } );
end

function free_kalmyak_marsh()
  free_smart_terrain( "kalmyak_marsh", { "kalmyak" } );
end

function free_marsh_exit_nebo()
  free_smart_terrain( "marsh_exit_nebo", { "dyak", "esc_saha" } );
end

function free_marsh_hunters()
  free_smart_terrain( "marsh_hunters", { "marsh_dan" } );
end


function cleanup_respawners()
  se_respawn.iterate_respawners( function( respawner )
      if respawner.parent then return end
      local ids = {}
      for _, id in ipairs( respawner.spawned_obj ) do
        table.insert( ids, id )
      end
      for _, id in ipairs( ids ) do
        local sobj = alife():object( id )
        if sobj then
          local strn_id
          if ( IsStalker( sobj ) or IsMonster( sobj ) ) and sobj.smart_terrain_id then
            strn_id = sobj:smart_terrain_id()
          else
            strn_id = 65535
          end
          if strn_id ~= 65535 then
            local strn = alife():object( strn_id )
            if strn then
              if
                not smart_terrain.is_same_level_group(
                  object_level_name( strn ),
                  object_level_name( sobj )
                )
              then
                log2(
                  "[cleanup_respawners]: remove %s from %s: smart_terrain %s has different level group: %s and %s",
                  id, respawner:name(), strn:name(),
                  object_level_name( strn ),
                  object_level_name( sobj )
                )
                respawner:remove_spawned( id )
              end
            else
              log2(
                "[cleanup_respawners]: remove %s from %s: smart_terrain %s not found",
                id, respawner:name(), strn_id
              )
              respawner:remove_spawned( id )
            end
          end
        else
          log2( "[cleanup_respawners]: remove %s from %s (%s): not found", id, respawner:name(), tostring( respawner.amk_name ) )
          respawner:remove_spawned( id )
        end
      end
  end )
end


function remove_ogse_relation_reverse_table()
  ogse.delete_var( "ogse_relation_reverse_table" )
end


local zone_ameba = {
  [ "atp_anom_ameba"              ] =   221,
  [ "atp_zone_ameba1_1"           ] =   222,
  [ "atp_zone_ameba1_2"           ] =   223,
  [ "land_arhara_anom_ameba1"     ] =   897,
  [ "land_arhara_anom_ameba2"     ] =   898,
  [ "aver_zone_ameba1_1"          ] =  1012,
  [ "aver_zone_ameba1_2"          ] =  1013,
  [ "aver_zone_ameba1_3"          ] =  1014,
  [ "labirint_arhara_ameba1"      ] =   458,
  [ "labirint_arhara_ameba2"      ] =   459,
  [ "av_peshera_ameba1_verx"      ] =   541,
  [ "av_peshera_ameba1_niz1"      ] =   542,
  [ "av_peshera_ameba1_niz2"      ] =   543,
  [ "dcity_zone_ameba1_1"         ] =  1285,
  [ "dcity_zone_ameba1_2"         ] =  1286,
  [ "dcity_zone_ameba1_3"         ] =  1287,
  [ "dcity_zvezda1"               ] =  1288,
  [ "dcity_zvezda2"               ] =  1289,
  [ "gener_zone_ameba1_1"         ] =  1585,
  [ "gener_zone_ameba1_2"         ] =  1586,
  [ "gener_anom_ameba"            ] =  1587,
  [ "gener_zone_ameba1_3"         ] =  1631,
  [ "gen_anom_ameba_krusha"       ] =  1813,
  [ "gen_anom_ameba_zabor"        ] =  1851,
  [ "esc_zone_ameba1_elevator"    ] =  3809,
  [ "esc_zone_ameba1_bunker"      ] =  3810,
  [ "garbage_zone_ameba1_les"     ] =  3898,
  [ "agro_zone_ameba1_razvilka"   ] =  4462,
  [ "dark_zone_ameba1_ostanovka"  ] =  5242,
  [ "dark_zone_ameba1_zapravka"   ] =  5243,
  [ "military_zone_ameba1_ostanovka" ] = 7581,
  [ "yantar_zone_ameba1_ostrov"   ] =  8469,
  [ "yantar_zone_ameba1_garaz"    ] =  8470,
  [ "radar_zone_ameba1_uchenuy"   ] =  9205,
  [ "radar_zone_ameba1_vert"      ] =  9206,
  [ "radar_zone_ameba1_dom_kukla" ] =  9207,
  [ "prip_zone_ameba1_koleso"     ] = 10369,
  [ "stancia_2_zone_ameba1"       ] = 11430,
  [ "village_zone_ameba1_yma"     ] = 12910,
  [ "village_zone_ameba1_pole"    ] = 12911,
  [ "village_anom_ameba1"         ] = 13025,
  [ "marsh_zone_ameba1_mex_dvor"  ] = 13232,
  [ "marsh_zone_ameba1_vushka"    ] = 13233,
  [ "marsh_zone_ameba1_tele_baza" ] = 13234,
  [ "marsh_zone_ameba1_vagonu"    ] = 13235,
--  [ "marsh_ameba1"                ] = 13388,
  [ "marsh_ameba2"                ] = 13389,
  [ "marsh_ameba3"                ] = 13390,
  [ "peshera_arhara_ameba1"       ] = 13829,
  [ "puzir_zone_ameba1_u_vxoda"   ] = 14314,
  [ "puzir_zone_ameba1_zenter"    ] = 14315,
  [ "puzir_zone_ameba1_krest"     ] = 14316,
  [ "puzir_zone_ameba1_vert_zent" ] = 14317,
  [ "zat_zone_ameba1_sosnodub_00" ] = 15574,
  [ "zat_zone_ameba1_sosnodub_01" ] = 15575,
  [ "zat_zone_ameba1_sosnodub_02" ] = 15576,
  [ "zat_zone_ameba1_sosnodub_03" ] = 15577,
  [ "zat_zone_ameba1_sosnodub_04" ] = 15578,
}

function fix_zone_ameba()
  for n, id in pairs( zone_ameba ) do
    if not alife():object( n ) then
      log2( "fix_zone_ameba: %s not found, creating...", n )
      alife():create( id )
    end
  end
end


function fix_prizrak_wpn()
  local npcs = { "new_prizrak", "generators_prizrak", "chaes1_prizrak" }
  for _, name in ipairs( npcs ) do
    local sobj = alife():object( name )
    if sobj then
      alife():create(
        "wpn_dark_gauss",
        sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
        sobj.id
      )
      alife():create(
        "ammo_gauss",
        sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
        sobj.id
      )
    end
  end
end


function fix_val_rob_buying()
  local strn = smart_terrain.get_smart_terrain_by_name( "val_rob" )
  strn:lock_population( true )
end


function cleanup_rats()
  local levels = {
    [ "atp_for_test22" ] = true,
    [ "av_peshera"     ] = true,
--    [ "aver"           ] = true,
--    [ "dead_city"      ] = true,
    [ "l01_escape"     ] = true,
    [ "l02_garbage"    ] = true,
    [ "l03_agroprom"   ] = true,
    [ "l03u_agr_underground" ] = true,
    [ "l04_darkvalley" ] = true,
    [ "l04u_labx18"    ] = true,
    [ "l05_bar"        ] = true,
    [ "l06_rostok"     ] = true,
    [ "l07_military"   ] = true,
    [ "l08_yantar"     ] = true,
    [ "l10_radar"      ] = true,
    [ "l10u_bunker"    ] = true,
    [ "l11_pripyat"    ] = true,
--    [ "l12_stancia"    ] = true,
--    [ "l12_stancia_2"  ] = true,
--    [ "l12u_control_monolith" ] = true,
--    [ "l12u_sarcofag"  ] = true,
    [ "marsh"          ] = true,
    [ "peshera"        ] = true,
    [ "puzir"          ] = true,
  }
  local sm = ogse_signals.get_mgr()
  for i = 1, 65535 do
    local sobj = alife():object( i )
    if
      sobj and IsMonster( sobj )
      and sobj:smart_terrain_id() == 65535
      and levels[ object_level_name( sobj ) ]
      and not (
        se_respawn.get_respawner_by_npc_id( sobj.id )
        or dsh_respawn.get_respawner_by_npc_id( sobj.id )
      )
    then
      log2( "dsh: found extra %s on %s", sobj:name(), object_level_name( sobj ) )
      alife():release( sobj )
      sm:call( "on_release_npc", sobj.id )
    end
  end
end


function start_dsh_walking_job()
  local next_m = math.random( 0, 59 )
  dsh.start_gtimerDHMS(
    "dsh_walking_stalkers.periodic_job",
    0, 1, next_m, 0,
    "dsh_walking_stalkers.periodic_job"
  )
end


function fix_prizrak_gauss()
  local npcs = { "new_prizrak", "generators_prizrak", "chaes1_prizrak" }
  for _, name in ipairs( npcs ) do
    local sobj = alife():object( name )
    if sobj then
      local sid = sobj.m_story_id
      alife():release( sobj )
      alife():create( alife():spawn_id( sid ) )
    end
  end
end


function fix_gener_spawn_tvari()
  local tvari = {
    [ "gener_electro_chim1_podstanziy" ] =  1847,
    [ "gener_electro_chim2_podstanziy" ] =  1848,
    [ "generators_bloodsucker_strong1" ] =  1771,
    [ "gen_bloodsucker_na_krushe"      ] =  1816,
    [ "red_bloodsucker_strong_0002"    ] = 14936,
    [ "red_m_poltergeist_strong_flame" ] = 14943,
    [ "red_m_poltergeist_normal_tele"  ] = 14945,
    [ "red_m_poltergeist_normal_tele_0000" ] = 14946,
  }
  for name, spawn_id in pairs( tvari ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "dsh: deleting %s", name )
      smart_terrain.unregister_npc( sobj )
      se_respawn.on_release_npc( sobj.id )
      dsh_respawn.on_release_npc( sobj.id )
      alife():release( sobj )
      log2( "dsh: creating %s, spawn_id = %s", name, spawn_id )
      sobj = alife():create( spawn_id )
      ASSERT( name == sobj:name(), "wrong spawn %s ~= %s", name, sobj:name() )
    end
  end
end


function fix_rx_wmgr_boxes( ver )
  if ver == 0 then return end
  local boxes = {}
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if
      sobj and sobj:section_name() == "inventory_box"
      and sobj.position.y == -300
    then
      log2( "dsh: found %s on %s", sobj:name(), object_level_name( sobj ) )
      boxes[ id ] = sobj
    end
  end
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if sobj and boxes[ sobj.parent_id ] then
      log2( "dsh: found %s on %s", sobj:name(), object_level_name( sobj ) )
      alife():release( sobj )
    end
  end
  for id, sobj in pairs( boxes ) do
    alife():release( sobj )
  end
end


function fix_nevid_monolit()
  local sobj = alife():object( "nevid_monolit" )
  if sobj and sobj:alive() then
    local sid = sobj.m_story_id
    alife():release( sobj )
    sobj = alife():create( alife():spawn_id( sid ) )
    pk = get_netpk( sobj, 1 )
    if pk:isOk() then
      local data = pk:get()
      data.visual_name = "new\\supernevidimka_orig"
      pk:set( data )
    end
  end
end


function free_aver_otshelnik()
  free_smart_terrain( "aver_otshelnik" );
end


function free_aver_hunter()
  free_smart_terrain( "aver_hunter" );
end


function fix_red_psy_dog_phantom()
  local sobj = alife():object( "red_psy_dog_phantom" )
  if sobj then
    log2( "dsh: deleting %s", sobj:name() )
    smart_terrain.unregister_npc( sobj )
    se_respawn.on_release_npc( sobj.id )
    dsh_respawn.on_release_npc( sobj.id )
    alife():release( sobj )
  end
end


local bar_walk_fixes = {
  [ "bar_bar_drunk_dolg"   ] = {
    path = "bar_bar_visitor_dolg_walk",
    pos  = vector():set(
      134.305435180664, -4.83976221084595, 26.5520305633545
    ),
  },
  [ "bar_bar_guard_2"      ] = "bar_bar_guard_walk",
  [ "bar_bar_lisiy"        ] = "bar_bar_square_3_place_1_walk",
  [ "bar_bar_visitor_hunter" ] = {
    path = "bar_bar_visitor_hunter_walk",
    pos  = vector():set(
      129.895431518555, -4.84401607513428, 28.121150970459
    ),
  },
  [ "bar_bar_visitors_2_1" ] = {
    path = "bar_bar_square_2_place_1_walk",
    pos  = vector():set(
      133.679824829102, -4.82401657104492, 29.4379711151123
    ),
  },
  [ "bar_barman"           ] = "bar_barman_hole_walk",
  [ "bar_dolg_bunker_0002" ] = "bar_dolg_bunker_guard_5_walk",
}

function fix_bar_barman()
  if level.name() == "l05_bar" then
    for name, path in pairs( bar_walk_fixes ) do
      local sobj = alife():object( name )
      if sobj then
        local pos
        if type( path ) == "table" then
          pos  = path.pos
          path = path.path
        end
        local patrol = patrol( path )
        alife():teleport_object(
          "",
          ( pos or patrol:point( 0 ) ),
          patrol:level_vertex_id( 0 ), patrol:game_vertex_id( 0 ),
          sobj.id
        )
      end
    end
  end
end


function free_green_forest()
  free_smart_terrain( "green_forest" );
end


function free_stalker_forest_bashya()
  free_smart_terrain( "stalker_forest_bashya" );
end


function remove_marsh_ameba1()
  local sobj = alife():object( "marsh_ameba1" )
  if sobj then
    alife():release( sobj )
  end
end


function free_warlab_svobodovzu()
  free_smart_terrain( "warlab_svobodovzu" );
end


function free_freedom_limansk()
  free_smart_terrain( "freedom_limansk" );
end


function free_lost_village_bandit()
  free_smart_terrain( "lost_village_bandit" );
end


function free_village_gulag_small()
  free_smart_terrain( "village_gulag_small" );
end


function free_village_gulag_big()
  free_smart_terrain( "village_gulag_big" );
end


function fix_crow_respawns()
  local sm = ogse_signals.get_mgr()
  for id = 1, 65534 do
    local crow = alife():object( id )
    if crow and string.find( crow:name(), "m_crow", 1, true ) then
      sm:call( "on_release_npc", id )
      alife():release( crow )
    end
  end
end


function fix_taynik_alexandrych()
  if ver == 0 then return end
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if sobj and sobj:section_name() == "m_inventory_box_alex_upiter" then
      alife():release( sobj )
      buusty_dialog.taynik_alexandrych_spawn()
      break
    end
  end
end


function fix_military_fotomuzhik()
  local names = { "military_fotomuzhik", "milit_zapas_fotomuzhik" }
  for _, n in ipairs( names ) do
    local sobj = alife():object( n )
    if sobj and sobj:alive() then
      pk = get_netpk( sobj, 1 )
      if pk:isOk() then
        local data = pk:get()
        data.visual_name = "new\\supernevidimka_orig"
        pk:set( data )
      end
    end
  end
end


function free_generators_orly()
  free_smart_terrain( "generators_orly", { "zemlyk" } );
end


function fix_af_pero()
  for i = 1, 65535 do
    local sobj = alife():object( i )
    if sobj and sobj:section_name() == "af_pero" then
      log2( "dsh: found %s", sobj:name() )
      local obj = level.object_by_id( sobj.id )
      if obj then
        obj:set_condition( 1 )
      end
      local tbl = amk.get_item_params( sobj )
      tbl.condition = 1
      amk.set_item_params( tbl, sobj )
    end
  end
end


function respawn_gavr_and_co()
  local sids = {
    [ 9623 ] = "mil_trader_gavr",
    [ 9624 ] = "mil_gavr_bodyguard1",
    [ 9625 ] = "mil_gavr_bodyguard2",
  }
  for sid, sect in pairs( sids ) do
    while alife():story_object( sid ) do
      local sobj = alife():story_object( sid )
      if sobj then
        log2(
          "dsh: found %s ( %s, %s )",
          sobj:name(), sobj:community(), object_level_name( sobj )
        )
        local strn_id = sobj:smart_terrain_id()
        if strn_id ~= 65535 then
          local strn = alife():object( strn_id )
          if strn then
            log2( "dsh: smart_terrain = %s", strn:name() )
            smart_terrain.unregister_npc( sobj )
          end
        end
        ogse_signals.get_mgr():call( "on_release_npc", sobj.id )
        alife():release( sobj )
      end
    end
  end
  if
    db.actor:has_info( "informator_pda_done" )
    and not db.actor:has_info( "info_gavr_dead" )
  then
    new_spawn.bar_informator()
  end
end


function remove_padar_spawn_zombi_kukla_restrictor()
  if db.actor:has_info( "muha_kukla_have" ) then
    local sobj = alife():object( "padar_spawn_zombi_kukla_restrictor" )
    if sobj then
      log2( "dsh: found %s", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_aes_battle_sounds()
  local names = {
    "aes_space_restrictor_sound_battle_0000",
    "aes_space_restrictor_sound_battle_0001",
  }
  for _, n in ipairs( names ) do
    local sobj = alife():object( n )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_marsh_barman()
  if level.name() == "marsh" then
    local sobj = alife():object( "marsh_barman" )
    if sobj then
      local patrol = patrol( "marsh_barman_walk" )
      alife():teleport_object(
        "", patrol:point( 0 ),
        patrol:level_vertex_id( 0 ), patrol:game_vertex_id( 0 ),
        sobj.id
      )
    end
  end
end


function fix_pri_battle_sounds()
  local names = {
    "pri_ambient_battle_sound_zone_0000",
    "pri_ambient_battle_sound_zone_0001",
    "pri_ambient_battle_sound_zone_0002",
    "pri_ambient_battle_sound_zone_0003",
  }
  for _, n in ipairs( names ) do
    local sobj = alife():object( n )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_ogse_actor_conditions_mgr_cam_inert()
  ogse.delete_var( "ogse_actor_conditions_mgr.cam_inert" )
  cmd( "cam_inert", "0" )
end


function fix_esc_bridge_pass_fire()
  db.actor:disable_info_portion( "esc_bridge_pass_fire" )
  db.actor:disable_info_portion( "sherstuk_enemy" )
end


function respawn_gavr_and_co_2( ver )
  -- выполнять только, если выполнялся respawn_gavr_and_co()
  if ver >= 29 then
    respawn_gavr_and_co()
  end
end


function fix_detector_suit()
  local obj = db.actor:object( "detector_suit" )
  if obj then
    local sobj = alife():object( obj:id() )
    if sobj then
      alife():release( sobj )
    end
  end
end


function free_generators_svoboda()
  free_smart_terrain( "generators_svoboda" );
end


function free_hospital_black()
  free_smart_terrain( "hospital_black" );
end


function fix_mil_tush1()
  local respawners = {
    "av_peshera_rat1",
    "av_peshera_rat2",
    "av_peshera_rat3",
    "av_peshera_rat4",
    "av_peshera_rat5",
    "esc_fracture",
    "dv_sak_1monstr",
    "mil_tush1",
    "mil_himer_family",
  }
  for _, name in ipairs( respawners ) do
    local resp = dsh_respawn.get_respawner( name )
    if resp then
      for _, v in ipairs( resp.spawned_obj ) do
        resp:remove_spawned( v )
      end
    end
  end
end


function fix_bar_angar_zoneguard()
  local sobj = alife():object( "bar_angar_zoneguard" )
  if not sobj then
    log2( "dsh: bar_angar_zoneguard not found, respawning..." )
    alife():create( 6759 )
  end
end


function fix_grib_respawn()
  braad_test.grib_respawn()
end


function fix_horrortime_begin()
  log2( "dsh: starting up horror time timer" )
  meceniy_in_hell.horrortime_begin( true )
end


function fix_af_transform_cnt()
  dsh.reset_af_transform_cnt()
end


function fix_trade_dialog_timers()
  db.actor:disable_info_portion( "price_doktor" )
  dsh.start_trade_dialog_timer( "sidor", 168, 10 )
  dsh.start_trade_dialog_timer( "barman"   )
  dsh.start_trade_dialog_timer( "petrenko" )
  dsh.start_trade_dialog_timer( "skraga"   )
  dsh.start_trade_dialog_timer( "sakharov" )
  dsh.start_trade_dialog_timer( "sak"      )
end


function fix_trade_dialog_timers2()
  dsh.start_trade_dialog_timer( "kuznezov", 168, 10 )
  dsh.start_trade_dialog_timer( "jlob"     )
  dsh.start_trade_dialog_timer( "sherstyk" )
end


function fix_stalk_semetskiy()
  if db.actor:has_info( "odnonogiy_first_start" ) then
    local sobj = alife():object( "stalk_semetskiy" )
    if sobj then
      log2( "dsh: found %s", sobj:name() )
      alife():release( sobj )
      log2( "dsh: ... removed" )
    end
  end
end


function fix_amk_anoms_generate_art()
  ogse.delete_var( "amk_anoms.generate_art" )
end


function fix_trade_dialog_timers3()
  dsh.start_trade_dialog_timer( "voron" )
end


function fix_bar_zastava_guard_3()
  local sobj = alife():story_object( story_ids.bar_zastava_commander ) -- 518
  if not sobj then
    log2( "dsh: bar_zastava_commander not found, respawning..." )
    alife():create( alife():spawn_id( story_ids.bar_zastava_commander ) )
  end
end


function fix_kot_hos()
  if db.actor:has_info( "we_ne_chmuri" ) then
    local sobj = alife():object( "kot_hos" )
    if sobj then
      log2( "dsh: found %s", sobj:name() )
      alife():release( sobj )
      log2( "dsh: ... removed" )
    end
  end
end


function fix_esc_buldozer22()
  local sobj = alife():object( "esc_buldozer22" )
  if sobj then
    log2( "dsh: found %s", sobj:name() )
    alife():release( sobj )
    log2( "dsh: ... removed" )
  end
end


function fix_gg_need_sleep()
  -- log2( "dsh: starting gg_need_sleep timer ..." )
  -- dsh_sleep.run_gg_need_sleep_timer()
end


function fix_val_zapis()
  for i = 1, 65535 do
    local sobj = alife():object( i )
    if sobj and string.find( sobj:section_name(), "^val_zapis_" ) then
      log2( "dsh: found %s, removing ...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_dead_military_esc()
--  if db.actor:dont_has_info( "snp_borov1_start" ) then
--    local sobj = alife():object( "dead_military_esc" )
--    if sobj then
--      log2( "dsh: found %s, spawning: snp_pda1", sobj:name() )
--      alife():create(
--        "snp_pda1",
--        sobj.position, sobj.m_level_vertex_id, sobj.m_game_vertex_id,
--        sobj.id
--      )
--    end
--  end
end


function fix_yantar_arhara_mine1()
  local sobj = alife():object( "yantar_arhara_mine1" )
  if sobj then
    log2( "dsh: found %s", sobj:name() )
    alife():release( sobj )
    log2( "dsh: ... removed" )
  end
end


function fix_horrortime_begin2()
  log2( "dsh: stopping the horror time timer" )
  meceniy_in_hell.horrortime_stop()
end


function fix_foto_monolitovets()
  local names = {
    "milit_zapas_fotomuzhik",
    "foto_monolitovets",
    "dcity_dok_nevidim",
    "wolffrend_talk",
    "bibliofrend_talk",
    "bibliofrend_talk_black",
    "esc_foto_muzhik",
    "zapasnoy_foto_muzhik",
  }
  for _, n in ipairs( names ) do
    local sobj = alife():object( n )
    if sobj and sobj:alive() then
      log2( "dsh: found %s", sobj:name() )
      pk = get_netpk( sobj, 1 )
      if pk:isOk() then
        local data = pk:get()
        data.visual_name = "new\\supernevidimka_orig"
        pk:set( data )
        log2( "dsh: ... changed" )
      end
    end
  end
end


function fix_emb( ver )
  if ver == 0 then return end
  local idx = amk.load_variable( "emb_idx", 0 )
  if idx > 0 then
    log2( "dsh: found emb_idx = %s, disabling...", idx )
    emb.worker_clean( idx )
    amk.del_variable( "emb_idx" )
    log2( "dsh: ... done" )
  end
  local infos = {
    "emb_container_done",
    "embt_vp1_done",
    "emb_kill_tm_done",
    "embt_td1_done",
    "emb_done",
  }
  news_manager.skip_send_task = true
  for _, info in ipairs( infos ) do
    db.actor:give_info_portion( info )
  end
  if
    db.actor:has_info( "ten_monolita_talk_done" )
    and not db.actor:has_info( "tm_find_info_done" )
  then
    level_tasks.set_task_state( task.completed, "tm_find_info", 0 )
    level_tasks.set_task_state( task.completed, "tm_find_info", 1 )
  end
  dsh.timeout( 1, function()
    news_manager.skip_send_task = false
  end )
end


function fix_dead_military_esc2()
  local remove_items = {
    "snp_note1",
    "snp_pda1",
  }
  for i = 1, 65534 do
    local sobj = alife():object( i )
    if sobj then
      local sect = sobj:section_name()
      if remove_items[ sect ] then
        log2( "dsh: found %s, deleting...", sobj:name() )
        alife():release( sobj )
      end
    end
  end
  local sobj = alife():story_object( 19901 )
  if sobj then
    log2( "dsh: found %s, deleting...", sobj:name() )
  end
  local infos = {
    "snp_borov1_start",
    "snp_find_sniper1_done",
    "snp_borov1_done",
    "snp_find_name1_done",
    "snp_kotobegemot1_done",
    "snpt_dt1_done",
    "snp_kotobegemot2_done",
    "snp_bioradar_parts_done",
  }
  news_manager.skip_send_task = true
  for _, info in ipairs( infos ) do
    db.actor:give_info_portion( info )
  end
  dsh.timeout( 1, function()
    news_manager.skip_send_task = false
  end )
end


function fix_war_door_lab()
  local sobj = alife():object( "war_door_lab" )
  if sobj then
    log2( "dsh: found %s, respawning...", sobj:name() )
    alife():release( sobj )
    alife():create( 14960 )
  end
end


function fix_find_chip( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "find_chip_start" )
    and not db.actor:has_info( "find_chip_have" )
  then
    level_tasks.set_task_state( task.completed, "find_chip", 0 )
    level_tasks.set_task_state( task.completed, "find_chip", 1 )
  end
  if
    db.actor:has_info( "vasily_chertez_start" )
    and not db.actor:has_info( "vasily_chertez_done" )
  then
    level_tasks.set_task_state( task.completed, "vasily_chertez", 0 )
    level_tasks.set_task_state( task.completed, "vasily_chertez", 1 )
  end
  dsh.timeout( 1, function()
    news_manager.skip_send_task = false
  end )
end


function fix_dragunov_ohota_talk( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "dragunov_ohota_start" )
    and not db.actor:has_info( "dragunov_ohota_talk" )
  then
    log2( "dsh: giving 'dragunov_ohota_talk' info_portion" )
    db.actor:give_info_portion( "dragunov_ohota_talk" )
  end
end


function fix_bar_arena_door_0000()
  all_spawn_fix.release_allspawn_object( "bar_arena_door_0000" )
end


function fix_marsh_band_spawn()
  if not db.actor:has_info( "marsh_band_spawn" ) then
    log2( "dsh: marsh_band_spawn not found, executing braad_test.marsh_band_spawn()" )
    braad_test.marsh_band_spawn()
  end
end


function fix_aem_admin()
  local id = xr_logic.pstor_retrieve( db.actor, "aem_id", 0 )
  if id > 0 then
    local sobj = alife():object( id )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
      db.storage[ db.actor:id() ].pstor[ "aem_id" ] = nil
    end
  end
end


function fix_bar_arena_man()
  local sobj = alife():story_object( story_ids.bar_arena_locator ) -- 571
  if not sobj then
    log2( "dsh: bar_arena_man not found, respawning..." )
    alife():create( alife():spawn_id( story_ids.bar_arena_locator ) )
  end
end


function fix_news_check()
  if amk.has_g_timer( "news_check" ) then
    log2( "dsh: found news_check amk timer, removing..." )
    amk.remove_timer( "news_check" )
  end
end


function fix_show_news()
  if amk.has_g_timer( "show_news" ) then
    log2( "dsh: found show_news amk timer, removing..." )
    amk.remove_timer( "show_news" )
  end
end


function fix_bandit_goodwill() end


function fix_kotobegemot_bar()
  local sobj = alife():story_object( 19901 )
  if sobj then
    log2( "dsh: found %s, deleting...", sobj:name() )
    alife():release( sobj )
  end
end


function fix_drop_boxes( ver )
  if ver == 0 then return end
  for _, v in ipairs( xr_box_data.def_boxes ) do
    local name, spawn_id = unpack( v )
    local sobj = alife():object( name )
    if sobj then
      log2( "dsh: found %s, skipping", sobj:name() )
    else
      log2( "dsh: %s not found, respawning...", name )
      sobj = alife():create( spawn_id )
      local pk = get_netpk( sobj, 1 )
      ASSERT( pk:isOk(), "can't read netpacket of %s", sobj:name() )
      local data = pk:get()
      data.visual_name = [[physics\box\box_wood_01]]
      data.custom_data:setString(
        "[drop_box]\norig_name = " .. name .. "\ncommunity = def_box\n"
      )
      data.physic_type = 3
      data.mass        = 10
      pk:set( data )
    end
  end
end


function fix_running_treasure()
  dsh.start_gtimerDHMS(
    "dsh_running_treasure.clear_rnd_treasure",
    0, math.random( 20, 24 * 7 ), 0, 0,
    "dsh_running_treasure.spawn_rnd_treasure"
  )
end


function fix_jup_gun_3()
  local items = {
    "jup_gun_2", "jup_gun_3",
    "jup_ammo_1", "jup_ammo_2", "jup_ammo_3", "jup_ammo_4", "jup_ammo_5",
    "jup_ammo_6", "jup_ammo_7",
  }
  for _, n in ipairs( items ) do
    local sobj = alife():object( n )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_letters( ver )
  if ver == 0 then return end
  local items = {}
  db.actor:iterate_inventory(
    function( npc, obj )
      if obj:section() == "letter" then
        table.insert( items, obj )
      end
    end,
    db.actor
  )
  for _, obj in ipairs( items ) do
    log2( "dsh: found %s, removing...", obj:name() )
    ogse.remove_item_from_inventory( obj )
  end
end


function fix_krest_topor( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "krest_topor" )
    and not db.actor:has_info( "krest_topor_done" )
  then
    log2( "dsh: giving 'krest_topor_done' info_portion" )
    news_manager.skip_send_task = true
    db.actor:give_info_portion( "krest_topor_done" )
    dsh.timeout( 0, function()
      news_manager.skip_send_task = false
    end )
  end
end


function fix_sleep_bags()
  -- Подушка на диване, в подвале ДН.
  dsh.spawn_physic_sleep_bag(
    vector():set( -214.66897583008,-22.854312896729,-127.25451660156 ),
    39266, 59
  )
  -- На АС, в штабе.
  dsh.spawn_physic_sleep_bag(
    vector():set( -19.310693740845,-3.7826442718506,-21.311328887939 ),
    288157, 1593
  )
  -- У Борова, в ТД.
  dsh.spawn_physic_sleep_bag(
    vector():set( 39.124752044678,4.880298614502,-81.890159606934 ),
    223240, 1100
  )
  -- У ученых в бункере, на Янтаре.
  dsh.spawn_physic_sleep_bag(
    vector():set( 30.377950668335,-10.974708557129,-279.49533081055 ),
    54978, 1480
  )
  -- На Баре, в штабе Долга.
  dsh.spawn_physic_sleep_bag(
    vector():set( 232.12272644043,-5.1097793579102,128.38359069824 ),
    59078, 1200
  )
  -- В Баре, у ремонтников.
  dsh.spawn_physic_sleep_bag(
    vector():set( 113.90551757813,-4.9745478630066,13.434575080872 ),
    33613, 1239
  )
  -- На Агропроме, на втором этаже, над сталкерами.
  dsh.spawn_physic_sleep_bag(
    vector():set( 0.75571030378342,7.836715221405,14.530187606812 ),
    239682, 682
  )
  -- На Свалке, в ангаре.
  dsh.spawn_physic_sleep_bag(
    vector():set( -73.496315002441,-1.8777117729187,16.13635635376 ),
    134381, 330
  )
  -- На Болотах, у охотников.
  dsh.spawn_physic_sleep_bag(
    vector():set( 409.00204467773,3.5339589118958,236.85739135742 ),
    409496, 3546
  )
  -- На Болотах, на базе ЧН.
  dsh.spawn_physic_sleep_bag(
    vector():set( -141.90623474121,1.1168230772018,-318.71026611328 ),
    75332, 3374
  )
  -- На Генераторах, в развалинах дома.
  dsh.spawn_physic_sleep_bag(
    vector():set( -122.82690429688,38.734680175781,-522.4990234375 ),
    194439, 3089
  )
  -- В Красном Лесу, у моста.
  dsh.spawn_physic_sleep_bag(
    vector():set( -119.96662902832,0.89263081550598,-256.01147460938 ),
    9112, 3241
  )
  -- В Красном Лесу, в вогончике у сталкеров.
  dsh.spawn_physic_sleep_bag(
    vector():set( 14.4216381073,1.4473948478699,-46.648189544678 ),
    74929, 3290
  )
  -- На АТП, рядом с Калининым.
  dsh.spawn_physic_sleep_bag(
    vector():set( -173.61164855957,3.5274684429169,225.39572143555 ),
    125764, 2799
  )
  -- На Неразведанной Земле, в домике у Отшельника.
  dsh.spawn_physic_sleep_bag(
    vector():set( -344.14367675781,-8.6550722122192,-7.5538892745972 ),
    277313, 2889
  )
end


function fix_bar_arena_triger()
  local bad_sr = {
    "bar_arena_triger",
    "bar_arena_comment_1",
    "bar_arena_comment_1_0000",
    "bar_arena_comment_1_0001",
    "bar_arena_rank_checker",
    "bar_arena_check_death",
    "bar_arena_comment_1_0002",
    "bar_arena_comment_1_0003",
    "bar_arena_comment_1_0004",
    "bar_arena_comment_1_0005",
    -- "bar_arena_restrictor",
  }
  for _, n in ipairs( bad_sr ) do
    local sobj = alife():object( n )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_wpn_toz34_arena( ver )
  if ver == 0 then return end
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if sobj and isMagazinedWeapon( sobj ) then
      local ammo = parse_names(
        get_string( sobj:section_name(), "ammo_class", "" )
      )
      local pk = get_netpk( sobj, 1 )
      if pk:isOk() then
        local data      = pk:get()
        local ammo_type = data.ammo_type
        if ammo_type >= table.getn( ammo ) then
          log2(
            "dsh: found wrong ammo_type: %s: %s >= %s",
            sobj:name(), ammo_type, table.getn( ammo )
          )
          data.ammo_type = 0
          pk:set( data )
        end
      end
    end
  end
end


function fix_explosive_barrel( ver )
  local loc  = {
    [ "atp_for_test22" ] = true,
    [ "aver"           ] = true,
    [ "dead_city"      ] = true,
    [ "generators"     ] = true,
    [ "hospital"       ] = true,
    [ "l01_escape"     ] = true,
    [ "l02_garbage"    ] = true,
    [ "l03_agroprom"   ] = true,
    [ "l04_darkvalley" ] = true,
    [ "l05_bar"        ] = true,
    [ "l06_rostok"     ] = true,
    [ "l07_military"   ] = true,
    [ "l08_yantar"     ] = true,
    [ "l10_radar"      ] = true,
    [ "l11_pripyat"    ] = true,
    [ "limansk"        ] = true,
    [ "lost_village"   ] = true,
    [ "marsh"          ] = true,
    [ "peshera"        ] = true,
    [ "red_forest"     ] = true,
    [ "warlab"         ] = true,
  }
  local sect = {
    [ "explosive_barrel"    ] = true,
    [ "explosive_fuelcan"   ] = true,
    [ "explosive_mobiltank" ] = true,
  }
  for i = 1, 65534 do
    local sobj = alife():object( i )
    if
      sobj and sect[ sobj:section_name() ]
      and loc[ object_level_name( sobj ) ]
    then
      log2( 
        "dsh: found %s on %s, removing", sobj:name(), object_level_name( sobj )
      )
      alife():release( sobj )
    end
  end
end


function fix_tamaz_body2()
  local sobj = alife():object( "tamaz_body2" )
  if sobj then
    log2( "dsh: found %s, removing...", sobj:name() )
    alife():release( sobj )
  end
end


function fix_gar_dm_novice( ver )
  if ver == 0 then return end
  local names = {
    [ "gar_dm_novice"   ] = 3970,
    [ "gar_seryi_drug2" ] = 4032,
    [ "gar_seryi_drug3" ] = 4051,
  }
  for name, spawn_id in pairs( names ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "dsh: found %s, recreating and teleporting...", sobj:name() )
      local pos = sobj.position
      local lvid, gvid = sobj.m_level_vertex_id, sobj.m_game_vertex_id
      alife():release( sobj )
      sobj = alife():create( spawn_id )
      alife():teleport_object( "", pos, lvid, gvid, sobj.id )
    end
  end
end


function fix_rebind_keys( ver )
  if ver == 0 then return end
  local keys = {
    [ "night_vision" ] = "ogse_nv_bind",
    [ "scores"       ] = "ogse_antirad_bind",
    [ "cam_4"        ] = "ogse_energy_drink_bind",
    [ "cam_3"        ] = "ogse_yod_bind",
    [ "torch"        ] = "ogse_bipsizon_bind",
    [ "drop"         ] = "ogse_handradio_bind",
    [ "buy_menu"     ] = "ogse_quicksave_bind",
  }
  local data = dsh_cfg.get_data()
  for k, v in pairs( keys ) do
    local dik = get_console():get_integer( v )
    if v then
      local kn = ogse_rebind_key.dik_to_name( dik )
      if kn ~= "" then
        log2( "dsh: rebind %s to %s", k, kn )
        data[ k ] = kn
        cmd( "bind " .. k, kn )
      end
    end
  end
  dsh_cfg.save()
end


function fix_podval_btr_nevid1( var )
  for _, name in ipairs({ "podval_btr_nevid1", "podval_btr_nevid2" }) do
    local sobj = alife():object( name )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_spawn_bunker_sekret( ver )
  if ver == 0 then return end
  local items = {
    [ "neizv_zapiska" ] = {
      [ "args" ] = { vector():set( 7.608, -22.439, 13.871 ), 7695, 2773 },
    },
    [ "osnova_fotik"  ] = {
      [ "args" ] = { vector():set( 7.608, -22.439, 13.871 ), 7695, 2773 },
    },
  }
  for i = 1, 65535 do
    local sobj = alife():object( i )
    if
      sobj and items[ sobj:section_name() ]
      and sobj.parent_id == 65535
      and object_level_name( sobj ) == "l10u_bunker"
    then
      items[ sobj:section_name() ].sobj = sobj
    end
  end
  for k, v in pairs( items ) do
    if v.sobj then
      log2( "dsh: found %s, recreating...", v.sobj:name() )
      alife():release( v.sobj )
      alife():create( k, unpack( v.args ) )
    end
  end
end


function fix_bunker_art_v_spiral_restrictor( ver )
  local sobj = alife():object( "bunker_art_v_spiral_restrictor" )
  if sobj then
    log2( "dsh: found %s, removing...", sobj:name() )
    alife():release( sobj )
  end
end


function fix_btr_nevid_krusha_kultorg( ver )
  local sobj = alife():object( "btr_nevid_krusha_kultorg" )
  if sobj then
    log2( "dsh: found %s, removing...", sobj:name() )
    alife():release( sobj )
  end
end


function fix_yantar_ecolog_general( ver )
  if level.name() == "l08_yantar" then
    local sobj = alife():object( "yantar_ecolog_general" )
    if sobj then
      local patrol = patrol( "yan_ucheniy_walk_talk" )
      alife():teleport_object(
        "", patrol:point( 0 ),
        patrol:level_vertex_id( 0 ), patrol:game_vertex_id( 0 ),
        sobj.id
      )
    end
  end
end


function fix_yakut_agro( ver )
  if ver == 0 then return end
  local sobj = alife():story_object( story_ids.yakut_agro ) -- 9630
  if not sobj then
    log2( "dsh: respawning yakut_agro..." )
    alife():create( alife():spawn_id( story_ids.yakut_agro ) )
  end
end


function fix_spawn_monstrov( ver )
  if ver == 0 then return end
  local sm = ogse_signals.get_mgr()
  for i = 1, 65535 do
    local sobj = alife():object( i )
    if
      sobj and IsMonster( sobj ) and sobj:clsid() == clsid.zombie_s
      and sobj:smart_terrain_id() == 65535
      and object_level_name( sobj ) == "l01_escape"
      and not (
        se_respawn.get_respawner_by_npc_id( sobj.id )
        or dsh_respawn.get_respawner_by_npc_id( sobj.id )
      )
    then
      log2( "dsh: found extra %s on %s", sobj:name(), object_level_name( sobj ) )
      alife():release( sobj )
      sm:call( "on_release_npc", sobj.id )
    end
  end
end


function fix_marsh_m_car( ver )
  local cars = { "veh_car_baggi", "mar_zil130" }
  for _, name in ipairs( cars ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_gar_no_gravity_vorota( ver )
  local sobj = alife():object( "gar_no_gravity_vorota" )
  if sobj then
    log2( "dsh: found %s, removing...", sobj:name() )
    alife():release( sobj )
  end
end


function fix_marsh_havan_restr( ver )
  local sobj = alife():object( "marsh_havan_restr" )
  if sobj then
    log2( "dsh: found %s, removing...", sobj:name() )
    alife():release( sobj )
  end
end


function fix_explosive_barrel2( ver )
  if ver == 0 then return end
  fix_explosive_barrel( ver )
end


function fix_gar_angar( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "garbage_meetstalker_done" )
    or db.actor:has_info( "garbage_meetstalker_die" )
  then
    local sobj = alife():object( "gar_angar" )
    if sobj then
      log2( "dsh: found %s, changing profile...", sobj:name() )
      ogse_signals.get_mgr():call( "on_empty_smart_terrain", sobj )
    end
  end
end


function free_marsh_baza_nebo()
  free_smart_terrain( "marsh_baza_nebo", { "clear_scy_leader", "agr_nebo_trader" } );
end


function fix_sysh_treasure_box()
  if
    not (
      db.actor:has_info( "treasure_sysh_start" )
      or db.actor:has_info( "treasure_sysh_have" )
    )
  then
    local sobj = alife():story_object( story_ids.sysh_treasure_box ) -- 9663
    if sobj then
      log2( "dsh: found %s, removing...", sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_zone_ozero( ver )
  local sobj = alife():create(
    "zone_ozero",
    vector():set( 58.848209381104, 1.0079244375229, 367.44982910156 ),
    276095, 3760
  )
  log2( "[%s]: created %s", script_name(), sobj:name() )
end


function fix_zat_fireball( ver )
  if ver == 0 then return end
  local anoms = {
    [ "zat_fireball_1" ] = 15603,
    [ "zat_fireball_2" ] = 15604,
    [ "zat_psychic_1"  ] = 15606,
    [ "zat_psychic_2"  ] = 15607,
    [ "zat_psychic_3"  ] = 15608,
    [ "zat_psychic_4"  ] = 15609,
    [ "zat_psychic_5"  ] = 15610,
    [ "zat_psychic_6"  ] = 15611,
    [ "zat_psychic_7"  ] = 15612,
    [ "zat_psychic_8"  ] = 15613,
    [ "zat_psychic_9"  ] = 15614,
    [ "zat_psychic_10" ] = 15615,
    [ "zat_psychic_11" ] = 15616,
    [ "zat_psychic_12" ] = 15617,
    [ "zat_psychic_13" ] = 15618,
    [ "zat_fireball_3" ] = 15626,
    [ "zat_elecball_4" ] = 15627,
    [ "pri_acidball"   ] = 14293,
    [ "pri_fireball_1" ] = 14294,
    [ "pri_acidball_2" ] = 14295,
    [ "pri_elecball_3" ] = 14296,
    [ "jup_elecball"   ] = 2774,
  }
  for name, spawn_id in pairs( anoms ) do
    local sobj = alife():object( name )
    if not sobj then
      log2( "[%s]: %s not found, creating %s", script_name(), name, spawn_id )
      alife():create( spawn_id )
    end
  end
end


function fix_door_hospital_01_l_0003( ver )
  local names = {
    "door_hospital_01_r_0003",
    "door_hospital_01_l_0003",
  }
  for _, n in ipairs( names ) do
    local sobj = alife():object( n )
    if sobj then
      log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_mil_physic_object_0001( ver )
  local sobj = alife():object( "mil_physic_object_0001" )
  if sobj then
    log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_dragunov_ohota( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "dragunov_ohota_start" )
    and not db.actor:has_info( "tm_find_info_done" )
  then
    log2( "[%s]: completing 'dragunov_ohota' task", script_name() )
    for i = 0, 2 do
      level_tasks.set_task_state( task.completed, "dragunov_ohota", i )
    end
  end
  if
    db.actor:has_info( "koloda_kuznec_start" )
    and not db.actor:has_info( "koloda_kuznec_done" )
  then
    log2( "[%s]: completing 'koloda_kuznec' task", script_name() )
    for i = 0, 3 do
      level_tasks.set_task_state( task.completed, "koloda_kuznec", i )
    end
  end
  if
    db.actor:has_info( "hamster_kuznec8_start" )
    and not db.actor:has_info( "taynik10_kuznec" )
  then
    log2( "[%s]: completing 'hamster_kuznec8' task", script_name() )
    for i = 0, 2 do
      level_tasks.set_task_state( task.completed, "hamster_kuznec8", i )
    end
  end
  dsh.timeout( 0, function()
    news_manager.skip_send_task = false
  end )
end


function fix_l10u_bunker_codedoor_key_0000( ver ) end
function fix_l10u_bunker_codedoor_key_0000_2( ver )
  for i = 1, 65534 do
    local sobj = alife():object( i )
    if
      sobj and sobj:name() == "codedoor_key_0000"
      and object_level_name( sobj ) == "l10u_bunker"
    then
      log2(
        "[%s]: found %s on %s, rewrite custom data",
        script_name(), sobj:name(), object_level_name( sobj )
      )
      alife():release( sobj )
      sobj = alife():create( 10000 )
      local pk = get_netpk( sobj, 1 )
      ASSERT(
        pk:isOk(), "[%s]: can't parse netpk: %s",
        script_name(), sobj:name()
      )
      local data = pk:get()
      data.custom_data:setString(
        "[collide]\nignore_static\n\n[logic]\ncfg = dsh\\logic\\l10u_bunker\\codedoor_key_0000.ltx\n"
      )
      pk:set( data )
      break
    end
  end
end


function fix_buusty_kvest_task( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "buusty_kvest_start" )
    and not db.actor:has_info( "buusty_kvest_done" )
  then
    log2( "[%s]: completing 'buusty_kvest_task' task", script_name() )
    for i = 0, 2 do
      level_tasks.set_task_state( task.completed, "buusty_kvest_task", i )
    end
    db.actor:disable_info_portion( "buusty_kvest_have" )
  end
  dsh.timeout( 0, function()
    news_manager.skip_send_task = false
  end )
end


function fix_strelok_taynik_pda0( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "strelok_taynik_pda0_start" )
    and not db.actor:has_info( "strelok_taynik_pda0_done" )
  then
    log2( "[%s]: completing 'strelok_taynik_pda0' task", script_name() )
    for i = 0, 1 do
      level_tasks.set_task_state( task.completed, "strelok_taynik_pda0", i )
    end
    db.actor:disable_info_portion( "strelok_taynik_pda0_start" )
  end
  dsh.timeout( 0, function()
    news_manager.skip_send_task = false
  end )
end


function fix_esc_dinamit_panera( ver )
  local sobj = alife():story_object( story_ids.esc_dinamit_panera )
  if sobj then
    log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_hamster_kuznec6( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "hamster_kuznec6_start" )
    and not db.actor:has_info( "taynik6_kuznec" )
  then
    log2( "[%s]: completing 'hamster_kuznec6' task", script_name() )
    for i = 0, 2 do
      level_tasks.set_task_state( task.completed, "hamster_kuznec6", i )
    end
  end
  dsh.timeout( 0, function()
    news_manager.skip_send_task = false
  end )
end


function fix_handmade_arts_cnt( ver )
  if ver == 0 then return end
  local value = db.actor:has_info( "acv_art" )
    and 100 or amk.load_variable( "acv_art", 0 )
  log2( "[%s]: initializing dsh.handmade_arts_cnt = %s", script_name(), value )
  dsh.handmade_arts_cnt( value )
end


function make_free_prizrak( ver )
  if ver == 0 then return end
  if db.actor:has_info( "posulku_poluchil" ) then
    log2( "[%s]: call dsh.make_free_prizrak()", script_name() )
    dsh.make_free_prizrak()
  end
end


function fix_land_arhara_biliyrd( ver )
  for _, name in ipairs({
    "land_arhara_biliyrd", "land_arhara_zimov_pulemet"
  }) do
    local sobj = alife():object( name )
    if sobj then
      log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_se_respawn( ver )
  se_respawn.startup_respawners()
end


function fix_stalker_kisluy( ver )
  if ver == 0 then return end
  if db.actor:has_info( "spawn_strelochniki" ) then
    arhara_dialog.del_stalker_kisluy()
  end
end


function fix_trade_dialog_maks( ver )
  if ver == 0 then return end
  local tname1 = "dsh.has_trade_dialog.maks"
  local tname2 = "dsh.hasnt_trade_dialog.maks"
  for _, t in ipairs({ tname1, tname2 }) do
    if ogse_st_mgr.timer_exists( t ) then
      ogse_st_mgr.get_timer( t ):stop()
      log2( "[%s]: stop timer %s", script_name(), t )
    end
  end
  ogse.delete_var( tname1 .. ".cnt" )
  db.actor:disable_info_portion( "price_maks" )
end


function fix_esc_surprise_box_015( ver )
  dsh.del_2soldier_outfits()
end


function fix_dsh_rukzak_storage( ver )
  if ver == 0 then return end
  for _, k in ipairs( ogse_unist.get_all_names() ) do
    local id = string.match( k, "^dsh_rukzak%.([^.]+)%.sections$" )
    if id then
      id = tonumber( id )
      local items = dsh_rukzak.load_rukzak( id )
      log2(
        "[%s]: change storage type of dsh_rukzak: %s",
        script_name(), id
      )
      dsh_rukzak.save_rukzak( id, items )
    end
  end
end


function fix_pseudodog_forest()
  local sobj = alife():object( "pseudodog_forest" )
  if sobj then
    log2( "[%s]: move %s", script_name(), sobj:name() )
    alife():teleport_object(
      "",
      vector():set( -3.7275488376617,-1.1764014959335,-303.84091186523 ),
      65240, 3274,
      sobj.id
    )
  end
end


function fix_dsh_ogse_relations( ver )
  if ver == 0 then return end
  log2( "[%s]: clear dsh_ogse_relations", script_name() )
  ogse.delete_var( "dsh_ogse_relations"         )
  ogse.delete_var( "dsh_ogse_relations.chunks"  )
  ogse.delete_var( "dsh_ogse_relations.records" )
end


function fix_dsh_deadmans_table_proxy( ver )
  if ver == 0 then return end
  log2( "[%s]: clear ogse.deadmans_table", script_name() )
  ogse.delete_var( "ogse.deadmans_table" )
end


function fix_dark_bland( ver )
  if ver == 0 then return end
  local sobj = alife():story_object( story_ids.dark_bland )
  if sobj then
    log2( "[%s]: respawn %s", script_name(), sobj:name() )
    alife():release( sobj )
    sobj = alife():create( alife():spawn_id( story_ids.dark_bland ) )
  end
end


function fix_netpacket_pda( ver )
  if ver == 0 then return end
  local t = {}
  amk_utils.inventory_iterate_section(
    "netpacket_pda",
    function( obj )
      table.insert( t, obj )
    end
  )
  if table.getn( t ) > 0 then
    log2(
      "[%s]: found %s netpacket_pda, deleting...",
      script_name(), table.getn( t )
    )
    for _, obj in ipairs( t ) do
      ogse.remove_item_from_inventory( obj )
    end
  end
  amk.del_variable( "have_netpacket_pda" )
end


function fix_amk_transmutator( ver )
  if ver == 0 then return end
  local obj = db.actor:object( "amk_transmutator" )
  if not obj then return end
  log2( "[%s]: found %s, deleting...", script_name(), obj:name() )
  ogse.remove_item_from_inventory( obj )
  sak.create_items_actor( "ammo_5.45x39_ap",  5 )
  sak.create_items_actor( "ammo_7.62x39_ap",  5 )
  sak.create_items_actor( "medkit_army",     10 )
end


function fix_anim_ph_zone_0004( ver )
  local sobj = alife():object( "anim_ph_zone_0004" )
  if sobj then
    log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_sak_flash( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "sak_reward_outfit_have" )
    or db.actor:has_info( "sak_reward_outfit_done" )
  then
    return
  end
  if db.actor:has_info( "sak_reward_outfit_start" ) then
    local found = false
    for id = 1, 65534 do
      local sobj = alife():object( id )
      if sobj and sobj:section_name() == "disk_flash" then
        found = true
        break
      end
    end
    if not found then
      log2( "[%s]: disk_flash not found, spawning...", script_name() )
      sak_dialog.take_sak_reward_outfit()
    end
  end
end


function fix_mozg( ver )
  if ver == 0 then return end
  if not db.actor:has_info( "svoboda_lukash_start" ) then return end
  local found = {}
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if sobj and sobj:section_name() == "mozg" then
      found[ object_level_name( sobj ) ] = true
    end
  end
  if
    not (
      db.actor:has_info( "svoboda_lukash_done" )
      or found.atp_for_test22
    )
  then
    log2(
      "[%s]: mozg on atp_for_test22 not found, spawning...", script_name()
    )
    arhara_dialog.mozg_atp_for_test22()
  end
  if not found.l12_stancia_2 then
    log2(
      "[%s]: mozg on l12_stancia_2 not found, spawning...", script_name()
    )
    arhara_dialog.mozg_l12_stancia_2()
  end
end


function fix_wpn_gungauss( ver )
  if ver == 0 then return end
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if sobj and sobj:section_name() == "wpn_gungauss" then
      log2(
        "[%s]: clearing UsefulForAI flag for %s...",
        script_name(), sobj:name()
      )
      dsh.clear_useful_for_ai( sobj )
    end
  end
end


function fix_info_restriction()
  if ver == 0 then return end
  if
    db.actor:has_info( "arhara_shaxter_start" )
    and not db.actor:has_info( "info_restriction" )
  then
    log2( "[%s]: fixing info_restriction...", script_name() )
    spawn_teleport.spawn_teleport1()
    spawn_teleport.spawn_teleport2()
    spawn_teleport.spawn_teleport3()
    spawn_teleport.spawn_teleport5()
    spawn_teleport.spawn_teleport7()
    spawn_teleport.spawn_teleport9()
    spawn_restrictor.create_sr1()
    spawn_restrictor.create_sr2()
    spawn_teleport.spawn_item1()
    db.actor:give_info_portion( "info_restriction" )
  end
end


function fix_vasily_chertez_reminder( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "vasily_chertez_start" )
    and not db.actor:has_info( "vasily_chertez_reminder" )
  then
    log2( "[%s]: fixing vasily_chertez_reminder...", script_name() )
    db.actor:give_info_portion( "vasily_chertez_reminder" )
  end
end


function fix_prizrak_treasure_box( ver )
  if db.actor:has_info( "treasure_ecolog_start" ) then return end
  local sobj = alife():story_object( story_ids.prizrak_treasure_box ) -- 9662
  if sobj then
    log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_dcity_pyatietazhka_yzik1( ver )
  local sobj = alife():object( "dcity_pyatietazhka_yzik1" )
  if sobj then
    log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_explosive_barrel_all( ver )
  if ver == 0 then return end
  fix_explosive_barrel( ver )
end


function fix_atp_presled_last( ver )
  -- типки в маскировочных экзоскелетах, каким-то чудом обогнавшие ГГ
  -- и прячущиеся за кустами впереди.
  for i  = 1, 3 do
    local n = "atp_presled_last" .. i
    local sobj = alife():object( n )
    if sobj then
      log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_warlab_sekret_generator5( ver )
  for i = 5, 7 do
    local n = "warlab_sekret_generator" .. i
    local sobj = alife():object( n )
    if sobj then
      log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_yakut_treasure_box( ver )
  if db.actor:has_info( "yakut_treasure_start" ) then return end
  local sobj = alife():story_object( story_ids.yakut_treasure_box ) -- 9661
  if sobj then
    log2( "[%s]: found %s, removing...", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_black_dok_gener_say_done( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "udav_vstrecha_start" )
    and not db.actor:has_info( "black_dok_gener_say_done" )
  then
    log2( "[%s]: found lost 'black_dok_gener_say_done' info", script_name() )
    db.actor:give_info_portion( "black_dok_gener_say_done" )
  end
end


function fix_dsh_rukzak_access_time( ver )
  if ver == 0 then return end
  for _, k in ipairs( ogse_unist.get_all_names() ) do
    local id = string.match( k, "^dsh_rukzak%.([^.]+)%.sections$" )
    if id then
      id = tonumber( id )
      if id then
        local name = "dsh_rukzak." .. id .. ".access_time"
        ogse.save_var( name, game.get_game_time(), "time" )
        log2( "[%s]: fix %s", script_name(), name )
      end
    end
  end
end


function fix_add_lchanger_location( ver )
  if ver == 0 then return end
  log2( "[%s]: fix add_lchanger_location", script_name() )
  level_tasks.add_lchanger_location()
end


function fix_foto_ohota_have( ver )
  if ver == 0 then return end
  if db.actor:has_info( "foto_anomaly_done" ) then
    log2( "[%s]: fix foto_ohota_have", script_name() )
    news_manager.skip_send_task = true
    db.actor:give_info_portion( "foto_ohota_done" )
    db.actor:give_info_portion( "foto_ohota_have" )
    db.actor:give_info_portion( "foto_ohota_end"  )
    dsh.exec_on_update( function()
      news_manager.skip_send_task = false
    end )
  end
end


function fix_create_sr18( ver )
  if ver == 0 then return end
  if db.actor:has_info( "net_teleport6" ) then
    for i = 35, 54 do
      local n  = "m_teleport_" .. i
      local id = xr_logic.pstor_retrieve( db.actor, n, 0 )
      if id > 0 then
        log2( "[%s]: found %s, trying to remove", script_name(), n )
        kostya_dialog.delete_teleport( n )
      end
    end
  end
end


function fix_dcity_stalki_matras_1( ver )
  local names = {
    [ "dcity_stalki_matras_1" ] = 1137,
    [ "dcity_stalki_matras_2" ] = 1138,
    [ "dcity_stalki_matras_3" ] = 1139,
  }
  for k, v in pairs( names ) do
    local sobj = alife():object( k )
    if sobj then
      log2( "[%s]: found %s, recreate", script_name(), sobj:name() )
      alife():release( sobj )
      sobj = alife():create( v )
      local pk = get_netpk( sobj, 1 )
      ASSERT(
        ( pk and pk:isOk() ), "[%s]: can't parse netpk: %s",
        script_name(), sobj:name()
      )
      local data = pk:get()
      data.custom_data:setString(
        "[collide]\nignore_static\n\n[logic]\ncfg = scripts\\esc_sleep.ltx\n"
      )
      pk:set( data )
    end
  end
end


function fix_add_new_lima_to_dead_city( ver )
  if ver == 0 then return end
  if not db.actor:has_info( "info_way_arhara_lima_dcity" ) then return end
  local sobj = alife():story_object( 97114 )
  if sobj then
    log2( "[%s]: found %s, moving", script_name(), sobj:name() )
    alife():teleport_object(
      "", vector():set( -52.046, -10.754, -184.263 ), 45067, 3016,
      sobj.id
    )
  end
end


function fix_aver_muha_bazar_sms_restrictor( ver )
  local sobj = alife():object( "aver_muha_bazar_sms_restrictor" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_val_bandit_krisyk( ver )
  local sobj = alife():object( "val_bandit_krisyk" )
  if sobj then
    log2(
      "[%s]: teleport %s to bandit_krisyk_walk",
      script_name(), sobj:name()
    )
    local patrol = patrol( "bandit_krisyk_walk" )
    alife():teleport_object(
      "", patrol:point( 0 ),
      patrol:level_vertex_id( 0 ), patrol:game_vertex_id( 0 ),
      sobj.id
    )
  end
end


function fix_dragunof_npc()
  if level.name() == "l11_pripyat" then
    local sobj = alife():story_object( story_ids.dragunof_npc ) -- 21003
    if sobj then
      alife():teleport_object(
        "",
        vector():set( 191.67535400391, 2.8055994510651, 212.01971435547 ),
        260495, 2219,
        sobj.id
      )
    end
  end
end


function fix_dsity_rasstrel_end( ver )
  if ver == 0 then return end
  if db.actor:has_info( "uhod_iz_mg_done" ) then
    log2( "[%s]: fix dsity_rasstrel_end", script_name() )
    db.actor:give_info_portion( "dsity_rasstrel_end"  )
  end
end


function fix_dcity_gg_neytral_restrictor( ver )
  local sobj = alife():object( "dcity_gg_neytral_restrictor" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_dokplen_spawn_one_restrictor( ver )
  local their_names = {
    "dokplen_spawn_one_restrictor",
      "last1_dokplen_spawn_one1",
      "last2_dokplen_spawn_one2",
    "dokplen_spawn_two_restrictor",
      "last1_dokplen_spawn_two1",
      "last2_dokplen_spawn_two2",
      "last3_dokplen_spawn_two3",
    "actor_chely_shtab_restrictor",
      "dcity_sniper1_shtab",
      "dcity_sniper2_shtab",
    "chely1_shtab1_lestnisa_restrictor",
      "dcity_sniper3_shtab",
      "dcity_sniper4_shtab",
    "sniper1_spawn_krusha1_restrictor",
      "sniper1_krusha1",
    "sniper2_spawn_krusha2_restrictor",
      "sniper2_1_krusha1",
      "sniper2_2_krusha1",
    "kanaliy_dinamit1_vzryv_restrictor",
    "kanaliy_dinamit2_vzryv_restrictor",
    "kanaliy_dinamit_nevid_vzryv_restrictor",
    "kanaliy_imitator_hit_restrictor",
  }
  for _, n in ipairs( their_names ) do
    local sobj = alife():object( n )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_dcity_lastday( ver )
  local dcity_lastday_mems = {
    "shtab_chasovoy_pered1",
    "shtab_chasovoy_pered2",
    "shtab_chasovoy_zad1",
    "shtab_chasovoy_zad2",
    "chasovoy_kultorg_pered",
    "kultorg_kemper1",
    "kultorg_vxod_bok",
    "kultorg_2etazh",
    "stab_1etazh2",
    "stab_vnutr_ohrana1",
    "stab_vnutr_ohrana2",
    "kultorg_kemper2",
    "shtab_fontan1",
    "patrul_kultorg_pered",
    "patrul_lenin",
    "vxod_kultorg_zad",
    "kultorg_1etazh",
    "stab_1etazh1",
    "stab_vnutr_ohrana3",
  }
  dsh.shuffle( dcity_lastday_mems )
  local sm = ogse_signals.get_mgr()
  for i = 1, math.floor( table.getn( dcity_lastday_mems ) / 2 ) do
    local sobj = alife():object( dcity_lastday_mems[ i ] )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      smart_terrain.unregister_npc( sobj )
      alife():release( sobj )
      sm:call( "on_release_npc", sobj.id )
    end
  end
end


function fix_marsh_udav( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "spawn_marsh_udav" )
    and not db.actor:has_info( "udav_vstrecha_start" )
  then
    local sobj = alife():story_object( story_ids.marsh_udav )
    if sobj then
      log2( "[%s]: found %s, respawn", script_name(), sobj:name() )
      alife():release( sobj )
      alife():create( alife():spawn_id( story_ids.marsh_udav ) )
    end
  end
end


function fix_val_borov_dead( ver )
  if ver == 0 then return end
  if db.actor:dont_has_info( "val_borov_dead" ) then return end
  local sobj = alife():story_object( story_ids.val_borov )
  if sobj and sobj:alive() then
    log2(
      "[%s]: found %s alive, disable val_borov_dead info",
      script_name(), sobj:name()
    )
    db.actor:disable_info_portion( "val_borov_dead" )
  end
end


function fix_av_peshera_mono2_bunker_niz( ver )
  local names = {
    "av_bunker_lestn_mina",
    "av_peshera_bunker_zharka_lestn",
    "av_peshera_bunker_zharka_sklad",
    "av_peshera_bunker_zharka_vuxod",
    "av_peshera_mono2_bunker_niz",
    "av_peshera_mono7_bunker_presklad1",
    "av_peshera_mono9_bunker_sklad1",
  }
  local sm = ogse_signals.get_mgr()
  for _, name in ipairs( names ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      local is_npc = IsStalker( sobj )
      if is_npc then smart_terrain.unregister_npc( sobj ) end
      alife():release( sobj )
      if is_npc then sm:call( "on_release_npc", sobj.id ) end
    end
  end
end


function fix_av_peshera_zone_emi1( ver )
  local names = {
    "av_peshera_zone_emi1",
    "av_peshera_zone_emi2",
    "av_peshera_zone_emi3",
    "av_peshera_zone_emi4",
    "av_peshera_zone_emi5",
  }
  local sm = ogse_signals.get_mgr()
  for _, name in ipairs( names ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_mar_level_changer_to_escape_1( ver )
  local sobj = alife():story_object( story_ids.mar_level_changer_to_escape_1 )
  if sobj then
    log2( "[%s]: found %s, fixing", script_name(), sobj:name() )
    local pk = get_netpk( sobj, 1 )
    ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
    local data = pk:get()
    data.dest_game_vertex_id  = 41
    data.dest_level_vertex_id = 10036
    data.dest_position        = vector():set( -249.71600341797,-16.43124961853,-202.36882019043 )
    pk:set( data )
  end
end


-- пересоздать физические объекты
function fix_physic_objects()
  if
    not (
      dsh_lc_fixes.has_level_changed()
      and fix_ph_position[ level.name() ]
    )
  then
    return
  end
  for name, spawn_id in pairs( fix_ph_position[ level.name() ] ) do
    local sobj = alife():object( name )
    if sobj then
      alife():release( sobj )
    end
    alife():create( spawn_id )
  end
end


function fix_yan_st_stalker3_kamp_1( ver )
  local p = patrol( "yan_st_stalker3_kamp_1" )
  dsh.create_campfire(
    p:point( 0 ), p:level_vertex_id( 0 ), p:game_vertex_id( 0 ),
    "objects\\koster_negorit", 0.7
  )
end


function fix_pri_dimak( ver )
  dsh.create_campfire(
    vector():set( 135.7427520752,4.9046115875244,-200.63697814941 ),
    363725, 3765,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.spawn_physic_sleep_bag(
    vector():set( 136.0898, 4.9049, -204.6948 ), 363716, 3765,
    "objects\\matras", 10, "bone01"
  )
end


function fix_pripyat_campfires( ver )
  -- в книгах, в зале за неактивными дверями
  dsh.create_campfire(
    vector():set( -181.8752746582, 0.64074690341949, -348.90435791016 ),
    33816, 3753,
    nil, 0.7
  )
  -- светлячок
  dsh.create_campfire(
    vector():set( -49.654216766357,-0.30959591269493,-354.38177490234 ),
    139219, 3753,
    "objects\\koster_palki_nastil", 0.7
  )
  -- универсам
  dsh.create_campfire(
    vector():set( -102.80925750732,0.49736765027046,-253.93940734863 ),
    89097, 3751,
    "objects\\koster_palki_nastil", 0.7
  )
  -- в госпитале, на втором этаже
  dsh.create_campfire(
    vector():set( 232.21240234375,4.4478893280029,26.575832366943 ),
    451530, 3768,
    "objects\\koster_palki_nastil", 0.7
  )
  -- речвокзал
  dsh.create_campfire(
    vector():set( 296.4831237793,0.68390381336212,237.0193939209 ),
    476945, 3769,
    nil, 0.7
  )
end


function fix_x18_campfires( ver )
  dsh.create_campfire(
    vector():set( -13.629398345947,4.1883325576782,8.7058591842651 ),
    1347, 1126,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( 14.393134117126,4.1887907981873,-13.240303993225 ),
    4991, 1117,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( 40.255779266357,-10.815406799316,4.6903095245361 ),
    7489, 1136,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( -5.8372869491577,-11.854700088501,-14.30740070343 ),
    2009, 1133,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -40.928089141846,-10.815729141235,6.7639007568359 ),
    218, 1148,
    "objects\\koster_palki_nastil", 0.7
  )
end


function fix_pripyat_campfires2( ver )
  dsh.create_campfire(
    vector():set( -104.06401824951,4.2089171409607,-101.97599029541 ),
    88109, 3759,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( 59.20983505249,0.48721626400948,177.9935760498 ),
    276725, 3761,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( 15.989818572998,4.4941573143005,288.72909545898 ),
    218595, 3760,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( 65.979499816895,0.32861027121544,370.88909912109 ),
    286400, 3760,
    nil, 0.7
  )
end


function fix_pri_dimak_pos()
  if level.name() == "pripyat" then
    local sobj = alife():story_object( story_ids.pri_dimak )
    if sobj then
      alife():teleport_object(
        "",
        vector():set(135.55590820313,4.9057364463806,-202.5612487793),
        363721, 3765,
        sobj.id
      )
    end
  end
end


function fix_akill_npc()
  if level.name() == "pripyat" then
    local sobj = alife():story_object( story_ids.akill_npc )
    if sobj then
      alife():teleport_object(
        "",
        vector():set( 133.15174865723,4.904456615448,-196.60328674316 ),
        360302, 3765,
        sobj.id
      )
    end
  end
end


function fix_lab_pri1( ver )
  if ver == 0 then return end
  if db.actor:has_info( "pri1_lab_info" ) then
    db.actor:give_info_portion( "lab_pri1_info" )
  end
end


function fix_jupiter_underground( ver )
  dsh.create_campfire(
    vector():set( 5.0671792030334,8.0631856918335,436.82061767578 ),
    16640, 3791,
    "objects\\koster_palki_nastil", 0.7
  )

  -- дверь во вторую секцию Путепровода
  local sobj = alife():object( "jund_pas_b400_physic_door" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2875 )
  local pk = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  local data = pk:get()
  local cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_physic_door.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  sobj = alife():create(
    "physic_object",
     vector():set( 6.2, 8.0336713790894, 335.0 ),
     17403, 3785
  )
  pk = get_netpk( sobj, 1 )
  ASSERT( pk:isOk(), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  data.custom_data:setString( "[collide]\nignore_static\n" )
  data.visual_name = "objects\\train\\train_vagon_01_open"
  data.physic_type = 3
  data.mass        = 1000
  data.fixed_bones = "bone01"
  pk:set( data )
  pk = get_netpk( sobj, 0 )
  ASSERT( pk:isOk(), "can't read netpacket of %s", sobj:name() )
  pk:setCallback({
    direction = vector():set( 0, 1.55, 0 ),
  })

  dsh.create_campfire(
    vector():set( 32.446899414063,8.0051937103271,258.47036743164 ),
    30336, 3799,
    "objects\\koster_palki_nastil", 0.7
  )

  -- дверь в третью секцию Путепровода
  sobj = alife():object( "jund_pas_b400_door_track" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2876 )
  pk   = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_door_track.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  -- дверь после лестницы
  sobj = alife():object( "jund_pas_b400_door_downstairs" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2878 )
  pk   = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_door_downstairs.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  dsh.create_campfire(
    vector():set( 51.964504241943,-0.00018477439880371,183.92384338379 ),
    36201, 3818,
    "objects\\koster_palki_nastil", 0.7
  )

  -- дверь в круглой комнате
  sobj = alife():object( "jund_pas_b400_door_control_down" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2884 )
  pk   = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_door_control_down.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  -- дверь в круглой комнате наверху
  sobj = alife():object( "jund_pas_b400_door_control_up" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2885 )
  pk   = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_door_control_up.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  -- выход из круглого зала
  sobj = alife():object( "jund_pas_b400_door_hall" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2883 )
  pk   = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_door_hall.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  -- выход в тоннель
  sobj = alife():object( "jund_pas_b400_door_way" )
  if sobj then
    alife():release( sobj )
  end
  sobj = alife():create( 2886 )
  pk   = get_netpk( sobj, 1 )
  ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
  data = pk:get()
  cd   = data.custom_data:getTable()
  cd.logic = {
    [ "cfg" ] = "dsh\\logic\\jupiter_underground\\jund_pas_b400_door_way.ltx"
  }
  data.custom_data:setTable( cd )
  pk:set( data )

  dsh.create_campfire(
    vector():set( 68.955108642578,4.3204076194763,-198.29489135742 ),
    39728, 3823,
    nil, 0.7
  )

  dsh.create_campfire(
    vector():set( -15.413643836975,0.0026839673519135,-74.39421081543 ),
    6469, 3778,
    "objects\\koster_palki", 0.8
  )

  if ver == 0 then return end
  for id = 1, 65534 do
    local sobj = alife():object( id )
    if
      sobj and (
        sobj:section_name() == "under_tele_1"
        or sobj:section_name() == "under_tele_2"
        or sobj:section_name() == "under_tele_3"
      )
    then
      alife():release( sobj )
    end
  end
end


function fix_lab_under( ver )
  if ver == 0 then return end
  if db.actor:has_info( "info_lab_under" ) then
    db.actor:disable_info_portion( "info_lab_under" )
    local sobj = alife():story_object( 130022 )
    if sobj then
      alife():release( sobj )
    end
    braad_test.lab_under()
  end
end


function fix_labx8( ver )
  dsh.create_campfire(
    vector():set( -71.871772766113,-20.165414810181,60.047252655029 ),
    4814, 3847,
    "objects\\koster_palki", 0.8
  )

  dsh.create_campfire(
    vector():set( -74.475860595703,-15.93800163269,109.57129669189 ),
    4541, 3846,
    "objects\\koster_negorit", 0.7
  )

  dsh.create_campfire(
    vector():set( -98.806762695313,-28.484575271606,95.178497314453 ),
    860, 3832,
    "objects\\koster_negorit", 0.7
  )
end


function fix_esc2_smart_stalker_exit_kamp_1( ver )
  local p = patrol( "esc2_smart_stalker_exit_kamp_1" )
  dsh.create_campfire(
    p:point( 0 ), p:level_vertex_id( 0 ), p:game_vertex_id( 0 ),
    "objects\\koster_palki", 0.8
  )
end


function fix_agr2_st_factory_kamp_1( ver )
  local p = patrol( "agr2_st_factory_kamp_1" )
  dsh.create_campfire(
    p:point( 0 ), p:level_vertex_id( 0 ), p:game_vertex_id( 0 ),
    "objects\\koster_palki_nastil", 0.7
  )
end


function fix_l03_agroprom_candles( ver )
  dsh.create_candle(
    vector():set( 24.21443939209,-0.65411001443863,-224.57250976563 ),
    263673, 436, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -134.34451293945,1.0590002536774,-203.86309814453 ),
    106220, 649, "physics\\decor\\gas_burner"
  )
end


function fix_l03u_agr_underground_candles( ver )
  dsh.create_candle(
    vector():set( -72.679161071777,-5.5085163116455,-75.402770996094 ),
    172, 703, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -113.21365356445,-14.993812561035,-22.003011703491 ),
    373, 759, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -40.954113006592,-3.9868292808533,0.92165052890778 ),
    4623, 730, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -104.44459533691,-15.592901229858,-101.30113220215 ),
    1214, 707, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -86.779090881348,-2.4215745925903,-145.2272644043 ),
    2361, 806, "physics\\decor\\gas_burner"
  )
end


function fix_jupiter( ver )
  dsh.create_candle(
    vector():set( -456.72171020508,1.2916003465652,-379.55160522461 ),
    13, 3702, "physics\\decor\\gas_burner"
  )
  dsh.create_campfire(
    vector():set( -415.30389404297,0.28906974196434,-374.18865966797 ),
    23677, 3702,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -388.431640625,0.26377919316292,-368.14733886719 ),
    59256, 3702,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -349.82049560547,3.7115612030029,407.80383300781 ),
    125006, 3703,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -364.34149169922,-2.0552632808685,-221.31158447266 ),
    100054, 3700,
    "objects\\koster_negorit", 0.7
  )
  dsh.create_candle(
    vector():set( -184.28823852539,1.534478187561,-280.98773193359 ),
    404370, 3710, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 50.910606384277,28.873067855835,-177.61737060547 ),
    802934, 3727, "physics\\decor\\gas_burner"
  )
  local sobj = alife():object( "jup_b207_ph_depot_cover" )
  if sobj then
    alife():release( sobj )
  end
  dsh.create_candle(
    vector():set( 171.15382385254,-7.3061528205872,209.61605834961 ),
    806559, 3727, "physics\\decor\\gas_burner"
  )
  dsh.create_campfire(
    vector():set( 139.52857971191,1.3363538980484,213.60955810547 ),
    954311, 3732,
    "objects\\koster_palki", 0.8
  )
  dsh.create_candle(
    vector():set( -394.66690063477,12.327070236206,9.9700231552124 ),
    52657, 3708, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 75.020805358887,-0.073683269321918,330.75927734375 ),
    841970, 3725, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 419.34759521484,5.3461313247681,-69.73876953125 ),
    1379516, 3744, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 264.33728027344,28.613309860229,-220.83633422852 ),
    1156923, 3739, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 387.98413085938,28.888719558716,-240.80683898926 ),
    1327755, 3743, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 314.18075561523,35.632732391357,-232.91732788086 ),
    1222905, 3743, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 356.04510498047,35.87947845459,-274.70642089844 ),
    1280754, 3743, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 399.4762878418,40.958679199219,-223.52084350586 ),
    1345451, 3743, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 431.31747436523,27.63756942749,-280.28659057617 ),
    1395417, 3747, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 449.58462524414,28.219541549683,-459.07278442383 ),
    1395417, 3747, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 387.58331298828,32.704139709473,-387.31915283203 ),
    1327691, 3745, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 418.05975341797,32.373275756836,-359.85699462891 ),
    1378098, 3745, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 340.3821105957,28.581056594849,-361.26431274414 ),
    1375989, 3745, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 322.42385864258,28.581056594849,-303.2526550293 ),
    1233545, 3745, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 223.59820556641,-9.1206064224243,167.29113769531 ),
    1098712, 3732, "physics\\decor\\gas_burner"
  )
  sobj = dsh.spawn_physic_sleep_bag(
    vector():set( -7.0397539138794,23.981300354004,243.9365234375 ),
    702881, 3725
  )
  local pk = get_netpk( sobj, 0 )
  ASSERT( pk:isOk(), "can't read netpacket of %s", sobj:name() )
  pk:setCallback({
    direction = vector():set( 0, 1.5, 0 ),
  })
  dsh.create_candle(
    vector():set( -7.6468667984009,24.057189941406,248.24877929688 ),
    702885, 3725, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -44.494304656982,4.707426071167,193.2515411377 ),
    643161, 3717, "physics\\decor\\gas_burner"
  )
end


function fix_jupiter_campfires( ver )
  dsh.create_campfire(
    vector():set( 391.43432617188,3.6243424415588,359.54635620117 ),
    1333722, 3746,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -194.5772857666,-13.736262321472,348.19024658203 ),
    387604, 3711,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -199.89437866211,3.4886932373047,-440.23831176758 ),
    377348, 3710,
    "objects\\koster_palki_nastil", 0.7
  )
  dsh.create_campfire(
    vector():set( -96.119010925293,26.827522277832,-491.59298706055 ),
    560416, 3714,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -78.920791625977,23.890998840332,-317.45986938477 ),
    588425, 3720,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( 226.54385375977,28.131425857544,-456.9111328125 ),
    1103798, 3734,
    "objects\\koster_negorit", 0.7
  )
  dsh.create_campfire(
    vector():set( -29.801790237427,3.1251952648163,-27.338813781738 ),
    667549, 3722,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -63.728164672852,-0.38933688402176,-147.5732421875 ),
    613464, 3722,
    "objects\\koster_negorit", 0.7
  )
  dsh.create_candle(
    vector():set( -338.67367553711,2.0852909088135,262.83532714844 ),
    664105, 3722, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -396.39767456055,14.629031181335,353.58963012695 ),
    52090, 3701, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 197.33331298828,36.721054077148,-442.89245605469 ),
    1054046, 3734, "physics\\decor\\gas_burner"
  )
end


function fix_warlab_fountain_average1_niz( ver )
  local sobj = alife():object( "warlab_fountain_average1_niz" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_aver_zone_emi1( ver )
  local sobj = alife():object( "aver_zone_emi1" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_arm_sklady_rg_box_0033( ver )
  if db.actor:has_info( "mil_freedom_cook_rg6_ask" ) then return end
  local sobj = alife():object( "arm_sklady_rg_box_0033" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_marsh_campfires( ver )
  dsh.create_campfire(
    vector():set( 458.09130859375,1.6140428781509,364.29473876953 ),
    445396, 3556,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 252.95385742188,1.3613117933273,307.6279296875 ),
    296617, 3509,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -57.793064117432,1.2502099275589,283.86331176758 ),
    109085, 3402,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -38.188804626465,0.73232710361481,137.62239074707 ),
    121273, 3404,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -276.74185180664,1.0221917629242,29.46337890625 ),
    7984, 3351,
    "objects\\koster_negorit", 0.7
  )
  dsh.create_campfire(
    vector():set( -158.93927001953,0.74808788299561,-138.91970825195 ),
    65649, 3373,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -22.687511444092,0.69377851486206,-138.26379394531 ),
    129606, 3398,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -67.653182983398,0.7159229516983,-82.172805786133 ),
    103473, 3394,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -61.387626647949,0.65357208251953,-85.00154876709 ),
    106367, 3395,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -26.17787361145,0.92761254310608,-68.31128692627 ),
    127258, 3405,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 36.142570495605,1.467332482338,-114.54546356201 ),
    157407, 3438,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 230.60270690918,0.72740268707275,-169.86502075195 ),
    280238, 3502,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 134.5712890625,0.77103698253632,39.570140838623 ),
    216669, 3471,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -98.953170776367,0.69491696357727,-9.0444831848145 ),
    92746, 3394,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 88.085998535156,0.76024651527405,179.85174560547 ),
    187634, 3455,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 196.25061035156,1.249173283577,171.82080078125 ),
    255480, 3489,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 278.9377746582,3.9308686256409,66.913078308105 ),
    316751, 3527,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 291.505859375,0.30063316226006,-43.003772735596 ),
    324986, 3526,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 372.67031860352,1.2184270620346,-126.99787139893 ),
    382011, 3541,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 507.08331298828,2.5428190231323,-187.2353515625 ),
    484171, 3563,
    nil, 0.7
  )
end


function fix_zaton( ver )
  dsh.create_campfire(
    vector():set( 136.311447143555, -2.17291688919067, 184.950607299805 ),
    1201550, 3686,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -360.17041015625,40.009124755859,-330.41522216797 ),
    1198116, 3686,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -127.9182434082,24.12681388855,-399.7236328125 ),
    256210, 3667,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -349.04962158203,18.124147415161,345.01776123047 ),
    682138, 3678,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 229.8557434082,6.7983055114746,-26.677629470825 ),
    265925, 3667,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 329.4140625,-5.9950556755066,-215.42510986328 ),
    1364144, 3688,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -20.664440155029,18.170932769775,-345.89096069336 ),
    1508711, 3688,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -2.5512528419495,-0.50655382871628,37.053302764893 ),
    938434, 3677,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 169.45251464844,10.545687675476,-259.51513671875 ),
    1012149, 3679,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( 287.17340087891,18.270143508911,146.01721191406 ),
    1258154, 3683,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -360.23968505859,23.215049743652,-184.85073852539 ),
    1453888, 3692,
    nil, 0.7
  )
  dsh.create_campfire(
    vector():set( -199.84281921387,-1.9452344179153,27.235654830933 ),
    543658, 3668,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -183.22811889648,6.9624252319336,124.56703948975 ),
    574980, 3670,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -0.33878067135811,25.331405639648,382.45880126953 ),
    944343, 3682,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( 291.97778320313,18.554203033447,529.12426757813 ),
    1464332, 3687,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -172.55172729492,-2.9075605869293,352.66174316406 ),
    595408, 3675,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( -315.75332641602,-7.271092414856,138.46153259277 ),
    317483, 3666,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( 145.94494628906,27.700189590454,-378.53717041016 ),
    1214632, 3683,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( 430.32049560547,11.916608810425,-166.33573913574 ),
    1672066, 3693,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( 419.83862304688,36.263305664063,-5.0698523521423 ),
    1654367, 3691,
    "objects\\koster_palki", 0.8
  )
  dsh.create_candle(
    vector():set( -395.98434448242,12.49892616272,-1.715663433075 ),
    186036, 3663, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -446.34466552734,6.1867060661316,47.369243621826 ),
    186037, 3663, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -312.98968505859,14.282513618469,428.57781982422 ),
    188164, 3663, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -165.07073974609,20.933296203613,-162.63577270508 ),
    612214, 3672, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 236.97570800781,34.614776611328,-331.14566040039 ),
    642853, 3672, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 322.71325683594,42.837917327881,-405.13616943359 ),
    642853, 3672, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 413.63241577148,40.346862792969,-4.6024670600891 ),
    1643588, 3693, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 149.77096557617,-5.8977656364441,-139.7918548584 ),
    1631369, 3693, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 125.15361785889,-6.120653629303,176.60772705078 ),
    1182876, 3686, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 411.03454589844,-2.5122284889221,232.81530761719 ),
    1204864, 3686, "physics\\decor\\gas_burner"
  )
  local sobj = alife():object( "station_priemnik_gorizont_01" )
  if sobj then
    alife():release( sobj )
  end
  sobj = dsh.spawn_physic_sleep_bag(
    vector():set( -4.8281245231628,-0.25045183300972,31.31383895874 ),
    934235, 3677
  )
  sobj = dsh.spawn_physic_sleep_bag(
    vector():set( 0.71345752477646,-0.44785210490227,42.127014160156 ),
    944008, 3677
  )
  local pk = get_netpk( sobj, 0 )
  ASSERT( pk and pk:isOk(), "can't read netpacket of %s", sobj:name() )
  pk:setCallback({
    direction = vector():set( 0, 1.5, 0 ),
  })
  sobj = dsh.spawn_physic_sleep_bag(
    vector():set( 110.6895904541,-2.3550486564636,181.17868041992 ),
    1157643, 3686
  )
  pk = get_netpk( sobj, 0 )
  ASSERT( pk and pk:isOk(), "can't read netpacket of %s", sobj:name() )
  pk:setCallback({
    direction = vector():set( 0, 1.5, 0 ),
  })
end


function fix_zaton_campfires( ver )
  dsh.create_campfire(
    vector():set( -342.17193603516,39.530136108398,-284.18402099609 ),
    268853, 3664,
    nil, 0.7
  )
  dsh.create_candle(
    vector():set( -427.03213500977,40.903762817383,-390.75357055664 ),
    1182876, 3686, "physics\\decor\\gas_burner"
  )
end


function fix_sherstuk_enemy( ver )
  db.actor:disable_info_portion( "sherstuk_enemy" )
end


function fix_zaton_campfires2( ver )
  -- костер в пещере с Барретом, где в ЗП контроллер говорит "уходи отсюда"
  dsh.create_campfire(
    vector():set( 21.981126785278,3.9355320930481,368.60858154297 ),
    988517, 3682,
    nil, 0.7
  )
end


function fix_karta_peschera( ver )
  if ver == 0 then return end
  local obj = db.actor:object( "karta_peschera" )
  if not obj then return end
  log2( "[%s]: found %s, deleting...", script_name(), obj:name() )
  dsh.karta_peschera( obj )
end


function fix_pri1_zaton( ver )
  if ver == 0 then return end
  if db.actor:has_info( "info_pri1_zaton" ) then
    db.actor:disable_info_portion( "info_pri1_zaton" )
    local sobj = alife():story_object( 130026 )
    if sobj then
      alife():release( sobj )
    end
    braad_test.pri1_zaton()
  end
end


function fix_zaton_ukamney_lager( ver )
  free_smart_terrain( "zaton_ukamney_lager" );
end


function fix_bandit_zaton1( ver )
  free_smart_terrain( "bandit_zaton1" );
end


function fix_upiter_gigants( ver )
  local smarts = {
    "upiter_gigants",
    "upiter_bibliotekars",
    "upiter_kogots",
    "upi_zanoza",
    "upi_pryguny",
    "upi_zombie",
    "podzemka_karlushy",
    "podzemka_polterburer",
    "podzemka_karliki",
    "pri_kogots",
    "pri_zanoza",
    "pri_chimera",
    "zaton_boars_flesh_izumr",
    "snork_zaton_katakomb",
    "zaton_raton_lair_1",
    "zaton_raton_lair_2",
    "zaton_raton_lair_3",
    "x_laba_karlushy",
    "x_laba_polterburer",
  }
  for _, n in ipairs( smarts ) do
    log2( "[%s]: reconfigure %s", script_name(), n )
    free_smart_terrain( n );
  end
end


function fix_spawn_babki_dcity_restrictor( ver )
  local sobj = alife():object( "spawn_babki_dcity_restrictor" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_esc_akim_lager( ver )
  for _, n in ipairs({ "esc_akim_lager", "escape_buusty_team" }) do
    local sobj = alife():object( n )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_arny_kogot( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "arny_kogot_start" )
    and not db.actor:has_info( "arny_kogot_have" )
  then
    log2( "[%s]: completing 'arny_kogot' task", script_name() )
    for i = 0, 1 do
      level_tasks.set_task_state( task.completed, "arny_kogot", i )
    end
  end
  dsh.exec_on_update( function()
    news_manager.skip_send_task = false
  end )
end


function fix_haker_soft( ver )
  if ver == 0 then return end
  news_manager.skip_send_task = true
  if
    db.actor:has_info( "haker_soft_start" )
    and not db.actor:has_info( "haker_soft_done" )
  then
    log2( "[%s]: completing 'haker_soft' task", script_name() )
    for i = 0, 2 do
      level_tasks.set_task_state( task.completed, "haker_soft", i )
    end
  end
  dsh.exec_on_update( function()
    news_manager.skip_send_task = false
  end )
end


function fix_poisk_partizan_spawn( ver )
  -- см. fix_poisk_partizan_spawn_2()
end


function fix_val_zone_radioactive_average( ver )
  local sobj = alife():object( "val_zone_radioactive_average" )
  if sobj then
    log2( "[%s]: found %s, removing", script_name(), sobj:name() )
    alife():release( sobj )
  end
end


function fix_esc_dogs_swarm( ver )
  if ver > 0 then return end
  local badnames = {
    "esc_dog_swarm_0001",
    "esc_dog_swarm_0002",
    "esc_dog_swarm_0004",
    "esc_dog_swarm_0007",
  }
  for _, name in ipairs( badnames ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      dsh.release_mob( sobj )
    end
  end
end




function fix_add_new_mil_110( ver )
  if ver == 0 then return end
  if not db.actor:has_info( "info_way110a" ) then return end
  local sobj = alife():story_object( story_ids.exit_to_mil_110 )
  if sobj then
    log2( "[%s]: found %s, moving", script_name(), sobj:name() )
    alife():teleport_object(
      "", vector():set( -66.320304870605, 1.0114997625351, 80.36954498291 ),
      96736, 899, sobj.id
    )
  end
end


function fix_add_new_darkvalley_111( ver )
  if ver == 0 then return end
  if not db.actor:has_info( "info_way111a" ) then return end
  local sobj = alife():story_object( story_ids.exit_to_darkvalley_111 )
  if sobj then
    log2( "[%s]: found %s, fixing", script_name(), sobj:name() )
    local pk = get_netpk( sobj, 1 )
    ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
    local data = pk:get()
    data.dest_game_vertex_id  = 899
    data.dest_level_vertex_id = 97547
    data.dest_position        = vector():set( -65.978820800781, 0.65926766395569, 76.747947692871 )
    pk:set( data )
  end
end


function fix_radar_campfires( ver )
  dsh.create_candle(
    vector():set( 306.26342773438,-38.353088378906,-22.537864685059 ),
    69058, 1930, "physics\\decor\\gas_burner"
  )
  dsh.create_campfire(
    vector():set( 276.66918945313,-50.808666229248,-137.66340637207 ),
    56916, 2088,
    "objects\\koster_palki", 0.8
  )
  dsh.create_campfire(
    vector():set( 288.43316650391,-49.388702392578,-297.61456298828 ),
    60449, 2075,
    "objects\\koster_palki", 0.8
  )
  dsh.create_candle(
    vector():set( 136.52418518066,-8.0612897872925,-25.320762634277 ),
    51915, 1975, "physics\\decor\\gas_burner"
  )
end


function fix_x10_campfires( ver )
  dsh.create_candle(
    vector():set( -5.8233556747437,-6.7167258262634,-64.019966125488 ),
    4764, 2662, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -28.574440002441,-8.9861993789673,4.1149482727051 ),
    2408, 2778, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -11.185073852539,-8.1736927032471,38.302978515625 ),
    2663, 2778, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 14.992925643921,-7.6343841552734,24.79235458374 ),
    8377, 2687, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 6.132426738739,-7.7942810058594,-12.193786621094 ),
    7643, 2693, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -29.416610717773,-22.121513366699,-17.641241073608 ),
    2313, 2707, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -54.639232635498,-21.890470504761,12.031219482422 ),
    664, 2719, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -67.023880004883,-20.682132720947,34.055320739746 ),
    26, 2726, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -1.3078932762146,-18.04984664917,24.910585403442 ),
    5987, 2768, "physics\\decor\\gas_burner"
  )
end


function fix_poisk_partizan_spawn_2( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "poisk_partizan_start" )
    and not db.actor:has_info( "poisk_partizan_have" )
  then
    local found = false
    for id = 1, 65534 do
      local sobj = alife():object( id )
      if sobj and sobj:section_name() == "partizan_npc" then
        found = true
        break
      end
    end
    if not found then
      log2( "[%s]: respawn partizan_npc", script_name() )
      akill.poisk_partizan_spawn()
    end
  end
end


function fix_esc_kidalo( ver )
  local sobj = alife():object( "esc_kidalo" )
  if sobj then
    log2( "[%s]: found %s, assign story_id", script_name(), sobj:name() )
    alife():assign_story_id( nil, nil, sobj.id, story_ids.esc_kidalo )
  end
end


function fix_grom_npc( ver )
  if ver == 0 then return end
  local sobj = alife():story_object( story_ids.grom_npc )
  if sobj then
    log2( "[%s]: found %s, respawn", script_name(), sobj:name() )
    alife():release( sobj )
    akill.grom_npc_spawn()
  end
end


function fix_red_forest_candles( ver )
  dsh.create_candle(
    vector():set( 26.942028045654,5.219012260437,23.353260040283 ),
    82160, 3263, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -120.14569091797,1.3644961118698,-256.76080322266 ),
    80548, 3263, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 178.89344787598,1.3003035783768,-207.21725463867 ),
    119157, 3309, "physics\\decor\\gas_burner"
  )
end


function fix_limansk_campfires( ver )
  dsh.create_campfire(
    vector():set( -36.813842773438,-4.711784362793,-151.49208068848 ),
    7178, 2993
  )
  dsh.create_campfire(
    vector():set( 34.613452911377,14.0,190.72259521484 ),
    44841, 3010
  )
  dsh.create_campfire(
    vector():set( 27.007537841797,20.887487411499,195.97515869141 ),
    40250, 3003
  )
  dsh.create_candle(
    vector():set( -32.880226135254,-3.0803685188293,-257.22930908203 ),
    9308, 3001, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -53.555999755859,-0.34261658787727,-182.75198364258 ),
    2492, 2991, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( -58.217575073242,-11.197783470154,-173.62608337402 ),
    2492, 2991, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 32.140037536621,3.6697955131531,-61.358688354492 ),
    43375, 3014, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 27.539840698242,-1.5200437307358,45.100280761719 ),
    40855, 3015, "physics\\decor\\gas_burner"
  )
  dsh.create_candle(
    vector():set( 79.950454711914,8.2537813186646,250.22091674805 ),
    40855, 3015, "physics\\decor\\gas_burner"
  )
end


function fix_volazar( ver )
  local bad_objects = {
    "restr_tel_mg_1",
    "restr_ozersky_check_1",
    "restr_ozersky_check_2",
    "restr_ozersky_check_3",
    "restr_ozersky_check_4",
    "restr_ozersky_check_6",
    "restr_fly_jup_1",
    "ozersky",
    "restr_tel_put_1",
    "restr_sidor_delo",
    "restr_sidor_delo_2",
    "restr_tel_x16_1",
    "restr_tel_chs1_1",
    "restr_tel_chs_1",
    "restr_tel_x8_1",
    "restr_tel_lim_1",
    "restr_tel_pri_1",
    "restr_tel_war_1",
    "restr_tel_zat_1",
  }
  for _, name in ipairs( bad_objects ) do
    local sobj = alife():object( name )
    if sobj then
      log2( "[%s]: found %s, removing", script_name(), sobj:name() )
      alife():release( sobj )
    end
  end
end


function fix_living_dead_code( ver )
  if ver == 0 then return end
  if
    db.actor:has_info( "living_dead_done" )
    and db.actor:dont_has_info( "living_dead_code" )
  then
    log2(
      "[%s]: found living_dead_done, giving living_dead_code", script_name()
    )
    db.actor:give_info_portion( "living_dead_code" )
  end
end


function fix_fotograf_about( ver )
  if ver == 0 then return end
  if db.actor:has_info( "fotograf_pobeg_start" ) then
    log2(
      "[%s]: found fotograf_pobeg_start, giving fotograf_about", script_name()
    )
    db.actor:give_info_portion( "fotograf_about" )
  end
end


function fix_volna_sak_have( ver )
  if ver == 0 then return end
  if db.actor:has_info( "volna_sak_test" ) then
    log2(
      "[%s]: found volna_sak_test, giving volna_sak_have", script_name()
    )
    db.actor:give_info_portion( "volna_sak_have" )
  end
end


function fix_marsh_campfires2( ver )
  dsh.create_campfire(
    vector():set( 357.1725769043,1.3454269170761,125.54545593262 ),
    369755, 3538
  )
  dsh.create_campfire(
    vector():set( 428.85186767578,0.81956124305725,-43.843982696533 ),
    422652, 3548
  )
end
