-- -*- mode: lua; coding: windows-1251-dos -*-

local pda_keys = { "active_jobs", "contacts", "console", "map" }


function attach( sm )
  sm:subscribe({ signal = "on_spawn", fun = this.on_spawn })
end


local subscribed

function on_spawn()
  if
    db.actor:has_info( "kpk_remont_poehali" )
    and not db.actor:has_info( "docent_kpk_gotov_start" )
    and not subscribed
  then
    break_pda()
    subscribed = { signal = "on_mm_return_game", fun = this.on_mm_return_game }
    ogse_signals.get_mgr():subscribe( subscribed )
  end
end


local is_broken = false
function break_pda()
  for _, o in ipairs( pda_keys ) do
    cmd( "unbind "     .. o )
    cmd( "unbind_sec " .. o )
  end
  is_broken = true
end


function repair_pda()
  local data = dsh_cfg.get_data()
  for _, o in ipairs( pda_keys ) do
    ASSERT( data[ o ], "%s not found", o )
    local knames = parse_names( data[ o ] )
    if knames[ 1 ] then
      cmd( "bind " .. o .. " " .. knames[ 1 ] )
      if knames[ 2 ] then
        cmd( "bind_sec " .. o .. " " .. knames[ 2 ] )
      end
    end
  end
  if subscribed then
    ogse_signals.get_mgr():unsubscribe( subscribed )
    subscribed = nil
  end
  is_broken = false
end


function on_mm_return_game()
  break_pda()
end


function is_pda_broken()
  return is_broken
end
