-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_destroy", fun = this.on_destroy })
  if not ui_mm_opt_main.GetOption( "disable_auto_r2" ) then
    sm:subscribe({ signal = "on_spawn", fun = this.on_spawn })
  end
end

function on_destroy()
  cmd( "r2_render_mode normal" )
end

-- взято из ogse.script:on_game_load()
function on_spawn( data )
  cmd( "r2_dof_control off" )
  cmd( "r2_ls_depth_bias -0.00005" )
  cmd( "r2_ls_depth_scale 1.00001" )
  cmd( "r2_sun_depth_far_bias -0.00001" )
  cmd( "r2_sun_depth_far_scale 1.0" )
  cmd( "r2_sun_depth_near_bias -0.0001" )
  cmd( "r2_sun_depth_near_scale 1.00004" )
  cmd( "r2_sun_focus on" )
  cmd( "r2_sun_near_border 1." )
  cmd( "r2_ls_bloom_threshold 1." )
  cmd( "r2_sun_lumscale 1." )
end
