-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_spawn", fun = this.on_spawn })
end


function on_spawn()
  local vname = "dsh_amk_respawners.recreated"
  if not ogse.load_var( vname, false ) then
    -- удалить все активные респаунеры, которые будут пересозданы при
    -- загрузке следующего сейва.
    amk_mod.spawn_unspawned_respawners( true )
    ogse.save_var( vname, true )
  end
end
