-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  if dsh_cfg.get_data().slow_garbagecollector then
    sm:subscribe({ signal = "on_destroy", fun = this.cleanupmem  })
    sm:subscribe({ signal = "on_spawn",   fun = this.configure   })
  end
end


function configure()
  log2( "[%s]: configure collectgarbage()", script_name() )
  collectgarbage( "setpause",   400 )
  collectgarbage( "setstepmul", 100 )
end


function cleanupmem()
  local memuse = collectgarbage( "count" )
  collectgarbage( "collect" )
  log2(
    "[%s]: garbage collected: %s -> %s",
    script_name(), memuse, collectgarbage( "count" )
  )
end
