-- -*- mode: lua; coding: windows-1251-dos -*-
--[=[ embrions
  idea by andrew53
  algorithm & optimization by Monnoroch
  realization by Shadowman
  special thanks to Malandrinus for manual on object_binder
--]=]

local mut_sec =  {
  [ "zone_krovosos"     ] = "bloodsucker_weak",
  [ "zone_burer"        ] = "burer_weak",
  [ "zone_zombie"       ] = "zombie_weak",
  [ "zone_snork"        ] = "snork_weak",
  [ "zone_flesh"        ] = "flesh_weak",
  [ "zone_gigant"       ] = "gigant_normal",
  [ "zone_poltergeist"  ] = "m_poltergeist_normal_tele",
  [ "zone_psevdodog"    ] = "pseudodog_weak",
  [ "zone_controller"   ] = "m_controller_normal",
  [ "zone_chimera"      ] = "chimera_weak",
  [ "zone_boar"         ] = "boar_weak",
  [ "zone_tushkano"     ] = "tushkano_normal",
  [ "zone_psydog"       ] = "psy_dog",
  [ "zone_cat"          ] = "cat_weak",
  [ "zone_dog"          ] = "dog_normal",
  -- emb
  [ "zone_rat"          ] = "rat_strong",
  [ "zone_tarakan"      ] = "tarakan_normal",
  [ "zone_tarakan2"     ] = "tarakan_strong",
  [ "zone_bloodsucker"  ] = "bloodsucker_effector",
  [ "zone_bloodsucker2" ] = "bloodsucker_hell",
  [ "zone_deathclaw"    ] = "deathclaw_strong",
  [ "zone_fracture"     ] = "fracture_strong",
  [ "zone_bibliotekar"  ] = "bibliotekar",
  [ "zone_mono"         ] = "snp_tank1",
  [ "zone_tm"           ] = "shadow_monolith_cocoon",
  [ "zone_babka"        ] = "zombie_babka_strong",
  [ "zone_ghost"        ] = "zombie_ghost",
  [ "zone_kachok"       ] = "boar_kachok",
  [ "zone_big"          ] = "gigant_big_strong",
  [ "zone_jumper"       ] = "gigant_jumper_strong",
  [ "zone_electro"      ] = "electro_chimera",
  [ "zone_x_ray"        ] = "chimera_x_ray",
  [ "zone_wolf"         ] = "chimera_wolf",
}

-- number of monsters from one coocon
local bonus = {
  [ "boar_weak"                 ] = 2,
  [ "tushkano_normal"           ] = 4,
  [ "cat_weak"                  ] = 2,
  [ "dog_normal"                ] = 3,
  [ "bloodsucker_weak"          ] = 1,
  [ "burer_weak"                ] = 1,
  [ "zombie_weak"               ] = 1,
  [ "snork_weak"                ] = 1,
  [ "flesh_weak"                ] = 1,
  [ "gigant_normal"             ] = 1,
  [ "m_poltergeist_normal_tele" ] = 1,
  [ "pseudodog_weak"            ] = 1,
  [ "m_controller_normal"       ] = 1,
  [ "chimera_weak"              ] = 1,
  [ "psy_dog"                   ] = 1,
  -- emb
  [ "rat_strong"                ] = 4,
  [ "tarakan_normal"            ] = 4,
  [ "tarakan_strong"            ] = 2,
  [ "bloodsucker_effector"      ] = 1,
  [ "bloodsucker_hell"          ] = 1,
  [ "deathclaw_strong"          ] = 1,
  [ "fracture_strong"           ] = 1,
  [ "bibliotekar"               ] = 1,
  [ "snp_tank1"                 ] = 1,
  [ "shadow_monolith_cocoon"    ] = 1,
  [ "zombie_babka_strong"       ] = 1,
  [ "zombie_ghost"              ] = 1,
  [ "boar_kachok"               ] = 1,
  [ "gigant_big_strong"         ] = 1,
  [ "gigant_jumper_strong"      ] = 1,
  [ "electro_chimera"           ] = 1,
  [ "chimera_x_ray"             ] = 1,
  [ "chimera_wolf"              ] = 1,
}


function init( obj )
  local new_binder = embr_binder( obj )
  obj:bind_object( new_binder )
end


class "embr_binder" ( object_binder )
function embr_binder:__init( obj ) super( obj )
end 


function embr_binder:reload( section )
  object_binder.reload( self, section )
end


function embr_binder:reinit()
  object_binder.reinit( self )
end


function embr_binder:net_spawn( data )
  local mutant_section = mut_sec[ self.object:name() ]
  for i = 1, bonus[ mutant_section ] do
    local sobj = alife():create(
      mutant_section,
      self.object:position(),
      self.object:level_vertex_id(), self.object:game_vertex_id()
    )
    dsh.mark_art_as_handmade( sobj, true )
  end
  alife():release( alife():object( self.object:id() ) )
  return object_binder.net_spawn( self, data )
end


function embr_binder:net_destroy()
  object_binder.net_destroy( self )
end
