-- ножи на худе
local st

function update()
if db.actor:active_slot()==0 and level.main_input_receiver()==nil then
	if st==nil then show_st() end
else
	remove_st()
end
end

function show_st()
	--local item=db.actor:item_in_slot(0)
	--if item then sect="fake_"..item:section() else return end
	local sect="fake_"..(db.actor:item_in_slot(0):section())
	st=CUIStatic()
	local ini=system_ini()
	local x=ini:r_u32(sect, "inv_grid_x")*50
 	local y=ini:r_u32(sect, "inv_grid_y")*50
	local width=ini:r_u32(sect, "inv_grid_width")*50
 	local height=ini:r_u32(sect, "inv_grid_height")*50
	st:InitTexture("ui\\ui_icon_equipment")
	st:SetOriginalRect(x,y,width,height)
	st:SetStretchTexture(true)

	local h=36	-- высота кнопки
	st:Init(1024-132,768-60,(width/height)*h,h) -- отображение на HUD
	get_hud():AddDialogToRender(st)
end

function remove_st()
	if st then get_hud():RemoveDialogToRender(st) st=nil end
end

function net_destroy()
	remove_st()
end