-- -*- mode: lua; coding: windows-1251-dos -*-

-- запускать проверку так:
-- if protected_items.obj_is_protected(obj,tabl,method)==true then
-- данное условие будет выполнено, если предмета в списке исключений
-- вещи исключения.
-- Проверка будет по точному имени секции предмета
-- Эти предметы нельзя отбирать у ГГ (по точному совпадению):
local items_protected = {
  ["3d_raziy"] = true,
  ["af_blood_tutorial"] = true,
  ["af_invul"] = true,
  ["agroprom_pda"] = true,
  ["amk_af_night_star"] = true,
  ["amk_transmutator"] = true,
  ["anom_egg"] = true,
  ["ara_flash"] = true,
  ["arhara_instruk"] = true,
  ["arhara_listok"] = true,
  ["arhara_tele"] = true,
  ["bad_psy_helmet"] = true,
  ["bandranen_pda"] = true,
  ["bar_ecolog_flash"] = true,
  ["bar_lucky_pda"] = true,
  ["bar_tiran_pda"] = true,
  ["bioradar"] = true,
  ["bioradar2"] = true,
  ["bland_flash"] = true,
  ["blocknot_saharova"] = true,
  ["bloknot_pantera"] = true,
  ["bolt"] = true,
  ["box_kalmyak"] = true,
  ["case_freeman"] = true,
  ["case_nebo"] = true,
  ["cit_doctors_key"] = true,
  ["computer"] = true,
  ["computer_new"] = true,
  ["crazy_flash"] = true,
  ["dar_document1"] = true,
  ["dar_document2"] = true,
  ["dar_document3"] = true,
  ["dar_document4"] = true,
  ["dar_document5"] = true,
  ["dar_pass_document"] = true,
  ["dar_pass_flash"] = true,
  ["decoder"] = true,
  ["decoder1"] = true,
  ["detektor_amorf"] = true,
  ["device_pda"] = true,
  -- ["device_pda_npc"] = true,
  ["device_torch"] = true,
  ["dimak_book"] = true,
  ["diplomat"] = true,
  ["disk_adren"] = true,
  ["doc_1"] = true,
  ["doc_8"] = true,
  ["doc_10"] = true,
  ["dosye_zvez"] = true,
  ["dynamite"] = true,
  ["esc_wounded_flash"] = true,
  ["flame_parts"] = true,
  ["flamethrower_bad"] = true,
  ["forest_last_dead_listok"] = true,
  ["foto_kontroller_yazva"] = true,
  ["foto_mozg_x16"] = true,
  ["fraer_pda"] = true,
  ["garbage_pda"] = true,
  ["glushitel"] = true,
  ["good_psy_helmet"] = true,
  ["gorelka"] = true,
  ["gunslinger_flash"] = true,
  ["inventory_new_box"] = true,
  ["inventory_sakbox_01"] = true,
  ["inventory_sakbox_02"] = true,
  ["inventory_sakbox_03"] = true,
  ["inventory_sakbox_04"] = true,
  ["inventory_sakbox_05"] = true,
  ["iskra_listok"] = true,
  ["kapitan_pda"] = true,
  ["klenov_opisalovo"] = true,
  ["klyak_forest_doc"] = true,
  ["korobka_sigars"] = true,
  ["kostya_taynik_pda21"] = true,
  ["kruglov_flash"] = true,
  ["lab_x10_documents"] = true,
  ["lab_x16_documents"] = true,
  ["lekar_kalmyak"] = true,
  ["malyva"] = true,
  ["manometr"] = true,
  ["matras"] = true,
  ["mem_module"] = true,
  ["mil_svoboda_leader_pda"] = true,
  ["mono_dead_doc"] = true,
  ["mono_note"] = true,
  ["mozg"] = true,
  ["mutant_boar_cocoon"] = true,
  ["mutant_burer_cocoon"] = true,
  ["mutant_burer_red_hand"] = true,
  ["mutant_cat_cocoon"] = true,
  ["mutant_chimera_cocoon"] = true,
  ["mutant_controller_cocoon"] = true,
  ["mutant_dog_cocoon"] = true,
  ["mutant_flesh_cocoon"] = true,
  ["mutant_gigant_cocoon"] = true,
  ["mutant_krovosos_cocoon"] = true,
  ["mutant_krovosos_red_jaw"] = true,
  ["mutant_poltergeist_cocoon"] = true,
  ["mutant_psevdodog_cocoon"] = true,
  ["mutant_psydog_cocoon"] = true,
  ["mutant_snork_cocoon"] = true,
  ["mutant_tushkano_cocoon"] = true,
  ["mutant_zombie_cocoon"] = true,
  ["mutant_rat_cocoon"] = true,
  ["mutant_tarakan_cocoon"] = true,
  ["mutant_tarakan2_cocoon"] = true,
  ["mutant_bloodsucker_cocoon"] = true,
  ["mutant_bloodsucker2_cocoon"] = true,
  ["mutant_deathclaw_cocoon"] = true,
  ["mutant_fracture_cocoon"] = true,
  ["mutant_bibliotekar_cocoon"] = true,
  ["mutant_mono_cocoon"] = true,
  ["mutant_tm_cocoon"] = true,
  ["mutant_babka_cocoon"] = true,
  ["mutant_ghost_cocoon"] = true,
  ["mutant_kachok_cocoon"] = true,
  ["mutant_big_cocoon"] = true,
  ["mutant_jumper_cocoon"] = true,
  ["mutant_electro_cocoon"] = true,
  ["mutant_x_ray_cocoon"] = true,
  ["mutant_wolf_cocoon"] = true,
  ["nauch_flash"] = true,
  ["nebo_clear"] = true,
  ["netpacket_pda"] = true,
  ["new_book"] = true,
  ["new_book_prizrak"] = true,
  ["new_document_sniper"] = true,
  ["notebook"] = true,
  ["notebook_new"] = true,
  ["old_doc"] = true,
  ["old_doc_2"] = true,
  ["old_doc_3_1"] = true,
  ["old_doc_3_2"] = true,
  ["old_doc_3_3"] = true,
  ["old_doc_3_4"] = true,
  ["old_doc_4"] = true,
  ["pda_art_mod"] = true,
  ["pda_francuz"] = true,
  ["pda_info"] = true,
  ["pda_krysyka"] = true,
  ["pda_padlikova"] = true,
  ["pda_priz"] = true,
  ["pisma_stalka"] = true,
  ["pri_decoder_documents"] = true,
  ["pribor"] = true,
  ["psewdofoto"] = true,
  ["quest_case_01"] = true,
  ["quest_case_02"] = true,
  ["quest_case_05"] = true,
  ["quest_case_06"] = true,
  ["rad_document6"] = true,
  ["rad_document7"] = true,
  ["rad_pda"] = true,
  ["razved_karta"] = true,
  ["recipi_bpb"] = true,
  ["red_mozg"] = true,
  ["rukzak_green"] = true,
  ["runner_tele"] = true,
  ["sak_book1"] = true,
  ["sak_book2"] = true,
  ["sak_book3"] = true,
  ["sak_book4"] = true,
  ["sak_document"] = true,
  ["sak_document2"] = true,
  ["sak_plan"] = true,
  ["sak_resiver"] = true,
  ["sak_resiver_yantar"] = true,
  ["scaintist_docs"] = true,
  ["scaintist_pda"] = true,
  ["siv_pda"] = true,
  ["sniper_flash"] = true,
  ["snpbiopart"] = true,
  ["stalker_outfit_m3"] = true,
  ["starogil_tele"] = true,
  ["stealth_pda"] = true,
  ["strelok_taynik_pda3"] = true,
  ["strelok_taynik_pda3_1"] = true,
  ["strelok_taynik_pda3_2"] = true,
  ["strelok_pda"] = true,
  ["stukach_book"] = true,
  ["sumka_arhara"] = true,
  ["sysh_document"] = true,
  ["sysh_flash"] = true,
  ["teleportator"] = true,
  ["televizor"] = true,
  ["trubka"] = true,
  ["und_pda"] = true,
  ["val_key_to_underground"] = true,
  ["video_kasseta"] = true,
  ["ver"] = true,
  ["voen_document"] = true,
  ["vorona_egg"] = true,
  ["wpn_binoc"] = true,
  ["wpn_fot"] = true,
  ["wpn_knife"] = true,
  ["wpn_pkm_m1"] = true,
  ["wpn_soulcube"] = true,
  ["zone_docs"] = true,
  -- Akill begin
  ["akill_kontr_note_1"] = true,
  ["akill_kontr_note_2"] = true,
  ["akill_kontr_note_3"] = true,
  ["akill_kontr_note_4"] = true,
  ["akill_kontr_note_5"] = true,
  ["docs_from_x10"] = true,
  ["doktor_diktofon"] = true,
  ["zajigalka"] = true,
  ["phantom_counter"] = true,
  ["sergeant_counter"] = true,
  ["keis_key"] = true,
  ["hostel_teleport"] = true,
  ["cube_pda"] = true,
  ["retranslator"] = true,
  ["psyhodelin"] = true,
  -- Akill end
  [ "wpn_gungauss"    ] = true, -- Гаусс-пистолет из ТД
  [ "snp_pda1"        ] = true, -- ПДА для запуска сюжета о снайпере
  [ "helm_teplovizor" ] = true, -- тепловизор для Кузнецова
  [ "letter"          ] = true, -- письма
  [ "af_inferno"      ] = true, -- артефакт, который нужно забрать у Бабуина
}

-- Эти предметы нельзя отбирать у ГГ (поиск по вхождению):
local items_protected_like = {
  "playboy",
  "val_zapis",
  "kostya_pda",
  "arhara_obman",
  "fli_",
  "emb_",
  "snp_",
  "_counter",
}

-- табличка исключений трупов сталкеров для уборщика - проверка по точному совпадению
local tabl_corps_keep = {
  ["aes_stalker"] = true,
  ["dar_stalker"] = true,
  ["aes_stalker_0000"] = true,
  ["agr_ratcatcher"] = true,
  ["amk_embankment_soldat1"] = true,
  ["amk_mini_bar_kulinar"] = true,
  ["amk_mini_bar_voron"] = true,
  ["bar_ecolog_crush_dead"] = true,
  ["bar_ecolog_crush_dead_0000"] = true,
  ["bar_ecolog_crush_dead_0001"] = true,
  ["bar_ecolog_crush_dead_0002"] = true,
  ["bar_ecolog_crush_dead_0003"] = true,
  ["bar_stalker"] = true,
  ["bar_stalker_0000"] = true,
  ["dar_stalker0001"] = true,
  ["dead_korchagin_military"] = true,
  ["dead_military_bunker1"] = true,
  ["dead_military_bunker2"] = true,
  ["dead_military_qvest_crest"] = true,
  ["ecolog_dead_bunker1"] = true,
  ["ecolog_dead_bunker2"] = true,
  ["ecolog_wound_bunker"] = true,
  ["esc_stalker_0000"] = true,
  ["esc_stalker_corpse"] = true,
  ["gar_bandit_post_1"] = true,
  ["gar_sniper_bandit"] = true,
  ["gar_stalker_0000"] = true,
  ["gar_stalker_0001"] = true,
  ["gar_stalker_0002"] = true,
  ["gar_stalker_0003"] = true,
  ["gar_stalker_0004"] = true,
  ["gar_stalker_0005"] = true,
  ["kat_bandit_0006"] = true,
  ["mil_stalker"] = true,
  ["mil_stalker_0000"] = true,
  ["mil_stalker_0001"] = true,
  ["mil_stalker_0002"] = true,
  ["mil_stalker_0004"] = true,
  ["mil_Svoboda_zombi_stalker"] = true,
  ["peshera_stalker"] = true,
  ["rad_stalker_0006_dead_scientist"] = true,
  ["rad_stalker_0007_dead_scientist"] = true,
  ["rad_stalker_0008_dead_scientist"] = true,
  ["rad_stalker_dead"] = true,
  ["rostok_dead_stalker_0000"] = true,
  ["rostok_dead_stalker_01"] = true,
  ["rostok_dead_stalker_02"] = true,
  ["rostok_dead_stalker_03"] = true,
  ["rostok_stalker"] = true,
  ["val_escort_bandit1_dead"] = true,
  ["val_escort_bandit2_dead"] = true,
  ["val_lager_bandit16_0000"] = true,
  ["val_sos_dead1"] = true,
  ["val_sos_dead2"] = true,
  ["village_stalk_dead3"] = true,
  ["warlab_kostolom_dead"] = true,
  ["generators_pantera_dead"] = true,
  ["trupak_truba"] = true,
  ["village_stalk_dead1"] = true,
  ["village_stalk_dead2"] = true,
  ["village_stalk_dead3"] = true,
  ["village_brat_dead"] = true,
  ["hospital_muha_trup"] = true,
  ["muha_die"] = true,
  ["atp_trupak_disk"] = true,
  ["peshera_stalker_dead"] = true,
  ["chees2_trup_vzruv_beter1"] = true,
  ["chees2_trup_vzruv_beter2"] = true,
  ["chees2_trup_vzruv_beter3"] = true,
  ["chees2_trup_vzruv_beter4"] = true,
  ["lim_strannik_dead"] = true,
  ["forest_lastday_dead"] = true,
  ["brainlab_ecolog_trupik"] = true,
  ["yan_stalker"] = true,
  -- Akill begin
  ["akill_npc"] = true,
  -- Akill end
}

-- табличка исключений оружия для уборщика - проверка по частичному совпадению
local tabl_wpn_keep = {
  "wpn_awm_new",
  "wpn_dark_gauss",
  "wpn_gungauss",
  "wpn_lr300_m1",
  "wpn_m_134",
  "wpn_knife",
  "wpn_binoc",
  "wpn_flame",
  "wpn_pkm_m1",
  "wpn_sr3t",
  "wpn_20w_vintorez",
  "esc_wpn_ak74u",
  "esc_wpn_pm",
  "esc_wpn_bm16",
  "esc_wpn_walther",
  "aver_wpn_g36",
  "aes_wpn_abakan",
  "aes_grenade_f_000",
  "aes_wpn_rpg7",
  "dar_wpn_ak74",
  "dar_wpn_rpg7",
  "gar_grenade_f_000",
  "val_wpn_ak74u",
  "val_wpn_mp5",
  "val_wpn_rpg_0000",
  "val_wpn_abakan",
  "yan_grenade_rgd5",
  "lost_village_wpn_vintorez",
  "mar_wpn_",
  "mil_grenade_f_00",
  "mil_grenade_rgd",
  "mil_wpn_rg-6",
  "mil_wpn_lr_0000",
  "mil_wpn_pm_0000",
  "mil_wpn_ak74u",
  "mil_wpn_ak000",
  "mil_wpn_bm16",
  "mil_wpn_pm",
  "mil_wpn_abakan",
  "mil_wpn_lr_000",
  "mil_wpn_vintorez",
  "kat_wpn_ak74_m1",
  "level_prefix_wpn_groza",
  "bun_grenade_f1_000",
  "jup_grenade_",
  "wpn_desert_eagle",
  "wpn_b94",
  "wpn_v94",
  "wpn_ksvk",
  "wpn_svd_foto",
  "wpn_fot",
  "wpn_soulcube",
  "wpn_mp5_m1",
  "wpn_eagle",
  "wpn_winch1887",
  "fake_wpn_knif4",
  "wpn_rg-6"
}

-- табличка исключений предметов для уборщика - проверка по частичному
-- совпадению
local tabl_items_keep = {
  "fli_",
  "emb_",
  "snp_",
  "3d_raziy",
  "af_",
  "agroprom_pda",
  "amk_zapiska",
  "akkumulytor",
  "amul_naemn",
  "amulet",
  "ara_pda",
  "arhara",
  "arc_diary_",
  "bullion_gild",
  "_book",
  "book_",
  "bandranen_pda",
  "bar_lucky_pda",
  "bar_tiran_pda",
  "box_kalmyak",
  "box_with_weapon",
  "bezoar",
  "bitvakl_pda",
  "britva",
  "case_",
  "chuchelo_body",
  "_cocoon",
  "computer",
  "cube_pda",
  "decoder",
  "detector",
  "diplomat",
  "disk_",
  "diversya_pda",
  "doc_",
  "_doc",
  "document",
  "dynamite",
  "ekza_akkumul",
  "elek_plata",
  "exo_mil_exoskeleton",
  "_flash",
  "flame_parts",
  "flamethrower_bad",
  "flash_pda",
  "flyga",
  "fonarik",
  "fraer_pda",
  "garbage_pda",
  "glushitel",
  "golem_pda",
  "gorelka",
  "hand_teleporter",
  "hostel_pda",
  "hunters_toz", --оружие, но без wpn_ - поэтому здесь :)
  "inventory_new_box",
  "kostya_pda",
  "kostya_taynik_pda",
  "ktdt_pda",
  "stdt_pda",
  "strelok_taynik_pda",
  "val_zapis",
  "_key",
  "kapitan_pda",
  "kluch",
  "kluk_karta",
  "kod_kamera",
  "kolba_",
  "kontroler_diary",
  "kubik",
  "kukla_",
  "kuvalda",
  "land_disketka",
  "lekar_kalmyak",
  "lekarstvo",
  "malyva",
  "manometr",
  "maz",
  "meceniy_outfit_new",
  "microshema",
  "mil_bolt_pda",
  "mil_svoboda_leader_pda",
  "money",
  "mono_note",
  "mozg",
  "naem_bloknot",
  "nebo_clear",
  "netpacket_pda",
  "notebook",
  "otvertka",
  "parcel",
  "pda_dimak",
  "pda_francuz",
  "pda_info",
  "pda_krysyka",
  "pda_padlikova",
  "pda_priz",
  "pda_vasilyev",
  "perfuzor_",
  "player",
  "playboy",
  "pribor",
  "pseudopechatka",
  "_psy_helmet",
  "rad_pda",
  "remontnyi_box",
  "rukzak_green",
  "quest_",
  "sakbox",
  "sak_",
  "scaintist_pda",
  "shaxter_tele",
  "shkatulka",
  "shpriz",
  "sidor_head",
  "siv_pda",
  "snotvornoe_tele",
  "spekulyant_pda",
  "soap",
  "starik_chasy",
  "stealth_pda",
  "strelok_pda",
  "suvorotka",
  "tabletki_",
  "televizor",
  "telefon",
  "termos_",
  "travka",
  "trubka",
  "trupak",
  "und_pda",
  "volkodav_pda",
  "vorona_egg",
  "detektor_amorf",
  "x_ray_antenna",
  "video_",
  "voen_pda",
  "wpn_mp5_m1",
  "wpn_eagle_m2",
  "wpn_svd_foto",
  "zapiska_ranennogo",
  -- Akill begin
  "phantom_counter",
  "sergeant_counter",
  "flash_",
  "akill_kontr_note_",
  "doktor_diktofon",
  "fake_wpn_knif4",
  "zajigalka",
  -- Akill end
  -- Chessplayer
  "note_zone",
  "dictofon",
  "blank_sheet",
  "notebook_oldman",
  "note",
  "diary_chess",
  "thief_pda",
  "vasya_head",
  -- Chessplayer end
  -- дипломат с деньгами у наемников на Юпитере
  "^case_buusty$",
  -- фотоаппарат в подземке Агропрома
  "^wpn_fot$",
  -- записная книжка Архары в подземке Агропрома
  "^new_book$",
  "^gagarin_outfit$",           -- Бронекостюм Гагарин
  "meceniy_outfit_new",         -- Невидимый экзоскелет
  "exo_mil_exoskeleton",        -- СКАТ - 15
  "^lab_x10_documents",         -- документ из трупа монолитовца
  "^container_morkov",          -- рис и морковь для Кулинара
  "^container_ris",
  "^soldier_outfit$",           -- Гравикостюм
  "^docs_x7$",
  "^voen_document$",      -- документа из трупа военного Андрея
  "^scaintist_docs$",     -- документы у ученого в ТД, у вертолета
  "^nauch_flash$",        -- флешка у ученого в X-18
  "^mono_dead_doc$",      -- документ с трупа монолитовца на Болотах
  "^snp_pda1$",           -- ПДА для запуска сюжета о снайпере
  "^helm_teplovizor$",    -- тепловизор для Кузнецова
  "^letter$",             -- письма
  "^af_inferno$",         -- артефакт, который нужно забрать у Бабуина
  "^sysh_flash$",         -- флэшка Сыча
  -- инструкция в трупике в Красном Лесу
  "^forest_last_dead_listok$",
}

-- метки апгрейдженного и уникального оружия встречаются в секциях
-- обычных стволов, поэтому проверяем его отдельно, не по вхождению, а
-- по последним трем символам секции
local unique_wpn_keep = {
  [ "_m1" ] = true,
  [ "_m2" ] = true,
  [ "_m3" ] = true,
}

-- Монстры-друзья для разных исключений, проверка по секции,
-- get_obj_name() тут почему-то работает некорректно
local monster_friends = {
  [ "dogfrend"          ] = true,
  [ "wolffrend_zaton"   ] = true,
  [ "wolffrend_zaton2"  ] = true,
  [ "bibliofrend_zaton" ] = true
}

-- Квестовые неписи, не участвующие в оффлайн и онлайн алайфе АМК, проверка по секции
local no_offline_alife_npcs = {
  ["kotobegemot_bar"] = true,
  ["kotobegemot_zaton"] = true,
  ["ariadna_bar"] = true,
  ["ariadna_zaton"] = true,
  ["fenrir_zaton"] = true,
  ["fenrir_2chaes"] = true,
  ["fenrir_jupiter"] = true,
  ["wolffrend_talk_zaton"] = true,
  ["wolffrend_talk_zaton2"] = true,
  ["resident_evil_zaton"] = true,
  ["resident_evil_jupiter"] = true,
  ["bibliofrend_talk_zaton"] = true,
  ["bibliofrend_talk_black_zaton"] = true,
  ["anna_zaton"] = true,
  ["anna_zaton2"] = true,
  ["anna_jupiter"] = true,
  ["ludmila_zaton"] = true,
  ["maria_kordon"] = true,
  ["elsa_yantar"] = true,
  ["gena_oso"] = true,
  ["snegir_2chaes"] = true,
  ["snegir_kordon"] = true,
  ["snegir2_2chaes"] = true,
  ["snegir3_2chaes"] = true,
  ["bubulyka_zaton"] = true,
  ["lobsang_zaton"] = true,
  ["brodaga_mg"] = true,
  ["brodaga_zaton"] = true,
  ["boroda_jupiter"] = true,
  ["boroda_zaton"] = true,
  ["vesker_zaton"] = true,
  ["proper70_limansk"] = true,
  ["proper70_jupiter"] = true,
  ["proper70_zaton"] = true,
  ["tm_jupiter1"] = true,
  ["parad_tm"] = true,
  ["tm_brother_labirint"] = true,
  ["tm_brother_2chaes"] = true,
  ["volazar"] = true,
  ["volazar_new"] = true,
  ["ozersky"] = true,
  -- Akill begin
  ["predator_npc"] = true,
  ["dragunof_npc"] = true,
  ["fotograf_npc"] = true,
  ["akill_npc"] = true,
  ["noi_npc"] = true
  -- Akill end
}

local grab_body_items_keep = {
  "_counter"
}

-- табличка исключений трупов сталкеров для уборщика по story_id
local tabl_corps_keep_by_story_id = {
  [ 21005 ] = true,
  [ 30118 ] = true,
  --chessplayer
  [ 22001 ] = true,
  [ 22002 ] = true,
  [ 22003 ] = true,
  [ 22004 ] = true,
  [ 22005 ] = true,
  [ 22006 ] = true,
  [ 22007 ] = true,
  [ 22008 ] = true,
  --chessplayer end
}

-- стволы, которые не разряжаются при обмене
local not_unloaded_weapons = {
  [ "wpn_flame"    ] = true,
  [ "wpn_eagle_m2" ] = true,
}


local tabl_corps_keep_by_info = {
  [ "aes_stalker"        ] = "sar_monolith_destroy",
  [ "aes_stalker_0000"   ] = "sar_monolith_destroy",
  [ "bar_ecolog_crush_dead"      ] = "yan_kill_brain_done",
  [ "bar_ecolog_crush_dead_0000" ] = "yan_kill_brain_done",
  [ "bar_ecolog_crush_dead_0001" ] = "yan_kill_brain_done",
  [ "bar_stalker"        ] = "agroprom_military_case_done",
  [ "dar_stalker"        ] = "bar_darklab_document_done",
  [ "dar_stalker0001"    ] = "bar_darklab_document_done",
  [ "esc_stalker_0000"   ] = "agroprom_military_case_done",
  [ "esc_stalker_corpse" ] = "esc_tutorial_secret_place",
  [ "gar_sniper_bandit"  ] = "gar_wounded_fight",
  [ "gar_stalker_0000"   ] = "agroprom_military_case_done",
  [ "gar_stalker_0001"   ] = "agroprom_military_case_done",
  [ "gar_stalker_0002"   ] = "agroprom_military_case_done",
  [ "gar_stalker_0004"   ] = "agroprom_military_case_done",
  [ "kat_bandit_0006"    ] = "agroprom_military_case_done",
  [ "lim_strannik_dead"  ] = "semetskiy_lima_spawn",
  [ "mil_stalker"        ] = "bar_deactivate_radar_done",
  [ "mil_stalker_0000"   ] = "bar_deactivate_radar_done",
  [ "mil_stalker_0002"   ] = "bar_deactivate_radar_done",
  [ "rostok_dead_stalker_0000"        ] = "acv_vandal",
  [ "rostok_dead_stalker_01" ] = "yan_kill_brain_done",
  [ "rostok_dead_stalker_02" ] = "yan_kill_brain_done",
  [ "rostok_dead_stalker_03" ] = "yan_kill_brain_done",
  [ "val_escort_bandit1_dead"         ] = "bar_darklab_document_done",
  [ "val_escort_bandit2_dead"         ] = "bar_darklab_document_done",
  [ "val_lager_bandit16_0000"         ] = "bar_darklab_document_done",
  [ "val_sos_dead1"      ] = "bar_darklab_document_done",
  [ "val_sos_dead2"      ] = "bar_darklab_document_done",
  [ "rad_stalker_0006_dead_scientist" ] = "bar_deactivate_radar_done",
  [ "rad_stalker_0007_dead_scientist" ] = "bar_deactivate_radar_done",
  [ "rad_stalker_0008_dead_scientist" ] = "bar_deactivate_radar_done",
  [ "yan_stalker"        ] = "yan_kill_brain_done",

  [ "dead_military_bunker1" ] = "ucen_talk_est",
  [ "dead_military_bunker2" ] = "ucen_talk_est",
  [ "ecolog_dead_bunker1"   ] = "ucen_talk_est",
  [ "ecolog_dead_bunker2"   ] = "ucen_talk_est",
  [ "ecolog_wound_bunker"   ] = "ucen_talk_est",

  [ "brainlab_ecolog_trupik" ] = "kvest_saxar_teleport_done",

  -- два трупика ученых у вертолета в ТД, по заданию Борова на чемодан
  [ 48800 ] = "borov_11_have",
  [ 48801 ] = "borov_11_have",
}


function is_unique_wpn_keep( section )
  return unique_wpn_keep[ string.sub( section, -3 ) ]
end


-- Получаем имя секции проверяемого объекта
-- obj может быть как игровым, так и серверным объектом (см. news_main.get_object_name(obj))
-- исправленная версия от naxac
function get_obj_name( obj )
  if not obj then return "" end
  local name    = obj:name()
  local section = ( obj.section ~= nil and obj:section() ) -- game_object
    or ( obj.section_name ~= nil and obj:section_name() ) -- server_object
    or ""                                                 -- wtf?
  local id      = ( type( obj.id ) == "function" and obj:id() ) or obj.id
  if name == section .. id then
    return section              -- section
  else
    return name                 -- name from all.spawn
  end
end


function switch_table( table_name )
  if table_name == "items_protected" then
    return items_protected
  end
  if table_name == "tabl_corps_keep" then
    return tabl_corps_keep
  end
  if table_name == "tabl_wpn_keep" then
    return tabl_wpn_keep
  end
  if table_name == "tabl_items_keep" then
    return tabl_items_keep
  end
end


-- Здесь проверка по имени секции по таблицам выбранным методом
-- Вернет true, если предмет внесен в исключения
-- параметры:
-- sobj - объект для проверки
-- tabl - по какой таблице прверять
-- method - либо "exactly" - по точному имени секции, либо "like" - по части имени
-- прим.: таблицы для проверки точного совпадения - свои, для частичного - свои
function obj_is_protected( sobj, tabl, method )
  local result       = false
  local item_section = get_obj_name( sobj )
  local t = switch_table( tabl )
  ASSERT( t, "tabl = %s not found", tostring( tabl ) )
  -- более быстрый метод, без цикла
  if method == "exactly" then
    if t[ item_section ] == true then
      result = true
    end
    -- более медленный, перебираем таблицу, нашли совпадение - прерываем
  elseif method == "like" then
    for _, v in ipairs( t ) do
      if string.find( item_section, v ) then
        result = true
        break
      end
    end
  end
  return result
end


function is_monster_friend( section )
  return monster_friends[ section ]
end


function is_no_offline_alife_npc( section )
  return no_offline_alife_npcs[ section ]
end


-- Предметы, которые неписям нельзя забирать с трупов при шмоне. В
-- функции проверяются таблицы:
--
--         items_protected - точное совпадение,
--         tabl_items_keep - частичное совпадение,
--         grab_body_items_keep - частичное совпадение.
--
-- Т.е. если предмет указан только в последней таблице, то неписи его
-- не заберут, а уборщик труп будет убирать
function is_grab_body_item_keep( section )
  if items_protected[ section ] then return true end
  for _, v in ipairs( tabl_items_keep ) do
    if string.find( section, v ) then
      return true
    end
  end
  for _, v in ipairs( grab_body_items_keep ) do
    if string.find( section, v ) then
      return true
    end
  end
  return false
end


-- Предметы, которые не отбираются у гг, проверка по секции
function actor_items_keep( section )
  if items_protected[ section ] then return true end
  for _, v in ipairs( items_protected_like ) do
    if string.find( section, v ) then
      return true
    end
  end
  return false
end


function is_corps_keep_by_story_id( obj )
  return tabl_corps_keep_by_story_id[ obj.m_story_id ] and true or false
end


function not_unloaded_weapon( section )
  return not_unloaded_weapons[ section ]
end


function unprotect_tabl_corps_keep( sobj )
  local name    = sobj:name()
  local by_name = tabl_corps_keep_by_info[ name ]
  local by_sid  = tabl_corps_keep_by_info[ sobj.m_story_id ]
  if by_name then
    if has_alife_info( by_name ) then
      tabl_corps_keep[ name ] = nil
    end
  elseif by_sid then
    if has_alife_info( by_sid ) then
      tabl_corps_keep_by_story_id[ sobj.m_story_id ] = nil
    end
  end
end
