
local places = {
["exit_as"] = {lv = 28719, gv = 1758, pos = {-317.23675537109,-26.327833175659,55.278633117676}, lvl = "l07_military"},
["exit_as2"] = {lv = 66343, gv = 1786, pos = {-274.62121582031,-27.297189712524,239.00979614258}, lvl = "l07_military"},
["exit_as3"] = {lv = 273147, gv = 1821, pos = {-33.368682861328,-20.897382736206,379.58074951172}, lvl = "l07_military"},
["exit_as4"] = {lv = 83694, gv = 1852, pos = {-243.89454650879,-0.28634393215179,435.28894042969}, lvl = "l07_military"},
["exit_bunker"] = {lv = 7807, gv = 2773, pos = {8.3457946777344,-23.525426864624,19.003190994263}, lvl = "l10u_bunker"},
["exit_svalka"] = {lv = 127101, gv = 351, pos = {-77.325019836426,-3.660080909729,195.34251403809}, lvl = "l02_garbage"},
["exit_svalka2"] = {lv = 1201, gv = 260, pos = {-289.04534912109,-6.6783475875854,-178.82406616211}, lvl = "l02_garbage"},
["exit_svalka3"] = {lv = 344517, gv = 401, pos = {200.77691650391,-0.638019323349,-145.20561218262}, lvl = "l02_garbage"},
["exit_svalka4"] = {lv = 284570, gv = 374, pos = {122.61166381836,-4.2376079559326,153.47959899902}, lvl = "l02_garbage"},
["exit_svalka5"] = {lv = 324917, gv = 384, pos = {173.82795715332,-0.30577194690704,51.149074554443}, lvl = "l02_garbage"},
["exit_svalka6"] = {lv = 311456, gv = 385, pos = {97.819366455078,15.575645446777,31.107891082764}, lvl = "l02_garbage"},
["exit_svalka7"] = {lv = 166216, gv = 332, pos = {-49.738338470459,20.034204483032,115.88290405273}, lvl = "l02_garbage"},
["exit_svalka8"] = {lv = 2848, gv = 314, pos = {-277.18438720703,0.42264106869698,26.608871459961}, lvl = "l02_garbage"},
["exit_svalka9"] = {lv = 27161, gv = 308, pos = {-204.31503295898,0.77477610111237,-14.08620929718}, lvl = "l02_garbage"},
["exit_svalka10"] = {lv = 117566, gv = 299, pos = {-43.285057067871,22.38338470459,-109.06379699707}, lvl = "l02_garbage"},
["exit_svalka11"] = {lv = 123627, gv = 268, pos = {-82.571281433105,-2.6017231941223,-208.38046264648}, lvl = "l02_garbage"},
["exit_svalka12"] = {lv = 272734, gv = 263, pos = {108.47253417969,-2.2334003448486,-264.66119384766}, lvl = "l02_garbage"},
["exit_pripyat"] = {lv = 260478, gv = 2219, pos = {190.84159851074,2.8052725791931,212.05661010742}, lvl = "l11_pripyat"},
["exit_pripyat2"] = {lv = 7817, gv = 2216, pos = {-112.93630981445,2.8031325340271,97.108512878418}, lvl = "l11_pripyat"},
["exit_x18"] = {lv = 4086, gv = 1155, pos = {5.0796270370483,-12.429841995239,15.65408706665}, lvl = "l04u_labx18"},
["exit_td"] = {lv = 212105, gv = 1025, pos = {31.025503158569,-2.9186296463013,-18.474792480469}, lvl = "l04_darkvalley"},
["exit_td2"] = {lv = 377579, gv = 938, pos = {177.20614624023,6.6501698493958,-368.2509765625}, lvl = "l04_darkvalley"},
["exit_kordon"] = {lv = 557888, gv = 245, pos = {288.75579833984,6.6381821632385,334.9274597168}, lvl = "l01_escape"},
["exit_kordon2"] = {lv = 220208, gv = 16, pos = {-56.72008895874,-29.649417877197,-352.75286865234}, lvl = "l01_escape"},
["exit_kordon3"] = {lv = 314641, gv = 198, pos = {33.526428222656,4.8442959785461,406.35510253906}, lvl = "l01_escape"},
["exit_kordon4"] = {lv = 326234, gv = 97, pos = {43.707790374756,1.604367017746,157.83784484863}, lvl = "l01_escape"},
["exit_kordon5"] = {lv = 346954, gv = 97, pos = {59.635650634766,19.672622680664,156.50126647949}, lvl = "l01_escape"},
["exit_kordon6"] = {lv = 479316, gv = 242, pos = {176.90881347656,6.2265067100525,274.12582397461}, lvl = "l01_escape"},
["exit_kordon7"] = {lv = 418761, gv = 115, pos = {116.21976470947,-7.5939545631409,-16.879535675049}, lvl = "l01_escape"},
["exit_kordon8"] = {lv = 71846, gv = 30, pos = {-178.17098999023,-29.790063858032,-355.4208984375}, lvl = "l01_escape"},
["exit_kordon9"] = {lv = 116591, gv = 19, pos = {-138.1682434082,-25.440311431885,-356.09561157227}, lvl = "l01_escape"},
["exit_kordon10"] = {lv = 46406, gv = 38, pos = {-206.31811523438,-36.486312866211,-275.36505126953}, lvl = "l01_escape"},
["exit_kordon11"] = {lv = 34087, gv = 47, pos = {-218.33445739746,-19.930738449097,-167.60050964355}, lvl = "l01_escape"},
["exit_kordon12"] = {lv = 45951, gv = 58, pos = {-207.27334594727,-22.535316467285,-128.54507446289}, lvl = "l01_escape"},
["exit_kordon13"] = {lv = 11502, gv = 67, pos = {-246.82745361328,-14.313711166382,-17.025833129883}, lvl = "l01_escape"},
["exit_kordon14"] = {lv = 143574, gv = 73, pos = {-112.90689849854,-8.191520690918,7.4986095428467}, lvl = "l01_escape"},
["exit_kordon15"] = {lv = 274973, gv = 108, pos = {-1.5780007839203,-17.687986373901,-152.26568603516}, lvl = "l01_escape"},
["exit_radar"] = {lv = 93230, gv = 2081, pos = {351.03564453125,-45.688995361328,-201.36804199219}, lvl = "l10_radar"},
["exit_radar2"] = {lv = 67978, gv = 1930, pos = {304.68270874023,-39.390411376953,-25.789834976196}, lvl = "l10_radar"},
["exit_radar3"] = {lv = 14611, gv = 2013, pos = {14.053562164307,-1.2424700260162,41.381050109863}, lvl = "l10_radar"},
["exit_radar4"] = {lv = 6439, gv = 1960, pos = {-12.000325202942,0.37741497159004,-67.812171936035}, lvl = "l10_radar"},
["exit_undergraund"] = {lv = 2505, gv = 745, pos = {-84.987205505371,-16.462963104248,-60.738975524902}, lvl = "l03u_agr_underground"},
["exit_bar"] = {lv = 45474, gv = 1188, pos = {193.61143493652,0.097166806459427,71.526657104492}, lvl = "l05_bar"},
["exit_bar2"] = {lv = 39883, gv = 1204, pos = {175.31533813477,-0.0002819299697876,145.91943359375}, lvl = "l05_bar"},
["exit_bar3"] = {lv = 47206, gv = 1270, pos = {198.24176025391,3.271665096283,-77.252685546875}, lvl = "l05_bar"},
["exit_bar4"] = {lv = 59366, gv = 1277, pos = {232.64491271973,5.1447978019714,-113.61502838135}, lvl = "l05_bar"},
["exit_bar5"] = {lv = 68763, gv = 1274, pos = {276.64755249023,0.055086404085159,-66.742523193359}, lvl = "l05_bar"},
["exit_bar6"] = {lv = 35860, gv = 1238, pos = {128.80438232422,-4.8249382972717,16.76756477356}, lvl = "l05_bar"},
["exit_bar7"] = {lv = 33903, gv = 1239, pos = {116.09830474854,-5.3052234649658,12.649393081665}, lvl = "l05_bar"},
["exit_agroprom"] = {lv = 428448, gv = 498, pos = {253.95002746582,-0.20055566728115,76.619018554688}, lvl = "l03_agroprom"},
["exit_agroprom2"] = {lv = 117939, gv = 523, pos = {-122.60626983643,10.350003242493,164.23361206055}, lvl = "l03_agroprom"},
["exit_agroprom3"] = {lv = 103987, gv = 621, pos = {-135.0357208252,4.9933753013611,-196.9232635498}, lvl = "l03_agroprom"},
["exit_yantar1"] = {lv = 6635, gv = 1486, pos = {-98.555587768555,-12.03422164917,-263.20428466797}, lvl = "l08_yantar"},
["exit_yantar2"] = {lv = 22009, gv = 1454, pos = {-49.516319274902,-12.687213897705,-263.55654907227}, lvl = "l08_yantar"},
["exit_yantar3"] = {lv = 85543, gv = 1440, pos = {87.165092468262,1.5326626300812,-137.15473937988}, lvl = "l08_yantar"},
["exit_yantar4"] = {lv = 98895, gv = 1520, pos = {110.79859924316,0.51710104942322,67.085777282715}, lvl = "l08_yantar"},
["exit_yantar5"] = {lv = 93237, gv = 1515, pos = {102.05886077881,-0.055661827325821,-38.264953613281}, lvl = "l08_yantar"},
["exit_yantar6"] = {lv = 50739, gv = 1505, pos = {23.551870346069,-3.417268037796,-50.092147827148}, lvl = "l08_yantar"},
["exit_yantar7"] = {lv = 57034, gv = 1445, pos = {35.566432952881,0.036594957113266,19.930288314819}, lvl = "l08_yantar"},
["exit_yantar8"] = {lv = 87168, gv = 1514, pos = {90.726051330566,0.028770864009857,-2.0428421497345}, lvl = "l08_yantar"},
["exit_yantar9"] = {lv = 38250, gv = 1525, pos = {-2.272828578949,0.31553617119789,-12.611492156982}, lvl = "l08_yantar"},
["exit_yantar10"] = {lv = 39736, gv = 1525, pos = {0.41521853208542,20.732145309448,-11.2778673172}, lvl = "l08_yantar"},
["exit_yantar11"] = {lv = 53157, gv = 1480, pos = {28.687835693359,-5.943422794342,-272.9033203125}, lvl = "l08_yantar"},
["exit_dt1"] = {lv = 15216, gv = 1391, pos = {-236.99816894531,9.3585262298584,56.257476806641}, lvl = "l06_rostok"},
["exit_dt2"] = {lv = 8119, gv = 1382, pos = {-254.47462463379,-5.8917918205261,88.748420715332}, lvl = "l06_rostok"},
["exit_dt3"] = {lv = 4658, gv = 1379, pos = {-268.44509887695,-6.0012273788452,106.45835113525}, lvl = "l06_rostok"},
["exit_dt4"] = {lv = 7269, gv = 1338, pos = {-282.68493652344,-0.0055593848228455,203.75721740723}, lvl = "l06_rostok"},
["exit_dt5"] = {lv = 32043, gv = 1329, pos = {-173.43870544434,-0.0011672079563141,192.25354003906}, lvl = "l06_rostok"},
["exit_dt6"] = {lv = 38957, gv = 1328, pos = {-149.55770874023,0.096051603555679,179.93653869629}, lvl = "l06_rostok"},
["exit_dt7"] = {lv = 22437, gv = 1370, pos = {-217.82315063477,1.935809969902,88.06103515625}, lvl = "l06_rostok"},
["exit_dt8"] = {lv = 32382, gv = 1322, pos = {-169.39688110352,-0.0033434927463531,82.040466308594}, lvl = "l06_rostok"},
["exit_dt9"] = {lv = 36070, gv = 1321, pos = {-159.36485290527,-0.0026704967021942,99.839752197266}, lvl = "l06_rostok"},
["exit_dt10"] = {lv = 27318, gv = 1326, pos = {-192.9693145752,-0.0026823878288269,119.04988098145}, lvl = "l06_rostok"},
["exit_dt11"] = {lv = 46578, gv = 1421, pos = {-89.581573486328,3.1074571609497,148.33610534668}, lvl = "l06_rostok"},
["exit_peshera"] = {lv = 32280, gv = 2880, pos = {-0.06784837692976,-2.0694215297699,-12.294366836548}, lvl = "peshera"},
["exit_peshera1"] = {lv = 18736, gv = 47, pos = {-241.71829223633,-16.903062820435,-155.92127990723}, lvl = "l01_escape"},
["exit_to_stancia21"] = {lv = 76262, gv = 2573, pos = {210.38436889648,79.390335083008,120.03535461426}, lvl = "l12_stancia_2"},
["exit_to_sarcofag"] = {lv = 3612, gv = 2407, pos = {11.051639556885,16.534572601318,16.863817214966}, lvl = "l12u_sarcofag"},
["exit_st_limansk"] = {lv = 9426, gv = 2993, pos = {-32.022926330566,-2.0075621604919,-148.88047790527}, lvl = "limansk"},
["exit_st_stancia"] = {lv = 405327, gv = 2276, pos = {919.07550048828,4.7601909637451,26.304740905762}, lvl = "l12_stancia"},
["exit_st_garbage"] = {lv = 240043, gv = 364, pos = {68.035255432129,5.6778559684753,163.51155090332}, lvl = "l02_garbage"},
["exit_st_pripyat"] = {lv = 113687, gv = 2159, pos = {9.7145528793335,4.4628782272339,7.1703128814697}, lvl = "l11_pripyat"},
["fli_hospital"] = {lv = 3351, gv = 3048, pos = {-85.302398681641,41.056434631348,776.25244140625}, lvl = "hospital"},
["exit_ht_x18"] = {lv = 4889, gv = 1135, pos = {13.947868347168,-6.8296647071838,-5.2945156097412}, lvl = "l04u_labx18"},

["exit_ao1"] = {lv = 5172, gv = 2417, pos = {25.456817626953,54.437591552734,28.762804031372}, lvl = "l12u_sarcofag"},
["exit_ao2"] = {lv = 6306, gv = 41, pos = {-259.61,-13.98,-187.48}, lvl = "l01_escape"},
["exit_ao3"] = {lv = 72760, gv = 2030, pos = {308.31381225586,-44.890308380127,-24.124353408813}, lvl = "l10_radar"},
["exit_ao4"] = {lv = 188933, gv = 3089, pos = {-127.49746704102,38.661094665527,-520.49487304688}, lvl = "generators"},
["exit_ao5"] = {lv = 66343, gv = 1786, pos = {-274.62121582031,-27.297189712524,239.00979614258}, lvl = "l07_military"},
["exit_ao6"] = {lv = 1158843, gv = 3686, pos = {111.87593078613,-3.9350895881653,176.39245605469}, lvl = "zaton"},
["exit_ao7"] = {lv = 33914, gv = 1254, pos = {116.0602722168,0.033155769109726,35.708042144775}, lvl = "l05_bar"},
["exit_ao8"] = {lv = 40068, gv = 3015, pos = {26.088516235352,-2.4164898395538,42.248687744141}, lvl = "limansk"},
["exit_ao9"] = {lv = 55496, gv = 2164, pos = {-43.435306549072,-0.57717317342758,268.41397094727}, lvl = "l11_pripyat"},
["exit_ao10"] = {lv = 560091, gv = 3717, pos = {-95.548728942871,5.2484011650085,203.49862670898}, lvl = "jupiter"},
["exit_ao11"] = {lv = 5345, gv = 3187, pos = {5.704110622406,1.0890669822693,-3.2182774543762}, lvl = "warlab"},
["exit_ao12"] = {lv = 142214, gv = 325, pos = {-49.409076690674,0.42059007287025,28.796478271484}, lvl = "l02_garbage"},
["exit_ao13"] = {lv = 360325, gv = 3765, pos = {133.20779418945,5.1283469200134,-182.25480651855}, lvl = "pripyat"},
["exit_ao14"] = {lv = 51891, gv = 3366, pos = {-178.7742767334,4.7911396026611,-275.01214599609}, lvl = "marsh"},
["exit_ao15"] = {lv = 53157, gv = 1480, pos = {28.734613418579,-5.9429059028625,-272.36102294922}, lvl = "l08_yantar"},
["exit_ao16"] = {lv = 281711, gv = 664, pos = {44.295482635498,7.4990944862366,-17.695718765259}, lvl = "l03_agroprom"},
["exit_ao17"] = {lv = 226054, gv = 856, pos = {40.993808746338,0.058221489191055,-207.00549316406}, lvl = "l04_darkvalley"}, 
["exit_ao18"] = {lv = 16905, gv = 1394, pos = {-233.31646728516,-0.0013412833213806,26.524562835693}, lvl = "l06_rostok"},
["exit_ao19"] = {lv = 18229, gv = 3330, pos = {16.050863265991,13.998382568359,26.675790786743}, lvl = "lost_village"},
["exit_ao20"] = {lv = 81814, gv = 3263, pos = {26.942283630371,0.56374621391296,1.8774330615997}, lvl = "red_forest"},
["exit_ao21"] = {lv = 8264, gv = 2867, pos = {-129.37750244141,-2.6931195259094,-52.077285766602}, lvl = "peshera"},
["exit_ao22"] = {lv = 147012, gv = 2974, pos = {-132.24591064453,15.993305206299,370.70886230469}, lvl = "av_peshera"},
["exit_ao23"] = {lv = 257785, gv = 2889, pos = {-355.35290527344,-8.947283744812,-10.452521324158}, lvl = "aver"},
["exit_ao24"] = {lv = 366146, gv = 2307, pos = {841.36560058594,0.21676424145699,-60.036106109619}, lvl = "l12_stancia"},
["exit_ao25"] = {lv = 76262, gv = 2573, pos = {210.38436889648,79.390335083008,120.03535461426}, lvl = "l12_stancia_2"},
["exit_ao26"] = {lv = 3566, gv = 3048, pos = {-86.706840515137,33.103744506836,777.02429199219}, lvl = "hospital"},
["exit_ao27"] = {lv = 321642, gv = 3634, pos = {-30.61820602417,1.3391841650009,47.41455078125}, lvl = "dead_city"},
["exit_ao28"] = {lv = 294411, gv = 2806, pos = {-57.948169708252,-2.6055943965912,206.89984130859}, lvl = "atp_for_test22"},
["exit_ao29"] = {lv = 155976, gv = 2882, pos = {-39.042659759521,1.3759714365005,-152.66925048828}, lvl = "puzir"},
["exit_ao30"] = {lv = 413, gv = 2483, pos = {-36.416271209717,-34.481643676758,13.138676643372}, lvl = "l12u_control_monolith"},
["exit_ao31"] = {lv = 3664, gv = 3848, pos = {-77.962303161621,-15.978303909302,68.778076171875}, lvl = "labx8"},
["exit_ao32"] = {lv = 2331, gv = 2708, pos = {-29.235069274902,-10.359714508057,-4.3701152801514}, lvl = "l10u_bunker"},
["exit_ao33"] = {lv = 730, gv = 1529, pos = {-91.174026489258,21.575830459595,-31.21177482605}, lvl = "l08u_brainlab"},
["exit_ao34"] = {lv = 2402, gv = 1134, pos = {-2.1915831565857,-10.814116477966,-7.9789485931396}, lvl = "l04u_labx18"},
["exit_ao35"] = {lv = 4444, gv = 739, pos = {-44.476081848145,-14.852001190186,-40.71529006958}, lvl = "l03u_agr_underground"},
["exit_ao36"] = {lv = 38033, gv = 3808, pos = {58.340644836426,3.091902256012,0.053759146481752}, lvl = "jupiter_underground"},

["gena_exit1"] = {lv = 457245, gv = 3117, pos = {104.18505859375,30.108690261841,-546.89520263672}, view = {-0.17,1.68,-0.17}, lvl = "generators"},
["gena_exit2"] = {lv = 1373, gv = 3837, pos = {-96.782424926758,-15.938969612122,102.60270690918}, lvl = "labx8"},
["gena_exit5"] = {lv = 52361, gv = 1480, pos = {27.432319641113,-11.718158721924,-271.48077392578}, view = {0,2.375,0}, lvl = "l08_yantar"}
}

-- таблица телепортов
-- art - требуемый арт для телепортации (если задан - отберётся у ГГ)
-- keep - оставлять ли телепорт
-- goto_func - список вариантов заброски телепортом
local teleports = {
	["gena_tele1"] = {
		goto_func = {
			"gena_exit1"
		}
	},
	["gena_tele2"] = {
		goto_func = {
			"gena_exit2"
		}
	},
	["gena_tele3"] = {
		goto_func = {
			"exit_ao11"
		}
	},
	["device_teleport"] = {
		art = "af_electra_moonlight",
		goto_func = {
			"exit_agroprom",
			"exit_agroprom2",
			"exit_agroprom3",
			"exit_as",
			"exit_as2",
			"exit_as3",
			"exit_as4",
			"exit_bar",
			"exit_bar2",
			"exit_bar3",
			"exit_bar4",
			"exit_bar5",
			"exit_bar6",
			"exit_bar7",
			"exit_bunker",
			"exit_dt1",
			"exit_dt2",
			"exit_dt3",
			"exit_dt4",
			"exit_dt5",
			"exit_dt6",
			"exit_dt7",
			"exit_dt8",
			"exit_dt9",
			"exit_dt10",
			"exit_dt11",
			"exit_kordon",
			"exit_kordon2",
			"exit_kordon3",
			"exit_kordon4",
			"exit_kordon5",
			"exit_kordon6",
			"exit_kordon7",
			"exit_kordon8",
			"exit_kordon9",
			"exit_kordon10",
			"exit_kordon11",
			"exit_kordon12",
			"exit_kordon13",
			"exit_kordon14",
			"exit_kordon15",
			"exit_pripyat",
			"exit_pripyat2",
			"exit_radar",
			"exit_radar2",
			"exit_radar3",
			"exit_radar4",
			"exit_svalka",
			"exit_svalka2",
			"exit_svalka3",
			"exit_svalka4",
			"exit_svalka5",
			"exit_svalka6",
			"exit_svalka7",
			"exit_svalka8",
			"exit_svalka9",
			"exit_svalka10",
			"exit_svalka11",
			"exit_svalka12",
			"exit_td",
			"exit_td2",
			"exit_undergraund",
			"exit_x18",
			"exit_yantar1",
			"exit_yantar2",
			"exit_yantar3",
			"exit_yantar4",
			"exit_yantar5",
			"exit_yantar6",
			"exit_yantar7",
			"exit_yantar8",
			"exit_yantar9",
			"exit_yantar10",
			"exit_yantar11"
		}
	},
	["science_teleport3"] = {
		art = "af_electra_moonlight",
		goto_func = {
	--		"exit_yantar1",
	--		"exit_yantar2",
			"exit_yantar3",
			"exit_yantar4",
	--		"exit_yantar5",
	--		"exit_yantar6",
	--		"exit_yantar7",
	--		"exit_yantar8",
	--		"exit_yantar9",
			"exit_yantar10",
			"exit_yantar11"
		}
	},
	["science_teleport2"] = {
		art = "af_electra_moonlight",
		goto_func = {
			"exit_bar",
			"exit_bar2",
	--		"exit_bar3",
	--		"exit_bar4",
	--		"exit_bar5",
			"exit_bar6",
			"exit_bar7"
		}
	},
	["science_teleport"] = {
		art = "af_electra_moonlight",
		goto_func = {
			"exit_kordon",
	--		"exit_kordon2",
	--		"exit_kordon3",
	--		"exit_kordon4",
	--		"exit_kordon5",
	--		"exit_kordon6",
	--		"exit_kordon7",
	--		"exit_kordon8",
	--		"exit_kordon9",
	--		"exit_kordon10",
			"exit_kordon11",
			"exit_kordon12",
	--		"exit_kordon13",
	--		"exit_kordon14",
			"exit_kordon15"
		}
	},
	["arhara_tele"] = {
		goto_func = {
			"exit_to_stancia21"
		}
	},
	["snp_sarcofag"] = {
		goto_func = {
			"exit_to_sarcofag"
		}
	},
	["snotvornoe_tele"] = {
		goto_func = {
			"exit_peshera"
		}
	},
	["shaxter_tele"] = {
		goto_func = {
			"exit_peshera1"
		}
	},
	["starogil_tele"]  = {
		keep = true, 
		pay = 10000, 
		goto_func = {
			"exit_st_limansk", 
			"exit_st_stancia", 
			"exit_st_garbage", 
			"exit_st_pripyat"
		}
	},
	["hostel_teleport"] = {
		art = "af_inferno",
		keep = false,
		sjedobniy = true,
		pay = 35000,
		goto_func = {
			"exit_ht_x18"
		}
	},
	-- для следующих телепортов обязательно должны быть указаны keep, pay и autosave
	["arhara_obman1"]  = {keep = true, pay = 35000, autosave = "l12u_sarcofag", goto_func = {"exit_ao1"}},
	["arhara_obman2"]  = {keep = true, pay = 25000, autosave = "l01_escape", goto_func = {"exit_ao2"}},
	["arhara_obman3"]  = {keep = true, pay = 30000, autosave = "l10_radar", goto_func = {"exit_ao3"}},
	["arhara_obman4"]  = {keep = true, pay = 40000, autosave = "generators", goto_func = {"exit_ao4"}},
	["arhara_obman5"]  = {keep = true, pay = 20000, autosave = "l07_military", goto_func = {"exit_ao5"}},
	["arhara_obman6"]  = {keep = true, pay = 35000, autosave = "zaton", goto_func = {"exit_ao6"}},
	["arhara_obman7"]  = {keep = true, pay = 20000, autosave = "l05_bar", goto_func = {"exit_ao7"}},
	["arhara_obman8"]  = {keep = true, pay = 35000, autosave = "limansk", goto_func = {"exit_ao8"}},
	["arhara_obman9"]  = {keep = true, pay = 25000, autosave = "l11_pripyat", goto_func = {"exit_ao9"}},
	["arhara_obman10"] = {keep = true, pay = 35000, autosave = "jupiter", goto_func = {"exit_ao10"}},
	["arhara_obman11"] = {keep = true, pay = 30000, autosave = "warlab", goto_func = {"exit_ao11"}},
	["arhara_obman12"] = {keep = true, pay = 20000, autosave = "l02_garbage", goto_func = {"exit_ao12"}},
	["arhara_obman13"] = {keep = true, pay = 30000, autosave = "pripyat", goto_func = {"exit_ao13"}},
	["arhara_obman14"] = {keep = true, pay = 25000, autosave = "marsh", goto_func = {"exit_ao14"}},
	["arhara_obman15"] = {keep = true, pay = 35000, autosave = "l08_yantar", goto_func = {"exit_ao15"}},
	["arhara_obman16"] = {keep = true, pay = 25000, autosave = "l03_agroprom", goto_func = {"exit_ao16"}},
	["arhara_obman17"] = {keep = true, pay = 25000, autosave = "l04_darkvalley", goto_func = {"exit_ao17"}},
	["arhara_obman18"] = {keep = true, pay = 25000, autosave = "l06_rostok", goto_func = {"exit_ao18"}},
	["arhara_obman19"] = {keep = true, pay = 40000, autosave = "lost_village", goto_func = {"exit_ao19"}},
	["arhara_obman20"] = {keep = true, pay = 35000, autosave = "red_forest", goto_func = {"exit_ao20"}},
	["arhara_obman21"] = {keep = true, pay = 20000, autosave = "peshera", goto_func = {"exit_ao21"}},
	["arhara_obman22"] = {keep = true, pay = 20000, autosave = "av_peshera", goto_func = {"exit_ao22"}},
	["arhara_obman23"] = {keep = true, pay = 30000, autosave = "aver", goto_func = {"exit_ao23"}},
	["arhara_obman24"] = {keep = true, pay = 25000, autosave = "l12_stancia", goto_func = {"exit_ao24"}},
	["arhara_obman25"] = {keep = true, pay = 30000, autosave = "l12_stancia_2", goto_func = {"exit_ao25"}},
	["arhara_obman26"] = {keep = true, pay = 35000, autosave = "hospital", goto_func = {"exit_ao26"}},
	["arhara_obman27"] = {keep = true, pay = 40000, autosave = "dead_city", goto_func = {"exit_ao27"}},
	["arhara_obman28"] = {keep = true, pay = 25000, autosave = "atp_for_test22", goto_func = {"exit_ao28"}},
	["arhara_obman29"] = {keep = true, pay = 25000, autosave = "puzir", goto_func = {"exit_ao29"}},
	["arhara_obman30"] = {keep = true, pay = 30000, autosave = "l12u_control_monolith", goto_func = {"exit_ao30"}},
	["arhara_obman31"] = {keep = true, pay = 20000, autosave = "labx8", goto_func = {"exit_ao31"}},
	["arhara_obman32"] = {keep = true, pay = 20000, autosave = "l10u_bunker", goto_func = {"exit_ao32"}},
	["arhara_obman33"] = {keep = true, pay = 20000, autosave = "l08u_brainlab", goto_func = {"exit_ao33"}},
	["arhara_obman34"] = {keep = true, pay = 20000, autosave = "l04u_labx18", goto_func = {"exit_ao34"}},
	["arhara_obman35"] = {keep = true, pay = 20000, autosave = "l03u_agr_underground", goto_func = {"exit_ao35"}},
	["arhara_obman36"] = {keep = true, pay = 20000, autosave = "jupiter_underground", goto_func = {"exit_ao36"}}
}

function create_level_changer(
	p_story_id,	-- STORY_ID нового level_changer (понадобится нам позже)
	p_position,	-- вектор, координаты точки, в которой будет располагаться центр нового level_changer
	p_lvertex_id,	-- level_vertext_id  - идентифицируют уровень, на котором будет создан level_changer
	p_gvertex_id,	-- game_vertext_id   	
 
	p_dest_lv,	-- level_vertex_id   - идентифицируют уровень, на который level_changer будет перебрасывать игрока 
	p_dest_gv,	-- game_vertex_id
	p_dest_pos,	-- координаты точки, в которой на новом уровне окажется игрок
	p_dest_dir,	-- направрение взгляда игрока
	p_dest_level,	-- название уровня, например "L11_Pripyat"
	p_silent	-- следует задать 1, чтобы подавить вопрос о смене уровня (автоматический переход)
)
	local sim = alife()
	local obj = sim:create("level_changer", p_position, p_lvertex_id, p_gvertex_id)
 
--	level.map_add_object_spot(obj.id, "level_changer", "")
 
	local packet = net_packet()
	obj:STATE_Write(packet)
 
	-- свойства cse_alife_object
	local game_vertex_id 			= packet:r_u16()
	local cse_alife_object__unk1_f32 	= packet:r_float()
	local cse_alife_object__unk2_u32 	= packet:r_u32()
	local level_vertex_id 			= packet:r_u32()
	local object_flags 			= packet:r_u32()
	local custom_data 			= packet:r_stringZ()
	local story_id 				= packet:r_u32()
	local spawn_story_id			= packet:r_u32()
 
	-- свойства cse_shape
	local shape_count 			= packet:r_u8()
	for i=1,shape_count do
		local shape_type 		= packet:r_u8()
		if shape_type == 0 then
			-- sphere
			local center 		= packet:r_vec3()
			local radius 		= packet:r_float()
		else
			-- box
			local axis_x_x = packet:r_float()
			local axis_x_y = packet:r_float()
			local axis_x_z = packet:r_float()
			local axis_y_x = packet:r_float()
			local axis_y_y = packet:r_float()
			local axis_y_z = packet:r_float()
			local axis_z_x = packet:r_float()
			local axis_z_y = packet:r_float()
			local axis_z_z = packet:r_float()
			local offset_x = packet:r_float()
			local offset_y = packet:r_float()
			local offset_z = packet:r_float()
		end
	end
 
	-- свойства cse_alife_space_restrictor
	local restrictor_type 			= packet:r_u8()
 
	-- свойства cse_level_changer
	local dest_game_vertex_id		= packet:r_u16()  
	local dest_level_vertex_id 		= packet:r_u32()  
	local dest_position 			= packet:r_vec3()
	local dest_direction 			= packet:r_vec3()
	local dest_level_name 			= packet:r_stringZ()
	local dest_graph_point 			= packet:r_stringZ()
	local silent_mode 			= packet:r_u8()
 
 
	packet:w_begin(game_vertex_id)			-- game_vertex_id
	packet:w_float(cse_alife_object__unk1_f32)
	packet:w_u32(cse_alife_object__unk2_u32) 
	packet:w_u32(level_vertex_id)			-- level_vertex_id
	packet:w_u32( bit_not(193) )			-- object_flags = -193 = 0xFFFFFF3E
	packet:w_stringZ(custom_data)
	packet:w_u32(p_story_id)			-- story_id
	packet:w_u32(spawn_story_id)
 
	packet:w_u8(1)			-- количество фигур
--		packet:w_u8(0)			-- тип фигуры: сфера
--		packet:w_vec3(vector():set(0, 0, 0))  -- sphere_center
--		packet:w_float(3.0)
	packet:w_u8(1)			-- тип фигуры: box
	packet:w_float(50)	   -- axis_x_x
	packet:w_float(0)	   -- axis_x_y
	packet:w_float(0)	   -- axis_x_z
	packet:w_float(0)	   -- axis_y_x
	packet:w_float(50)	   -- axis_y_y
	packet:w_float(0)	   -- axis_y_z
	packet:w_float(0)	   -- axis_z_x
	packet:w_float(0)	   -- axis_z_y
	packet:w_float(50)	   -- axis_z_z
	packet:w_float(0)	   -- offset_x
	packet:w_float(0)	   -- offset_y
	packet:w_float(0)          -- offset_z
 
	packet:w_u8(3)	 	   -- restrictor_type
 
	packet:w_u16(p_dest_gv)			-- destination game_vertex_id
	packet:w_s32(p_dest_lv)			-- destination level_vertex_id
	packet:w_vec3(p_dest_pos)		-- destination position
	packet:w_vec3(p_dest_dir)		-- destination direction (направление взгляда)
	packet:w_stringZ(p_dest_level)		-- destination level name
	packet:w_stringZ("start_actor_02")	-- some string, always const
	packet:w_u8(p_silent)			-- 1 for silent level changing
 
	packet:r_seek(0)
	obj:STATE_Read(packet, packet:w_tell())
 level.add_pp_effector ("teleport.ppe", 2006, false)
 
end

function jumpTo(where)
 level.enable_input()
 
 if not db.actor:alive() then return end
 
 local actor = db.actor
 local place = places[where]
 local view
 if place.view then
	view = vector():set(place.view[1],place.view[2],place.view[3])
 else
	view = vector():set(0,0,0)
 end
 create_level_changer(9799, actor:position(), actor:level_vertex_id(), actor:game_vertex_id(),
  place.lv,
  place.gv,
  vector():set(place.pos[1],place.pos[2],place.pos[3]),
  view,
  place.lvl,
  1)
end

-- Калбек на потерю предмета
function checking_droped_obj(obj)
	if has_alife_info("biznes_remove_special_item") then return end

	local obj_sect = obj:section()
	
	if obj_sect == "teleportator" then
		amk.start_timer("use_teleportator", 0.2)
		return
	end
	
	if not teleports[obj_sect] then return end -- не наш "клиент"
	
	local tbl = {}
	tbl.obj_id = obj:id()
	tbl.obj_sect = obj_sect
	amk.start_timer("timer_drop_obj_teleport", 0.2, tbl)
end

function do_teleport(obj_sect)
	db.actor:give_info_portion("teleport_started")
	level.start_stop_menu(level.main_input_receiver(), true)

	if telepot_allowed(obj_sect) then
		-- телепортируем
		teleport_start(obj_sect)
	else
		-- неудача
		teleport_fail(obj_sect)
	end
end

function telepot_allowed(obj_sect)
	local num = teleports[obj_sect].pay

	if has_alife_info("no_teleport_near_heli_btr") then 
		news_manager.send_tip(db.actor, "Телепортация из района скопления вражеских сил невозможна по техническим причинам. Для восстановления функциональности устраните угрозу.", nil, "nano", 20000)
		return false
	elseif has_alife_info("kod_vveden_verno") and not has_alife_info("dead_city_atpeshka") then 
		news_manager.send_tip(db.actor, "Телепортация временно невозможна по техническим причинам. Попробуйте активировать функцию позднее.", nil, "nano", 20000)
		return false
	elseif actor_is_in_danger() then
		return false
	elseif num and db.actor:money() < num then
		news_manager.send_tip(db.actor, "Для телепортации недостаточно денег.", nil, "nano", 20000)
		return false
	elseif not drrr.weight_ok() then
		news_manager.send_tip(db.actor, "Телепортация перегруженного человека невозможна по техническим причинам. Снизьте вес или отремонтируйте бронекостюм.", nil, "nano", 20000)
		return false
	elseif teleports[obj_sect].art and not db.actor:object(teleports[obj_sect].art) then  	
		-- если арт не нужен или его нет у ГГ
		news_manager.send_tip(db.actor, "Отсутствует необходимый для телепортации артефакт "..game.translate_string(amk.get_inv_name(teleports[obj_sect].art))..".", nil, "nano", 20000)
		return false
	end
	return true
end

-- наличие опасности в зависимости от уровня сложности
function actor_is_in_danger()
	local difficulty = level.get_game_difficulty()
	local danger_text = "Телепортация при наличии вражеской угрозы невозможна по техническим причинам. Для восстановления функциональности устраните угрозу."

	if difficulty < 2 then
		return false
	else
		return danger.actor_in_danger(danger_text, danger_text, difficulty == 2)
	end
end

function teleport_start(obj_sect)
	fly.stop()

	-- вернем телепорт в рюкзак
	if teleports[obj_sect].keep then
		return_teleport(obj_sect)
	end

	-- autosave
	local to_level = teleports[obj_sect].autosave
	if to_level and to_level ~= level.name() then
		u3_utils.savegame_lc("Телепорт", to_level)
	end

	db.actor:disable_info_portion("no_gravigun")

	local num = teleports[obj_sect].pay
	if num then
		aem_manager.manage_money(num, "out")
	end

	-- отбираем арт
	if teleports[obj_sect].art then
		sak.out_item_namber(teleports[obj_sect].art,1)
	end

	level.disable_input()

	-- вызываем случайную функцию для данного телепорта. таймер дается для автосейва
	amk.start_timer("teleport_jumpto", 3.0, teleports[obj_sect].goto_func[math.random(#(teleports[obj_sect].goto_func))])
end

function teleport_fail(obj_sect)
	-- неудача - возвращаем использованный ТП
	return_teleport(obj_sect)
	db.actor:disable_info_portion("teleport_started")
end

function return_teleport(obj_sect)
	-- с телепортатором многоразовые ТП не возвращаем
	if db.actor:object("teleportator") and string.find(obj_sect,"arhara_obman") then return end

	amk.spawn_item_in_inv(obj_sect)
end

function remove_old_teleport()
	local se_obj = alife():story_object(9799)
	if se_obj then
		alife():release(se_obj, true)
		archievements.acv_count_2event("acv_tp", 50, "Лётчик", "acv_tp2", 100, "Аномальный странник")
	end
	
	db.actor:disable_info_portion("teleport_started")
end

function on_take_teleportator(obj)
	local obj_sect = obj:section()
	if obj_sect == "teleportator" then
		-- нашли телепортатор - переносим в него все имеющиеся телепорты
		amk.start_timer("on_take_teleportator",0.2)
	end
end

function on_take_teleportator_chunk()
	db.actor:give_info_portion("biznes_remove_special_item")
	db.actor:inventory_for_each(transfer_to_teleporter)
	news_manager.send_tip(db.actor, "Все имеющиеся ручные телепорты перенесены в Телепортатор.", nil, "nano", 20000)
	db.actor:disable_info_portion("biznes_remove_special_item")
end
function transfer_to_teleporter(obj)
	local obj_sect = obj:section()

	if string.find(obj_sect,"arhara_obman") then
		db.actor:give_info_portion(obj_sect)
		amk.remove_item_from_inventory(obj, db.actor)
	end
end

function on_take_teleporter(obj)
	-- нашли телепорт - добавляем его в телепортатор
	if not db.actor:object("teleportator") then return end
	
	local obj_sect = obj:section()

	if string.find(obj_sect, "arhara_obman") then
		db.actor:give_info_portion(obj_sect)
		news_manager.send_tip(db.actor, "В Телепортатор добавлена новая территория: "..game.translate_string(teleports[obj_sect].autosave)..".", nil, "nano", 20000)
		archievements.acv_cognized_zone()

		db.actor:give_info_portion("biznes_remove_special_item")
		amk.remove_item_from_inventory(obj, db.actor)
		db.actor:disable_info_portion("biznes_remove_special_item")
	end
end

function teleport_name(obj_sect)
	return teleports[obj_sect]
end
