-- -*- mode: lua; coding: windows-1251-dos -*-

-- Выдача тайника
function treasure()
  local treasures = {}
  local tmgr      = treasure_manager.get_treasure_manager()
  for k, v in pairs( tmgr.treasure_info ) do
    table.insert( treasures, k )
  end
  local idx = dsh.get_next_random(
    script_name() .. ".treasure.rnd", table.getn( treasures )
  )
  tmgr:give_treasure( treasures[ idx ] )
end
