--Vergas часы-таймер
class "cheat" (CUIScriptWnd)

local hh = 0      		-- кол-во часов до выброса при установке
local mm = 0      		-- кол-во минут до выброса при установке
local volume_wnd_3 = nil
local volume_wnd_1 = nil
local flag_set_timer  	-- флаг установленного таймера
local flag_set_sek		-- флаг установленного секундомера
local timer_mode		-- флаг установленного режима (1 - таймер, 2 - секундомер)

function cheat:__init(owner) super()
	self.owner = owner
	self:InitControls()
	self:InitCallBacks()
end

function cheat:InitControls()
	
	-- Положение и размеры окна
	self:Init(676,0,347,658)
	
	-- файл-описатель элементов
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_cheat_timer.xml")
	
	xml:InitStatic("background", self)   --Собственно часики
	xml:InitStatic("background_2", self) --Фон для надписи  
	xml:InitStatic("static_1", self)  --надпись УСТАНОВКА ТАЙМЕРА
	xml:InitStatic("static_2", self)  --надпись ИНСТРУЦИЯ ИСПОЛЬЗОВАНИЯ
	--xml:InitStatic("static_3", self)  --надпись текст инструкции строка 1
	--xml:InitStatic("static_4", self)  --надпись текст инструкции строка 2
	
	self:Register(xml:Init3tButton("btn_sbros", self),"btn_sbros")	-- Кнопка СБРОС
	self:Register(xml:Init3tButton("btn_ok", self),"btn_ok")	    -- Кнопка ОК
	self:Register(xml:Init3tButton("btn_quit", self),"btn_quit")	-- Кнопка СТОП
	self:Register(xml:Init3tButton("btn_hh", self),"btn_hh")	    -- Кнопка ЧЧ
	self:Register(xml:Init3tButton("btn_mm", self),"btn_mm")	    -- Кнопка MM
	self:Register(xml:Init3tButton("btn_change", self),"btn_change")	-- Кнопка РЕЖИМ
	
	-- Вывожу инструкцию
	-- первая строка
	local inst = "Кнопка СКМ:ТМР - смена режима (таймер-секундомер)"	
	volume_wnd_i_1 = CUIStatic()
	volume_wnd_i_1:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_1)
	volume_wnd_i_1:SetWndRect(-340, 367, 200,20)    --337, 200)       
	volume_wnd_i_1:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_1:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_1:SetText(inst)
	
	-- вторая строка
	local inst = "Кнопка ОК - запуск выбранного режима"
	volume_wnd_i_2 = CUIStatic()
	volume_wnd_i_2:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_2)
	volume_wnd_i_2:SetWndRect(-340, 377, 200,20)    --337, 200)       
	volume_wnd_i_2:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_2:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_2:SetText(inst)
	
	-- третья строка
	local inst = "Кнопка СБРОС - отключение запущенного режима"
	volume_wnd_i_3 = CUIStatic()
	volume_wnd_i_3:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_3)
	volume_wnd_i_3:SetWndRect(-340, 387, 200,20)    --337, 200)       
	volume_wnd_i_3:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_3:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_3:SetText(inst)
	
	-- четвертая строка
	local inst = "Кнопка ВЫХОД - убрать часы"
	volume_wnd_i_4 = CUIStatic()
	volume_wnd_i_4:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_4)
	volume_wnd_i_4:SetWndRect(-340, 397, 200,20)    --337, 200)       
	volume_wnd_i_4:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_4:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_4:SetText(inst)

	-- пятая строка
	local inst = "Кнопка ЧЧ - управление показанием часов"
	volume_wnd_i_5 = CUIStatic()
	volume_wnd_i_5:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_5)
	volume_wnd_i_5:SetWndRect(-340, 407, 200,20)    --337, 200)       
	volume_wnd_i_5:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_5:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_5:SetText(inst)
	
	-- шестая строка
	local inst = "Кнопка ММ - управление показанием минут"
	volume_wnd_i_6 = CUIStatic()
	volume_wnd_i_6:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_6)
	volume_wnd_i_6:SetWndRect(-340, 417, 200,20)    --337, 200)       
	volume_wnd_i_6:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_6:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_6:SetText(inst)

	-- седьмая строка
	local inst = "Индикатор зеленый - ввод выбранного режима"
	volume_wnd_i_7 = CUIStatic()
	volume_wnd_i_7:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_7)
	volume_wnd_i_7:SetWndRect(-340, 427, 200,20)    --337, 200)       
	volume_wnd_i_7:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_7:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_7:SetText(inst)
	
	-- восьмая строка
	local inst = "Индикатор красный - выбранный режим запущен"
	volume_wnd_i_8 = CUIStatic()
	volume_wnd_i_8:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_8)
	volume_wnd_i_8:SetWndRect(-340, 437, 200,20)    --337, 200)       
	volume_wnd_i_8:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_8:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_8:SetText(inst)
	
	-- девятая строка
	local inst = "ПОЛНАЯ ГАРАНТИЯ на период жизни сталкера"
	volume_wnd_i_9 = CUIStatic()
	volume_wnd_i_9:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_9)
	volume_wnd_i_9:SetWndRect(-340, 447, 200,20)    --337, 200)       
	volume_wnd_i_9:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_9:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_9:SetText(inst)
	
	-- десятая строка
	local inst = "ПРИЯТНОГО ИСПОЛЬЗОВАНИЯ!"
	volume_wnd_i_10 = CUIStatic()
	volume_wnd_i_10:SetAutoDelete(true)
	self:AttachChild(volume_wnd_i_10)
	volume_wnd_i_10:SetWndRect(-270, 467, 200,20)    --337, 200)       
	volume_wnd_i_10:SetFont(GetFontLetterica16Russian())
	volume_wnd_i_10:SetTextColor(255, 255, 255, 255)
	volume_wnd_i_10:SetText(inst)

	-- Вывожу время
	local time_h = level.get_time_hours() 
	local time_m = level.get_time_minutes() 
	local str_t = timer_v.timer_str(time_m, time_h)
	--имитирую секунды
	local str_sek = timer_v.imitation_sek(time_h,time_m)
	
	str_t = "Время  "..str_t..str_sek
	
	volume_wnd_1 = CUIStatic()
	volume_wnd_1:SetAutoDelete(true)
	self:AttachChild(volume_wnd_1)
	volume_wnd_1:SetWndRect(118, 240, 100, 15)       
	volume_wnd_1:SetFont(GetFontLetterica18Russian())
	volume_wnd_1:SetTextColor(100, 154, 205, 50)
	volume_wnd_1:SetText(str_t)
	
	--Вывожу дни в Зоне
	local time_d = amk.game_days()
	if (time_d >= 10)  and (time_d < 10 ) then
		str_d = string.format(" %d", time_d)
	elseif time_d >= 100 then
		str_d = string.format("%d", time_d)
	elseif time_d < 10 then
		str_d = string.format("  %d", time_d)
	end
	
	
	local volume_wnd_2 = nil
	volume_wnd_2 = CUIStatic()
	volume_wnd_2:SetAutoDelete(true)
	self:AttachChild(volume_wnd_2)
	volume_wnd_2:SetWndRect(85,260, 100, 15)
	volume_wnd_2:SetFont(GetFontLetterica18Russian())
	volume_wnd_2:SetTextColor(100, 154, 205, 50)
	volume_wnd_2:SetText("День пребывания в Зоне:"..str_d)
	
	--Вывожу показания таймера и секундомера
	volume_wnd_3 = CUIStatic()
	volume_wnd_3:SetAutoDelete(true)
	self:AttachChild(volume_wnd_3)
	volume_wnd_3:SetWndRect(116,150, 100, 15)
	volume_wnd_3:SetFont(GetFontLetterica18Russian())
	
	-- определяю режим 
	if timer_mode == nil then  --режим неопределен.
		flag_set_timer = timer_v.timer_flag_in_cheat(1)
		flag_set_sek = timer_v.timer_flag_in_cheat(2)
		
		if flag_set_timer == 1 then
			timer_mode = 1
		elseif flag_set_sek == 1 then
			timer_mode = 2
		end
		if timer_mode == nil then  --режим неопределен.
			--на всякий случай обнуляю флаги таймера и секундомера
			flag_set_timer = 0
			flag_set_sek = 0
			hh = 0
			mm = 0
			timer_v.set_timer_flag(1,flag_set_timer,hh,mm)
			timer_v.set_timer_flag(2,flag_set_sek,hh,mm)
			timer_mode = 1		   -- Принудительно ставлю режим таймера
		end
	end
	
	-- Режим таймера
	if timer_mode ==1 then
		flag_set_timer = timer_v.timer_flag_in_cheat(1)
		if (flag_set_timer == 0) or (flag_set_timer == nil) then
			hh = 0
			mm = 0
		end
		local str_t = timer_v.timer_str(mm, hh)
		if flag_set_timer == 1 then
			volume_wnd_3:SetTextColor(255, 178, 34, 34)		--вывод красным
			str_t = timer_v.h_m_from_mm()
		else
			volume_wnd_3:SetTextColor(100, 154, 205, 50)	--вывод зеленым
		end
		volume_wnd_3:SetText("До выброса "..str_t)
	end
	
	--Режим секундомера
	if timer_mode == 2 then
		flag_set_sek = timer_v.timer_flag_in_cheat(2)
		if (flag_set_sek == 0) or (flag_set_sek == nil) then
			hh = 0
			mm = 0
		end
		local str_t = timer_v.timer_str(mm, hh)
		if flag_set_sek == 1 then
			volume_wnd_3:SetTextColor(255, 178, 34, 34)		--вывод красным
			str_t = timer_v.h_m_from_mm()
		else
			volume_wnd_3:SetTextColor(100, 154, 205, 50)	--вывод зеленым
		end
		volume_wnd_3:SetText("Секундомер "..str_t)
	end
end

function cheat:InitCallBacks()
	self:AddCallback("btn_sbros", ui_events.BUTTON_CLICKED, self.btn_sbros, self)   	-- Кнопка СБРОС
	self:AddCallback("btn_ok", ui_events.BUTTON_CLICKED, self.btn_ok, self)         	-- Кнопка ОК
	self:AddCallback("btn_quit", ui_events.BUTTON_CLICKED, self.btn_quit, self)     	-- Кнопка ВЫХОД
	self:AddCallback("btn_hh", ui_events.BUTTON_CLICKED, self.btn_hh, self)         	-- Кнопка ЧЧ
	self:AddCallback("btn_mm", ui_events.BUTTON_CLICKED, self.btn_mm, self)         	-- Кнопка ММ
	self:AddCallback("btn_change", ui_events.BUTTON_CLICKED, self.btn_change, self)     -- Кнопка РЕЖИМ
end

function cheat:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		-- на выход повесим Esc
		if dik == DIK_keys.DIK_ESCAPE then
			self:on_quit()
		-- реакция на 1
		elseif dik == DIK_keys.DIK_1 then
			
		end
	end
	return true
end

function cheat:on_quit()
--amk.spawn_item_in_inv("timer")
	self:GetHolder():start_stop_menu (self,true)
end

function cheat:btn_sbros()					-- Кнопка СБРОС
	hh = 0
	mm = 0
	local str_t = timer_v.timer_str(mm, hh)
	volume_wnd_3:SetTextColor(100, 154, 205, 50)
	if timer_mode == 1 then
		volume_wnd_3:SetText("До выброса "..str_t)
		flag_set_timer = 0   -- таймер сброшен на часах
		timer_v.set_timer_flag(1,flag_set_timer,hh,mm) --таймер сброшен на худе
	else
		volume_wnd_3:SetText("Секундомер "..str_t)
		flag_set_sek = 0   -- секундомер сброшен на часах
		timer_v.set_timer_flag(2,flag_set_sek,hh,mm) --секундомер сброшен на худе
	end
end

function cheat:btn_ok()					    -- Кнопка ОК
	-- снимаю текущее время
	local time_h = level.get_time_hours() 
	local time_m = level.get_time_minutes() 
	local str_t = timer_v.timer_str(time_m, time_h)
	--имитирую секунды
	local str_sek = timer_v.imitation_sek(time_h,time_m)
	str_t = "Время  "..str_t..str_sek
	--вывожу время
	volume_wnd_1:SetText(str_t)
	
	--проверяю, а не установлен ли ужо кой-нить режим?
	if (flag_set_timer == 1) or (flag_set_sek == 1) then
		return  --кнопочку жать нельзя, пока не сбросил установленный режим
	end
	
	--включаю таймер на часах
	if timer_mode == 1 then
		if (hh ~= 0) or (mm ~= 0) then
			flag_set_timer = 1  --таймер установлен на часах
			--вывожу надпись красным
			str_t = timer_v.timer_str(mm, hh)
			volume_wnd_3:SetTextColor(255, 178, 34, 34)
			volume_wnd_3:SetText("До выброса "..str_t)
			timer_v.set_timer_flag(1,flag_set_timer,hh,mm) --передаю флаг и данные для установки таймера на худе
		end
	end
	
	--включаю секундомер на часах
	if timer_mode == 2 then
		flag_set_sek = 1  --секундомер установлен на часах
		--вывожу надпись красным
		str_t = timer_v.timer_str(mm, hh)
		volume_wnd_3:SetTextColor(255, 178, 34, 34)
		volume_wnd_3:SetText("Секундомер "..str_t)
		timer_v.set_timer_flag(2,flag_set_sek,hh,mm) --передаю флаг и данные для установки секундомера на худе
	end
end

function cheat:btn_quit()					-- Кнопка ВЫХОД
		self:on_quit()
end

function cheat:btn_hh()					    -- Кнопка ЧЧ
	-- проверяю, а можно ли жать?
	if timer_mode == 1 then
		if flag_set_timer == 0 then
			-- расчитываю
			hh = hh + 1
			if hh == 24 then
				mm = 0
			elseif hh == 25 then
				hh = 0
			end
			-- вывожу
			local str_t = timer_v.timer_str(mm, hh)
			volume_wnd_3:SetText("До выброса "..str_t)
		end
	end
end

function cheat:btn_mm()					    -- Кнопка ММ
	-- проверяю, а можно ли жать?
	if timer_mode == 1 then
		if flag_set_timer == 0 then
			-- расчитываю
			if mm < 59 then
				mm = mm + 1
			else
				mm = 0
				if hh < 24 then
					hh = hh+1
				end
			end
			if hh == 24 then
				mm = 0
			end
			-- вывожу
			local str_t = timer_v.timer_str(mm, hh)
			volume_wnd_3:SetText("До выброса "..str_t)
		end
	end
end

function cheat:btn_change()					    -- Кнопка РЕЖИМ 
	--проверяю, а можно ли жать?
	if (flag_set_timer == 1) or (flag_set_sek == 1) then
		return      -- жать нельзя: один из режимов активен и не сброшен
	end
	
	--меняю режим
	if timer_mode ==1 then
		timer_mode = 2
	else
		timer_mode = 1
	end
	
	-- Изменяю худ часов
	mm = 0
	hh = 0
	local str_t = timer_v.timer_str(mm, hh)
	if timer_mode == 1 then
		volume_wnd_3:SetText("До выброса "..str_t)
	else
		volume_wnd_3:SetText("Секундомер "..str_t)
	end
end

