function add_krysyk_pomer_treasure()
	treasure_manager.get_treasure_manager():give_treasure("esc_secret_village_rucksack")
end

function check_bes_dead()
    local actor = db.actor
    local rnd = math.random
    local have_box = false
    if actor and actor:has_info("gar_hellcar_umer") and 
        actor:has_info("val_pula_ammo_start") and 
        not actor:has_info("val_pula_ammo_done") then
            for i=0, actor:object_count()-1 do
                local obj = actor:object(i)
            if obj and obj:section() == "inventory_sakbox_01" then
                    have_box = true
            end
            end
            if not actor:has_info("val_pula_ammo_newsinfo1") then
                -- for i=0, actor:object_count()-1 do
                -- local obj = actor:object(i)
                -- if obj and obj:section() == "inventory_sakbox_01" then
                if have_box then
                    amk.start_timer("sms",rnd(20,30),1)
                    actor:give_info_portion("val_pula_ammo_newsinfo1")
                end
                if not actor:has_info("val_pula_ammo_newsinfo2") then 
                    -- for i=0, actor:object_count()-1 do
                    -- local obj = actor:object(i)
                    -- if obj and obj:section() == "inventory_sakbox_01" then
                    if have_box then
                        amk.start_timer("sms",rnd(50,60),2)
                        actor:give_info_portion("val_pula_ammo_newsinfo2")
                    end
                    if not actor:has_info("val_pula_ammo_newsinfo3") then
                        -- for i=0, actor:object_count()-1 do
                            -- local obj = actor:object(i)
                            -- if obj and obj:section() == "inventory_sakbox_01" then
                        if have_box then
                           amk.start_timer("sms",rnd(70,80),3)
                            actor:give_info_portion("val_pula_ammo_newsinfo3")
            end
                        -- end
                    -- end
            end
                -- end
            end
     end
    end
end
function smski_besu(st)
    local actor = db.actor
    if st==1 then
        actor:give_info_portion("sms_pulya")
                amk.send_tip(game.translate_string("sms_pulya_text"),nil,nil,30)
   elseif st==2 then
        actor:give_info_portion("sms_lukash")
                amk.send_tip(game.translate_string("sms_lukash_text"),nil,nil,30)
   elseif st==3 then
        actor:give_info_portion("sms_serega")
                amk.send_tip(game.translate_string("sms_serega_text"),nil,nil,30)
   end
end

function check_krysyk_dead()
    local actor = db.actor
--[[ Продолжение Крысюк - Жила:
    if actor and actor:has_info("bandit_krisyk_umer") and 
        actor:has_info("bandit_krisyk_start") and 
        not actor:has_info("bandit_krisyk_done") and 
        not actor:has_info("bandit_krisyk_newsinfo") then
                amk.start_timer("smska_borova",math.random(7,10))
            actor:give_info_portion("bandit_krisyk_newsinfo")
    end]]
    if actor and actor:has_info("bandit_krisyk_umer") and 
        actor:has_info("bandit_krisyk_finish") and 
        not actor:has_info("bandit_krisyk_newsinfo")
	then
        amk.start_timer("smska_borova",math.random(7,10))
		db.actor:disable_info_portion("bandit_krisyk_have")
        actor:give_info_portion("bandit_krisyk_newsinfo")
    end
--
end
function smska_borova()
    local actor = db.actor
    actor:give_info_portion("sms_borov")
                amk.send_tip(game.translate_string("sms_borov_text"),nil,nil,30)
end

function check_tolik_dead()
    local actor = db.actor
    if actor and actor:has_info("esc_vagon_wounded_umer") and 
        actor:has_info("mil_volk_resiver_start") and 
        not actor:has_info("mil_volk_resiver_done") and 
        not actor:has_info("mil_volk_resiver_newsinfo") then
                amk.start_timer("smska_volka",math.random(30,60))
      db.actor:give_info_portion("mil_volk_resiver_newsinfo")
    end
end
function smska_volka()
      db.actor:give_info_portion("sms_volk")
                amk.send_tip(game.translate_string("sms_volk_text"),nil,nil,30)
end
function check_maks_dead()
    local actor = db.actor
    if actor and actor:has_info("mil_freedom_member0018_umer") and 
        actor:has_info("mil_max_teleport_08_start") and 
        not actor:has_info("mil_max_teleport_08_done") and 
        not actor:has_info("mil_max_teleport_08_newsinfo") then
                amk.start_timer("smska_shurupa",math.random(30,60))
            actor:give_info_portion("mil_max_teleport_08_newsinfo")
    end
end
function smska_shurupa()
      db.actor:give_info_portion("sms_shurup")
                amk.send_tip(game.translate_string("sms_shurup_text"),nil,nil,30)
end
function check_yurik_dead()
    local actor = db.actor
    if actor and db.actor:has_info("gar_dm_novice_umer") and 
        actor:has_info("gar_dram_novice_mp5_m1_start") and 
        not actor:has_info("gar_dram_novice_mp5_m1_done") and 
        not actor:has_info("gar_dram_novice_mp5_m1_newsinfo") then
--                amk.start_timer("smska_dana",math.random(30,60))
            actor:give_info_portion("gar_dram_novice_mp5_m1_newsinfo")
    end
end
function smska_dana()
      db.actor:give_info_portion("sms_dan")
                amk.send_tip(game.translate_string("sms_dan_text"),nil,nil,30)
end
