-- list of registered modules, can have dependence one from other (must be grouped in table)
-- in every module must be an "init()" function for module's initialization
-- for some events (like packet save or load) order is VERY important
binds = {
	"xs_helpers",
	"xs_netpk",
	"xs_stor",
	"xs_timers",
	"ogse_mental_fix",
--	"ogse_firebat",
--	"ogse_anomaly_evader",
--	"xrs_battle_ai"	--- ÍÅ ÇÀÊÎÌÌÅÍÒÈĞÎÂÀÒÜ ÍÈ Â ÊÎÅÌ ÑËÓ×ÀÅ!!! ĞÓÊÈ ÎÁÎĞÂÓ! KamikaZze
	--"xs_svn" -- should be last!
}