-- -*- mode: lua; coding: windows-1251-dos -*-
-- list of registered modules, can have dependence one from other (must be grouped in table)
-- in every module must be an "init()" function for module's initialization
-- for some events (like packet save or load) order is VERY important
binds = {
  "xs_helpers",
  "xs_netpk",
--  "xs_stor",
--  "xs_timers",
  "dsh",
  --"xs_svn" -- should be last!
}
