-- -*- mode: lua; coding: windows-1251-dos -*-

-- таблица настроек битв
battles = {
  -- Пропавший сержант
  [ 30 ] = {
    {
      timeout = 3,
    },
    {
      tip     = "battle_l10_radar_0",
    },
  },

  -- Засада Монолита на Радаре
  [ 31 ] = {
    {
      timeout = 5,
    },
    {
      timeout = 15,
      tip     = "battle_l10_radar_1",
    },
    {
      func    = "akill.zasada_monolit_spawn()",
    },
  },
}
